### PR TITLE
[DataGrid] Add touch support on column resize

### LINKED ISSUE #416: [DataGrid] Add support for Column resizing on mobile
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The column resizing isn't working with a touch pointer. Most frequently, touch pointers can be found on mobile devices but that's not the only place. They can be found too on desktop, e.g. Windows Surface.

## Expected Behavior 🤔

Column resizing works with a touch pointer.

## Steps to Reproduce 🕹

Steps:

1. Open https://material-ui.com/components/data-grid/columns/#column-resizing
2. Try to resize 

## Context 🔦

Resizing is implemented with a mouse move handler.

https://github.com/mui-org/material-ui-x/blob/05ccbe31f6c5954e50399262f1afffe52006aca0/packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx#L44

However, with the latest browser proposal: https://github.com/mui-org/material-ui/pull/22814, we can drop all the mouse and touch handlers, replacing them with the [PointerEvent](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent) API. Browser support: https://caniuse.com/mdn-api_pointerevent.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.6  |

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #416 

This PR adds the ability to resize columns on touch devices. The solution was taken from the `Slider` component that is part of the core repo -> https://github.com/mui-org/material-ui/blob/0d0e370c6e783f967fbd922ac925f576bee2b9ae/packages/material-ui/src/Slider/Slider.js#L675

Preview: https://deploy-preview-537--material-ui-x.netlify.app/components/data-grid/#commercial-version

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx [hunk 1]
```diff
@@ -110,12 +111,134 @@ export const useColumnResize = (columnsRef: React.RefObject<HTMLDivElement>, api
...
   });
 
+  // TODO: remove support for Safari < 13.
+  // https://caniuse.com/#search=touch-action
+  //
+  // Safari, on iOS, supports touch action since v13.
+  // Over 80% of the iOS phones are compatible
+  // in August 2020.
+  let cachedSupportsTouchActionNone;
+  function doesSupportTouchActionNone() {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:121]: is it pure function? Can we move it to a utils file to keep the hook clean

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx [hunk 2]
```diff
@@ -110,12 +111,134 @@ export const useColumnResize = (columnsRef: React.RefObject<HTMLDivElement>, api
...
+      const element = document.createElement('div');
+      element.style.touchAction = 'none';
+      document.body.appendChild(element);
+      cachedSupportsTouchActionNone = window.getComputedStyle(element).touchAction === 'none';
+      element.parentElement!.removeChild(element);
+    }
+    return cachedSupportsTouchActionNone;
+  }
+
+  function trackFinger(event, currentTouchId) {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:132]: Same here

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 1 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:121]: It's not pure, there is a cache.

I definitely agree that we should isolate the logic, so moving it to the top scope would be much better.

Regarding creating a utility file for it, why about we wait for the need to share the logic? This way we can more easily refactor in the future. It's not like having a dedicated file really help to avoid duplication or with discoverability, it doesn't much.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx [hunk 3]
```diff
@@ -124,5 +247,11 @@ export const useColumnResize = (columnsRef: React.RefObject<HTMLDivElement>, api
     };
   }, [stopListening]);
 
-  return React.useMemo(() => ({ onMouseDown: handleMouseDown }), [handleMouseDown]);
+  return React.useMemo(
+    () => ({
+      onMouseDown: handleMouseDown,
+      onTouchStart: handleTouchStart,
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:253]: Should be a ref to allow no passive event.

**Review by oliviertassinari — CHANGES_REQUESTED** [review]

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 3 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:253]: This one needs to be pass around, and todo that we'll do property drilling. How about we do the same as the column reordering so we avoid that and we do the same pattern in the whole component.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 1 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:121]: I think if it can be outside the component, it's better to move it.
About the extra file, it's just to keep this file clean and focus on its own purpose. Creating another file is not only to share code, it can also be to keep the code clean... Up to you, I don't have a strong opinion on this, as the file is not that big.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 3 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:253]: From what I understand, property drilling will be required for both the customization API, the unstyled components and the composability of the plugin. What's the advantage of avoiding it?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:253]: @DanailH See for more details: https://github.com/facebook/react/pull/19654 why we need a ref.

Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:253]: mm I guess that is because of Safari. Ok I'll see how to delegate that event because I don't want to attach it to each of the separators.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 1 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:121]: It's not a pure function but I will rework it because I took it from the slider directly and wanted to validate the approach first. I'll convert it to a memo and the `cachedSupportsTouchActionNone ` to a ref so it's more optimal

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 2 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:132]: Same as the discussion above, I'll change it to a memo and make it more optimal.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 3 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:253]: We support Safari, starting at 12.1. touch-action none is supported after 13: https://en.wikipedia.org/wiki/Safari_version_history#Safari_12. We could decide to degrade the UX on 12.1 if it's significantly simpler. In such a case, we would drop `doesSupportTouchActionNone`, it's useless.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 1 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:121]: What do you mean by keeping code clean? Why is it cleaner? From what I understand, we could have files with 1,000 LOCs. I think that the most important aspect to optimize on this matter is: How easy can we delete code? If you can delete, you can refactor, you can't understand what's going on either.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 2 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:132]: I don't get it, why does it need a memo? I can be in the outer scope, it doesn't need to be in the scope of the hook.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 1 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:121]: I don't get it, why does it need a memo? I can be in the outer scope, it doesn't need to be in the scope of the hook.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 3 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx]: I did some testing, It's quite bad that you can scroll and resize at the same time. For the slider, it wasn't so bad but the grid is basically unusable if there is a horizontal scroll and you try to decrease the size of a cell => the outcome is that you can because you scroll and resize left at the same time which breaks the resize logic due to coordinates change.

I've updated the event listener.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 1 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx]: Ok, I've moved these 2 at the top of the file so in the future when we need it we can easily abstract them in their own utility file.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx [hunk 4]
```diff
@@ -185,14 +186,21 @@ export const useColumnResize = (columnsRef: React.RefObject<HTMLDivElement>, api
...
+      (finger as CursorCoordinates).x -
+      colElementRef.current!.getBoundingClientRect().left;
     newWidth = Math.max(MIN_COL_WIDTH, newWidth);
 
     updateWidth(newWidth);
   });
 
-  const handleTouchStart = useEventCallback((event: React.TouchEvent<HTMLElement>) => {
+  const handleTouchStart = useEventCallback((event) => {
     // If touch-action: none; is not supported we need to prevent the scroll manually.
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:198]: We could move the comment back to `if (!doesSupportTouchActionNone()) {`.

File: packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts [hunk 5]
```diff
@@ -10,6 +10,7 @@ export const useStyles = makeStyles(
     const gridStyle: { root: any } = {
       root: {
         flex: 1,
+        touchAction: 'none',
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts:13]: We can't prevent scroll on the whole grid. It should only be applied on the resizing area.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts:13]: For instance, you can't scroll starting from the pagination.

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx [hunk 6]
```diff
@@ -110,19 +151,117 @@ export const useColumnResize = (columnsRef: React.RefObject<HTMLDivElement>, api
...
+      (finger as CursorCoordinates).x -
+      colElementRef.current!.getBoundingClientRect().left;
+    newWidth = Math.max(MIN_COL_WIDTH, newWidth);
+
+    updateWidth(newWidth);
+  });
+
+  const handleTouchStart = useEventCallback((event) => {
+    // If touch-action: none; is not supported we need to prevent the scroll manually.
+    colElementRef.current = event.target.closest(`.${HEADER_CELL_CSS_CLASS}`) as HTMLDivElement;
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:199]: We should only allow resizing when using the resize area, not the whole header cell.

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
- On Android, I can no longer sort
- On iOS it sorts when I resize

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 4 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx]: Done

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 6 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx]: Fixed

File: packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts (hunk 5 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts]: I moved it to the cell separator, this should do the trick. I tested it on IOS (Chrome and Safari) it is working. It should also work on Android.

**Comment by oliviertassinari** [comment]
The hover style gets persisted on mobile:

Capture d’écran 2020-11-06 à 14 04 42

**Comment by oliviertassinari** [comment]
The following error is thrown when using the resize (dev & prod)

Capture d’écran 2020-11-06 à 14 07 37

File: packages/grid/_modules_/grid/hooks/utils/useScrollFn.ts [hunk 7]
```diff
@@ -4,7 +4,6 @@ import { ScrollFn, ScrollParams } from '../../models/params/scrollParams';
 import { useLogger } from './useLogger';
 
 export function useScrollFn(
-  apiRef: any,
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/utils/useScrollFn.ts:7]: nice clean up

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx [hunk 8]
```diff
@@ -110,19 +155,117 @@ export const useColumnResize = (columnsRef: React.RefObject<HTMLDivElement>, api
...
+      columnsHeaderElement?.removeEventListener('touchstart', handleTouchStart);
+
       clearTimeout(stopResizeEventTimeout.current);
       stopListening();
     };
-  }, [stopListening]);
+  }, [columnsHeaderElement, handleTouchStart, stopListening]);
 
-  return React.useMemo(() => ({ onMouseDown: handleMouseDown }), [handleMouseDown]);
+  return React.useMemo(
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx]: I'm pushing a change as we don't need this change to distract us during the review.

**Review by oliviertassinari — APPROVED** [review]

**Comment by oliviertassinari** [comment]
@DanailH Well done :)

File: packages/grid/_modules_/grid/hooks/utils/useScrollFn.ts (hunk 7 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/utils/useScrollFn.ts:7]: thanks

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx [hunk 9]
```diff
@@ -110,19 +156,121 @@ export const useColumnResize = (columnsRef: React.RefObject<HTMLDivElement>, api
...
+      HEADER_CELL_CSS_CLASS,
+    ) as HTMLDivElement;
+    const field = colElementRef.current!.getAttribute('data-field') as string;
+    const colDef = apiRef.current.getColumnFromField(field);
+
+    logger.debug(`Start Resize on col ${colDef.field}`);
+    apiRef.current.publishEvent(COL_RESIZE_START, { field });
+
+    colDefRef.current = colDef;
+    colElementRef.current = columnsHeaderElement!.querySelector(
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:231]: getFieldFromHeaderElem

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx [hunk 10]
```diff
@@ -110,19 +156,121 @@ export const useColumnResize = (columnsRef: React.RefObject<HTMLDivElement>, api
...
+    if (touch != null) {
+      // A number that uniquely identifies the current finger in the touch session.
+      touchId.current = touch.identifier;
+    }
+
+    colElementRef.current = findParentElementFromClassName(
+      event.target,
+      HEADER_CELL_CSS_CLASS,
+    ) as HTMLDivElement;
+    const field = colElementRef.current!.getAttribute('data-field') as string;
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:224]: getFieldFromHeaderElem

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 9 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:231]: findCellElementsFromCol

Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx:231]: the opposite of getFieldFromHeaderElem

Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx]: Done

File: packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx (hunk 10 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx]: Done

**Review by dtassone — APPROVED** [review]
