### PR TITLE
[DataGrid] Add useGridApiContext to access the GridApiContext

### LINKED ISSUE #1401: [DataGrid] Should fail with an explicit error when context is missing
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When the context provider of the data grid is missing, it fails with an obscure message.

## Expected Behavior 🤔

It should fail with a clear error message.

## Steps to Reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/data-grid-bug-loading-empty-row-forked-x20om?file=/src/App.js

Screenshot 2021-04-13 at 00 23 26

Note that it won't reproduce in our local env as we share the same react context instance. Use https://codesandbox.io/s/data-grid-bug-loading-empty-row-forked-2i56s?file=/src/App.js instead.

```jsx
import * as React from "react";
import { GridOverlay } from "@material-ui/data-grid";

export default function App() {
  return (
    <div className="App" style={{ height: "500px" }}>
      <GridOverlay />
    </div>
  );
}
```

## Context 🔦

This is a follow-up on #1326 where we didn't leverage the feedback as much as we could. The first time I saw this problem was in https://github.com/mui-org/material-ui/issues/686.

## Your Environment 🌎

v4.0.0-alpha.24

### PR DESCRIPTION
**Pull request by m4theushw**
Closes #1401

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/root/useGridApiContext.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import * as React from 'react';
+import { GridApiContext } from '../../components/GridApiContext';
+
+export function useGridApiContext() {
+  const apiRef = React.useContext(GridApiContext);
+
+  if (apiRef === undefined) {
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/root/useGridApiContext.ts:7]: What do you think about raising a warning instead of throwing and only in dev mode to not have any bundle size impact? Is it important enough to throw?

Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/root/useGridApiContext.ts:7]: I think it is important to throw as users would have issues at a later stage.

We could also consider combining it with useGridApiRef so you have a single point to get or create the apiRef 🤔

File: packages/grid/data-grid/src/tests/components.DataGrid.test.tsx [hunk 2]
```diff
@@ -45,4 +48,25 @@ describe('<DataGrid /> - Components', () => {
       expect(document.querySelectorAll('.customFooter').length).to.equal(0);
     });
   });
+
+  it('should throw if a component is used without proving the context', function test() {
```
Comment (dtassone) [inline packages/grid/data-grid/src/tests/components.DataGrid.test.tsx:52]: proving?

**Review by DanailH — APPROVED** [review]

File: packages/grid/_modules_/grid/hooks/root/useGridApiContext.ts (hunk 1 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/root/useGridApiContext.ts:7]: > What do you think about raising a warning instead of throwing and only in dev mode to not have any bundle size impact?

@oliviertassinari  I tested with the docs and the warning wasn't sent to the console, but to the terminal that was running the dev server. A throw in this situation facilitates for the user to know where's the problem.

> We could also consider combining it with useGridApiRef so you have a single point to get or create the apiRef 🤔

@dtassone Let's imagine that there's another grid inside the grid, like a child row. How will we know if a apiRef has to be created or the one in the context should used? Maybe we need to add an argument to force to create the apiRef even if there's a context in the tree.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/root/useGridApiContext.ts:7]: > but to the terminal that was running the dev server.

@m4theushw True, I was actually just talking about this problem in https://github.com/mui-org/material-ui/issues/18119#issuecomment-860877215. It's a Next.js thing only, that they could solve by forwarding the console log too (not only the error).

> How will we know if a apiRef has to be created or the one in the context should used?

💯. I would even push it one step further is unbundle useGridApiRef. I think that we need 3 hooks not 1.

- `useGridApiContext` to consume the API ref
- `const apiRef = React.useRef<GridApi>(createGridApi());` to create the apiRef and store it.
- `useGridApiRef`to read the API ref from the child data grid **ONLY**

I did a first step in this direction with #990
