### PR TITLE
[DataGrid] Add getRowId prop

### LINKED ISSUE #378: [DataGrid] Create prop to map required id to another field in the data set
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Related to: https://github.com/mui-org/material-ui-x/issues/342#issuecomment-700760440

As a Developer my data set may contain a uniquely identifying field that is not called "id" (i.e. "application_id"). If the data set is missing an "id" field you receive and error: 

> Uncaught Error: Material-UI: The data grid component requires all rows to have a unique id property. A row was provided without in the rows prop:

Ideally we should be able to pass some kind of id override as a prop to set the field that should be used as the unique identifier.

## Examples 🌈

In the below data example, the "app_id" is the unique field:

{
"__typename":"Application",
"app_id": "...",
"app_business_id": "...",
"app_support_team_dl": "...",
"app_support_model": "...", 
app_status": "..."
}

How to implement as a prop:

<DataGrid rows={data} columns={columns} id="app_id" />

## Motivation 🔦

The backend team has provided me data without an "id" field. So either I have to run a loop to add an "id" field or DB changes need to be made. It feels like an odd work around to have to run a potentially performance taxing loop just to add a fake field to each entry. Requesting DB changes is also potentially a nightmare depending on team requirements.

### PR DESCRIPTION
**Pull request by dtassone**
fix #378

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/rows/useGetRowId.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+export const useGetRowId = (apiRef: ApiRef, getRowIdProp?: RowIdGetter) => {
+  const getRowId = React.useCallback(
+    (row: RowData) => {
+      if (getRowIdProp != null) {
+        return getRowIdProp(row);
+      }
+      return getDefaultRowId(row);
+    },
+    [getRowIdProp],
+  );
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/rows/useGetRowId.ts:17]: Can you inverse the branching? We don't need to test each time if the prop is defined or not. We can do the test only once.

File: packages/grid/_modules_/grid/hooks/features/rows/useRows.ts [hunk 2]
```diff
@@ -51,19 +61,23 @@ export const useRows = (rows: RowsProp, apiRef: ApiRef): void => {
 
   const internalRowsState = React.useRef<InternalRowsState>(gridState.rows);
 
+  const getRowId = React.useCallback(
+    (row: RowData) => {
+      return apiRef.current.getRowId(row);
+    },
+    [apiRef],
+  );
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/rows/useRows.ts:69]: The `apiRef` never changes during amounting lifecycle, the `getRowId` can. The logic is not correct:

```suggestion
  const getRowId = apiRef.current.getRowId(row);
```

**Review by oliviertassinari — COMMENTED** [review]
We need to update the api pages to mention the existence of the prop, otherwise, developers won't find it.

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
We need to update the api pages to mention the existence of the prop, otherwise, developers won't find it.

File: packages/grid/_modules_/grid/hooks/features/rows/useRows.ts (hunk 2 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/rows/useRows.ts]: No because it is undefined on the first run as we have to run the hooks...

Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/rows/useRows.ts]: otherwise I'll have to check for null and it's just better to put it in the react cycle using the useCallback I think

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/rows/useRows.ts]: > No because it is undefined on the first run as we have to run the hooks...

Ok, then the root problem is worse. We should **respect effect dependencies** as much as possible. When we update a prop, it should rerun all the effects. For instance, in https://codesandbox.io/s/material-demo-forked-7bg1k?file=/demo.js the fact that the warning for missing id isn't raising is a red flag.

File: packages/grid/_modules_/grid/hooks/features/rows/useRows.ts [hunk 3]
```diff
@@ -2,36 +2,48 @@ import * as React from 'react';
...
-  rows,
-  totalRowCount,
-}: {
-  rows: RowsProp;
-  totalRowCount?: number;
-}): InternalRowsState {
+import { getInitialRowState, InternalRowsState } from './rowsState';
+
+export function addRowId(getRowId: RowIdGetter, rowData: RowData): RowModel {
+  return { ...rowData, id: getRowId(rowData) };
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/rows/useRows.ts:19]: How about bypassing the whole operation if `getRowId` is no provided?

```suggestion
  if (getRowId) {
    return { ...rowData, id: getRowId(rowData) };
  } else {
    return rowData;
  }
```

Actually, why do we even clone the structure now while we weren't doing it before?

File: packages/grid/_modules_/grid/hooks/features/rows/useGetRowId.ts [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+export const useGetRowId = (apiRef: ApiRef, getRowIdProp?: RowIdGetter) => {
+  const getRowId = React.useCallback(
+    (row: RowData) => {
+      if (!getRowIdProp) {
+        return getDefaultRowId(row);
+      }
+      return getRowIdProp(row);
+    },
+    [getRowIdProp],
+  );
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/rows/useGetRowId.ts:17]: We can still inverse the branching; reduce the amount of work done when processing 100,000 rows.

File: packages/grid/_modules_/grid/hooks/features/rows/useRows.ts [hunk 5]
```diff
@@ -87,10 +96,12 @@ export const useRows = (rows: RowsProp, apiRef: ApiRef): void => {
       }
 
       const idRowsLookup = allNewRows.reduce((lookup, row) => {
+        row = addRowId(getRowId, row);
+        checkRowHasId(row);
         lookup[row.id] = row;
         return lookup;
       }, {});
-      const allRows = allNewRows.map((row) => row.id);
+      const allRows = allNewRows.map((row) => getRowId(row));
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/rows/useRows.ts:104]: Could this boost performance?

```suggestion
      const allRows = getRowId ? allNewRows.map((row) => getRowId(row)) : allNewRows.map((row) => row.id);
```

Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/rows/useRows.ts:104]: I don't think it will boost perf as `getRowId` returns `row.id` as it's just about removing 1 function of the memory. in exchange of a check for null value. So it will be negligeable, we can remove the default value but then we will have to do checks everywhere.
That said, getRowId is only used when initial rows are set or updated.

File: packages/grid/_modules_/grid/hooks/features/rows/useRows.ts (hunk 3 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/rows/useRows.ts:19]: Well I'm not sure we want to have different behaviour for when you pass the prop or not.
That would bring edge cases and potential issues one way or the other. I'm more in favour of treating every case the same way 🤔

File: packages/grid/_modules_/grid/hooks/features/rows/useRows.ts (hunk 2 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/rows/useRows.ts]: > > No because it is undefined on the first run as we have to run the hooks...
> 
> Ok, then the root problem is worse. We should **respect effect dependencies** as much as possible. The useCallback swallows it. When we update a prop, it should rerun all the effects. For instance, in https://codesandbox.io/s/material-demo-forked-7bg1k?file=/demo.js the fact that the warning for "missing id" isn't raising is a signal that the architecture is not correct.

I don't share the same opinion. I do not think the problem is 'worse', it's exactly the same root issue mentioned in the api provider POC PR.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/rows/useRows.ts]: > I do not think the problem is 'worse'

You are right, I was referring to my understanding of the situation. It's in absolute, the same problem.

**Comment by dtassone** [comment]
consider renaming `row.id ` to `row.rowId` to avoid conflict with users' data 🤔

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
I like the updated code architecture of the PR 👍  but there is a performance regression, at least seems to be of 1 extra seconds with 100,000 rows . I believe it's related to the cloning behavior I have reported previously. Compare:

**HEAD**:
https://master--material-ui-x.netlify.app/components/data-grid/#commercial-version

Capture d’écran 2021-02-04 à 12 29 45

**PR**:
https://deploy-preview-972--material-ui-x.netlify.app/components/data-grid/#commercial-version

Capture d’écran 2021-02-04 à 12 29 39

This is the time it takes to rerender when pressing this button (the same thing with the initial render but harder to measure is isolation):

Capture d’écran 2021-02-04 à 12 30 31

**Comment by dtassone** [comment]
Test on this branch with spread
convertRowsPropToState: 1827.47998046875 ms
convertRowsPropToState: 1723.870849609375 ms
with mutation
convertRowsPropToState: 1510.81982421875 ms

Test on master 
convertRowsPropToState: 1302.665283203125 ms
convertRowsPropToState: 1035.637939453125 ms

This test was run using dev mode, react dev version, debugger open, (grid debug off)... Perf should be faster in prod

**Comment by oliviertassinari** [comment]
> This test was run using dev mode

A side note on this as I don't recall making this point in the past: We shouldn't make decisions based on performance in development. It can be used as a tool to nourish intuition but has little to no value compared to what the performance in production yields.

**Comment by dtassone** [comment]
> What should we do then?
> 
> > This test was run using dev mode
> 
> A side note on this as I don't recall making this point in the past: We shouldn't make decisions based on performance in development. It can be used as a tool to nourish intuition but has little to no value compared to what the performance in production are.

> We shouldn't make decisions based on performance in development.

Agree!

Basically it seems that it creates a small perf hit of around 300-500ms when you parse about 100 000 rows.
Well anyone should go server side for that amount of rows, but if we want to avoid the perf hit, then we can only clone the row when getRowId is used, which can lead to edge case issues... 
If we consider that 10 000 rows is our benchmark then we have 30-50 ms extra.

**Comment by oliviertassinari** [comment]
I would personally vote for going down the edge cases direction. So far, we only have a small number of entry points for feeding data and the difference can be felt when opening [HEAD](https://master--material-ui-x.netlify.app/components/data-grid/#commercial-version) vs. [PR](https://deploy-preview-972--material-ui-x.netlify.app/components/data-grid/#commercial-version) (look at the time the No rows message is shown, it goes from a few ms to over a second). @DanailH what do you think?

**Comment by dtassone** [comment]
We could remove having a `row.id` attached to the row data, so we would store ids in the state lookup key and we have an id array. 
Having a `row.id` is easier from a coding perspective and if we remove it, it will be a quite big refactoring as we would need to pass it separately in few places but it's doable 🤔

**Review by oliviertassinari — APPROVED** [review]

**Comment by oliviertassinari** [comment]
> We could remove having a row.id attached to the row data, so we would store ids in the state lookup key and we have an id array.
Having a row.id is easier from a coding perspective and if we remove it, it will be a quite big refactoring as we would need to pass it separately in few places but it's doable 🤔

Yeah, if we were to change the structure of the state, it might even be better to store the id into a structure close to:

```tsx
Row {
  id?: string | number;
  rowData?: any;
}
```

**Comment by dtassone** [comment]
> > We could remove having a row.id attached to the row data, so we would store ids in the state lookup key and we have an id array.
> > Having a row.id is easier from a coding perspective and if we remove it, it will be a quite big refactoring as we would need to pass it separately in few places but it's doable 🤔
> 
> Yeah, if we were to change the structure of the state, it might even be better to store the id into a structure close to:
> 
> ```tsx
> interface Row {
>   id?: string | number; // extracted id
>   rowData?: any; // input, referential equal with object provided by the developer.
> }
> ```

We had that before, but we won't really need it as mentioned above we can just use the key of the lookup...

**Comment by oliviertassinari** [comment]
> We had that before, but we won't really need it as mentioned above we can just use the key of the lookup...

@dtassone True, I believe we have found a new use case for such structure: getRowId, and how it allows to not clone/mutate the data provided by the developer.

**Comment by dtassone** [comment]
> > We had that before, but we won't really need it as mentioned above we can just use the key of the lookup...
> 
> @dtassone True, I believe we have found a new use case for such structure: getRowId, and how it allows to not clone/mutate the data provided by the developer, reducing pressure on the memory and allowing developers to compare the reference (a pain I have seen popup a bunch of time in the main library, for instance, the combo box)

I agree with the idea of maintaining the same ref. But I'm not sure about re-adding the row structure as I don't like the idea of storing meta row data in this row model as it was before as it removes the composability of the component.
ie if you store the selected state on the row object and not use the `useSelected` hook then you have a useless field in the structure.

**Comment by oliviertassinari** [comment]
@dtassone Agree, to consider for later
