### PR TITLE
[XGrid] Fix multi-sorting when focus is not in the grid root

### LINKED ISSUE #1204: [XGrid] Multi-sort not working
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When the <kbd>Shift</kbd> or <kbd>Ctrl</kbd> key is pressed without DOM focus in the data grid, the feature is no working.

## Expected Behavior 🤔

When the <kbd>Shift</kbd> or <kbd>Ctrl</kbd> key is pressed without DOM focus in the data grid, the feature is still working.

## Steps to Reproduce 🕹

Steps:

1. Open https://material-ui.com/components/data-grid/sorting/#multi-column-sorting
2. Hold <kbd>Ctrl</kbd>
3. Click on two columns
4. 💥

multi-sort

## Context 🔦

We can remove code by fixing this issue. The current logic listens to the *keydown* event on the data grid's root, which is not triggered when the <kbd>Ctrl</kbd> key is held with the DOM focus somewhere else. 
Instead, we could ask the event if other keys are pressed. It's, for instance, what we do here:

https://github.com/mui-org/material-ui/blob/ebeb1492b5e645eccdea920fbbf561fe2a0c3031/packages/material-ui-lab/src/TreeView/TreeView.js#L666

The other alternative is to listen on the document owning the data grid's root (but it seems more complexity than needed).

## Your Environment 🌎

v4.0.0-alpha.21

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #1204 

There're multiple solutions to this bug:

1. Check if a multiple key was pressed during `click`.
2. Listen for `keydown` events in the document.
3. 1 + remove the `GRID_MULTIPLE_KEY_PRESS_CHANGED` listener and add a 3nd argument to `sortColumn` for when it's called programatically.

~I went with 1, as it's the simplest and has less side effects than 2.~ 3

### CODE REVIEW

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
Could we remove `GRID_MULTIPLE_KEY_PRESS_CHANGED` and all the logic that comes with it? It doesn't seem to bring value, the opposite.

**Comment by m4theushw** [comment]
It's used to do a multi-sort when calling `sortColumn` programatically. What do you think of the 3rd solution?

**Comment by oliviertassinari** [comment]
Why is `event.shiftKey || event.metaKey || event.ctrlKey` not all we need?

**Comment by dtassone** [comment]
`GRID_MULTIPLE_KEY_PRESS_CHANGED` is also used in selection
It allows to have the same multiple keys for all features in the grid.

File: packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts [hunk 1]
```diff
@@ -211,25 +209,26 @@ export const useGridSorting = (apiRef: GridApiRef, rowsProp: GridRowsProp) => {
...
-    [upsertSortModel, setSortModel, createSortItem],
+    [upsertSortModel, setSortModel, createSortItem, options.disableMultipleColumnsSorting],
   );
 
   const headerClickHandler = React.useCallback(
-    ({ colDef }: GridColumnHeaderParams) => {
-      sortColumn(colDef);
+    ({ colDef }: GridColumnHeaderParams, event: React.MouseEvent) => {
+      const isMultipleKeyPressed = event.shiftKey || event.metaKey || event.ctrlKey;
+      sortColumn(colDef, undefined, isMultipleKeyPressed);
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts:231]: What if we use the enter key?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts:231]: It seems to work the same way https://codesandbox.io/s/charming-hopper-cpr1f?file=/src/App.js, https://deploy-preview-1422--material-ui-x.netlify.app/components/data-grid/sorting/#multi-column-sorting. What issue do you have in mind?

**Comment by oliviertassinari** [comment]
> GRID_MULTIPLE_KEY_PRESS_CHANGED is also used in selection
It allows to have the same multiple keys for all features in the grid.

@dtassone Then it sounds like we can remove even more code :). I have pushed it one step further in 2a7dca3. Is there a case where `const isMultipleKeyPressed = event.shiftKey || event.metaKey || event.ctrlKey;` won't be enough?

File: packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts (hunk 1 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts:231]: hmm ok that's because enter Key or space key publish a column header click 🤔 
see useGridKeyboard line 215

File: packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts [hunk 2]
```diff
@@ -61,9 +60,8 @@ export const useGridKeyboard = (
       }
 
       forceUpdate();
-      apiRef.current.publishEvent(GRID_MULTIPLE_KEY_PRESS_CHANGED, isPressed);
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts:64]: what's the point of keeping `setMultipleKeyState` if you don't publish the event?

File: packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts (hunk 1 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts:231]: > hmm ok that's because enter Key or space key publish a column header click 🤔
> see useGridKeyboard line 215

so the event in the click would be of a wrong type if it is triggered from the keyboard.
I thing there should be more granular events here, like in `cellEditStart`

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts:231]: Oh yeah, this is completely wrong:

https://github.com/mui-org/material-ui-x/blob/fa346f0fbe3d9b9eea9bb403fe4675f544d6abf9/packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts#L205-L210

File: packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts (hunk 2 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts:64]: It seems to update the gridState, which is used somewhere by another feature.

File: packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts (hunk 1 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts:231]: `GRID_COLUMN_HEADER_CLICK` should only be dispatched by a click event. It violates our rules when dispatched by other event. I'll add another listener just for the keyboard event.

File: packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts (hunk 2 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts:64]: Well that would involve refactoring the selection and the expand selection with the keyboard, which could move to the useSelection hook 🤔 

I suggest leaving this code as it is. As it might create an issue to remove the publication of the event at this stage
Do another PR to refactor the selection.

File: packages/grid/_modules_/grid/utils/keyboardUtils.ts [hunk 3]
```diff
@@ -38,3 +38,6 @@ export const isNavigationKey = (key: string) =>
 export const isKeyboardEvent = (event: any): event is React.KeyboardEvent => !!event.key;
 
 export const isHideMenuKey = (key) => isTabKey(key) || isEscapeKey(key);
+
+export const isMultipleKeyPressed = (event: any) =>
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/utils/keyboardUtils.ts:42]: for once, an event helper that makes sense 👍

**Review by oliviertassinari — APPROVED** [review]

**Review by dtassone — APPROVED** [review]
