### PR TITLE
[DataGrid][1] Make GridMainContainer tabbable

### LINKED ISSUE #1291: [DataGrid] Roving tabindex is wrong
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Misalignment with the guidelines WAI-ARIA guidelines.

## Expected Behavior 🤔

Alignment with the guidelines.

## Steps to Reproduce 🕹

1. Open: https://codesandbox.io/s/material-demo-forked-c6kb1?file=/demo.js
2. Set the focus on the "start" button
3. Use <kbd>Tab</kbd> to move the focus forward until reaching the "end" button

I see 3 things wrongs:

1. No focus-visible feedback on when the focus is on the root container
2. The root container shouldn't be focusable. See "Because focus is managed using roving tabindex , the grid element is **not focusable**." https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html
3. Per the [roving focus index](https://www.w3.org/TR/wai-aria-practices/#kbd_roving_tabindex) management in a composite widget, setting `tabIndex="0"` on the first item would make more sense. This is the most IMPORTANT part of this bug report. Without it, end-users, can't navigate the cells with the keyboard only.

## Context 🔦

First reported in #1289 by @DanailH.

> as far as I could work out there is no way to navigate to focus a cell in the grid, meaning that when changing focus using tab the focus will move through what is in the toolbar and then be lost - IMO it should focus the first cell or column header (needs to be decided)

Also, looking at the example in https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html. They set tabIndex={-1} on the inner button in the cells. I wonder if we shouldn't do the same with our checkboxes. No idea.

## Your Environment 🌎

v4.0.0-alpha.23

### PR DESCRIPTION
**Pull request by DanailH**
Aims to solve point 1 and 3 listed in here #1291 (potentially solving point 2 as well)

With this change when using `tab` to navigate the page, after the focus passes through the elements in the toolbar it will focus on the `GridMainContainer` (the component that holds the columns and the rows of the grid). 

When the `GridMainContainer` is focused using the arrow keys will focus the cell with `{colIndex: 0, rowIndex: 0}` effectively allowing us to reach the cells using the keyboard. Normal keyboard navigation rules apply after the first cell is focused.

Preview: https://deploy-preview-1327--material-ui-x.netlify.app/components/data-grid/rendering/#flex-layout

### CODE REVIEW

File: packages/grid/_modules_/grid/components/containers/GridMainContainer.tsx [hunk 1]
```diff
@@ -1,5 +1,33 @@
...
+    }),
+    [publish],
+  );
+
+  return (
+    <div
+      className="MuiDataGrid-main"
+      role="rowgroup"
+      /* eslint-disable-next-line jsx-a11y/no-noninteractive-tabindex */
+      tabIndex={0}
```
Comment (DanailH) [inline packages/grid/_modules_/grid/components/containers/GridMainContainer.tsx:27]: As far as I understand this needs to change back to `-1` when the element loses focus?

File: packages/grid/_modules_/grid/components/containers/GridMainContainer.tsx [hunk 2]
```diff
@@ -1,5 +1,33 @@
...
+    () => ({
+      onKeyDown: publish(GRID_CONTAINER_KEYDOWN),
+    }),
+    [publish],
+  );
+
+  return (
+    <div
+      className="MuiDataGrid-main"
+      role="rowgroup"
```
Comment (DanailH) [inline packages/grid/_modules_/grid/components/containers/GridMainContainer.tsx:25]: I'm not 100% sure about `rowgroup` but this is the only one from the spec that makes sense in our case. I'm opened to suggestions.

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
It doesn't look what the WAI-ARIA say. Shouldn't the first cell have `tabIndex={0}` and the containers leaving the focus alone?

**Comment by oliviertassinari** [comment]
> Fixes #1291

I don't think that it should close this issue, as there are two different issues to solve for this one. Here, we go after one, it would be a great first step.

**Comment by DanailH** [comment]
> It doesn't look what the WAI-ARIA say. Shouldn't the first cell have `tabIndex={0}` and the all the containers leave the focus alone?

I was following this https://www.w3.org/TR/wai-aria-practices/#kbd_roving_tabindex when looking for a solution. I will try wit cell `0-0` with `tabIndex=0` and the rest with `tabIndex=-1`

Note to self: Once the https://github.com/mui-org/material-ui-x/pull/1289 is merged the element with `tabIndex=0` should change to the first column header

**Comment by DanailH** [comment]
> > Fixes #1291
> 
> I don't think that it should close this issue, as there are two different problems to solve for this GitHub issue. Here, we go after one, it's a great first step.

OK i guess you mean that point

> The root container shouldn't be focusable. See "Because focus is managed using roving tabindex , the grid element is not focusable." https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html

I agree It seems that the bigger problem is the fact that you can't reach the cells using only the keyboard which this PR aims to solve.

File: packages/grid/_modules_/grid/components/containers/GridRoot.tsx [hunk 3]
```diff
@@ -27,7 +27,7 @@ export const GridRoot = React.forwardRef<HTMLDivElement, GridRootProps>(function
       role="grid"
       aria-colcount={visibleColumnsLength}
       aria-rowcount={gridState.rows.totalRowCount}
-      tabIndex={0}
+      tabIndex={-1}
```
Comment (DanailH) [inline packages/grid/_modules_/grid/components/containers/GridRoot.tsx:30]: Should we do this here to tackle point 2 from the ticket?

**Comment by DanailH** [comment]
Ok I severely simplified the solution - the bottom line is that it works as expected - you are able to reach the cells inside the grid by only using the keyboard.

I would say that in here https://github.com/mui-org/material-ui-x/pull/1289 the first column header should still have `tabIndex=-1` and the first cell selected in the grid should be the one with coordinates `0-0`. If we agree I will change the other PR to match this requirement.

File: packages/grid/_modules_/grid/components/containers/GridMainContainer.tsx (hunk 2 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/containers/GridMainContainer.tsx]: No longer relevant

File: packages/grid/_modules_/grid/components/containers/GridMainContainer.tsx (hunk 1 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/containers/GridMainContainer.tsx]: No longer relevant

**Review by oliviertassinari — COMMENTED** [review]
This is not correct. It's not matching https://www.w3.org/TR/wai-aria-practices/#kbd_roving_tabindex. Tested in https://codesandbox.io/s/3g31i?file=/demo.js.

1. It's the value of hasFocus that should be fixed. the first cell should get `tabIndex={0}` unless `state.keyboard.cell` is defined.
2. The container should have `tabIndex={0}` when no cells are available or no attribute at all. IMHO, this is a small detail. I think that we should ignore it and simply remove the tabIndex from the container.

How about we focus on a smaller problem, one that is a recent regression from #1205 and has fewer dependencies with the other effort. <kbd>Tab</kbd> should move to the next tabbable element, not the next focusable one.

File: packages/grid/_modules_/grid/components/containers/GridRoot.tsx (hunk 3 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/containers/GridRoot.tsx:30]: The correct state should be:

```suggestion
```

**Comment by oliviertassinari** [comment]
Oh actually, since we are working on the accessibility and the tab behavior. It sounds like a great opportunity to leverage the work of @eps1lon https://github.com/mui-org/material-ui/pull/25405. Otherwise, we won't be able to write correct tests.

**Comment by DanailH** [comment]
> This is not correct. It's not matching https://www.w3.org/TR/wai-aria-practices/#kbd_roving_tabindex. Tested in https://codesandbox.io/s/3g31i?file=/demo.js.
> 
> 1. It's the value of `hasFocus` that should be fixed. the first cell should get `tabIndex={0}` unless `state.keyboard.cell` is defined.
> 2. The container should have `tabIndex={0}` when no cells are available or no attribute at all. IMHO, this is a small detail. I think that we should ignore it and simply remove the tabIndex from the container.
> 
> How about we focus on a smaller problem, one that is a recent regression from #1205 and has fewer dependencies with the other effort. Tab should move to the next tabbable element, not the next focusable one.
> 
> Then once #1289 is merged. We can come back to fix the tabIndex.

Ok, so basically 
```tsx
const currentFocusedCell = apiRef!.current.getState().keyboard.cell;
const isCellFocusable = (currentFocusedCell && hasFocus) || (rowIndex === 0 && colIndex === 0 && !currentFocusedCell);

...

<div tabIndex={isCellFocusable ? 0 : -1} />
```
That way initially using the only tab you will get to the cell `0-0` and then once selected using the arrow keys the focus will move and only the currently focused cell will have `tabIndex=0`, the rest will have `tabIndex=-1`.

**Comment by DanailH** [comment]
> Oh actually, since we are working on the accessibility and the tab behavior. It sounds like a great opportunity to leverage the work of @eps1lon [mui-org/material-ui#25405](https://github.com/mui-org/material-ui/pull/25405). Otherwise, we won't be able to write reliable tests.
> @DanailH Do you want to setup the same test infra (copy it)?

I can take it but I would prefer to do it as a separate PR.

File: packages/grid/_modules_/grid/components/cell/GridCell.tsx [hunk 4]
```diff
@@ -56,6 +56,9 @@ export const GridCell: React.FC<GridCellProps> = React.memo((props) => {
   const valueToRender = formattedValue || value;
   const cellRef = React.useRef<HTMLDivElement>(null);
   const apiRef = React.useContext(GridApiContext);
+  const currentFocusedCell = apiRef!.current.getState().keyboard.cell;
+  const isCellFocusable =
+    (currentFocusedCell && hasFocus) || (rowIndex === 0 && colIndex === 0 && !currentFocusedCell);
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/cell/GridCell.tsx:61]: Why not keeping is as simple as?

```diff
diff --git a/packages/grid/_modules_/grid/hooks/features/core/gridState.ts b/packages/grid/_modules_/grid/hooks/features/core/gridState.ts
index 831b5be5..51996e25 100644
--- a/packages/grid/_modules_/grid/hooks/features/core/gridState.ts
+++ b/packages/grid/_modules_/grid/hooks/features/core/gridState.ts
@@ -66,7 +66,7 @@ export const getInitialGridState: () => GridState = () => ({
   scrollBar: { hasScrollX: false, hasScrollY: false, scrollBarSize: { x: 0, y: 0 } },
   viewportSizes: { width: 0, height: 1 },
   sorting: getInitialGridSortingState(),
-  keyboard: { cell: null, columnHeader: null, isMultipleKeyPressed: false },
+  keyboard: { cell: { colIndex: 0, rowIndex: 0 }, columnHeader: null, isMultipleKeyPressed: false },
   selection: {},
   filter: getInitialGridFilterState(),
   columnMenu: { open: false },
```

**Review by oliviertassinari — COMMENTED** [review]
> I can take it but I would prefer to do it as a separate PR.

Right, we could use this very behavior for the first test.

File: packages/grid/_modules_/grid/components/cell/GridCell.tsx (hunk 4 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/cell/GridCell.tsx:61]: As far as I understand doing it like that would mean that by default the first cell is always focused. This state only has a value once an interaction with the keyboard happens. If you click on a cell that state should remain emply.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/cell/GridCell.tsx:61]: AFAIK, it's what the spec ask for. The first cell should be, by default, the active item in the roving index, meaning tabbable and focusable. But it doesn't mean that it should get the focus, IMHO the focus in an effect is plain wrong.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/cell/GridCell.tsx:61]: I think that it comes down to what should this state host?

I would personally advocate for the tabIndex value, not the activeElement. I think that the focus should be managed imperatively. I also think that the performance of they keyboard is far from great. It's really lagging, compared to ag-Grid. I think that the only way to solve this is by managing the tabIndex and focus at the DOM level, bypassing React. It's the only solution we found on the Autocomplete to make the keyboard handler 
feel instant.

Comment (DanailH) [reply packages/grid/_modules_/grid/components/cell/GridCell.tsx:61]: Alright, then how about I create a separate ticket focused on only refactoring the keyboard state because now this change will also impact the logic from https://github.com/mui-org/material-ui-x/pull/1289?

File: packages/grid/_modules_/grid/components/cell/GridCell.tsx [hunk 5]
```diff
@@ -150,7 +153,7 @@ export const GridCell: React.FC<GridCellProps> = React.memo((props) => {
       aria-colindex={colIndex}
       style={style}
       /* eslint-disable-next-line jsx-a11y/no-noninteractive-tabindex */
-      tabIndex={hasFocus ? 0 : -1}
+      tabIndex={isCellFocusable ? 0 : -1}
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/cell/GridCell.tsx:156]: it's not because the cell is focusable that it has the focus. 
If it has the focus then tabIndex = 0, not when it's focusable.
Some refactoring to do here...

Comment (DanailH) [reply packages/grid/_modules_/grid/components/cell/GridCell.tsx:156]: Yes, that is what `isCellFocusable` do, probably better wording would be `isCellFocused`?

**Review by dtassone — APPROVED** [review]

File: packages/grid/_modules_/grid/components/cell/GridCell.tsx (hunk 5 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/cell/GridCell.tsx]: > If it has the focus then tabIndex = 0, not when it's focusable.

@dtassone This is true, but with one important limitation. The cell having the focus is not the only case when we set a cell tabbable (`tabIndex={0}`). It's also occurs for the initial rendering, so the first cell can be <kbd>Tab</kbd> on.

**Review by oliviertassinari — APPROVED** [review]
The behavior looks good, and mostly rely on removing code 😁

It would be great to follow up with the test case

File: packages/grid/_modules_/grid/components/cell/GridCell.tsx (hunk 4 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/cell/GridCell.tsx]: Sounds good
