### PR TITLE
[DataGrid] Allow to customize the overlay when there're no filtered rows

### LINKED ISSUE #1288: [DataGrid] NoResultOverlay should render when there is no result after filtering
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

`DataGrid` doesn't render anything when there is no result after filtering.

## Expected Behavior 🤔

`DataGrid` renders `NoRowsOverlay` when there is no result after filtering.

## Steps to Reproduce 🕹

* Set `<DataGrid rows{[]} />`.
* `DataGrid` renders `NoRowsOverlay` as expected.

But when:

* Populate row data `<DataGrid rows={rows} />`.
* Start filtering.
* If there is no results, render nothing instead of `NoRowsOverlay`.

## Your Environment 🌎

[Edit 66783261/not-able-to-display-no-rows-message-after-applying-filter-in-react-material-ui](https://codesandbox.io/s/66783261not-able-to-display-no-rows-message-after-applying-filter-in-react-material-ui-t848y?fontsize=14&hidenavigation=1&theme=dark)

### PR DESCRIPTION
**Pull request by m4theushw**
Closes #1288

### CODE REVIEW

File: packages/grid/_modules_/grid/models/gridSlotsComponent.ts [hunk 1]
```diff
@@ -66,6 +67,10 @@ export interface GridSlotsComponent extends GridIconSlotsComponent {
    * No rows overlay component rendered when the grid has no rows.
    */
   NoRowsOverlay?: React.ElementType;
+  /**
+   * All filtered overlay component rendered when the grid has no results after filtering.
+   */
+  AllFilteredOverlay?: React.ElementType;
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/gridSlotsComponent.ts:73]: I'm not a big fan of my initial name proposal. Do we have better candidates?

Comment (m4theushw) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:73]: I have some: NoFilterResultsOverlay, NoFilteredRowsOverlay, NoMatchingRowsOverlay.

Comment (dtassone) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:73]: My idea was NoResultOverlay

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:73]: I was also going to propose `NoFilteredRowsOverlay`.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:73]: `NoResultsOverlay` could work too 👍

Comment (m4theushw) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:73]: Another suggestion: `NoVisibleRowsOverlay`. I know it doesn't make clear where it's used but it translates the condition used to display it. @DanailH do you want to help us decide?

File: docs/pages/api-docs/data-grid.md [hunk 2]
```diff
@@ -103,8 +103,8 @@ Api of the `components` props of type `GridSlotsComponent`
 | <span class="prop-name">Toolbar</span> | <span class="prop-type">React.ElementType</span> | <span class="prop-type">GridToolbar</span> | Toolbar component rendered above the grid column header bar.|
 | <span class="prop-name">PreferencesPanel</span> | <span class="prop-type">React.ElementType</span> | <span class="prop-type">PreferencesPanel</span> | PreferencesPanel component that renders the ColumnSelector or FilterPanel within a Panel component.|
 | <span class="prop-name">LoadingOverlay</span> | <span class="prop-type">React.ElementType</span> | <span class="prop-type">LoadingOverlay</span> | Loading overlay component rendered when the grid is in a loading state.|
+| <span class="prop-name">NoFilteredRowsOverlay </span> | <span class="prop-type">React.ElementType</span> | <span class="prop-type">NoFilteredRowsOverlay </span> | No filtered rows overlay component rendered when the grid has no results after filtering.|
```
[the remark this answers is not in the document]
Comment (m4theushw) [reply docs/pages/api-docs/data-grid.md:106]: Actually, we didn't reach an agreement in https://github.com/mui-org/material-ui-x/pull/1445#discussion_r616683146. I chose this one because having "filtered" in the name makes it explicit that it's used in the filtering feature.

File: packages/grid/_modules_/grid/models/gridSlotsComponent.ts (hunk 1 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts]: I'm in favour `NoResultsOverlay` since it sounds generic enough and we can use it in other situations later on but `NoVisibleRowsOverlay` is ok too.

Comment (m4theushw) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts]: Changed to `NoResultsOverlay`.

**Comment by oliviertassinari** [comment]
The visual change might seem strange at first sight but it's actually expected. All the rows in the visual regression tests are the same. So it never matches.

File: packages/grid/_modules_/grid/locales/ptBR.ts [hunk 3]
```diff
@@ -6,6 +6,7 @@ const ptBRGrid: Partial<GridLocaleText> = {
   // Root
   rootGridLabel: 'Grade',
   noRowsLabel: 'Nenhuma linha',
+  allRowsFilteredLabel: 'Todos os registros estão filtrados',
```
Comment (DanailH) [inline packages/grid/_modules_/grid/locales/ptBR.ts:9]: It's a side note, but I was thinking if we should keep the translations up to date somehow. Anyone any ideas about this? @oliviertassinari are there efforts like this in the core?

File: packages/grid/_modules_/grid/components/GridNoResultsOverlay.tsx [hunk 4]
```diff
@@ -0,0 +1,16 @@
+import * as React from 'react';
+import { GridApiContext } from './GridApiContext';
+import { GridOverlay, GridOverlayProps } from './containers/GridOverlay';
+
+export const GridNoResultsOverlay = React.forwardRef<HTMLDivElement, GridOverlayProps>(
+  function GridNoResultsOverlay(props, ref) {
+    const apiRef = React.useContext(GridApiContext);
+    const allRowsFilteredLabel = apiRef!.current.getLocaleText('allRowsFilteredLabel');
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/GridNoResultsOverlay.tsx:8]: can we rename this key to match the component name please?
noResultOverlayLabel

File: packages/storybook/src/stories/grid-filter.stories.tsx [hunk 5]
```diff
@@ -643,3 +643,24 @@ export function DemoMultiFilteringGrid() {
     </div>
   );
 }
+
+export function AllFilteredSnap() {
```
Comment (dtassone) [inline packages/storybook/src/stories/grid-filter.stories.tsx:647]: NoResultSnap

File: packages/grid/_modules_/grid/locales/ptBR.ts (hunk 3 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/locales/ptBR.ts:9]: The situation is different in the core as we have fewer translations key, and change them less frequently.

However, what we have done is to update all the locales with the commented keys in English. It makes a clear signal for the community that it's not handled and up for grab.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/locales/ptBR.ts:9]: It would be interesting to write a script that automatically detect out of date locale and transform them. It's typically the type of infrastructure work that Sebastian has been doing in the core.

File: packages/grid/_modules_/grid/constants/localeTextConstants.ts [hunk 6]
```diff
@@ -4,7 +4,7 @@ export const GRID_DEFAULT_LOCALE_TEXT: GridLocaleText = {
   // Root
   rootGridLabel: 'grid',
   noRowsLabel: 'No rows',
-  allRowsFilteredLabel: 'All rows are filtered',
+  noResultsOverlayLabel: 'All rows are filtered',
```
Comment (dtassone) [inline packages/grid/_modules_/grid/constants/localeTextConstants.ts:7]: `No results found.` ? 🤔

File: packages/grid/_modules_/grid/locales/ptBR.ts [hunk 7]
```diff
@@ -6,6 +6,7 @@ const ptBRGrid: Partial<GridLocaleText> = {
   // Root
   rootGridLabel: 'Grade',
   noRowsLabel: 'Nenhuma linha',
+  noResultsOverlayLabel: 'Nenhum registro encontrado.',
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/locales/ptBR.ts:9]:
```suggestion
  noResultsOverlayLabel: 'Nenhum resultado encontrado.',
```

File: packages/grid/_modules_/grid/locales/bgBG.ts [hunk 8]
```diff
@@ -6,6 +6,7 @@ const bgBGGrid: Partial<GridLocaleText> = {
   // Root
   rootGridLabel: 'мрежа',
   noRowsLabel: 'Няма редове',
+  // noResultsOverlayLabel: 'No results found.',
```
Comment (dtassone) [inline packages/grid/_modules_/grid/locales/bgBG.ts:9]: this is going to throw an exception in this language

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/locales/bgBG.ts:9]: Why? Or even better, do you have a proof? It's not the case. Proof: https://material-ui.com/components/data-grid/localization/#translation-keys.

**Review by oliviertassinari — APPROVED** [review]

File: packages/grid/_modules_/grid/locales/bgBG.ts (hunk 8 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/locales/bgBG.ts:9]: It won't. We use the English language as fallback:

https://github.com/mui-org/material-ui-x/blob/4bd386579466b6efd7a1029097a43f1b3b7ca178/packages/grid/_modules_/grid/hooks/utils/useOptionsProp.ts#L43-L50

**Review by dtassone — APPROVED** [review]
