### PR TITLE
[DataGrid] Fix crash when id has a single-quote

### LINKED ISSUE #1953: [DataGrid] When id has a single-quote or newline character checkboxSelection fails
When using the DataGrid, if the id has single-quotes or new line characters, using checkboxSelection will result in an error

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Console error log
```
index.js:1 Material-UI: GridComponent - An unexpected error occurred. Error: Failed to execute 'querySelector' on 'Element': ':scope .MuiDataGrid-row[data-id=''a
b
c
d
']' is not a valid selector..  DOMException: Failed to execute 'querySelector' on 'Element': ':scope .MuiDataGrid-row[data-id=''a
b
c
d
']' is not a valid selector.
    at pl (http://localhost:3000/static/js/vendors~main.chunk.js:22003:12)
    at ml (http://localhost:3000/static/js/vendors~main.chunk.js:22010:13)
    at Object.getCellElement (http://localhost:3000/static/js/vendors~main.chunk.js:26048:108)
    at uc.t.current.hasOwnProperty.t.current.<computed> [as getCellElement] (http://localhost:3000/static/js/vendors~main.chunk.js:22580:115)
    at http://localhost:3000/static/js/vendors~main.chunk.js:23435:19
    at renderWithHooks (http://localhost:3000/static/js/vendors~main.chunk.js:59007:22)
    at updateForwardRef (http://localhost:3000/static/js/vendors~main.chunk.js:61029:24)
    at beginWork (http://localhost:3000/static/js/vendors~main.chunk.js:63017:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/vendors~main.chunk.js:47957:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/vendors~main.chunk.js:48006:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/vendors~main.chunk.js:48066:35)
    at beginWork$1 (http://localhost:3000/static/js/vendors~main.chunk.js:67808:11)
    at performUnitOfWork (http://localhost:3000/static/js/vendors~main.chunk.js:66644:16)
    at workLoopSync (http://localhost:3000/static/js/vendors~main.chunk.js:66581:9)
    at renderRootSync (http://localhost:3000/static/js/vendors~main.chunk.js:66547:11)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/vendors~main.chunk.js:66164:22)
    at http://localhost:3000/static/js/vendors~main.chunk.js:55417:30
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:79631:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:55363:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/vendors~main.chunk.js:55412:13)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/vendors~main.chunk.js:55400:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/vendors~main.chunk.js:67467:7)
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:79631:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:55363:14)
    at flushPassiveEffects (http://localhost:3000/static/js/vendors~main.chunk.js:67300:18)
    at http://localhost:3000/static/js/vendors~main.chunk.js:67181:15
    at workLoop (http://localhost:3000/static/js/vendors~main.chunk.js:79581:38)
    at flushWork (http://localhost:3000/static/js/vendors~main.chunk.js:79555:18)
    at MessagePort.performWorkUntilDeadline (http://localhost:3000/static/js/vendors~main.chunk.js:79321:31) undefined
```

## Expected Behavior 🤔

Expect the DataGrid to render

## Steps to Reproduce 🕹

https://codesandbox.io/s/admiring-darkness-332ck?file=/src/App.js

## Context 🔦

User enters text which is then classified, the text and result is then displayed in the DataGrid, I've assigned the id to be the text entered

## Your Environment 🌎

  System:
    OS: macOS 11.4
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.106
    Edge: Not Found
    Firefox: 78.11.0
    Safari: 14.1.1
  npmPackages:
    @material-ui/core: ^4.11.4 => 4.11.4 
    @material-ui/data-grid: 4.0.0-alpha.30 => 4.0.0-alpha.30 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  5.0.0-alpha.35 
    @types/react:  17.0.11 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 

Version 91.0.4472.106 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by rbrishabh**
Fixes #1953 

Hey @oliviertassinari! How does this look?
Let me know if this needs any changes! Thanks

### CODE REVIEW

**Comment by oliviertassinari** [comment]
I have used the opportunity to remove the dead `:scope` logic.

File: packages/grid/_modules_/grid/utils/domUtils.ts [hunk 1]
```diff
@@ -62,7 +62,7 @@ export function getGridColumnHeaderElement(root: Element, field: string) {
 
 export function getGridRowElement(root: Element, id: GridRowId) {
   return root.querySelector(
-    `:scope .${GRID_ROW_CSS_CLASS}[data-id="${escapeOperandAttributeSelector(String(id))}"]`,
+    `.${GRID_ROW_CSS_CLASS}[data-id="${escapeOperandAttributeSelector(String(id))}"]`,
```
Comment (dtassone) [inline packages/grid/_modules_/grid/utils/domUtils.ts:65]: we already have an `escapeRegExp`, can't we reuse it?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/utils/domUtils.ts:65]: I don't understand regexp and attribute selectors are unrelated.

Comment (dtassone) [reply packages/grid/_modules_/grid/utils/domUtils.ts:65]: hence the question `can't we reuse it?` if they both result in `\'` or similar we might not need a new method.
Also removing `:scope` will now allow the header row as a result

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/utils/domUtils.ts:65]: OK, I will keep two different methods because the concepts are unrelated.

Regarding `:scope`, do you have a simple codesandbox to illustrate the issue?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/utils/domUtils.ts]: I have reverted the change around :scope as it doesn't need to be in this PR, and it also doesn't seem to be that trivial. Move to #2115.
