### PR TITLE
[DataGrid] Fix SSR support

### LINKED ISSUE #98: Server-side rendering support
Rending the grid on the server fails on: 

https://github.com/mui-org/material-ui-x/blob/da5e83aa69291821e14218184d05a2c1c313bfd6/packages/grid/x-grid-modules/src/hooks/utils/useLogger.ts#L4

> ReferenceError: localStorage is not defined

This makes me also wonder. Do we want to bundle the `useLogger` package in production? Is there a way we could make is a noop when `process.env.NODE_ENV === 'production'`?

### PR DESCRIPTION
**Pull request by oliviertassinari**
Fix #98.

I didn't test the changes, I would need #115 for doing such but I hope it's good enough, finger crossed.

This is important so we can document the data grid components.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
I have tested the change manually, we are good, I'm merging to unlock #115.

File: packages/grid/x-grid-modules/src/hooks/utils/useLogger.ts [hunk 1]
```diff
@@ -40,31 +55,28 @@ const getAppender = (name: string, logLevel: string, appender: Logger = console)
...
-export type LoggerFactoryFn = (name: string) => Logger;
+type LoggerFactoryFn = (name: string) => Logger;
 
 // TODO Refactor to allow different logger for each grid in a page...
 let factory: LoggerFactoryFn | null;
+
 export function useLoggerFactory(
   customLogger?: Logger | LoggerFactoryFn,
-  logLevel: string | boolean = 'debug',
+  logLevel: string = 'debug',
```
Comment (dtassone) [inline packages/grid/x-grid-modules/src/hooks/utils/useLogger.ts:71]: the boolean was to turn off logging

Comment (oliviertassinari) [reply packages/grid/x-grid-modules/src/hooks/utils/useLogger.ts:71]: You are right. I have restored it in a follow up pull request. If you check master it should be back in here. It was creating TypeScript errors in the demos/stories but wasn't catch by the CI.

The CI part is now covered by building in Netlify the current commit, it's not ideal but it's a good first safeline.
