### PR TITLE
[DataGrid] GridMenu should not remove the anchor before the end of the closing transition

### LINKED ISSUE #2720: [DataGrid] Menu loses anchor when closing
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

szQU14d7fq

### Expected behavior 🤔

It should not appear outside the grid and it should close with a fade. Now it closes abruptly.

With MUI v4 it was working correctly. https://v4.mui.com/components/data-grid/components/#toolbar

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/toolbargrid-material-demo-forked-eh2bf
2. Open the Density menu
3. Click outside the menu to close it

### Context 🔦

I noticed this in #2714. It happens with all features that are based on `GridMenu`.

We are setting `open=false` and `target=null` at the same time. We should wait for the transition to end before removing the anchor: https://mui.com/components/popper/#transitions

https://github.com/mui-org/material-ui-x/blob/8afd596c40fabe9b2ce7531386cb6acdd280b157/packages/grid/_modules_/grid/components/toolbar/GridToolbarDensitySelector.tsx#L108-L109

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Closes #2720 

https://user-images.githubusercontent.com/3309670/135226242-4e47113b-9436-4a3d-9039-817bc3808f32.mp4

### CODE REVIEW

File: packages/grid/_modules_/grid/components/toolbar/GridToolbarDensitySelector.tsx [hunk 1]
```diff
@@ -21,7 +21,10 @@ export const GridToolbarDensitySelector = React.forwardRef<HTMLButtonElement, Bu
     const densityValue = useGridSelector(apiRef, gridDensityValueSelector);
     const densityButtonId = useId();
     const densityMenuId = useId();
-    const [anchorEl, setAnchorEl] = React.useState(null);
+
+    const [open, setOpen] = React.useState(false);
+    const buttonRef = React.useRef<HTMLButtonElement>(null);
+    const forkedButtonRef = useForkRef(ref, buttonRef);
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/components/toolbar/GridToolbarDensitySelector.tsx:27]: The return value is commonly named `handleRef` in the core.

```suggestion
    const handleRef = useForkRef(ref, buttonRef);
```

https://github.com/mui-org/material-ui/blob/b6977280a603551ff0e5412982b1464b48805cbf/packages/mui-core/src/SliderUnstyled/SliderUnstyled.js#L272

**Review by m4theushw — APPROVED** [review]
