### PR TITLE
[DataGrid] Fix checkbox selection issue

### LINKED ISSUE #283: [DataGrid] The intermediate state is lost when scrolling
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Capture d’écran 2020-09-14 à 12 18 32

## Expected Behavior 🤔

Capture d’écran 2020-09-14 à 12 18 35

## Steps to Reproduce 🕹

Steps:

1. https://master--material-ui-x.netlify.app/components/data-grid/#commercial-version
2. intermediate

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v0.1.67  |

### PR DESCRIPTION
**Pull request by dtassone**
Fix #283

### CODE REVIEW

File: packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx [hunk 1]
```diff
@@ -27,6 +27,15 @@ export const HeaderCheckbox: React.FC<ColParams> = React.memo(({ api }) => {
     return api.onSelectionChange(selectionChange);
   }, [api, selectionChange]);
 
+  React.useEffect(() => {
+    const selectedRows = api.getSelectedRows();
+    const allRowsCount = api.getAllRowIds().length;
+    const isCurrentChecked = selectedRows.length === allRowsCount;
+    const isCurrentIndeterminate = selectedRows.length > 0 && selectedRows.length !== selectedRows;
+    setChecked(isCurrentChecked);
+    setIndeterminate(isCurrentIndeterminate);
```
Comment (oliviertassinari) [inline packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:36]: Why have the logic in an effect? Would it be simpler to pull the value from the state at render time, with the context? 

How will we handle the controllable API? #246: https://next.material-ui.com/components/data-grid/selection/#controlled-selection

**Review by oliviertassinari — COMMENTED** [review]
I have tried to think at how we could test this fix. I can't think of a simple answer. Maybe it's one of these rare cases where we can ignore it.

File: packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx [hunk 2]
```diff
@@ -17,7 +17,7 @@ export const HeaderCheckbox: React.FC<ColParams> = React.memo(({ api }) => {
       const isAllSelected =
         api.getAllRowIds().length === event.rows.length && event.rows.length > 0;
       const hasNoneSelected = event.rows.length === 0;
-      setChecked(isAllSelected || !hasNoneSelected);
+      setChecked(isAllSelected && !hasNoneSelected);
```
Comment (oliviertassinari) [inline packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:20]: Are you sure?
Capture d’écran 2020-09-14 à 20 43 02

vs.

Capture d’écran 2020-09-14 à 20 42 56

Comment (dtassone) [reply packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:20]: For me, checked is when all checkbox are checked and none are unchecked
But up to you, I can change it

Comment (oliviertassinari) [reply packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:20]: It makes me think of https://github.com/mui-org/material-ui/issues/20476. No specific preference. It could simply surface that the **intermediate state should always have the same visual look** no matter the checked state. At least it seems to be what bootstrap, [ant design](https://stackblitz.com/edit/react-hjpsz4?file=index.js).

@eps1lon any tips on the matter?

Comment (eps1lon) [reply packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:20]: What's the question here? If this is about color then the mixed state should have the same color as the checked state. At least that's [how our Checkbox behaves](https://material-ui.com/components/checkboxes/#basic-checkboxes) so if it behaves different here then there should be a rationale that doesn't apply to the general purpose use case.

Also note that the color doesn't really matter anyway because of SC 1.4.1 in WCAG 2.x. If there's a difference between checked+indeterminate and checked+determinate then it needs to be encoded in something other than color as well. Though ARIA does not support both of these states but rather a single `"mixed"` state.

Comment (oliviertassinari) [reply packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:20]: OK awesome. I think that it perfectly answer the question, when `indeterminate` is set:

- It doesn't matter if checked is true or false, it's in a mixed state. 
- The color shouldn't change based on the checked state, if it does, it could incentive people to break 1.4.1. 

So as the next step, I propose:

- Here, we can do the change or note, it doesn't matter, so maybe use the new logic.
- On the main repository side, update the CSS so indeterminate unchecked has the primary color.

File: packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx (hunk 1 above)
Comment (eps1lon) [reply packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:36]: All these derived states should be computable at render time which the naming of the methods indicated. E.g. `get*` implies to me that there are now side-effects which means it's safe to call at render time. Then `getDerivedStateFromProps` would apply which has a documented pattern for hooks: https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops

File: packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx [hunk 3]
```diff
@@ -4,9 +4,14 @@ import { SelectionChangeParams } from '../models/params/selectionChangeParams';
...
-  const [isChecked, setChecked] = React.useState(false);
-  const [isIndeterminate, setIndeterminate] = React.useState(false);
+export const HeaderCheckbox: React.FC<ColParams> = ({ api }) => {
+  const selectedRows = api.getSelectedRows();
+  const allRowsCount = api.getAllRowIds().length;
+  const isCurrentIndeterminate = selectedRows.length > 0 && selectedRows.length !== selectedRows;
+  const isCurrentChecked = selectedRows.length === allRowsCount || isCurrentIndeterminate;
+
+  const [isChecked, setChecked] = React.useState(isCurrentChecked);
+  const [isIndeterminate, setIndeterminate] = React.useState(isCurrentIndeterminate);
```
Comment (eps1lon) [inline packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:14]: Does `api` not change if we select a different row? Seems very brittle to have individual components duplicate the logic of which row is considered checked and which isn't.

Comment (dtassone) [reply packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:14]: this is just the header checkbox

Comment (eps1lon) [reply packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:14]: It always starts out with "just this small component". If we have the choice between robust and brittle we might as well use robust. I guess `api` is not changing if the underlying data changes? How are "subscribers" usually notified when the data changes?

Comment (dtassone) [reply packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:14]: No Api is not changing. They can use an event handler to get latest data.

**Review by oliviertassinari — APPROVED** [review]

File: packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx [hunk 4]
```diff
@@ -4,9 +4,14 @@ import { SelectionChangeParams } from '../models/params/selectionChangeParams';
 import { ColParams } from '../models/params/colParams';
 import { CellParams } from '../models/params/cellParams';
 
-export const HeaderCheckbox: React.FC<ColParams> = React.memo(({ api }) => {
-  const [isChecked, setChecked] = React.useState(false);
-  const [isIndeterminate, setIndeterminate] = React.useState(false);
+export const HeaderCheckbox: React.FC<ColParams> = ({ api }) => {
```
Comment (oliviertassinari) [inline packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:7]: We do no longer need the memo?

Comment (oliviertassinari) [reply packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:7]: Would it make sense to pull the api from the context here?

Comment (dtassone) [reply packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx:7]: This is just an implementation of the col prop renderHeader.
So we pass api as a prop so it's easier for the user.
Yes users could use the context as well.

File: packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx (hunk 2 above)
Comment (oliviertassinari) [reply packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx]: > On the main repository side, we update the CSS so indeterminate unchecked has the primary color.

@dtassone Do you want to use this issue as an opportunity to make your first contribution to the core? :)
