### PR TITLE
[core] Polish filtering internals

### LINKED ISSUE #1709: [DataGrid] Filtering is reapplied when adding empty filters
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When an existing filter is applied and a new empty one is added, the rows are refiltered.

## Expected Behavior 🤔

When an existing filter is applied and a new empty one is added, the rows are not refiltered.

## Steps to Reproduce 🕹

Steps:

1. Open https://material-ui.com/components/data-grid/#commercial-version
2. Apply one filter
3. Click on "Add filter"
4. Notice how slow the UI is to respond to the previous click event. It takes about 1,000ms while it should take around 100ms.

slow filter

## Context 🔦

Noticed on #1506.

### PR DESCRIPTION
**Pull request by ZeeshanTamboli**
~Fix #1709~

~Let me know if this solution works and is fine.~

~Existing: https://material-ui.com/components/data-grid/#commercial-version After improvement: https://deploy-preview-1760--material-ui-x.netlify.app/components/data-grid/#commercial-version~

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts [hunk 1]
```diff
@@ -174,11 +174,18 @@ export const useGridFilter = (apiRef: GridApiRef, rowsProp: GridRowsProp): void
         };
         return newState;
       });
+
+      // When clicking on "Add Filter" (empty filter) we need not reapply the existing filter
+      if (Object.keys(item).length === 0) {
+        forceUpdate();
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:180]: Not sure about this solution, it seems to defer the problem. My assumption was that we shouldn't run the filtering logic when the non-empty filters are the same.

**Review by oliviertassinari — COMMENTED** [review]
We would need to add a test case, this should be straightforward by checking if the filter operator is called.

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts (hunk 1 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:180]: We could add an argument to control whether `applyFilters` should be called or not. When deleting the last filter, it's called twice.

**Comment by dtassone** [comment]
There are a few things to improve around this area which I'm going to pick up after I'm done with my PR.
I will fix this one along the way and refactor a few things in this hook.

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts (hunk 1 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:180]: @m4theushw Yeah, what I was expecting is `applyFilters` to be called as a response to changes in the filterModel, columns or rows **only**.

**Comment by oliviertassinari** [comment]
@dtassone Are you saying that we should close this PR, that you would rather own this effort?

File: packages/storybook/src/stories/grid-filter.stories.tsx [hunk 2]
```diff
@@ -261,8 +261,8 @@ export function ServerFilterViaProps() {
   );
 
   React.useEffect(() => {
-    applyFilter();
-  }, [applyFilter, demoServer.data.rows]);
+    applyFilters();
+  }, [applyFilters, demoServer.data.rows]);
```
Comment (oliviertassinari) [inline packages/storybook/src/stories/grid-filter.stories.tsx:265]: Correct terminology

File: packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx [hunk 3]
```diff
@@ -285,12 +280,12 @@ describe('<XGrid /> - Filter', () => {
       />,
     );
 
+    expect(handleFilterChange.callCount).to.equal(1);
     expect(getColumnValues()).to.deep.equal(['Adidas', 'Puma']);
     const input = screen.getByPlaceholderText('Filter value');
     fireEvent.change(input, { target: { value: 'ad' } });
     clock.tick(SUBMIT_FILTER_STROKE_TIME);
-    expect(visibleRows.size).to.equal(1);
-    expect(visibleRows.get(1)).to.deep.equal({ id: 1, brand: 'Adidas' });
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx:293]: I would argue that this assertion was wrong. Changing the filter model doesn't mean the rows are filtered.

File: packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx [hunk 4]
```diff
@@ -90,13 +88,13 @@ describe('<XGrid /> - Filter', () => {
   };
 
   it('should apply the filterModel prop correctly', () => {
-    render(<TestCase filterModel={model} />);
+    render(<TestCase filterModel={filterModel} />);
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx:91]: No shortcuts, creates confusion

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts [hunk 5]
```diff
@@ -305,6 +310,33 @@ export const useGridFilter = (apiRef: GridApiRef, rowsProp: GridRowsProp): void
...
+        apiRef.current.applyFilters();
+      }
+    });
+  }, [apiRef]);
+
+  React.useEffect(() => {
+    return apiRef.current.subscribeEvent(GRID_ROWS_UPDATED, () => {
+      apiRef.current.applyFilters();
+    });
+  }, [apiRef]);
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:338]: It seems that this was missing, we didn't explicitly depend on the row stream update API.

**Review by oliviertassinari — COMMENTED** [review]
I have pushed the changes one step further. It should solve the performance issue and improve the core logic.

File: packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx [hunk 6]
```diff
@@ -217,19 +215,19 @@ describe('<XGrid /> - Filter', () => {
...
-        onFilterModelChange={onFilterModelChange}
+        onFilterModelChange={handleFilterModelChange}
         state={{
           preferencePanel: { openedPanelValue: GridPreferencePanelsValue.filters, open: true },
         }}
       />,
     );
     // TODO should equal 0, the state doesn't change
-    expect(onFilterModelChange.callCount).to.equal(4);
+    expect(handleFilterModelChange.callCount).to.equal(1);
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx:225]: One step closer to the correct behavior.

**Comment by oliviertassinari** [comment]
Anyon  to review the changes I did? cc @mui-org/x

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts [hunk 7]
```diff
@@ -251,15 +253,20 @@ export const useGridFilter = (apiRef: GridApiRef, rowsProp: GridRowsProp): void
...
+        return;
+      }
+
       clearFilterModel();
       logger.debug('Setting filter model');
-      applyFilterLinkOperator(model.linkOperator);
-      model.items.forEach((item) => upsertFilter(item));
-
+      setFilterLinkOperator(filterModel.linkOperator, true);
+      filterModel.items.forEach((item) => upsertFilter(item, true));
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:266]: You might want to check that length > 1 instead of true

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts [hunk 8]
```diff
@@ -305,6 +310,33 @@ export const useGridFilter = (apiRef: GridApiRef, rowsProp: GridRowsProp): void
...
+  const prevFilterModelRef = React.useRef();
+
+  React.useEffect(() => {
+    return apiRef.current.subscribeEvent(GRID_FILTER_MODEL_CHANGE, (params) => {
+      const prevFilterModel = prevFilterModelRef.current;
+      prevFilterModelRef.current = params.filterModel;
+
+      const trimFilterModel = (filterModel) => ({
+        ...filterModel,
+        items: filterModel.items.filter((item) => item.value !== undefined),
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:322]: That should be handled by applyFilters. I don't think it should be in the effect

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts (hunk 5 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:338]: Not necessary it seems, it was working before. Check /story/x-grid-tests-streaming--single-subscription-fast

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts [hunk 9]
```diff
@@ -115,28 +115,26 @@ export const useGridFilter = (apiRef: GridApiRef, rowsProp: GridRowsProp): void
...
-      apiRef.current.applyFilter(filterItem, linkOperator);
+      applyFilter(filterItem, linkOperator);
     });
     forceUpdate();
-  }, [apiRef, clearFilteredRows, forceUpdate, options.filterMode]);
+  }, [apiRef, clearFilteredRows, forceUpdate, options.filterMode, applyFilter]);
 
   const upsertFilter = React.useCallback(
-    (item: GridFilterItem) => {
+    (item: GridFilterItem, batch: boolean = false) => {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:137]: batch 🤔 
hasMultiple?

File: packages/grid/_modules_/grid/models/api/gridFilterApi.ts [hunk 10]
```diff
@@ -20,12 +20,6 @@ export interface GridFilterApi {
    * @param {GridFilterItem} item The filter to update.
    */
   upsertFilter: (item: GridFilterItem) => void;
-  /**
-   * Applies a [[GridFilterItem]] on alls rows. If no `linkOperator` is given, the "and" operator is used.
-   * @param {GridFilterItem} item The filter to be applied.
-   * @param {GridLinkOperator} linkOperator The link operator to use.
-   */
-  applyFilter: (item: GridFilterItem, linkOperator?: GridLinkOperator) => void;
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/models/api/gridFilterApi.ts:28]: This makes the PR a breaking change. I've updated the description to provide an alternative.

File: packages/grid/_modules_/grid/models/api/gridFilterApi.ts [hunk 11]
```diff
@@ -39,7 +33,7 @@ export interface GridFilterApi {
    * Changes the [[GridLinkOperator]] used to connect the filters.
    * @param {GridLinkOperator} operator The new link operator. It can be: `"and"` or `"or`".
    */
-  applyFilterLinkOperator: (operator: GridLinkOperator) => void;
+  setFilterLinkOperator: (operator: GridLinkOperator) => void;
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/models/api/gridFilterApi.ts:36]: This makes the PR a breaking change. I've updated the description to provide an alternative.

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts (hunk 9 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:137]: skipModelChangePublishing?

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts [hunk 12]
```diff
@@ -305,6 +310,33 @@ export const useGridFilter = (apiRef: GridApiRef, rowsProp: GridRowsProp): void
     }
   }, [apiRef, clearFilteredRows, logger, rowsProp]);
 
+  const prevFilterModelRef = React.useRef();
+
+  React.useEffect(() => {
+    return apiRef.current.subscribeEvent(GRID_FILTER_MODEL_CHANGE, (params) => {
```
Comment (DanailH) [inline packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:316]: it will look cleaner if you move that function in its own definition, like `handleFilterModelChange` or smth.

File: packages/grid/_modules_/grid/models/api/gridFilterApi.ts (hunk 11 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/models/api/gridFilterApi.ts:36]: Is this change necessary? The logic of the method is more or less the same.

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts (hunk 5 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:338]: My bad, I don't know how to read. It was already there, at the top of the file.

**Comment by oliviertassinari** [comment]
I'm giving up on the changes, I went down a rabbit hole that would have taken me the whole day. Instead, I have updated the PR to only keep the cleanup that is safe to go in.

**Review by dtassone — APPROVED** [review]
