### PR TITLE
[DataGrid] Refactor keyboard/click event management

### LINKED ISSUE #3265: [DataGrid] Pressing Shift + space should select new row without having to unselect the other row first
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently non multi select keyboard row selection on a datagrid requires a user to unselect a row, via shift + space, before another row can be selected.

### Expected behavior 🤔

Row selection for non multi select keyboard selection should behave the same as mouse click where it moves and selects the new row after a user presses shift + space

https://codesandbox.io/s/datagridprodemo-material-demo-forked-lostt?file=/demo.js

### Steps to reproduce 🕹

https://codesandbox.io/s/datagridprodemo-material-demo-forked-lostt?file=/demo.js

Steps:

1. Select a row in the grid with your mouse
2. navigate table to another row via arrows (stay in first column where edit cell won't be enabled)
3. click shift + space - nothing happens
4. navigate via keyboard to selected row, and deselect row with shift + space
5. navigate table to another row via arrows (stay in first column where edit cell won't be enabled)
6. click shift + space, new row is now selected

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Browser: Chrome 95.0.4638.69 
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.29)
  npmPackages:
    @emotion/react: 11.5.0 => 11.5.0
    @emotion/styled: 11.3.0 => 11.3.0
    @mui/core:  5.0.0-alpha.54
    @mui/icons-material: 5.1.0 => 5.1.0
    @mui/lab: 5.0.0-alpha.54 => 5.0.0-alpha.54
    @mui/material: 5.1.0 => 5.1.0
    @mui/private-theming:  5.1.0
    @mui/styled-engine:  5.1.0
    @mui/styles: 5.1.0 => 5.1.0
    @mui/system:  5.1.0
    @mui/types:  7.1.0
    @mui/utils:  5.1.1
    @mui/x-data-grid-pro: 5.0.1 => 5.0.1
    @mui/x-license-pro:  5.0.1
    @types/react:  17.0.1
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
```
</details>

### Order ID 💳 (optional)
#3197

### LINKED ISSUE #3272: [Datagrid] isRowSelectable={false}  / disableSelectionOnClick={true}
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Cannot disable row selection on the datagrid using the following two props when using the keyboard (shift + space)
isRowSelectable={false}
disableSelectionOnClick={true}

### Expected behavior 🤔

above properties should work the same for mouse click and keyboard control
in this case the rows should not be selectable

### Steps to reproduce 🕹

https://codesandbox.io/s/disablerowselection-material-demo-forked-fu98t?file=/demo.js

Steps:
1. Click on the row with a mouse
2. No selection
3. Use the keyboard and move to another row
4. press space + keybaord
5. row will be selected

### Context 🔦

trying to disable row selection for table

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
```
  Don't forget to mention which browser you used.
  Browser:  Chrome - Version 96.0.4664.45 (Official Build) (64-bit)

  Output from `npx @mui/envinfo` goes here.
System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.29)
  npmPackages:
    @emotion/react: 11.5.0 => 11.5.0 
    @emotion/styled: 11.3.0 => 11.3.0 
    @mui/core:  5.0.0-alpha.54 
    @mui/icons-material: 5.1.0 => 5.1.0 
    @mui/lab: 5.0.0-alpha.54 => 5.0.0-alpha.54 
    @mui/material: 5.1.0 => 5.1.0 
    @mui/private-theming:  5.1.0 
    @mui/styled-engine:  5.1.0 
    @mui/styles: 5.1.0 => 5.1.0 
    @mui/system:  5.1.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.1.1 
    @mui/x-data-grid-pro: 5.0.1 => 5.0.1 
    @mui/x-license-pro:  5.0.1 
    @types/react:  17.0.1 
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
```
</details>

### Order ID 💳 (optional)

319##

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #3265 and fix  #3272

This is a first step to handle all the keyboard events in their feature hook https://github.com/mui-org/material-ui-x/issues/3265#issuecomment-977898327

### CODE REVIEW

**Comment by alexfauquette** [comment]
The `handleCellKeyDown` can not be completely merged with `handleCellNavigationKeyDown` because of the early return

```
if ((event.target as any).nodeType === 1 && !isGridCellRoot(event.target as Element)) {
        return;
}
```

this condition prevents from applying keyboard shortcuts if the focus is not on a cell component (for example a select input)

To apply keyboard events inside cells (for example when the focus is on a button) the event `cellNavigationKeyDown` is dispatched. This one triggers `handleCellNavigationKeyDown` which does not check if the `event.target` is a Cell component.

So the solution still needs improvement, but at least it solves the two issues

File: packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx [hunk 1]
```diff
@@ -103,7 +103,7 @@ const GridHeaderCheckbox = React.forwardRef<HTMLInputElement, GridColumnHeaderPa
           event.stopPropagation();
         }
         if (isNavigationKey(event.key) && !event.shiftKey) {
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx:105]: Shouldn't we fire the `columnHeaderKeyDown` on any key, not just navigation one ?

**Review by flaviendelangle — COMMENTED** [review]
To avoid breaking changes, we should still fire `columnHeaderNavigationKeydown` even if we do not use it internally.

File: packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts [hunk 2]
```diff
@@ -326,6 +334,34 @@ export const useGridSelection = (
...
+      }
+
+      // Get the most recent params because the cell mode may have changed by another listener
+      const cellParams = apiRef.current.getCellParams(params.id, params.field);
+      const isEditMode = cellParams.cellMode === GridCellModes.Edit;
+      if (isEditMode) {
+        return;
+      }
+
+      if (isSpaceKey(event.key) && event.shiftKey) {
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts:352]: Since this is new code, let's avoid these one line helpers.

```suggestion
      if (event.key === ' ' && event.shiftKey) {
```

File: packages/grid/_modules_/grid/utils/domUtils.ts [hunk 3]
```diff
@@ -24,6 +24,10 @@ export function isGridHeaderCellRoot(elem: Element | null): boolean {
   return elem != null && elem.classList.contains(gridClasses.columnHeader);
 }
 
+export function isGridHeaderSelectAllCheckBox(elem: Element | null): boolean {
+  return elem != null && elem.ariaLabel === 'Select All Rows checkbox';
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/utils/domUtils.ts:28]: It could have been translated.

File: packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts [hunk 4]
```diff
@@ -157,11 +158,17 @@ export const useGridKeyboardNavigation = (
...
 
-  const handleColumnHeaderNavigationKeyDown = React.useCallback<
+  const handleColumnHeaderKeyDown = React.useCallback<
     GridEventListener<GridEvents.columnHeaderNavigationKeyDown>
   >(
     (params, event) => {
       event.preventDefault();
+      if (
+        !isGridHeaderCellRoot(event.target as HTMLElement) &&
+        !isGridHeaderSelectAllCheckBox(event.target as HTMLElement)
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts:168]: Checking `params.field` is safer.

File: packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx (hunk 1 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx:105]: Should we remove this handler and let `columnHeaderKeyDown` to propagate freely?

**Review by m4theushw — COMMENTED** [review]
> This is a draft PR to explain the proposed solution in #3265 (comment)

Is it still in draft? I don't know how rigorous should I review it.

image

File: packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts [hunk 5]
```diff
@@ -68,12 +64,7 @@ export const useGridKeyboard = (apiRef: GridApiRef): void => {
       }
 
       if (isSpaceKey(event.key) && event.shiftKey) {
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts:66]:
```suggestion
      if (event.key === ' ' && event.shiftKey) {
```

File: packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts [hunk 6]
```diff
@@ -68,12 +64,7 @@ export const useGridKeyboard = (apiRef: GridApiRef): void => {
...
-        event.preventDefault();
-        apiRef.current.selectRow(
-          cellParams.id,
-          !apiRef.current.isRowSelected(cellParams.id),
-          false,
-        );
+        // This is a select event
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts:67]:
```suggestion
        // This is a select event, so it's handled by the selection hook
```

File: packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts [hunk 7]
```diff
@@ -326,6 +333,34 @@ export const useGridSelection = (
     [apiRef, props.checkboxSelectionVisibleOnly, props.pagination],
   );
 
+  const handleCellKeyDown = React.useCallback<GridEventListener<GridEvents.cellKeyDown>>(
+    (params, event) => {
+      // The target is not an element when triggered by a Select inside the cell
+      // See https://github.com/mui-org/material-ui/issues/10534
+      if ((event.target as any).nodeType === 1 && !isGridCellRoot(event.target as Element)) {
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts:340]: In #3220, I changed the original code you copied this from.

File: packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts [hunk 8]
```diff
@@ -326,6 +333,34 @@ export const useGridSelection = (
...
+      // Get the most recent params because the cell mode may have changed by another listener
+      const cellParams = apiRef.current.getCellParams(params.id, params.field);
+      const isEditMode = cellParams.cellMode === GridCellModes.Edit;
+      if (isEditMode) {
+        return;
+      }
+
+      if (event.key === ' ' && event.shiftKey) {
+        event.preventDefault();
+        handleSingleRowSelection(cellParams.id, event);
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts:353]: As a good practice.

```suggestion
        handleSingleRowSelection(cellParams.id, event);
        return;
```

File: packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts [hunk 9]
```diff
@@ -253,35 +255,40 @@ export const useGridSelection = (
     }
   }, [apiRef]);
 
+  const handleSingleRowSelection = React.useCallback(
+    (id: GridRowId, event: React.MouseEvent | React.KeyboardEvent) => {
+      const hasCtrlKey = event.metaKey || event.ctrlKey;
+
+      // Without checkboxSelection, multiple selection is only allowed if CTRL is pressed
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts:262]: > Without checkboxSelection, multiple selection **via click** is only allowed if CTRL is pressed

There's a regression here. I can't select multiple rows with <kbd>Shift</kbd> + click. Try in https://deploy-preview-3275--material-ui-x.netlify.app/components/data-grid/selection/#multiple-row-selection.



wxWSSCssDd

**Review by m4theushw — COMMENTED** [review]
It would be nice to add some test cases to cover the fixed issues.

File: packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts (hunk 9 above)
Comment (flaviendelangle) [reply packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts]: Did a test fail for this bug ? If not could we add one ?

File: packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx [hunk 10]
```diff
@@ -83,6 +83,48 @@ describe('<DataGrid /> - Selection', () => {
     });
   });
 
+  describe('props: checkboxSelection = false (single selection), with keyboard events', () => {
+    it('should select one row at a time on Shift + Space', () => {
+      render(<TestDataGridSelection />);
+      getCell(0, 0).focus();
+      fireEvent.keyDown(document.activeElement || document.body, { key: ' ', shiftKey: true });
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx:90]: Why `document.activeElement || document.body`? This will snooze the ESLint rule "Don't use document.activeElement as a target for keyboard events.". You can pass the cell element as bellow:

https://github.com/mui-org/material-ui-x/blob/1d82bea672afc1ece26739a47b2de7ae298de9bc/packages/grid/x-data-grid-pro/src/tests/clipboard.DataGridPro.test.tsx#L91-L93

File: packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx [hunk 11]
```diff
@@ -83,6 +83,48 @@ describe('<DataGrid /> - Selection', () => {
...
+      expect(getSelectedRowIds()).to.deep.equal([0]);
+
+      fireEvent.keyDown(document.activeElement || document.body, { key: 'ArrowDown' });
+      fireEvent.keyDown(document.activeElement || document.body, { key: ' ', shiftKey: true });
+
+      expect(getSelectedRowIds()).to.deep.equal([1]);
+    });
+
+    it(`should not deselect the selected row on Shift + Space`, () => {
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx:99]: It should. At least, this is how https://mui.com/components/data-grid/selection/#single-row-selection is working.

**Review by m4theushw — COMMENTED** [review]
We miss a test for https://github.com/mui-org/material-ui-x/pull/3275#discussion_r762361739 in `selection.DataGridPro.test.tsx`.

File: packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx (hunk 10 above)
Comment (alexfauquette) [reply packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx:90]: Not really, it is to follow the documentation :)
 > This will also test that the element in question can even receive keyboard events

https://testing-library.com/docs/guide-events#keydown

**Comment by alexfauquette** [comment]
@m4theushw I added a commit to prevent keyboard "Shift+Space" from starting editing the cell, which is a pain when selecting rows in an editable DataGrid

File: packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx (hunk 10 above)
Comment (m4theushw) [reply packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx:90]: The element is passed to improve readability: https://github.com/mui-org/material-ui/pull/20945

> This will also test that the element in question can even receive keyboard events
 
This check is embedded into the custom `fireEvent` we use. See https://github.com/mui-org/material-ui/blob/69b7e4d911e8ff99d17a74330496ae69e7cc0ade/test/utils/createRenderer.tsx#L622

File: packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts (hunk 9 above)
Comment (alexfauquette) [reply packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts]: I added a unit test to verify that with multiple select (checkboxes activated) the Shift+Space allows to select multiple lines

File: packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx (hunk 10 above)
Comment (alexfauquette) [reply packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx]: I've done the modifications, but I'm not really convinced that it improves readability

The core team has element which are all meaning full, leading to testing code such as 
```js
fireEvent.keyDown(button, ...);
fireEvent.keyDown(firstTab, ...);
```

We are navigating between cells so most of the components with focus are cells which only differ by there coordinates which is translated by
```js
fireEvent.keyDown(cell01, ...);
fireEvent.keyDown(cell23, ...);
```

Comment (m4theushw) [reply packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx]: Take as example the following test case:

```tsx
expect(getActiveCell()).to.equal('8-1');
fireEvent.keyDown(document.activeElement!, { key: 'ArrowDown' });
fireEvent.keyDown(document.activeElement!, { key: 'ArrowRight' });
fireEvent.keyDown(document.activeElement!, { key: 'ArrowLeft' });
fireEvent.keyDown(document.activeElement!, { key: 'ArrowUp' });
```

Can you easily spot where the focus is after the last `keyDown`? 😛

**Review by m4theushw — APPROVED** [review]
Good job.

File: packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts [hunk 12]
```diff
@@ -163,10 +162,7 @@ export const useGridKeyboardNavigation = (
...
     (params, event) => {
       event.preventDefault();
-      if (
-        !isGridHeaderCellRoot(event.target as HTMLElement) &&
-        !isGridHeaderSelectAllCheckBox(event.target as HTMLElement)
-      ) {
+      if (!params.field) {
         return;
       }
       const dimensions = apiRef.current.getRootDimensions();
```
Comment (alexfauquette) [inline packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts:168]: This modification
