### PR TITLE
[DataGrid] Fix `onPageChange` doesn't update the `page` when a pagination button is clicked

### LINKED ISSUE #1711: [DataGrid] `onPageChange` doesn't update the `page` when a pagination button is clicked
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

With the update to [4.0.0-alpha.29](https://github.com/mui-org/material-ui-x/releases/tag/v4.0.0-alpha.29), the `onPageChange` function no longer increment/decrements the `page`.

## Expected Behavior 🤔

Prior to v4.0.0-alpha.29 the `page` parameter from the `onPageChange` function would increment/decrement when a pagination button is clicked.

## Steps to Reproduce 🕹

Repo [here](https://github.com/mattcarlotta/datagrid-jsdom-bug/tree/pagination).

Instructions can be found [here](https://github.com/mattcarlotta/datagrid-jsdom-bug/blob/pagination/README.md).

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
System:
    OS: Linux 5.8 Linux Mint 20.1 (Ulyssa)
  Binaries:
    Node: 14.17.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.13 - /usr/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @material-ui/core: ^4.11.4 => 4.11.4 
    @material-ui/data-grid: ^4.0.0-alpha.29 => 4.0.0-alpha.29 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  17.0.4 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.2.4 => 4.2.4
```
</details>

### PR DESCRIPTION
**Pull request by ZeeshanTamboli**
Fixes #1711

In `setPage` and `setPageSize`, `applyConstraints` should not pass `options.page` as page is already set by `params.page`. Page prop `options.page` _if supplied_ is always set as `page` in state. So here in page change it should not be supplied.

Preview: https://deploy-preview-1719--material-ui-x.netlify.app/components/data-grid/pagination/#controlled-pagination

### CODE REVIEW

**Comment by mattcarlotta** [comment]
Just a heads up, not sure if this is related to this PR, but hovering over the table seems to trigger the "source" tooltip:

[Current demo](https://material-ui.com/components/data-grid/pagination/#controlled-pagination)
[PR demo](https://deploy-preview-1719--material-ui-x.netlify.app/components/data-grid/pagination/#controlled-pagination)

https://user-images.githubusercontent.com/22607722/119021084-dad8d680-b953-11eb-8b5e-6e9eb8a40606.mp4

**Review by oliviertassinari — CHANGES_REQUESTED** [review]

File: packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts [hunk 1]
```diff
@@ -38,13 +38,10 @@ export const useGridPagination = (apiRef: GridApiRef): void => {
 
       setGridState((state) => ({
         ...state,
-        pagination: applyConstraints(
-          {
-            ...state.pagination,
-            page,
-          },
-          options.page,
```
[the remark this answers is not in the document]
Comment (ZeeshanTamboli) [reply packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts:46]: As far as I debugged through code I came to the conclusion that,

**1.** Initially on render, if the `page` prop is provided (controlled mode), the two effects run at:
https://github.com/mui-org/material-ui-x/blob/9953f25ca0f5d0c60777e2717dd8d11d4ea0249b/packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts#L86
https://github.com/mui-org/material-ui-x/blob/9953f25ca0f5d0c60777e2717dd8d11d4ea0249b/packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts#L111
and `applyConstraints` apply the pageProp at (line 23) through `options.prop`: 
https://github.com/mui-org/material-ui-x/blob/9953f25ca0f5d0c60777e2717dd8d11d4ea0249b/packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts#L16-L25

**2.** When the `page` prop is not provided (uncontrolled mode), it picks the `state.page` in `applyConstraints`. (line 23)

And when page is changed on click, the `setPage` is triggered and there it is setting the `page` of `GridPageChangeParams` from params at:
https://github.com/mui-org/material-ui-x/blob/9953f25ca0f5d0c60777e2717dd8d11d4ea0249b/packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts#L35-L48
(line 42-44) and thus no need to pass `options.page` at line 46. (for both uncontrolled and controlled mode)

Similarly for `setPageSize`, I think no need to pass `options.page`.

[the remark this answers is not in the document]
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts:46]: From what I understood, the purpose of `applyConstraints` is to make sure that the new page number or new page size is within the limits. In both effects, the prop value should be used because in controlled mode the user could send an off-limit value. But, in `setPage` and `setPageSize`, the source of truth is the value in the argument, no prop should be considered.

---

I don't know if everyone agrees, but I think we should change the signature of `applyConstraints` to:

```diff
-function applyConstraints(state: GridPaginationState, pageProp?: number): GridPaginationState {
+function applyConstraints(state: GridPaginationState, newPage?: number, newPageSize?: number): GridPaginationState 
```
Where:
- `state` is always `state.pagination` with the old page and page size
- `newPage` is the new page number - it comes from the prop or the argument
- `newPageSize` is the new page size - it comes from the prop or the argument

The function returns the updated state with the new values clamped to the limits.

File: packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx [hunk 2]
```diff
@@ -90,6 +91,34 @@ describe('<DataGrid /> - Pagination', () => {
...
+        const handleOnPageChange = (params: GridPageChangeParams) => {
+          setPage(params.page);
+        };
+
+        return (
+          <div style={{ width: 300, height: 300 }}>
+            <DataGrid
+              {...baselineProps}
+              page={page}
+              onPageChange={handleOnPageChange}
```
Comment (m4theushw) [inline packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:107]: Instead of testing if the pagination works, could you use a `spy` here and check if `params.page` is the right value?

File: packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (ZeeshanTamboli) [reply packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts:46]: > In both effects, the prop value should be used because in controlled mode the user could send an off-limit value. But, in setPage and setPageSize, the source of truth is the value in the argument, no prop should be considered.

Correct, this is what I also found out. And thus removed passing of  page prop`options.page`

File: packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx (hunk 2 above)
Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:107]: The issue is not if `params.page` value is right or wrong. It's right even now in current release. The issue is that page prop seems to take precedence over `params.page` during changing of page.

Comment (m4theushw) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:107]: Actually, the issue is that the value of `params.page` is wrong. The idea of a `spy` is to check that the callback is called with the right params and that we'll not break this again in the future. If, instead of calling `setPage(params.page)`, I call `setPage(page > 1 ? page - 1 : page + 1)` the test will also be green but the params could be wrong.

https://codesandbox.io/s/material-demo-forked-w7ynh?file=/demo.js

YEAl9QrVt6

Comment (oliviertassinari) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:107]: @m4theushw Correct, I was about to make the same feedback. The current test is not as good as it could be. This #1711 issue is interesting as it surfaces how the previous logic was not following the convention. If the state is controlled, the internal state should never be the source of truth. I'm not sure how this bug should be fixed. In `GridPagination` we call `apiRef!.current!.setPage` with the new value. Maybe setPage should fire a `GRID_PAGESIZE_CHANGE` event (not `GRID_PAGESIZE_CHANGED`).

Comment (m4theushw) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:107]: > If the state is controlled, the internal state should never be the source of truth. I'm not sure how this bug should be fixed.

@oliviertassinari I didn't understand this statement. The `onPageChange` should be called with the new page number, so it can be used to update the `page` prop. It's the same as in a Select component, where the callback is always called with the new value, not the prop value.

> Maybe setPage should fire a GRID_PAGESIZE_CHANGE event (not GRID_PAGESIZE_CHANGED).

Yeah, this event is not following our convention. #1383

Comment (oliviertassinari) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:107]: > I didn't understand this statement.

I meant that I have seen controlled states that aren't. You could see the grid change the internal value, and the screen just after is reverted back by the parent of the grid.

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:107]: > Actually, the issue is that the value of params.page is wrong. The idea of a spy is to check that the callback is called with the right params and that we'll not break this again in the future. If, instead of calling setPage(params.page), I call setPage(page > 1 ? page - 1 : page + 1) the test will also be green but the params could be wrong.

@m4theushw You are correct. I was checking the internal `setPage` params at:
```js
  const setPage = React.useCallback(
    (page: number) => {
      logger.debug(`Setting page to ${page}`);
      console.log('Setting page to: ', page);
      setGridState((state) => ({
        ...state,
        pagination: applyConstraints(
          {
            ...state.pagination,
            page,
          },
          options.page,
        ),
      }));
      forceUpdate();
```

https://user-images.githubusercontent.com/20900032/119152554-09e36b00-ba6e-11eb-8018-9925f6ed796c.mov

But the event `GRID_PAGE_CHANGED` was publishing wrong `params` which gets published after the internal state through `applyConstraints` is updated. I will update the test. Thanks.

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx]: Updated the test case.

File: packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx [hunk 3]
```diff
@@ -90,6 +90,21 @@ describe('<DataGrid /> - Pagination', () => {
...
+      render(
+        <div style={{ width: 300, height: 300 }}>
+          <DataGrid {...baselineProps} page={1} onPageChange={onPageChange} pageSize={1} />
+        </div>,
+      );
+
+      fireEvent.click(screen.getByRole('button', { name: /next page/i }));
+      expect(onPageChange.lastCall.args[0].page).to.equal(2);
+      fireEvent.click(screen.getByRole('button', { name: /previous page/i }));
+      expect(onPageChange.lastCall.args[0].page).to.equal(1);
```
Comment (oliviertassinari) [inline packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:105]: The state doesn't change, it should be:

```suggestion
      expect(onPageChange.lastCall.args[0].page).to.equal(0);
```

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:105]: > The state doesn't change

🤔  Umm, the state changes whenever the `onPageChange` is called. It changes here:
```js
setGridState((state) => ({
        ...state,
        pagination: applyConstraints({
          ...state.pagination,
          page,
        }),
      }));
```
I did not get you. If you click previous it will change from 2 to 1. How come directly `0`?

Comment (oliviertassinari) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:105]: > If you click previous it will change from 2 to 1. 

No, it doesn't change, the page stays on 1 because the state is controlled and forced on 1.

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:105]: So are you saying the `page` prop isn't for setting current page when the DataGrid is loaded initially? And when it is forced with the prop (hardcoded), the user can't paginate? And when `onPageChange` is applied, it still shouldn't paginate?

> the page always stays on 1 

And you suggested code change above from `1` to `0`, now you are saying page always stays on `1`... 

> The page doesn't change, the page always stays on 1 because the state is controlled and forced with the prop.

I am talking about `params.page`, are you saying that `params.page` doesn't change? I am testing parameters page.

Comment (m4theushw) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:105]: Your test is right in asserting that `params.page` is equal to 1. We need to ensure that it's called with the right value.

The concern raised by @oliviertassinari is valid, but I think we should address it in another PR, since it was already working this way before the regression. In controlled mode, there shouldn't be any change to the state. The `page` prop, and only it, controls the pagination. What we should do is to call `onPageChange` with the new page number, but is the developer who is responsible for updating the `page` prop with the value received. No `setGridState` calls in controlled mode.

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx:105]: Okay. I was getting a bit confused by what Olivier meant. Also I apologise, if I sounded rude here in  https://github.com/mui-org/material-ui-x/pull/1719#discussion_r637062864. I am also trying my best to understand and fix the bug. 
I would say it is all fine now but only if we all agree.

**Review by oliviertassinari — APPROVED** [review]
I have pushed an extra commit to simplify the logic (less code). The fix is +2 LOC. But I have used the opportunity to improve the logic I could find.

**Comment by ZeeshanTamboli** [comment]
> I have pushed an extra commit to simplify the logic (less code). The fix is +2 LOC. But I have used the opportunity to improve the logic I could find.

Thanks, now I understood if it is forced with the page prop it should stay on that page even on page change.

File: packages/grid/_modules_/grid/constants/eventsConstants.ts [hunk 4]
```diff
@@ -346,16 +346,16 @@ export const GRID_COLUMN_HEADER_DRAG_END = 'columnHeaderDragEnd';
 export const GRID_SELECTION_CHANGED = 'selectionChange';
 
 /**
- * Fired when the current page has changed. Called with a [[GridPageChangeParams]] object.
+ * Fired when the current page change. Called with a [[GridPageChangeParams]] object.
  * @event
  */
-export const GRID_PAGE_CHANGED = 'pageChange';
+export const GRID_PAGE_CHANGE = 'pageChange';
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/constants/eventsConstants.ts:352]: Per our naming convention, this is both a breaking change and a bug fix, depending on how you see it. Since we are leaning toward documenting `pageChange` and have developers figure out the import name (based on @m4theushw PR), I would see this more as a bug fix.

File: packages/grid/_modules_/grid/constants/eventsConstants.ts [hunk 5]
```diff
@@ -346,16 +346,16 @@ export const GRID_COLUMN_HEADER_DRAG_END = 'columnHeaderDragEnd';
...
 
 /**
- * Fired when the page size has changed. Called with a [[GridPageChangeParams]] object.
+ * Fired when the page size change. Called with a [[GridPageChangeParams]] object.
  * @event
  */
-export const GRID_PAGESIZE_CHANGED = 'pageSizeChange';
+export const GRID_PAGESIZE_CHANGE = 'pageSizeChange';
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/constants/eventsConstants.ts:358]: Next, we need to rename it:

```suggestion
export const GRID_PAGE_SIZE_CHANGE = 'pageSizeChange';
```

File: packages/grid/_modules_/grid/constants/eventsConstants.ts (hunk 4 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/constants/eventsConstants.ts:352]: Yes, I would keep it as a breaking change, but once the documentation for events is up we could stop documenting constant **name** changes and only focus on constant **value** changes.
