### PR TITLE
[DataGrid] Fix invalid translation key

### LINKED ISSUE #1500: [DataGrid] Error "Missing translation for key filterOperator..." when using GridToolbar filter with number column
- [x] The issue is present in the latest release.
**This issue presents in latest 4.0.0-alpha.26 and 4.0.0-alpha.25, but does not present in 4.0.0-alpha.24**

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
In DataGrid with GridToolbar using filter on column with type 'number' causes error "Missing translation for key filterOperator".

## Expected Behavior 🤔
no error

## Steps to Reproduce 🕹

Steps:

1. Go to example of using toolbar in DataGrid documentation ( https://material-ui.com/components/data-grid/filtering/#toolbar) 
2. Click on "Edit in CodeSandbox" button for this example
3. In example opened in CodeSandbox click "FILTERS" button in toolbar and clear current filter ("Commodity contains 'rice'")
4. Click FILTERS button again and set some filter for "Quantity" column (e.g. Quantity > 100)
5. Click somewhere outside of the filter (below the table). 

An error appears "Missing translation for key filterOperator>."

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #1500

### CODE REVIEW

File: packages/grid/_modules_/grid/models/gridFilterItem.ts [hunk 1]
```diff
@@ -3,6 +3,7 @@ export interface GridFilterItem {
   columnField?: string;
   value?: string;
   operatorValue?: string;
+  operatorLabel?: string;
```
Comment (dtassone) [inline packages/grid/_modules_/grid/models/gridFilterItem.ts:6]: we already have a label in `GridFilterOperator`, can we use this one?

Comment (DanailH) [reply packages/grid/_modules_/grid/models/gridFilterItem.ts:6]: that is the object that is being passed to the tooltip. Basically, if the filter operator has a filter it will pass it along. Since the numeric operators are the only ones that have a label only then will that value be present? It doesn't add anything new, only passes values along. and it is optional.

**Review by dtassone — APPROVED** [review]

**Comment by dtassone** [comment]
I think I approved too fast

File: packages/grid/_modules_/grid/models/gridFilterItem.ts (hunk 1 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/models/gridFilterItem.ts:6]: I see.
The issue is that now we are exposing this new prop to the users as part of the filter model. Also it will only work in the toolbar button as we use the operator label in the filter form.
So I think, we need to load the operators from the `ColDef` in the toolbar button, so we get its label...

File: packages/grid/_modules_/grid/components/toolbar/GridFilterToolbarButton.tsx [hunk 2]
```diff
@@ -51,9 +51,12 @@ export const GridFilterToolbarButton = React.forwardRef<HTMLButtonElement, Butto
               ...(lookup[item.columnField!] && (
                 <li key={item.id}>
                   {`${lookup[item.columnField!].headerName || item.columnField}
-                  ${apiRef!.current.getLocaleText(
-                    `filterOperator${capitalize(item.operatorValue!)}` as GridTranslationKeys,
-                  )}
+                  ${
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/toolbar/GridFilterToolbarButton.tsx:54]: This is better as it avoids modifying the model
```tsx
const getOperatorLabel = (item: GridFilterItem):string=>
        lookup[item.columnField!].filterOperators!.find((operator) => operator.value === item.operatorValue)!.label
        || apiRef!.current!.getLocaleText(
          `filterOperator${capitalize(item.operatorValue!)}` as GridTranslationKeys,
        )!.toString();

      return (
        <div>
          {apiRef!.current.getLocaleText('toolbarFiltersTooltipActive')(counter)}
          <ul className={classes.list}>
            {activeFilters.map((item) => ({
              ...(lookup[item.columnField!] && (
                <li key={item.id}>
                  {`${lookup[item.columnField!].headerName || item.columnField}
                  ${getOperatorLabel(item)}
                  ${item.value}`}
                </li>
              )),
            }))}
          </ul>
        </div>
      );
```

**Review by dtassone — CHANGES_REQUESTED** [review]

File: packages/grid/_modules_/grid/components/toolbar/GridFilterToolbarButton.tsx (hunk 2 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/toolbar/GridFilterToolbarButton.tsx:54]: +1 for keeping the controllable state as lean as possible (what we can a model, BTW the name is weird).

**Comment by dtassone** [comment]
Also I'm not sure we want to throw an error in `getLocaleText`
```
 const getLocaleText = React.useCallback(
    (key: any): any => {
      if (localeText[key] == null) {
        throw new Error(`Missing translation for key ${key}.`);
      }
      return localeText[key];
    },
    [localeText],
  );
```
as it is going to break this approach https://github.com/mui-org/material-ui-x/pull/1445/files#r621456770

I suggest we do a warning and return the key. Or we fill all translation files with English

**Comment by oliviertassinari** [comment]
> Also I'm not sure we want to throw an error in getLocaleText

@dtassone The motivation for throwing is to incentivize developers to open issues, which what happened with #1500. The alternative is to log an error, wrapped with a process.env.NODE_ENV. Why not.

**Comment by oliviertassinari** [comment]
@DanailH For writing a test case, a simple reproduction you can use: https://codesandbox.io/s/material-demo-forked-ecmbt?file=/demo.tsx

**Comment by dtassone** [comment]
FYI I will takeover this PR as Danail is on holidays :)

**Comment by dtassone** [comment]
Moved to #1512

**Review by dtassone — APPROVED** [review]
