### PR TITLE
[DataGrid] Close other actions menus when opening a new one

### LINKED ISSUE #3489: [DataGrid] Previous "menuList" hang on screen every click for "type:actions" cells
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Previous "menuList" hang on screen after every click for "type:actions" cells. Only if you click anywhere on screen, it would be hidden.
https://mui.com/components/data-grid/columns/#special-properties
bug
bug2

### Expected behavior 🤔

Previous "menuList" should be hidden after every click for "type:actions" cells.Only new "menuList" should show.

### Steps to reproduce 🕹

Steps:

1.Click action button in grid
2.Then,click another action button in grid
3.
4.

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #3489

Preview: https://deploy-preview-3492--material-ui-x.netlify.app/components/data-grid/columns/#special-properties

If we continue to add more column types with interactive elements, then it makes sense to add a per-column `disableSelectionOnClick`.

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts [hunk 1]
```diff
@@ -25,6 +25,7 @@ import { GridPreProcessingGroup, useGridRegisterPreProcessor } from '../../core/
 import { GridCellModes } from '../../../models/gridEditRowModel';
 import { GridColumnsRawState } from '../columns/gridColumnsState';
 import { isKeyboardEvent } from '../../../utils/keyboardUtils';
+import { gridClasses } from '../../..';
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts:28]: We should probably not import it from the parent index file to avoid risk of circular imports

Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts]: VSCode import suggestions never work correctly.

Comment (flaviendelangle) [reply packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts]: Neither do Webstorm one :/

**Comment by flaviendelangle** [comment]
> If we continue to add more column types with interactive elements, then it makes sense to add a per-column `disableSelectionOnClick`.

I agree that putting logic for a specific type in `useGridSelection` is not great in the longer run.
But good enough for a 1st version.

**Review by flaviendelangle — APPROVED** [review]
