### PR TITLE
[DataGrid] Fix cell accessibility aria-colindex

### LINKED ISSUE #1657: [DataGrid] Accessibility aria-colindex  should start at 1
Mui DataGrid is failing an axe accessibility audit for creating `aria-colindex` starting at 0 instead of 1. 

`GridCell` sets `aria-colindex` to the `colIndex` passed in as a prop. `GridColumnHeaderItem` sets `aria-colindex` to `colIndex + 1` which I _believe_ is the preferred solution. 

Here is the documentation to explain that the numbers must start at 1 and increment: https://www.digitala11y.com/aria-colindexproperties/

I ran an axe audit (using the Chrome extension) on the most basic DataGrid demo and it failed, so I am fairly certain this is not an error I introduced.

- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

`GridPanel` cells are given an `aria-colindex` starting at 0.

## Expected Behavior 🤔

`GridPanel` cells should be given an `aria-colindex` starting at 1. 

## Steps to Reproduce 🕹

Steps:

1. Open sandbox: https://codesandbox.io/s/kind-tu-h2g8g?file=/src/Demo.tsx
2. Inspect the first row, first cell
2. Look at the `aria-colindex` and see that it equals 0:
Screen Shot 2021-05-12 at 4 19 16 PM

## Context 🔦
I'm aiming for not having any critical accessibility issues. This one seems like it might be relatively easy fix (updating the component and relevant tests). 

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
   System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Edge: 90.0.818.56
    Firefox: Not Found
    Safari: 13.1.3
  npmPackages:
    @material-ui/core: ^4.9.9 => 4.11.0 
    @material-ui/data-grid: ^4.0.0-alpha.22 => 4.0.0-alpha.22 
    @material-ui/icons: ^4.9.1 => 4.9.1 
    @material-ui/pickers: ^3.2.10 => 3.2.10 
    @material-ui/styles:  4.10.0 
    @material-ui/system:  4.9.14 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.10.2 
    @types/react:  16.9.51 
    react: ^16.8.6 => 16.13.1 
    react-dom: ^16.8.2 => 16.13.1 
    typescript: ^3.4.3 => 3.9.7 
```
</details>

## Order id 💳
null 😅

### PR DESCRIPTION
**Pull request by ZeeshanTamboli**
Fixes #1657 

Note this comment : https://github.com/mui-org/material-ui-x/issues/1657#issuecomment-841217870

Regarding tests, had to increment col index of `getActiveCell()` assertions, example from `0-1` to `0-2`.
Also fixed `getColumnHeaderCell`. For targeting a cell and its values in tests only `getCell` and `getColumnValues` implementation had to be changed.

Preview: https://deploy-preview-1669--material-ui-x.netlify.app/components/data-grid/#mit-version

### CODE REVIEW

File: test/utils/helperFn.ts [hunk 1]
```diff
@@ -55,13 +55,15 @@ export async function sleep(duration: number) {
...
-  return Array.from(document.querySelectorAll(`[role="cell"][aria-colindex="${colIndex}"]`)).map(
-    (node) => node!.textContent,
-  );
+  return Array.from(
+    document.querySelectorAll(`[role="cell"][aria-colindex="${colIndex + 1}"]`),
+  ).map((node) => node!.textContent);
 }
 
 export function getColumnHeaderCell(colIndex: number): HTMLElement {
-  const columnHeader = document.querySelector(`[role="columnheader"][aria-colindex="${colIndex}"]`);
```
Comment (ZeeshanTamboli) [inline test/utils/helperFn.ts:64]: I think this getter was incorrect as `aria-colindex` was `colIndex + 1`:
https://github.com/mui-org/material-ui-x/blob/5667025a4c0b5beb6cbf65141480daa9ff931a48/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx#L195

so had to refactor the tests.

File: packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx [hunk 2]
```diff
@@ -92,9 +92,9 @@ describe('<DataGrid /> - Keyboard', () => {
     );
     const input = screen.getByTestId('custom-input');
     input.focus();
-    expect(getActiveCell()).to.equal('0-1');
+    expect(getActiveCell()).to.equal('0-2');
```
Comment (oliviertassinari) [inline packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: This looks very wrong. The x and y axis have two different bases (zero base vs. one base) now.

@dtassone previously defended the idea to keep zero-base for the internal state. We have to choice between keeping a zero-base for the test assertions or to move to a 1-base to follow the aria convention. What should we do?

Rely on the internal convention, or on the aria convention? I would be leaning for the latter, as more intuitive.

**Review by oliviertassinari — DISMISSED** [review]

File: packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx (hunk 2 above)
Comment (oliviertassinari) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: I would +1 for the aria so we can be agnostic to the implementation, it also seems more intuitive.

**Comment by oliviertassinari** [comment]
On a related note, what we have might be off. Is it expected to have two different values for aria and data?

```html
<div data-rowindex="0" aria-rowindex="2" class="MuiDataGrid-row" />
```

Screenshot 2021-05-15 at 21 15 05

https://deploy-preview-1669--material-ui-x.netlify.app/components/data-grid/#mit-version

File: packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx (hunk 2 above)
Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: Will wait for @dtassone's review. If considering aria based then we need to change `getActiveCell` implementation right?

Comment (dtassone) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: The index is 0 based because it is the index position in the array of columns. As always, arrays starts at 0.
So internally I think we should keep a 0 based index.

Then when we render cells, we can just add 1 for the aria-colindex and aria-rowindex.

They are one-based as they're used by screen readers.
https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Gridcell_role

For the tests, I think we should use the 0 based convention as it would be easier to map with the real internal position of a column or a row in the array of columns.

Therefore, `GetActiveCell` should use data-rowindex and data-colindex, so the first cell will be 0-0 instead of 1-1 or worse 0-1. IMO, it makes more sense for developers to be 0 based.
What do you think?

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: There is no `data-colindex`. Should we add one in `GridCell`?

**Comment by dtassone** [comment]
> On a related note, what we have might be off. Is it expected to have two different values for aria and data?
> 
> ```
> <div data-rowindex="0" aria-rowindex="2" class="MuiDataGrid-row" />
> ```
> 
> Screenshot 2021-05-15 at 21 15 05
> 
> https://deploy-preview-1669--material-ui-x.netlify.app/components/data-grid/#mit-version

I would say yes.

Actually aria-rowindex includes the column header as the first row, which makes things even less straightforward.

aria indexes are 1 based, thought, and are used for accessibility reason. So they could be treated separately.

File: packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx (hunk 2 above)
Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: > For the tests, I think we should use the 0 based convention as it would be easier to map with the real internal position of a column or a row in the array of columns.
Agree, I also vote for zero-based for _tests_ selecting with `data` attribute.

Comment (dtassone) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: well we could just convert the aria values in getActiveCell to return the 0 based index if it is just used there.
After we can argue that, it could be useful to add the data-colIndex directly on the element 🤔

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: As for `data-rowIndex`, it is used here as well (not only tests):
https://github.com/mui-org/material-ui-x/blob/ca7718b7f1afbbf056f00309d691094f75f5c978/packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts#L73.
So the question is would it be fine to add `data-colIndex` just for _tests_?

> well we could just convert the aria values in getActiveCell to return the 0 based index if it is just used there.

Why decrement aria by one for tests (currently it is 1-based)? I think it would be confusing later on.

Comment (dtassone) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: let's add a return type in `getActiveCell `, we have `GridCellIndexCoordinates` that seems like a good fit.
Index coordinates are 0 based. So the function signature will be self explanatory.

> Why decrement aria by one for tests (currently it is 1-based and should be 1-based)? I think it would be confusing later on.

Currently it is 0 based as there is this issue, and we use data-rowindex.

> So the question is would it be fine to add data-colIndex just for tests?
Not only for tests, it will also be for consistency so you can go ahead I think...

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: @dtassone Do you mean changing assertions if considering return type `GridCellIndexCoordinates`? 
```suggestion
    expect(getActiveCell()).to.deep.equal({ colIndex: 0, rowIndex: 0 });
```

Comment (dtassone) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: Ah yes it's quite verbose.
```tsx
expect(formatCoordinates(getActiveCell())).to.deep.equal('0-0'); 
expect(formatIndexes(getActiveCell())).to.deep.equal('0-0'); 
```

What do you think? 🤔

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: Does not look worth to me. If we are considering `format` for coordinates, then what is the benefit of having signature for `getActiveCell` after wrapping it around `format`?  `getActiveCell` is a test util only. Instead would keep `getActiveCell` as it is. What do you think? I am not sure. 

This is how it would be then:
```ts
function formatCooridnates(cellCoordinates: GridCellIndexCoordinates) {
  const { rowIndex, colIndex } = cellCoordinates;
  return `${rowIndex}-${colIndex}`;
}

export function getActiveCell(): GridCellIndexCoordinates | null {
  let activeElement: Element | null;
  if (document.activeElement && document.activeElement.getAttribute('role') === 'cell') {
    activeElement = document.activeElement;
  } else {
    activeElement = document.activeElement && document.activeElement.closest('[role="cell"]');
  }

  if (!activeElement) {
    return null;
  }

  const cellCoordinates = {
    rowIndex: Number(activeElement.getAttribute('data-rowindex')),
    colIndex: Number(activeElement.getAttribute('data-colindex')),
  };

  return cellCoordinates;
}
```

Note: We also have `getActiveColumnHeader`

Comment (dtassone) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:95]: Fine. Let's keep it as a string, just use the correct values for indexes. 
No need to enforce the return type...

We could add a test to make sure that getActiveCell works as expected... 🤔

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx]: Updated. Considered `data-colindex`. Not much changes in tests now after removal of considering `aria-colindex`.

File: packages/grid/_modules_/grid/utils/domUtils.ts [hunk 3]
```diff
@@ -78,7 +78,7 @@ export function getGridCellElementFromIndexes(
   { colIndex, rowIndex }: GridCellIndexCoordinates,
 ) {
   return root.querySelector(
-    `:scope .${GRID_CELL_CSS_CLASS}[aria-colIndex='${colIndex}'][data-rowIndex='${rowIndex}']`,
+    `:scope .${GRID_CELL_CSS_CLASS}[aria-colIndex='${colIndex + 1}'][data-rowIndex='${rowIndex}']`,
```
Comment (dtassone) [inline packages/grid/_modules_/grid/utils/domUtils.ts:81]: could we change the aria here as well pls?

File: test/utils/helperFn.ts [hunk 4]
```diff
@@ -55,13 +55,15 @@ export async function sleep(duration: number) {
...
-  return Array.from(document.querySelectorAll(`[role="cell"][aria-colindex="${colIndex}"]`)).map(
+  return Array.from(document.querySelectorAll(`[role="cell"][data-colindex="${colIndex}"]`)).map(
     (node) => node!.textContent,
   );
 }
 
 export function getColumnHeaderCell(colIndex: number): HTMLElement {
-  const columnHeader = document.querySelector(`[role="columnheader"][aria-colindex="${colIndex}"]`);
+  const columnHeader = document.querySelector(
+    `[role="columnheader"][aria-colindex="${colIndex + 1}"]`,
```
Comment (dtassone) [inline test/utils/helperFn.ts:65]: Here too?

File: packages/grid/_modules_/grid/utils/domUtils.ts (hunk 3 above)
Comment (ZeeshanTamboli) [reply packages/grid/_modules_/grid/utils/domUtils.ts:81]: Actually this method `getGridCellElementFromIndexes` is not being used anywhere and I think we are exporting `domUtils.ts` in bundle. Is it for users? Should I remove the method itself?

File: test/utils/helperFn.ts (hunk 4 above)
Comment (ZeeshanTamboli) [reply test/utils/helperFn.ts:65]: This is `column header`, not `cell`. So no `data-colIndex` for this, right? Check this comment - https://github.com/mui-org/material-ui-x/pull/1669#discussion_r632935645

File: packages/grid/_modules_/grid/utils/domUtils.ts (hunk 3 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/utils/domUtils.ts:81]: yes remove it please 👍

Comment (ZeeshanTamboli) [reply packages/grid/_modules_/grid/utils/domUtils.ts]: Removed

File: test/utils/helperFn.ts (hunk 4 above)
Comment (dtassone) [reply test/utils/helperFn.ts:65]: I would prefer to use the `data-colindex` everywhere as it would be more consistent with the code and the cell element

File: test/utils/helperFn.ts [hunk 5]
```diff
@@ -76,7 +78,7 @@ export function getColumnHeadersTextContent() {
 
 export function getCell(rowIndex: number, colIndex: number): HTMLElement {
   const cell = document.querySelector(
-    `[role="cell"][data-rowindex="${rowIndex}"][aria-colindex="${colIndex}"]`,
+    `[role="cell"][data-rowindex="${rowIndex}"][data-colindex="${colIndex}"]`,
```
Comment (oliviertassinari) [inline test/utils/helperFn.ts:81]: ARIA > implementation details of the implementation

```suggestion
    `[role="cell"][data-rowindex="${rowIndex}"][aria-colindex="${colIndex + 1}"]`,
```

Comment (ZeeshanTamboli) [reply test/utils/helperFn.ts:81]: I had went with @dtassone 's suggestion considering zero-based with `data`: https://github.com/mui-org/material-ui-x/pull/1669#discussion_r633337082. 
> to not leak implementation details on the public API

What are we leaking? `data` attribute?

Comment (oliviertassinari) [reply test/utils/helperFn.ts:81]: For the confusing aspect, I had assumed that this aspect is hidden to the maintainers writing tests, you don't need to know about it. We could add a comment to explain the rational.

For testing the a11y, this is the beauty of using aria, there are fewer tests to write.

> What are we leaking? data attribute?

Yes, this is the other aspect that can be challenged. We are now providing the developers two different and non consistent ways to test their data grid. They can either use aria or data, both that use two different references. They have to decide which one to choose.

File: test/utils/helperFn.ts (hunk 4 above)
Comment (ZeeshanTamboli) [reply test/utils/helperFn.ts:65]: First thing - are we considering `aria` or `data` after @oliviertassinari 's review yesterday. What conclusion we have made which would be better for us _clearly_? 
As for using `data-colindex: colIndex` for `ColumnHeader` as well, then the row cell element will be having starting base co-ordinates as `{rowIndex}-{colIndex}` -- `0-0`. And column header will be `data-colindex` -- `0` i.e now the header base is zero-based instead of one-based like previously. Are we good?

File: test/utils/helperFn.ts (hunk 5 above)
Comment (ZeeshanTamboli) [reply test/utils/helperFn.ts:81]: > We are now providing the developers two different and non consistent ways to test their data grid. They can either use aria or data, both that use two different references. They have to decide which one to choose.

Hmm, okay. I see. They will have to know `aria` is 1-based while `data` is 0-based if they retrieve for tests.

**Review by dtassone — APPROVED** [review]
