### PR TITLE
[DataGrid] Fix the accessibility of the column menu

### LINKED ISSUE #882: [DataGrid] The column menu isn't accessible
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

Capture d’écran 2021-01-20 à 00 38 43

## Current Behavior 😯

1. The button doesn't have `aria-haspopup="true"`
1. The button doesn't have `aria-controls`
1. The button doesn't have `aria-expanded="true"`
1. Opening the popup doesn't move the focus to it
1. <kbd>Arrow Down</kbd> doesn't allow to navigate the options
1. <kbd>Escape</kbd> doesn't closes the popup
1. The ul has no aria-labelledby

## Expected Behavior 🤔

1. The button has `aria-haspopup="true"`
1. The button has `aria-controls`
1. The button has `aria-expanded="true"`
1. Opening the popup moves the focus to it
1. <kbd>Arrow Down</kbd> allows to navigate the options
1. <kbd>Escape</kbd> closes the popup
1. The ul has aria-labelledby

The pattern: https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

## Steps to Reproduce 🕹

Steps:

1. https://master--material-ui-x.netlify.app/components/data-grid/columns/#column-selector

## Context 🔦

⚠️ The behavior required for the column menu is different from the one needed for the density selector (#881).

## Your Environment 🌎

`@material-ui/data-grid@v4.0.0-alpha.17`

### PR DESCRIPTION
**Pull request by zj9495**
Closes #882

### CODE REVIEW

File: packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenuItems.tsx [hunk 1]
```diff
@@ -15,15 +15,15 @@ export function GridColumnHeaderMenuItems(props: GridColumnHeaderMenuItemsProps)
...
+      if (event.key === 'Tab' || event.key === 'Escape') {
         event.preventDefault();
         hideMenu();
       }
     },
     [hideMenu],
   );
   return (
-    <MenuList id="menu-list-grow" onKeyDown={handleListKeyDown}>
+    <MenuList aria-labelledby={`menu-button-${currentColumn.field}`} autoFocus autoFocusItem id="menu-list-grow" onKeyDown={handleListKeyDown}>
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenuItems.tsx:26]: not sure about the `menu-button` hardcoded prefix

Comment (zj9495) [reply packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenuItems.tsx:26]: @dtassone thanks! any good suggestions?

Comment (DanailH) [reply packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenuItems.tsx:26]: Why is the `id` here necessary, maybe I'm not seeing something?

**Comment by DanailH** [comment]
The build is failing due to format issues. Running `yarn prettier` will fix that.

File: packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenuItems.tsx (hunk 1 above)
Comment (zj9495) [reply packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenuItems.tsx:26]: image
image
https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html
This document clarifies that `aria-labelledby` must be an ID reference, so i added a `id` to the column header filter button, and then used this ID as the `aria-labelledby` attribute of the column header MenuList

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenuItems.tsx]: We have a `useId` helper in the main repo, it's meant as a bridge until https://github.com/reactjs/rfcs/pull/32 is resolved.

**Comment by oliviertassinari** [comment]
Any update on this effort? What's the blocker?

File: packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenuItems.tsx (hunk 1 above)
Comment (zj9495) [reply packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenuItems.tsx]: I have some doubts about how I can share this `id` between these two components if I use `useId()`? should i store `id` in `ColumnMenuState`?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenuItems.tsx]: In theory, I would expect each button and menu to be rendered in the same component, so sharing the id should be possible because in the same scope.

**Comment by dtassone** [comment]
> Any update on this effort? What's the blocker?

It looks good! I think we just need to restart the build to make sure the codesandbox works and merge

**Review by dtassone — APPROVED** [review]
