### PR TITLE
[DataGrid] Add customisation on panels

### LINKED ISSUE #895: [DataGrid] Scroll is broken when opening Column selector
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The page scrolls to the top

## Expected Behavior 🤔

The scroll shouldn't change

## Steps to Reproduce 🕹

Steps:

1. Open https://master--material-ui-x.netlify.app/components/data-grid/columns/#column-selector
2. Click on "Columns"
3. Scroll is at the top

## Context 🔦

It was broken in #851, it's not released yet. Storybook makes us blind to regressions like this.

### PR DESCRIPTION
**Pull request by dtassone**
Add customisation on 3 components
- Filter panel
- Columns panel
- Panel 

Fixes #895

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/useComponents.tsx [hunk 1]
```diff
@@ -33,7 +34,8 @@ const wrapWithProps: <TProps, StaticProps>(
 };
 
 export const useComponents = (
-  componentsProp: GridSlotsComponent | undefined,
+  componentSlotsProp: GridSlotsComponent | undefined,
+  componentsProp: GridSlotsComponentProps | undefined,
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/useComponents.tsx:38]: How about we avoid renaming the variables? Maybe something consistent (`Prop` suffix and `GridSlots` prefix) like this?

```suggestion
  componentsProp: GridSlotsComponents | undefined,
  componentsPropsProp: GridSlotsComponentsProps | undefined,
```

File: packages/grid/_modules_/grid/components/panel/Panel.tsx [hunk 2]
```diff
@@ -2,46 +2,18 @@ import * as React from 'react';
 import ClickAwayListener from '@material-ui/core/ClickAwayListener';
 import Paper from '@material-ui/core/Paper';
 import Popper from '@material-ui/core/Popper';
-import { makeStyles, Theme } from '@material-ui/core/styles';
 import { ApiContext } from '../api-context';
 import { isMuiV5 } from '../../utils';
-
-const useStyles = makeStyles(
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/panel/Panel.tsx:9]: Why move the style outside of the panel? I think that it would be much better to keep them as close as possible to the underlying nodes. As far as I remember, the only reason why we have a large CSS file at the root is to improve the performance when rendering the cells. This is not a concern with the panel as only opened temporarily.

File: packages/grid/_modules_/grid/models/api/componentsApi.ts [hunk 3]
```diff
@@ -30,11 +31,27 @@ export interface ApiRefComponentsProperty extends GridIconSlotsComponent {
    * Pagination component rendered in the grid footer by default.
    */
   Pagination: React.ElementType;
+  /**
+   * FilterPanel component rendered when clicking the filter button.
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/api/componentsApi.ts:35]:
```suggestion
   * Filter panel component rendered when clicking the filter button.
```

File: packages/grid/_modules_/grid/models/api/componentsApi.ts [hunk 4]
```diff
@@ -30,11 +31,27 @@ export interface ApiRefComponentsProperty extends GridIconSlotsComponent {
...
+   */
+  FilterPanel: React.ElementType;
+  /**
+   * ColumnsPanel component rendered when clicking the columns button.
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/api/componentsApi.ts:39]:
```suggestion
   * Columns panel component rendered when clicking the columns button.
```

File: packages/grid/_modules_/grid/models/api/componentsApi.ts [hunk 5]
```diff
@@ -30,11 +31,27 @@ export interface ApiRefComponentsProperty extends GridIconSlotsComponent {
...
 
 export interface ComponentsApi {
   /**
    * The set of overridable components used in the grid.
    */
   components: ApiRefComponentsProperty;
+  /**
+   * Overrideable components props dynamic passed to the component at rendering.
+   */
+  componentsProps?: GridSlotsComponentProps;
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/api/componentsApi.ts:56]: Could we update the API pages, e.g. https://material-ui.com/api/data-grid/ to mention it?

File: packages/grid/_modules_/grid/models/gridSlotsComponent.ts [hunk 6]
```diff
@@ -59,6 +62,18 @@ export interface GridSlotsComponent extends GridIconSlotsComponent {
    * Pagination component rendered in the grid footer by default.
    */
   Pagination?: React.ElementType<BaseComponentProps>;
+  /**
+   * FilterPanel component rendered when clicking the filter button.
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/gridSlotsComponent.ts:66]:
```suggestion
   * Filter panel component rendered when clicking the filter button.
```

File: packages/grid/_modules_/grid/models/gridSlotsComponent.ts [hunk 7]
```diff
@@ -59,6 +62,18 @@ export interface GridSlotsComponent extends GridIconSlotsComponent {
...
+   */
+  FilterPanel?: React.ElementType<BaseComponentProps>;
+  /**
+   * ColumnsPanel component rendered when clicking the columns button.
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/gridSlotsComponent.ts:70]:
```suggestion
   * Columns panel component rendered when clicking the columns button.
```

**Review by oliviertassinari — CHANGES_REQUESTED** [review]

File: packages/grid/_modules_/grid/hooks/features/useComponents.tsx (hunk 1 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/useComponents.tsx:38]: This is not part of the public api. It's just internal to the hook to differentiate the 2 notions.
PropsProp feels a bit weird

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/useComponents.tsx:38]: I was trying to optimize for making it easier for somebody new to this part of the codebase to understand what's going on.

File: packages/grid/_modules_/grid/components/panel/Panel.tsx (hunk 2 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:9]: This is to be able to reuse the css classes outside the root panel. 
This is used in `/story/x-grid-demos-custom-components--custom-panel`

Current issue with field
image

File: packages/grid/_modules_/grid/models/api/componentsApi.ts (hunk 5 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/models/api/componentsApi.ts:56]: Yes I will update the doc

File: packages/grid/_modules_/grid/components/panel/Panel.tsx (hunk 2 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:9]: I don't understand, what's the link?

Comment (dtassone) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:9]: I just fixed it, I couldn't find the style breaking it.

File: packages/grid/_modules_/grid/components/panel/Panel.tsx [hunk 8]
```diff
@@ -2,46 +2,18 @@ import * as React from 'react';
...
-      '& .MuiDataGridPanel-footer': {
-        padding: 4,
-        display: 'flex',
-        justifyContent: 'space-between',
-      },
-    },
-  }),
-  { name: 'MuiDataGridPanel' },
-);
+import { useStyles } from '../containers/GridRootStyles';
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/panel/Panel.tsx:7]: I think that this is worse, we inject twice unelated styles. What's wrong with the existing solution?

File: packages/grid/_modules_/grid/hooks/features/useComponents.tsx (hunk 1 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/useComponents.tsx:38]: In this case, could we keep it semantically correct:

```suggestion
  componentSlotsProp: GridSlotsComponent | undefined,
  componentsProps: GridSlotsComponentProps | undefined,
```

**Review by oliviertassinari — CHANGES_REQUESTED** [review]

File: packages/grid/_modules_/grid/components/panel/Panel.tsx (hunk 8 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:7]: it's discussable.
As the popper is rendered outside the grid container, and we prefix all class with our root class, when we render outside the grid then we cannot use the classes prefixed with the root class. Unless we import it as it is or we manually add the root class to the container, but we will potentially miss some standard grid styles hence why I took this path

File: packages/grid/_modules_/grid/components/panel/Panel.tsx [hunk 9]
```diff
@@ -77,12 +49,13 @@ export function Panel(props: PanelProps) {
   return (
     <Popper
       placement="bottom-start"
-      open={open}
+      open={!!open}
```
Comment (DanailH) [inline packages/grid/_modules_/grid/components/panel/Panel.tsx:52]: Why do we need the `!!` infront? I see that it is already marked as a `boolean`.

File: packages/grid/_modules_/grid/components/panel/Panel.tsx (hunk 8 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:7]: What's wrong with isolating the styles, keeping them as close as possible to where they are needed? Why do we move them to the GridContainer?

File: packages/grid/_modules_/grid/components/panel/Panel.tsx (hunk 9 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:52]: Why not make the open state required?

File: packages/grid/_modules_/grid/components/panel/Panel.tsx (hunk 8 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:7]: if you don't use the Panel then you will not load those styles. So you won't be able to use the container panel or footer outside the Panel component

File: packages/grid/_modules_/grid/components/panel/Panel.tsx (hunk 9 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:52]: extra props need to be optional for customizable component

File: packages/grid/_modules_/grid/components/panel/Panel.tsx (hunk 8 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:7]: > So you won't be able to use the container panel or footer outside the Panel component

Yes, it's one of the reasons why I think we shouldn't do it.

File: packages/grid/_modules_/grid/components/panel/Panel.tsx (hunk 9 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:52]: What's the use case for using `<Panel open={false}>`?

Comment (dtassone) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:52]: if you customize the panel you need to know if it's open or not

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:52]: So it should be required?

Comment (dtassone) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:52]: yes but there are some typings constraints with the components slots implementation atm

File: packages/grid/_modules_/grid/components/panel/Panel.tsx (hunk 8 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:7]: https://deploy-preview-890--material-ui-x.netlify.app/storybook/?path=/story/x-grid-demos-custom-components--custom-panel

This story uses the panel container, footer, and header without the wrapper, so if you don't use Panel you won't get the style. Hence why I put it in root. We can move it and make the user import it, but I'm not sure it will have any benefits as it will already be part of the bundle...

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
I would recommend the following:

1. We close this pull request, it's too ambitious to start with the customization of the panel. Instead, we break it down into a bunch of small pull requests. **Each will bring value to the product**. This PR was great for exploration purposes.
2. We fix the CSS injection order with the diff shared (reorder of the imports), if we want to anticipate emotion/sc, we can also remove the box-sizing wildcard inheritance.
1. We fix the scroll regression #895, `useEnhancedEffect` could be the solution. 
3. We add the `componentsProps` prop, add the missing API documentation at the same time.
4. We fix the rerender regression, by replacing the `wrapWithProps` pattern with `componentsProps`.
6. We fix the null-isf behavior of the `components`.
5. We break down the style of the panel into smaller components.
6. Finally, we add the customization of the panel 🎉.

File: packages/grid/_modules_/grid/hooks/features/useComponents.tsx [hunk 10]
```diff
@@ -55,7 +57,7 @@ export const useComponents = (
   );
 
   const components: ApiRefComponentsProperty = React.useMemo(() => {
-    const allComponents = { ...DEFAULT_SLOTS_COMPONENTS, ...componentsProp };
+    const allComponents = { ...DEFAULT_SLOTS_COMPONENTS, ...componentSlotsProp };
```
[the remark this answers is not in the document]
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/useComponents.tsx:17]: A bit confused here. 
So do you want to render an empty component when the component is falsy or do you want to fall back on the default one?

[the remark this answers is not in the document]
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/useComponents.tsx:17]: From what I understand, right now it renders an empty components. It would be easier and more consistent for developers if it was rendering the default component.

File: docs/pages/api-docs/data-grid.md [hunk 11]
```diff
@@ -20,7 +20,8 @@ import { DataGrid } from '@material-ui/data-grid';
 | <span class="prop-name required">columns<abbr title="required">*</abbr></span> | <span class="prop-type">Columns</span> |   | Set of columns of type 'Columns'. |
 | <span class="prop-name">columnBuffer</span> | <span class="prop-type">number</span> | 2 | Number of columns rendered outside the grid viewport. |
 | <span class="prop-name">columnTypes</span> | <span class="prop-type">ColumnTypesRecord</span> |   | Extend native column types with your new column types. |
-| <span class="prop-name">components</span> | <span class="prop-type">GridComponentOverridesProp</span> |   | Overrideable components. |
+| <span class="prop-name">components</span> | <span class="prop-type">GridSlotsComponent</span> |   | Overrideable components. |
+| <span class="prop-name">componentsProps</span> | <span class="prop-type">GridSlotsComponentProps</span> |   | Overrideable components Props. |
```
Comment (oliviertassinari) [inline docs/pages/api-docs/data-grid.md:24]:
```suggestion
| <span class="prop-name">componentsProps</span> | <span class="prop-type">componentProps</span> |   | Overrideable components Props. |
```

x2

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
Please break it down. It's too big.

**Comment by oliviertassinari** [comment]
> Please break it down, it mixes too many unrelated changes that can deliver value on their own.

**Comment by oliviertassinari** [comment]
Oops, I was on my phone, I didn't meant to close it, I was hoping you would.

File: docs/pages/api-docs/data-grid.md (hunk 11 above)
Comment (dtassone) [reply docs/pages/api-docs/data-grid.md:24]: What do you mean? Isn't it the type?

Comment (oliviertassinari) [reply docs/pages/api-docs/data-grid.md:24]: Oops, my bad.

File: packages/grid/_modules_/grid/components/panel/PanelContent.tsx [hunk 12]
```diff
@@ -0,0 +1,26 @@
...
+);
+
+export function PanelContent(props: React.PropsWithChildren<React.HTMLAttributes<HTMLDivElement>>) {
+  const classes = useStyles();
+  const { children, className, ...otherProps } = props;
+  return (
+    <div className={classnames(classes.root, className)} {...otherProps}>
+      {children}
+    </div>
+  );
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/panel/PanelContent.tsx:25]: You can use a shorthand (I have also used `other` for consistency).

```suggestion
  const { className, ...other } = props;
  return <div className={classnames(classes.root, className)} {...other} />;
```

x3 (the other Panel components)

File: packages/grid/_modules_/grid/components/panel/PanelContent.tsx [hunk 13]
```diff
@@ -0,0 +1,26 @@
+import * as React from 'react';
+import { makeStyles } from '@material-ui/core/styles';
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/panel/PanelContent.tsx:2]: Did you consider using the `styled()` helper instead? It could be simpler and help with v5 migration.

x3 (the other Panel components)

File: packages/grid/_modules_/grid/components/panel/PanelHeader.tsx [hunk 14]
```diff
@@ -0,0 +1,22 @@
+import * as React from 'react';
+import { makeStyles } from '@material-ui/core/styles';
+import { classnames } from '../../utils/classnames';
+
+const useStyles = makeStyles(
+  () => ({
+    root: {
+      padding: 8,
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/panel/PanelHeader.tsx:8]: I wonder if it should be 
```suggestion
      padding: theme.spacing(1),
```

**Review by oliviertassinari — COMMENTED** [review]
We are close :)

File: packages/grid/_modules_/grid/components/panel/Panel.tsx [hunk 15]
```diff
@@ -80,9 +66,10 @@ export function Panel(props: PanelProps) {
       open={open}
       anchorEl={anchorEl}
       modifiers={getPopperModifiers()}
+      className={classes.root}
     >
       <ClickAwayListener onClickAway={handleClickAway}>
-        <Paper className={classes.root} elevation={8}>
```
[the remark this answers is not in the document]
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/Panel.tsx:85]: Actually, here, the class should have been named `paper` not `root` as it's not applied on the root element.

File: packages/grid/_modules_/grid/components/panel/PanelContent.tsx (hunk 13 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/panel/PanelContent.tsx:2]: That's a separate issue that can be done in the whole grid

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/PanelContent.tsx:2]: Ok, I'm asking because at's this point, the probability we deprecate makeStyles/withStyles in v5 is over 99%. I was wondering about the potential to save time in a future migration to introduce new more "compatible" code.

**Review by oliviertassinari — APPROVED** [review]
It seems to solve the last regressions we had on HEAD. I can make a release once it's merged.

File: packages/grid/_modules_/grid/components/panel/PanelContent.tsx (hunk 13 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/panel/PanelContent.tsx:2]: Let's do a separate issue, so we don't have a mix in the codebase of makestyle and styled.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/PanelContent.tsx:2]: Ok

For the curious ones, `styled` is a "thin" wrapper on top of makeStyles: https://github.com/mui-org/material-ui/blob/7bc6e3e10ada78a6133292979abca5ee5b9d1779/packages/material-ui-styles/src/styled/styled.js#L6.
