### PR TITLE
[DataGrid] Fix rendering issues

### LINKED ISSUE #481: [DataGrid] Give access to the sorted rows
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Since sort is managed internally, it can be difficult to recover which item is immediately before or after the selected element. 

## Examples 🌈

My use case: clicking a row opens a dialog in which the user can take some actions. I want to add "Previous" and "Next" buttons to this Dialog so that users can move from item to item without repeatedly opening and closing the dialog. 

## Motivation 🔦

Reduce clicks for our beloved users =)

### LINKED ISSUE #1309: [DataGrid] Last page has extra blank space after the last row
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Using server side pagination mode. Last page renders more rows then expected.
Seems like it always renders exact amount of rown on each page disptite last page has less rows. Thats why white space is there
image

## Expected Behavior 🤔
Last page shoudl have no blanck space when scrolled to the last item

### LINKED ISSUE #1323: [DataGrid] Cell selection isn't selecting the correct one
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Cell selection is no working when scrolling.

## Expected Behavior 🤔

Cell selection is working when scrolling.

## Steps to Reproduce 🕹

1. Open https://master--material-ui-x.netlify.app/components/data-grid/#commercial-version
2. 

https://user-images.githubusercontent.com/3165635/113157672-66c75f80-923b-11eb-95d6-ef7b989a2ba0.mp4

This regression isn't released yet. It comes from #1253 (I have tested with a `git revert 575f10a24a3818580a16a8b6700bd50c1f6efb22` from HEAD)

### PR DESCRIPTION
**Pull request by dtassone**
fix #1309 
fix #1323

fix #481, done as rowIndex depends on sorted rows

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts [hunk 1]
```diff
@@ -122,6 +122,8 @@ export const useGridKeyboardNavigation = (
       nextCellIndexes.colIndex = nextCellIndexes.colIndex <= 0 ? 0 : nextCellIndexes.colIndex;
       nextCellIndexes.colIndex =
         nextCellIndexes.colIndex >= colCount ? colCount - 1 : nextCellIndexes.colIndex;
+
+      apiRef.current.scrollToIndexes(nextCellIndexes);
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts:126]: Still looking at an issue in this function

File: packages/grid/x-grid/src/tests/rows.XGrid.test.tsx [hunk 2]
```diff
@@ -342,5 +342,40 @@ describe('<XGrid /> - Rows', () => {
       const isVirtualized = apiRef!.current!.getState().containerSizes!.isVirtualized;
       expect(isVirtualized).to.equal(false);
     });
+
+    describe('Pagination', () => {
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/rows.XGrid.test.tsx:346]: We have dedicated pagination tests. Would it fit better there than here?

File: packages/grid/x-grid/src/tests/rows.XGrid.test.tsx [hunk 3]
```diff
@@ -342,5 +342,40 @@ describe('<XGrid /> - Rows', () => {
...
+        render(<TestCaseVirtualization pagination pageSize={32} />);
+        const gridWindow = document.querySelector('.MuiDataGrid-window')!;
+        gridWindow.scrollTop = 10e6; // scroll to the bottom
+        gridWindow.dispatchEvent(new Event('scroll'));
+
+        const lastCell = document.querySelector(
+          '[role="row"]:last-child [role="cell"]:first-child',
+        )!;
+        expect(lastCell.textContent).to.equal('31');
+        const totalHeight = apiRef!.current!.getState().containerSizes?.totalSizes.height!;
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/rows.XGrid.test.tsx:357]: This seems to be the only reason for testing `XGrid` and not `DataGrid`. I wonder if for the tests, we shouldn't expose the apiRef so we can have as much tests as possible on `DataGrid`.

File: packages/grid/_modules_/grid/components/cell/GridCell.tsx [hunk 4]
```diff
@@ -128,7 +128,11 @@ export const GridCell: React.FC<GridCellProps> = React.memo((props) => {
...
   React.useLayoutEffect(() => {
-    if (hasFocus && cellMode === 'view' && cellRef.current) {
+    if (
+      hasFocus &&
+      cellRef.current &&
+      (!document.activeElement || !cellRef.current!.contains(document.activeElement))
+    ) {
       cellRef.current!.focus();
     }
   });
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/cell/GridCell.tsx:138]: I would personally remove the whole block for Point 5. of https://github.com/mui-org/material-ui-x/issues/1300 and #1295.

**Review by oliviertassinari — COMMENTED** [review]
Shouldn't it be a draft? I'm asking because, for instance, there are no descriptions in the PR, in the new API.

File: packages/grid/x-grid/src/tests/rows.XGrid.test.tsx (hunk 2 above)
Comment (dtassone) [reply packages/grid/x-grid/src/tests/rows.XGrid.test.tsx:346]: no because I'm testing the virtualisation with pagination

File: packages/grid/x-grid/src/tests/rows.XGrid.test.tsx (hunk 3 above)
Comment (dtassone) [reply packages/grid/x-grid/src/tests/rows.XGrid.test.tsx:357]: Testing DataGrid and XGrid is the same as they both use GridComponent under the hood

File: packages/grid/_modules_/grid/components/cell/GridCell.tsx (hunk 4 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/cell/GridCell.tsx:138]: it's fixed

File: packages/grid/x-grid/src/tests/rows.XGrid.test.tsx (hunk 3 above)
Comment (oliviertassinari) [reply packages/grid/x-grid/src/tests/rows.XGrid.test.tsx:357]: As far as we know, the plan is to have them as two different components, where XGrid uses extra "plugins". So we should optimize now for this known future. 

In such configuration, I wonder if it's better to tests the version of the component with the fewer plugins, DataGrid, or with the most XGrid. I guess it depend.

- what's most likely to happen: a missing plugin to implement the behavior or an extra plugin breaking the behavior? No idea.
- what's most used? DataGrid
- what's more mission critical? XGrid

Comment (dtassone) [reply packages/grid/x-grid/src/tests/rows.XGrid.test.tsx:357]: Let's keep that in mind.
- We could run each test on each implementation, and we should expect some test to fail. But that would be quite big to setup. I don't think we are there yet, more important things to focus on
- We could stand on the more feature we have the more difficult it is to integrate so we test on XGrid and if something should be turned off for dataGrid, we check that it works as expected. 
- We check everything on DataGrid and if we need apiRef or testing an xgrid feature we switch. Kind of bad DX IMO

Anyway I think those are very core feature. So it would be difficult for the grid to work without atm. 
IMHO, I think we should take a pragmatic approach and merge as this PR fixes a few regressions.

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
I don't know about the others but I have no idea what line fix what nor if each fix is tested/correctly documented.
For instance, it says `fix #1295` but it's still broken (using the reproduction on the issue).

Could we stop bunding bug fixes, especially if there are not directly related or don't need to be (e.g. #481)? How can we expect the team to review the changes?

I would highly encourage we close this PR and restart with smaller chunks, one issue at a time. Smaller iteration helps to be more methodical, and rigorous, which I think we lack. Of course, it takes more time, in the beginning. 
Or even consider the following, in one year from now, we have a regression on some behavior, being able to blame to see exactly what was done for a specific issue save so much time (I feel that this happens often in the main repo).

File: packages/grid/x-grid/src/tests/rows.XGrid.test.tsx (hunk 3 above)
Comment (oliviertassinari) [reply packages/grid/x-grid/src/tests/rows.XGrid.test.tsx:357]: I was leaving a general note, agree that it's outside of the scope of the changes here.

**Comment by dtassone** [comment]
#481 is fixed because I needed those methods to fix the issue that danail mentioned.

**Comment by dtassone** [comment]
I updated the description and remove #1295

File: packages/grid/x-grid/src/tests/events.XGrid.test.tsx [hunk 5]
```diff
@@ -142,7 +144,28 @@ describe('<XGrid /> - Events Params', () => {
         api: apiRef.current,
       });
     });
+    it('should include the correct params when grid is sorted', () => {
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/events.XGrid.test.tsx:147]:
```suggestion

    it('should include the correct params when grid is sorted', () => {
```

File: packages/grid/x-grid/src/tests/events.XGrid.test.tsx [hunk 6]
```diff
@@ -142,7 +144,28 @@ describe('<XGrid /> - Events Params', () => {
...
+        formattedValue: 'Jack',
+        isEditable: true,
+        element: cell01,
+        row: baselineProps.rows[1],
+        rowIndex: 0,
+        colDef: apiRef!.current.getColumnFromField('first'),
+        colIndex: 1,
+        api: apiRef.current,
+      });
+    });
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/events.XGrid.test.tsx:168]:
```suggestion
    });

```

File: packages/grid/x-grid/src/tests/rows.XGrid.test.tsx [hunk 7]
```diff
@@ -342,5 +342,40 @@ describe('<XGrid /> - Rows', () => {
       const isVirtualized = apiRef!.current!.getState().containerSizes!.isVirtualized;
       expect(isVirtualized).to.equal(false);
     });
+
+    describe('Pagination', () => {
+      it('should render only the pageSize ', () => {
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/rows.XGrid.test.tsx:347]:
```suggestion
      it('should render only the pageSize', () => {
```

File: packages/grid/x-grid/src/tests/rows.XGrid.test.tsx [hunk 8]
```diff
@@ -342,5 +342,40 @@ describe('<XGrid /> - Rows', () => {
...
+
+        const lastCell = document.querySelector(
+          '[role="row"]:last-child [role="cell"]:first-child',
+        )!;
+        expect(lastCell.textContent).to.equal('31');
+        const totalHeight = apiRef!.current!.getState().containerSizes?.totalSizes.height!;
+        expect(gridWindow.scrollHeight).to.equal(totalHeight);
+      });
+
+      it('should not virtualized the last page if smaller than viewport ', () => {
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/rows.XGrid.test.tsx:361]:
```suggestion
      it('should not virtualized the last page if smaller than viewport', () => {
```

**Review by oliviertassinari — COMMENTED** [review]
> fix #1300

This one seems to only be fixed on the surface. Could remove it from the list as well? I'm saying on the surface, because, for instance, if you press backspace, GRID_CELL_EXIT_EDIT is fired (why? the cell is not in edit mode), or the fact that if you press backspace, it re-renders the whole grid (slower), or the fact that it doesn't have a dedicate test case.

I think that without it, we would be almost ok. I still fail to see why we bundle a bug fix on virtualization (#1309) with a feature enhancement on sorting (#481). In my external context, I see no links between the two. But at least, #481 is only a small sidecar to the man focus #1309. I guess we don't need to update the documentation for it?

**Comment by DanailH** [comment]
In general, I support the idea of PR per ticket. I can also see that this fixes the one I mentioned yesterday in slack (https://material-ui.slack.com/archives/G011VC970AW/p1617094662001100).

Regarding https://github.com/mui-org/material-ui-x/issues/1300 - probably is better to have e separate effort for it (we can still have the enhancement here but if there is more work to be done that one shouldn't be closed).

Lastly - I know that the bugs this PR aims to fix are listed in the description but if the fix is not straightforward, simple change It would really help when reviewing if there are a couple of sentences explaining what the changes are.

**Comment by dtassone** [comment]
> > fix #1300
> 
> This one seems to only be fixed on the surface. Could remove it from the list as well? I'm saying on the surface, because, for instance, if you press backspace, GRID_CELL_EXIT_EDIT is fired (why? the cell is not in edit mode), or the fact that if you press backspace, it re-renders the whole grid (slower), or the fact that it doesn't have a dedicate test case.

I considered backspace to be an edit with a commit straightaway hence why it fires the GRID_CELL_EXIT_EDIT.
It rerenders the whole grid as we update the grid state. There is already a test case.
`should allow to delete a cell directly if editable using delete key`

> 
> I think that without it, we would be almost ok. I still fail to see why we bundle a bug fix on virtualization (#1309) with a feature enhancement on sorting (#481). In my external context, I see no links between the two. But at least, #481 is only a small sidecar to the man focus #1309. I guess we don't need to update the documentation for it?

The main issue of this PR was only raised on slack
Sorry for trying to sort out important issues in short delays.

**Review by oliviertassinari — APPROVED** [review]
I have added `Fix #1319` in the pull request as it covers it. It also seems to have a dedicated test case 👍

**Comment by dtassone** [comment]
> I have added `Fix #1319` in the pull request as it covers it. It also seems to have a dedicated test case 👍

1319 is this PR

**Comment by oliviertassinari** [comment]
> I considered backspace to be an edit with a commit straightaway hence why it fires the GRID_CELL_EXIT_EDIT.

The main part that is counter-intuitive to me is that the focus is on a nested input, **not on the cell container**. As far as I know, this interaction was designed for the case where we can to quickly empty a cell: "read mode > backspace > edit mode > empty > commit > exit event > read mode". It doesn't seem to make sense once the focus is move inside the cell, on a button, or a textbox.

**Comment by oliviertassinari** [comment]
> The main issue of this PR was only raised on slack. Sorry for trying to sort out important issues in short delays.

@dtassone I think that the intent is great: these GitHub issues deserved to be handled, soon or later 👍. We have a bunch, which is fun to handle 😄.

I also think that the bundling is the opposite of the methodology @eps1lon and I have tried to generalize so far. I strongly don't think that we can grow the project, both in terms of product quality and in terms of the size of the team by grouping GitHub issues that don't need to be. I think that it's really important and something we should rarely trade for something else (like convenience). Yes, it requires opening more pull requests, yes it forces us to think in more depth about each problem, which should translate into clearer thinking and stronger mastery (at the cost of spending more time) :).

**Comment by dtassone** [comment]
> > The main issue of this PR was only raised on slack. Sorry for trying to sort out important issues in short delays.
> 
> @dtassone I think that the intent is great: these GitHub issues deserved to be handled, soon or later 👍💯. We have a bunch, which is fun to handle 😄.
> 
> I also think that the bundling is the opposite of the methodology @eps1lon and I have tried to generalize so far. I strongly don't think that we can grow the project, both in terms of product quality (we have a strong focus on this in the core) and in terms of the size of the team by grouping GitHub issues that don't need to be. I think that it's really important and something we should rarely trade for something else (like convenience). Yes, it requires opening more pull requests, yes it forces us to think in more depth about each problem, which should translate into clearer thinking and stronger mastery (at the cost of spending more time and more concurrent effort) :).

While I agree to some extent. I believe that it can be counter-productive to not allow some flexibility to this policy in certain cases.
- Sometimes bugs are very closely related, you need the first fix to fix the second. Or your first fix impact the second. So you have to wait that the first bug to be merged to properly fix the second one. Should be small enough to group.
- There are regressions due to a lastly merged PR, different contributors work in the area, and need your fixes to approach their work properly. You're blocking them, issues get created, and it's breaking the component or crashing the page totally.

**Comment by eps1lon** [comment]
> Sometimes bugs are very closely related, you need the first fix to fix the second. Or your first fix impact the second. So you have to wait that the first bug to be merged to properly fix the second one. Should be small enough to group.

Note that you can always stack PRs on top of another.

1. create a branch `fix-1` from `main`
2. create a branch `fix-2` from `fix-1`
3. Open PR for `fix-1` (no special attention)
4. Open PR for `fix-2`. Include a note that this PR is stacked on another one and add a link to the diff between `fix-1...fix-2`.

The idea is that we later want to isolate problems. While two bugs might seem closely related right now, they may no longer be closely related in the future. But since they were at some point, and you decided to fix both in a single commit, they become coupled indefinitely. Mapping past implementation to future implementation is no trivial task so when we do have the opportunity to make future readability easier at the expense of present work we should always pay that price. In the end we will always spend more time reading code than writing code.

There is some upfront cost in learning more advanced git techniques but I can guarantee you that being able to rebase confidently pays of big time in the long term.

**Comment by oliviertassinari** [comment]
@eps1lon 💯

The learnings I personally got from my previous effort on the project is that:

- As much as issues seems related on the surface (behavior) the root causes are in a large majority of the cases different and isolated. Based on all the bugs I have seen so far. 
- The smaller the PR is, the less likely it will be challenged during a review, overlooked aspect will be found, the faster the change will be merged, and the faster they will unlock the rest of the team.
- Breaking down changes into smaller indivual efforts very often yield higher quality solutions. Once made systematic, I believe it explain some of why Material-UI got so popular. Basically, do less but do it really well. Which in a mature market where UI components are almost of commodity with high competition helps differentiate.
- So far, in most of the cases the audience doesn't seem to care if a bug fix make it in one release or the next one, a week later. It seems that the development cycles are a lot longer for them.

**Comment by oliviertassinari** [comment]
We got a regression linked to these changes: #1334.
