### PR TITLE
[DataGrid] Performance optimization 

### LINKED ISSUE #1506: [XGrid] Performance issue when sorting/filtering 100k rows client-side
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When we use XGrid for 100k rows, performance is very slow and usually crashes the browser. For 50k rows, performance is still unacceptably slow. How can we improve the performance? What are the trade offs of server side filtering and server side paginating?

## Expected Behavior 🤔

Faster UX.

## Steps to Reproduce 🕹

https://codesandbox.io/s/awesome-framework-kqbcp?file=/src/Demo.tsx

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
- Browser:
    Chrome
- System:
    OS: Windows 10 10.0.18363
- Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
- Browsers:
    Chrome: 90.0.4430.85
    Edge: Spartan (44.18362.1474.0)
```
</details>

## Order id 💳

Order #23360

### PR DESCRIPTION
**Pull request by dtassone**
### Breaking changes

- Remove the params property `element`, `rowIndex`, `colIndex`, across all relevant params argument due to their heavy calculation work.
```diff
-  params.element
-  params.rowIndex
-  params.colIndex
```
- Refactor `params.getValue` across all params argument, due to reference change on each closure, this method is now pointing to `apiRef.current.getCellValue`.
```diff
-  params.getValue(field)
+  params.getValue(params.id, field)
```
- Remove usage of `getValue` in sort string number comparator .
- Refactor the arguments of `setCellFocus` to use `id` and `field` to match other api methods.
```diff
-  apiRef.current.setCellFocus: (indexes: GridCellIndexCoordinates) => void;
+  apiRef.current.setCellFocus: (id: GridRowId, field: string) => void;
```
- Add `tabIndex` and `hasFocus` in `GridCellParams`.
```diff
+  params.tabIndex
+  params.hasFocus
```
- Rename `getRowIndexFromId` to `getRowIndex`
```diff
-  apiRef.current.getRowIndexFromId(...)
+  apiRef.current.getRowIndex(...)
```

Work on #1506, #569, #1427

Preview: https://deploy-preview-1513--material-ui-x.netlify.app/components/data-grid/#commercial-version

### CODE REVIEW

**Comment by dtassone** [comment]
Not sure that will work. 
As if many components load the "heavy work" internally, we'll end up with the same issue 🤔

**Comment by dtassone** [comment]
Test with 1 million rows

- New version 
https://7q6dc.csb.app/
- 4.0.0-alpha.26
https://tyr6e.csb.app/

**Comment by dtassone** [comment]
Filter and rendering should be faster. 

Sorting will not be affected, as this change did not affect the comparator functions.

**Comment by oliviertassinari** [comment]
>https://tyr6e.csb.app/

@dtassone I think that we should be very careful with using measures in development. It's ok to get a rough idea of where the bottleneck is, but I don't think that it has any other value. For instance, it should especially not be used to determine if a PR is an improvement or a regression. In our case, it was so slow before that it was as if the feature wasn't present 😁.

I had a look, using the production versions:

### Sorting

In this reproducible benchmark, I have sorted the quantity column once.

Screenshot 2021-04-29 at 00 51 29

https://deploy-preview-1513--material-ui-x.netlify.app/components/data-grid/#commercial-version

Screenshot 2021-04-29 at 00 51 25

https://material-ui.com/components/data-grid/#commercial-version

It looks the same. If you account for the fact that sorting these very 100,000 rows [takes <1ms](https://codesandbox.io/s/material-demo-forked-0d22r?file=/demo.tsx), I don't see why it wouldn't render in ~100ms, not x10 more.

### Filtering

In this benchmark, I filter the rows with quantity > 1.

Screenshot 2021-04-29 at 00 54 35

https://deploy-preview-1513--material-ui-x.netlify.app/components/data-grid/#commercial-version

Screenshot 2021-04-29 at 00 57 39

https://material-ui.com/components/data-grid/#commercial-version

It looks like the filtering was not working before. However, if you account for the fact that filtering these very 100,000 rows [takes <1ms](https://codesandbox.io/s/material-demo-forked-0d22r?file=/demo.tsx), something seems still x10, I don't see why it wouldn't render in ~100ms, not x10 more.

File: packages/grid/_modules_/grid/models/params/gridColumnHeaderParams.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ export interface GridColumnHeaderParams {
   /**
    * The HTMLElement column header element.
    */
-  element?: HTMLElement | null;
+  getElement: (field: string) => HTMLElement | null;
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/params/gridColumnHeaderParams.ts:8]: This doesn't make sense, we are already on a specific field
```suggestion
  getElement: () => HTMLElement | null;
```

**Comment by dtassone** [comment]
More perf tweaks
- Remove functions of params (avoid rerendering)
- Remove SVG icons
- Add React.memo

@oliviertassinari do we see more improvements?

**Comment by oliviertassinari** [comment]
@dtassone Netlify is not building I can't tell. What is the current bottleneck?

**Comment by oliviertassinari** [comment]
Having a quick look at the bottleneck.

The x10 issue with the number sorting seems to come from the code structure, it does a lot of work that ends up trashed. Assuming [N](https://en.wikipedia.org/wiki/Big_O_notation) is the number of rows doesn't understand why:

- we compute the value O(2N), instead of O(N).
- we don't start by extracting all the values O(N) times, instead of doing it O(N^2) times.
- we compute the row while we might not need it

I would expect a significant difference by solving the bove

Regarding the filtering, the issue is simpler than sorting, there is no N^2 scaling issue. It's more about computing a log of things that are trashed in the end.

**Comment by dtassone** [comment]
TODO
- Remove use of rowIndex and Col index in setCellFocus, and internally
- Add tabIndex (or hasFocus) in cell params? 
- Add getValue function only in cellValueGetter?

Sorting Perf issue
- Refactor comparator to avoid calling getValue(A) getValue(B) => check perf

**Comment by oliviertassinari** [comment]
A summary of what we talk about during today's call

1. filtering doesn't work >60s => remove read DOM, x100 faster https://github.com/mui-org/material-ui-x/issues/1506. We can add the same test case as we did for the sorting that was reading the DOM
2. slow rerender when heavy components in cell => prune rendering at one layer before the cell level https://github.com/mui-org/material-ui-x/issues/569. It work much better. We can add a test case to test if it rerenders or not
3. keyboard too slow => improve rerendering perf (2.) or bypass React with imperative DOM actions https://github.com/mui-org/material-ui-x/issues/1427
4. sort n*log(n) => prepare arguments for the sortCompartor. win => log(n), x6 with 100k rows
5. filtering & sort computing extra params that are not used. win potential x4, maybe reproduce what vercel has to monitor performance https://github.com/vercel/next.js/pull/24440
6. hook dependencies comparison cost => maybe later in the future (no proof that it's a bottleneck now)
7. 60 FPS resize freeze: https://github.com/mui-org/material-ui-x/issues/799
8. tree-shaking:

File: packages/storybook/src/stories/playground/customize-components.stories.tsx [hunk 2]
```diff
@@ -158,7 +158,9 @@ StyledColumns.args = {
       headerClassName: 'highlight',
       sortable: false,
       valueGetter: (params) =>
-        `${params.getValue('firstName') || ''} ${params.getValue('lastName') || ''}`,
+        `${params.api.getCellValue(params.id, 'firstName') || ''} ${
+          params.api.getCellValue(params.id, 'lastName') || ''
```
Comment (dtassone) [inline packages/storybook/src/stories/playground/customize-components.stories.tsx:162]: Should ValueGetterParams get the `getValue` function 🤔

Comment (dtassone) [reply packages/storybook/src/stories/playground/customize-components.stories.tsx:162]: So ppl that didn't buy the licence can use it

File: packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts [hunk 3]
```diff
@@ -53,26 +53,24 @@ export function useGridParamsApi(apiRef: GridApiRef) {
...
         id,
         field,
         row,
         value: row[field],
-        getValue: (columnField: string) => apiRef.current.getCellValue(id, columnField),
         colDef: apiRef.current.getColumnFromField(field),
         cellMode: apiRef.current.getCellMode(id, field),
-        rowIndex: apiRef.current.getRowIndexFromId(id),
-        colIndex: apiRef.current.getColumnIndex(field, true),
+        // getValue: apiRef.current.getCellValue,
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts:65]: add or clean!

File: packages/storybook/src/stories/playground/customize-components.stories.tsx (hunk 2 above)
Comment (dtassone) [reply packages/storybook/src/stories/playground/customize-components.stories.tsx]: Done!

File: packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts (hunk 3 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts]: added

**Comment by dtassone** [comment]
Cell editing is broken

**Comment by oliviertassinari** [comment]
I have pushed two commits to improve the performance of sort, leveraging the log(N) point I made earlier. I have tested on the "Quantity" column: https://deploy-preview-1513--material-ui-x.netlify.app/components/data-grid/#commercial-version.

**Before**
Screenshot 2021-05-08 at 02 24 21

**After**
Screenshot 2021-05-08 at 02 24 11

Enjoy.

**Comment by oliviertassinari** [comment]
Regarding the PR titles, I have renamed this one, we uppercase after the [label] and renamed optimisation, we use en_US not en_GB.

**Review by oliviertassinari — DISMISSED** [review]
> One thing that would be awesome is to add a performance test to make sure we can't completely break it in the future, [as we did](https://github.com/mui-org/material-ui-x/blob/3d06625fb9f3b9045c91f6fe19f7f5969e4acbd3/packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx#L222) a month ago. 

Actually, since we fixed the rerendering logic. I think that it's really important that we add a test for this as well, something [in this order](https://github.com/mui-org/material-ui/blob/4a0e2459dc33c5e99df8419fc251db90638d65e7/packages/material-ui-styles/src/makeStyles/makeStyles.test.js#L508). It seems easy to break.

File: packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx [hunk 4]
```diff
@@ -221,5 +221,43 @@ describe('<XGrid /> - Sorting', () => {
...
+            <XGrid columns={cols} rows={data.rows} />
+          </div>
+        );
+      };
+
+      render(<TestCasePerf />);
+      const header = document.querySelector('.currency-pair-component');
+      renderHeaderCount = 0;
+      fireEvent.click(header);
+      await waitFor(() => expect(document.querySelector('.MuiDataGrid-sortIcon')).to.not.be.null);
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx:259]:
```suggestion
      await waitFor(() => expect(document.querySelector('.MuiDataGrid-sortIcon')).to.not.equal('null'));
```

File: packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx [hunk 5]
```diff
@@ -221,5 +221,43 @@ describe('<XGrid /> - Sorting', () => {
...
+      let renderHeaderCount = 0;
+      const TestCasePerf = () => {
+        const [cols, setCols] = React.useState<GridColDef[]>([]);
+        const data = useData(5000, 10);
+
+        React.useEffect(() => {
+          if (data.columns.length) {
+            const newColumns = [...data.columns];
+            newColumns[1].renderHeader = (params) => {
+              renderHeaderCount += 1;
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx:241]: As a general note, it would be better to move this into a useEffect, so we can leave React start and interrupts its rendering as he sees fit, and only see when a change is actually committed.

File: packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx [hunk 6]
```diff
@@ -257,6 +259,48 @@ describe('<XGrid /> - Filter', () => {
...
+            columnField: 'currencyPair',
+            value: 'usd',
+            operatorValue: 'startsWith',
+          },
+        ],
+      };
+      const t0 = performance.now();
+      apiRef.current.setFilterModel(newModel);
+
+      await waitFor(() => expect(document.querySelector('.MuiDataGrid-filterIcon')).to.not.be.null);
```
[the remark this answers is not in the document]
Comment (dtassone) [reply packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx:298]: I added the class name as I thought it was missing, as we have an equivalent class for the sort icon. 
This is basically the exact same approach as we did for the sort performance test.

[the remark this answers is not in the document]
Comment (dtassone) [reply packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx:298]: The rows are randomly generated to not sure how many there will be after the filtering

File: packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx (hunk 5 above)
Comment (dtassone) [reply packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx:241]: Not sure what you mean.
If I add a useEffect in the TestComponent, I don't think it will be meaningful as it won't reflect the grid internal rendering

Comment (oliviertassinari) [reply packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx:235]: In strict mode, render methods are called twice for each commit. In concurrent mode, React can render but not commit. In order to reliably test that memo is working, useEffect is a reliably to assert if a memo has worked, or not.

Comment (oliviertassinari) [reply packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx:238]: @eps1lon Thanks for sharing these thoughts, however, I'm not sure we can act on it here.
The problem we are trying to solve is: how to reliably test that a memo logic is working (to avoid regressions)? I had linked https://github.com/mui-org/material-ui/blob/4a0e2459dc33c5e99df8419fc251db90638d65e7/packages/material-ui-styles/src/makeStyles/makeStyles.test.js#L508 as a way to approach it. What would you recommend?

Comment (dtassone) [reply packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx:238]: if you just want to add 
```tsx
        const rendered = React.useRef(1);
        React.useEffect(() => {
          rendered.current += 1;
        });
```
Then you need to add it in a component that will be rerendered when the grid renders, that could be a header, footer, cell, or column header. 

The way I did it, is via the `renderCell` and `renderHeader` functions, which get called when the cell or header render so it's the same. I can add an intermediary component such as below but I doubt it will add any value
```tsx
const TestCell = ()=> {
        const rendered = React.useRef(1);
        React.useEffect(() => {
          rendered.current += 1;
        });
...
}

renderCell: ()=> <TestCell {...params} />
```

**Comment by oliviertassinari** [comment]
@dtassone So no peer reviews?

File: packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx (hunk 5 above)
Comment (oliviertassinari) [reply packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx:238]: >  I can add an intermediary component such as below but I doubt it will add any value

Yes, this what I had assumed would ensure we reliably test the memo, based on: https://github.com/mui-org/material-ui-x/pull/1513/files#r629548477, e.g. if we are in strict mode, you should get two render call for each "interaction".

**Comment by dtassone** [comment]
> @dtassone So no peer reviews (I don't count 😁)?

😄  Well I took `Outside of the notes I have left, nothing to report :)` as ready beside the tests.

It's a very important PR, as it's touching also the new issues that @m4theushw is looking at now, so we needed it in right now.  It's very important to integrate otherwise we will have to refactor new work...
I have created a new issue for the tests #1653

File: packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx (hunk 5 above)
Comment (eps1lon) [reply packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx:238]: > I'm not sure we can act on it here.

I was responding to your claims. Neither Damien nor I could make sense of them so I tried to bring some clarity.

> How to reliably test that a memo logic is working (to avoid regressions)?

You don't. You monitor performance because that's the feature `React.memo` is implementing. You don't test the actual implementation detail.

**Comment by bgandy94** [comment]
So I'm sure it's something in my code, and I'll try to create a CSB asap, but in a `valueGetter` in a `GridColDef`, is it still valid to use the `getValue()` method to retrieve the cell value?

I just tried upgrading to `4.0.0-alpha.29` and had to change my `getValue(name)` to `getValue(id, name)` and now the return of the `getValue` call is undefined. is this related to #1731?

**Comment by oliviertassinari** [comment]
@dtassone Why did we change the API of `getValue`? I have tried:

```diff
diff --git a/packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts b/packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
index 17126faa..b0f4783c 100644
--- a/packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
+++ b/packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
@@ -63,7 +63,7 @@ export function useGridParamsApi(apiRef: GridApiRef) {
         value: row[field],
         colDef: apiRef.current.getColumn(field),
         cellMode: apiRef.current.getCellMode(id, field),
-        getValue: apiRef.current.getCellValue,
+        getValue: (...args) => apiRef.current.getCellValue(...args),
         api: apiRef.current,
         hasFocus: cellFocus !== null && cellFocus.field === field && cellFocus.id === id,
         tabIndex: cellTabIndex && cellTabIndex.field === field && cellTabIndex.id === id ? 0 : -1,
```

I couldn't notice a change in the number of React renders nor in the time taken by the filtering to handle 100k rows.

**Comment by dtassone** [comment]
```tsx
       getValue: (...args) => apiRef.current.getCellValue(...args),
```
You create a new function every time you call `getCellParams`, so it will break the component memoization.

**Comment by oliviertassinari** [comment]
> it will break the component memoization

@dtassone Thanks for the clarification. I have tried to follow to see where the property is used. `getValue` is used by `getRowParams` which results is never applied on a React element. `getValue` is also used by `getBaseCellParams`, spread on `getCellParams`, that is then provided to `renderCell`.

I guess it saves a rerender if a developer spread all the props into a component that is memo? But isn't the parent Cell, in the core of the data grid already memo and avoid the rerenders?

So it seems that we can restore the previous logic, is it accurate?

**Comment by oliviertassinari** [comment]
> I guess it saves a rerender if a developer spread all the props into a component that is memo? But isn't the parent Cell, in the core of the data grid, already memo? avoiding the rerenders.
So it seems that we can restore the previous logic, is it accurate?

@dtassone I had a closer look, I'm giving up on the idea. Even if the parent of renderCell has a memo logic, making a memo of the children harmful in most of the cases, since the breaking change has been released for a coupe of weeks now, doing the opposite BC would likely be more harmful than helpful.
