### PR TITLE
[XGrid] Support column reordering inside the whole grid

### LINKED ISSUE #445: [DataGrid] Column reordering is too limiting
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

- End-users have to concentrate on keeping the same vertical alignment with their pointing device when reordering columns.
- End-users can't cancel the reorder of a column if they did it by mistake.

## Expected Behavior 🤔

- Column reordering works inside the whole grid (not only the header).
- Previous swaps of columns are canceled when the pointer leaves the grid.

## Steps to Reproduce 🕹

https://master--material-ui-x.netlify.app/components/data-grid/columns/#column-reorder

## Context 🔦

Follow-up on #165.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.6  |

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #445.
Preview https://deploy-preview-1250--material-ui-x.netlify.app/components/data-grid/demo/

### Breaking changes

- [XGrid] Event `GRID_COLUMN_REORDER_DRAG_OVER_HEADER` is no longer emitted

---

My approach here was to turn every cell into a droppable target. If https://github.com/mui-org/material-ui-x/issues/206 gets implemented an additional check may be needed to determine if a column cell or a row cell was dropped. I'm using the value of [`dropEffect`](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect) to determine if the user canceled the reordering (dropping outside or pressing Escape).

Result:

Peek 2021-03-18 00-07

### CODE REVIEW

**Comment by m4theushw** [comment]
I need some help to fix the failing tests on CI. In [all](https://app.circleci.com/pipelines/github/mui-org/material-ui-x/3645/workflows/40548a05-a4bc-42ee-8029-b278f2804ece/jobs/16285) browsers they passed, but not on Safari. Locally, using the version I have, they passed too. 

Screen Shot 2021-03-17 at 23 49 38

File: packages/grid/_modules_/grid/components/GridCell.tsx [hunk 1]
```diff
@@ -102,6 +101,21 @@ export const GridCell: React.FC<GridCellProps> = React.memo((props) => {
     [publish, publishClick],
   );
 
+  const onDragEnter = React.useCallback((event) => apiRef!.current.onColItemDragEnter(event), [
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/GridCell.tsx:104]: this onColItem... should be refactored and will be removed
#1201

File: packages/grid/_modules_/grid/components/GridCell.tsx [hunk 2]
```diff
@@ -52,6 +50,7 @@ export const GridCell: React.FC<GridCellProps> = React.memo((props) => {
   const valueToRender = formattedValue || value;
   const cellRef = React.useRef<HTMLDivElement>(null);
   const apiRef = React.useContext(GridApiContext);
+  const { align = 'left', field } = column;
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/GridCell.tsx:53]: Why do you need the column now?

**Comment by dtassone** [comment]
lot of refactoring are also coming on the grid cell as part of #1205

File: packages/grid/_modules_/grid/components/GridCell.tsx (hunk 2 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/components/GridCell.tsx:53]: I need it to call `onColItemDragOver` later in this file. Previously I just had the field and align from the column as props.

Comment (dtassone) [reply packages/grid/_modules_/grid/components/GridCell.tsx:53]: in #1201 we will remove this method of apiRef as they don't really make sense. 
I think #1201 should come before this changes.
This method start an action instead of letting you subscribe to an event.

You can refactor by passing the field and retrieving the column directly in the handler using apiRef.

File: packages/grid/_modules_/grid/components/GridCell.tsx (hunk 1 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/GridCell.tsx:104]: I think we still need to keep the APIs because they are used in the header cells but we will need to add handlers on the grid component itself that call those APIs to satisfy the requirement from https://github.com/mui-org/material-ui-x/issues/1201

File: packages/grid/_modules_/grid/components/GridCell.tsx [hunk 3]
```diff
@@ -102,6 +101,21 @@ export const GridCell: React.FC<GridCellProps> = React.memo((props) => {
     [publish, publishClick],
   );
 
+  const onDragEnter = React.useCallback((event) => apiRef!.current.onColItemDragEnter(event), [
+    apiRef,
+  ]);
+
+  const onDragOver = React.useCallback(
```
Comment (DanailH) [inline packages/grid/_modules_/grid/components/GridCell.tsx:108]: We have a convention that we use `handle` instead of `on` so this method will become `handleDragOver`.

```suggestion
  const handleDragOver = React.useCallback(
```

Comment (m4theushw) [reply packages/grid/_modules_/grid/components/GridCell.tsx:108]: I'll rename it. I took these names from [here](https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx#L74).

File: packages/grid/_modules_/grid/components/GridCell.tsx (hunk 1 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/GridCell.tsx:104]: apiRef should not be trigger for events.

There should not be any method like `handleDragEnd ` on it. You can subscribe to an handler using `subscribeEvent` but not just put them there. That's not its purpose.

Only api methods that can be used to retrieve data, or manipulate the grid. 
Something like `setColumnIndex(field, index)` is appropriate in this case.
So users can reset the index outside the drag action.

**Comment by oliviertassinari** [comment]
> I need some help to fix the failing tests on CI. In all browsers they passed, but not on **Safari**. Locally, using the version I have, they passed too.

@m4theushw You can use our BrowserStack credentials to run the test in Safari, only. Here https://www.notion.so/BrowserStack-945f0ccb9f7749ccb9e84b9eb9b13ec7, use the "env" part.

File: packages/grid/_modules_/grid/constants/eventsConstants.ts [hunk 4]
```diff
@@ -59,12 +67,6 @@ export const GRID_COL_RESIZE_STOP = 'colResizing:stop';
 
 export const GRID_COLUMN_ORDER_CHANGE = 'columnOrderChange';
 
-export const GRID_COLUMN_REORDER_START = 'columnReordering:dragStart';
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/constants/eventsConstants.ts:62]: IMO events should be named according to the DOM events that they listen to and not the context in which they are used. Different hooks could subscribe to the same event.

**Review by dtassone — APPROVED** [review]
