### PR TITLE
[DataGrid] Fix delete key for uneditable cells

### LINKED ISSUE #1452: [DataGrid] The `backspace` key empties no editable cells
When I select a cell by click on it and then I press the Backspace button from the keyword the cell completely clears.

I'm already using disableSelectionOnClick and disableClickEventBubbling.

**THE SAME ISSUE IS WITH DELETE BUTTON ALSO.**

download

SandBox Link: https://codesandbox.io/s/datagrid-quick-start-forked-446ly

### PR DESCRIPTION
**Pull request by dtassone**
fix #1452

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts [hunk 1]
```diff
@@ -268,7 +268,7 @@ export function useGridEditRows(apiRef: GridApiRef) {
 
   const handleCellKeyDown = React.useCallback(
     (params: GridCellParams, event) => {
-      if (event.isPropagationStopped()) {
+      if (!params.isEditable || event.isPropagationStopped()) {
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts:271]: This makes me think about https://github.com/mui-org/material-ui-x/issues/1300#issuecomment-808742299. We could likely do a follow up with them.

File: packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx [hunk 2]
```diff
@@ -139,6 +139,17 @@ describe('<XGrid /> - Edit Rows', () => {
...
 
+  it('should not allow to delete a cell directly if it is not editable', () => {
+    render(<TestCase isCellEditable={()=> false} />);
+    const cell = getCell(1, 0);
+    cell.focus();
+
+    expect(cell.textContent).to.equal('Adidas');
+    fireEvent.keyDown(cell, { key: 'Delete' });
+    expect(cell).to.not.have.class('MuiDataGrid-cellEditable');
+    expect(cell.textContent).to.equal('Adidas');
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx:150]: You could improve the error message if we break this test with:

```suggestion
    expect(cell).to.have.text('Adidas');
```

File: packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx [hunk 3]
```diff
@@ -139,6 +139,17 @@ describe('<XGrid /> - Edit Rows', () => {
...
   });
 
+  it('should not allow to delete a cell directly if it is not editable', () => {
+    render(<TestCase isCellEditable={()=> false} />);
+    const cell = getCell(1, 0);
+    cell.focus();
+
+    expect(cell.textContent).to.equal('Adidas');
+    fireEvent.keyDown(cell, { key: 'Delete' });
+    expect(cell).to.not.have.class('MuiDataGrid-cellEditable');
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx:149]: See https://github.com/mui-org/material-ui/pull/24884 for the best English semantic:

```suggestion
    expect(cell).not.to.have.class('MuiDataGrid-cellEditable');
```

**Review by oliviertassinari — APPROVED** [review]
