### PR TITLE
[DataGrid] Fix shift+space keyboard regression to select row

### LINKED ISSUE #889: [DataGrid] Keyboard shortcut to select a row (Shift+Space) not working
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Datagrid renders and a cell has tab focus, using the shortcut SHIFT+SPACE as per [docs](https://material-ui.com/components/data-grid/accessibility/) to select the row, results in nothing to happen. Tested on latest Chrome and Firefox releases.

## Expected Behavior 🤔

The row of the cell that had focus after using the shortcut is selected.

## Steps to Reproduce 🕹
See current behavior
https://codesandbox.io/s/material-ui-issue-latest-forked-njidy?file=/src/Demo.js

## Context 🔦

Aim: Make the datagrid accessible again.

## Your Environment 🌎
  Chrome: Version 87.0.4280.141 (Official Build) (x86_64)
  Firefox: 84.0.2 (64-bit)
  
<details>
  <summary>`npx @material-ui/envinfo`</summary>
```
 System:
    OS: macOS 11.1
  Binaries:
    Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.14.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Not Found
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    @material-ui/core: ^4.11.0 => 4.11.0 
    @material-ui/data-grid: ^4.0.0-alpha.17 => 4.0.0-alpha.17 
    @material-ui/icons: ^4.9.1 => 4.9.1 
    @material-ui/lab: ^4.0.0-alpha.56 => 4.0.0-alpha.56 
    @material-ui/styles:  4.10.0 
    @material-ui/system:  4.9.14 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.10.2 
    @types/react: ^16.9.32 => 16.9.55 
    react: 16.14.0 => 16.14.0 
    react-dom: ^16.12.0 => 16.14.0 
    styled-components: ^5.2.1 => 5.2.1 
    typescript: ^3.8.3 => 3.9.7 
```
</details>

### PR DESCRIPTION
**Pull request by dtassone**
Fix #889

### CODE REVIEW

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
It's a regression and not obvious to spot, I think that it should have a test case

File: packages/grid/_modules_/grid/utils/keyboardUtils.ts [hunk 1]
```diff
@@ -1,10 +1,10 @@
 export const MULTIPLE_SELECTION_KEYS = ['Meta', 'Control'];
-export const isMultipleKey = (code: string): boolean => MULTIPLE_SELECTION_KEYS.indexOf(code) > -1;
-export const isTabKey = (code: string): boolean => code === 'Tab';
-export const isSpaceKey = (code: string): boolean => code === 'Space';
-export const isArrowKeys = (code: string): boolean => code.indexOf('Arrow') === 0;
-export const isHomeOrEndKeys = (code: string): boolean => code === 'Home' || code === 'End';
-export const isPageKeys = (code: string): boolean => code.indexOf('Page') === 0;
+export const isMultipleKey = (key: string): boolean => MULTIPLE_SELECTION_KEYS.indexOf(key) > -1;
```
Comment (DanailH) [inline packages/grid/_modules_/grid/utils/keyboardUtils.ts:2]: Didn't @oliviertassinari rename those to `key` not that long ago? I personally am ok with either one but `key` does sound more appropriate as it represents the actual key name, the `code` is different.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/utils/keyboardUtils.ts:2]: @DanailH The change looks great, what's your concern?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/utils/keyboardUtils.ts:2]: Actually, why is it implemented like this? Why didn't we use a stateless approach?

https://github.com/mui-org/material-ui/blob/67e75ced891966ef38f9fff3253db8582d0fbe87/packages/material-ui-lab/src/TreeView/TreeView.js#L645

Comment (DanailH) [reply packages/grid/_modules_/grid/utils/keyboardUtils.ts:2]: Ignore/resolve my comment. For some reason, I thought that the change is from `key` to `code`.

Comment (dtassone) [reply packages/grid/_modules_/grid/utils/keyboardUtils.ts:2]: Yes we could refactor isMultipleKey..., it will impact sorting, selection...
ATM I didn't feel it was too much a pain so left it

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/utils/keyboardUtils.ts:2]: Agree, it's definitely off-topic for the bug we are solving :)

File: test/utils/helperFn.ts [hunk 2]
```diff
@@ -49,3 +49,23 @@ export function getColumnHeaders() {
...
+export function getCell(rowIndex: number, colIndex: number): HTMLElement {
+  const cell = document.querySelector(
+    `[role="cell"][data-rowindex="${rowIndex}"][aria-colindex="${colIndex}"]`,
+  );
+  if (cell == null) {
+    throw new Error(`Cell ${rowIndex} ${colIndex} not found`);
+  }
+  return cell as HTMLElement;
+}
+export function focusCell(rowIndex: number, colIndex: number) {
```
Comment (oliviertassinari) [inline test/utils/helperFn.ts:61]: I think that it's important we keep the usage of the test helpers to their bare minimum. The fewer we can get away with, the more duplication we can have between tests, the more reliable and helpful they will be.

In this case, the focusCell looks redundant, there are no complexity worth abstracting.

```suggestion
```

Comment (dtassone) [reply test/utils/helperFn.ts:61]: it avoids doing `getCell(0, 0).focus()` 
It looks nice and easy to read.
Also I was thinking of moving the check active element  or even deleting it

File: packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx [hunk 3]
```diff
@@ -153,17 +153,32 @@ describe('<DataGrid /> - Keyboard', () => {
...
+    render(<KeyboardTest />);
+    getCell(0, 0).focus();
+    expect(getActiveCell()).to.equal('0-0');
+    fireEvent.keyDown(document.activeElement!, SHIFT_SPACE_KEY);
+    const row = getRow(0);
+    const isSelected = row.classList.contains('Mui-selected');
+    expect(isSelected).to.equal(true);
+  });
+
+  it('Space only should go to the bottom of the page', async () => {
```
Comment (oliviertassinari) [inline packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:166]:
```suggestion
  it('Space only should go to the bottom of the page', () => {
```

File: test/utils/helperFn.ts [hunk 4]
```diff
@@ -49,3 +49,20 @@ export function getColumnHeaders() {
     (node) => node!.textContent,
   );
 }
+export function getCell(rowIndex: number, colIndex: number): HTMLElement {
```
Comment (oliviertassinari) [inline test/utils/helperFn.ts:52]:
```suggestion

export function getCell(rowIndex: number, colIndex: number): HTMLElement {
```

File: packages/grid/_modules_/grid/utils/keyboardUtils.ts [hunk 5]
```diff
@@ -1,10 +1,10 @@
 export const MULTIPLE_SELECTION_KEYS = ['Meta', 'Control'];
-export const isMultipleKey = (code: string): boolean => MULTIPLE_SELECTION_KEYS.indexOf(code) > -1;
-export const isTabKey = (code: string): boolean => code === 'Tab';
-export const isSpaceKey = (code: string): boolean => code === 'Space';
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/utils/keyboardUtils.ts:4]: It took me some time to find where was the fix, spotted. `Space` => `' '`

**Review by oliviertassinari — APPROVED** [review]

**Review by DanailH — APPROVED** [review]
