### PR TITLE
[DataGrid] Add 'nonce' prop to allow inline style if user has CSP

### LINKED ISSUE #541: [DataGrid] CSP nonce does not get passed to AutoSizer component
DataGrid component does not pass CSP nonce to AutoSizer component at https://github.com/mui-org/material-ui-x/blob/069daa728084f53db049544f70922af66f740568/packages/grid/_modules_/grid/GridComponent.tsx#L96, which in turn does not get passed to resize observer at https://github.com/mui-org/material-ui-x/blob/069daa728084f53db049544f70922af66f740568/packages/grid/_modules_/grid/components/AutoSizer.tsx#L117

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Error `Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://fonts.googleapis.com 'nonce-R29+/m4IVse+cw3MIfe57A=='". Either the 'unsafe-inline' keyword, a hash ('sha256-deDIoPlRijnpfbTDYsK+8JmDfUBmpwpnb0L/SUV8NeU='), or a nonce ('nonce-...') is required to enable inline execution.` appears in browser console when trying to render DataGrid component, despite `<meta property="csp-nonce" name="csp-nonce" content="LJ6WDXdsQlWY/6YSN9P/Mw==">` being present in page header as per https://material-ui.com/styles/advanced/#what-is-csp-and-why-is-it-useful.

## Expected Behavior 🤔

Generated styles use CSP nonce and error does not appear.

## Steps to Reproduce 🕹

Steps:

1. Configure web server to serve `Content-Security-Policy` header with `nonce` value for `style-src`;
2. Add csp-nonce meta tag as per https://material-ui.com/styles/advanced/#what-is-csp-and-why-is-it-useful
3. Try to render DataGrid component in page;
4. Observe error.

## Context 🔦

I'm trying to follow best CSP practices and MUI guidelines.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| @material-ui/data-grid | 4.0.0-alpha.8  |
| React         |    17.0.1     |
| Browser       |   Chrome @ latest      |
| TypeScript    |    4.0.5     |

### PR DESCRIPTION
**Pull request by ZeeshanTamboli**
Resolves #541 

Introduce `nonce` prop for DataGrid and XGrid. Updated docs API as well. Let me know if I missed anything or any change. 

My first PR for the Material-UI organization. You guys do excellent work! Looking forward to contribute more! 

Thanks!

### CODE REVIEW

**Review by oliviertassinari — APPROVED** [review]

File: packages/grid/_modules_/grid/GridComponent.tsx [hunk 1]
```diff
@@ -123,7 +123,7 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
     }
 
     return (
-      <AutoSizer onResize={onResize}>
+      <AutoSizer onResize={onResize} nonce={props.nonce}>
```
Comment (dtassone) [inline packages/grid/_modules_/grid/GridComponent.tsx:126]: Should it be on on the `AutoSizer` or `GridRoot` 🤔

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/GridComponent.tsx:126]: What do you mean? `nonce` is not an HTML attribute in case the confusion come from there.

**Comment by oliviertassinari** [comment]
@ZeeshanTamboli Thanks
