### PR TITLE
[DataGrid] Fix display of row count and selected rows on mobile

### LINKED ISSUE #440: [DataGrid] Footer issue on mobile
The problem: 

- there is an empty white area.
- we are missing selected rows
- we are missing total rows

footer

The solution: display them, in a smart way

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #440 

This PR aims to solve the issue of having the `Total Rows` and  `rows selected` counts hidden on small screens. I didn't change the styling but only made the 2 files visible.

Screenshot 2020-10-29 at 15 22 44

### CODE REVIEW

**Review by oliviertassinari — COMMENTED** [review]
It doesn't fit on mobile with pagination:

Capture d’écran 2020-10-29 à 15 40 08

https://deploy-preview-508--material-ui-x.netlify.app/components/data-grid/pagination/

**Comment by DanailH** [comment]
> It doesn't fit on mobile with pagination:
> 
> Capture d’écran 2020-10-29 à 15 40 08
> 
> https://deploy-preview-508--material-ui-x.netlify.app/components/data-grid/pagination/

Yes about that, I saw it (its event worst if you select a row) but I'm not sure how to handle it design-wise. Maybe we can have a discussion about it. The fix will be easy to implement. What do you think @oliviertassinari  ?

**Comment by oliviertassinari** [comment]
What about we make it use two rows if the feature is abled? cc @dtassone

**Comment by DanailH** [comment]
That would definitely solve the issue but with the tradeoff that the footer height will increase and if you have set your grid to height to a smaller number there may bot be enough height for the visible part (although I'm not sure how valid of an argument that is since setting the height of the Grid is done by the user)

**Comment by oliviertassinari** [comment]
Oh right, in this case, maybe we can keep as single row, but have a priority rule, pagination wins over selected row/row count. If no pagiantino nor row count, hide the footer.

**Comment by dtassone** [comment]
How about we hide a few things in the pagination component.
So we just display 2 buttons to navigate bw pages

**Comment by dtassone** [comment]
For the info about rows we can change it as well, reduce the wordings or put it on 2 rows

200 Rows, 1 selected

**Comment by oliviertassinari** [comment]
> For the info about rows we can change it as well, reduce the wordings or put it on 2 rows

This would need to be translated, I would vote against for simplicity. Can a mobile user leverage the information.

**Comment by dtassone** [comment]
> > For the **info about rows we can change it as well**, reduce the wordings or put it on 2 rows
> 
> The wordings will need to be **translated** with an API, it will increase it. It might also still overflow in another locale, so I would vote against for simplicity. Can a mobile user leverage the information?

Yeah maybe just the total rows on mobile. Also can we put only 2 btns for pagination?

**Comment by DanailH** [comment]
I'll play around and create a couple of options and attach them here as screenshots to see which one will look the best

**Comment by oliviertassinari** [comment]
Mayby hiding the rows per page would be enough. The best case is if we can manage the logic with CSS only, so its easier to customize (as opposed to changing the DOM).

**Comment by DanailH** [comment]
Ok I did some tests and it seems that the easies and most secure option is what @oliviertassinari suggested - hide the selected row and total row count. The reason is that the for the footer we are using the `TablePagination` from `core` and changing that will be tricky. The other option is to implement our own DataGrid footer component. I'm open for suggestions :D

**Comment by oliviertassinari** [comment]
@DanailH Sounds good, so and on desktop, we leave it untouched.

**Comment by dtassone** [comment]
> Ok I did some tests and it seems that the easies and most secure option is what @oliviertassinari suggested - hide the selected row and total row count. The reason is that the for the footer we are using the `TablePagination` from `core` and changing that will be tricky. The other option is to implement our own DataGrid footer component. I'm open for suggestions :D

How about we keep what is circled in orange only?

image

The row counter is actually displayed already in the pagination

**Comment by DanailH** [comment]
> @DanailH Sounds good, so and on desktop, we leave it untouched.

Sure, we can do that. currently, it hides it also on desktop but I can easily change it 😉

**Comment by DanailH** [comment]
> > Ok I did some tests and it seems that the easies and most secure option is what @oliviertassinari suggested - hide the selected row and total row count. The reason is that the for the footer we are using the `TablePagination` from `core` and changing that will be tricky. The other option is to implement our own DataGrid footer component. I'm open for suggestions :D
> 
> How about we keep what is circled in orange only?
> 
> image
> 
> The row counter is actually displayed already in the pagination

This change will still require to update/change the `TablePagination` component from `core` because the rows per page section is in it and there is no API to hide it or at least I cant' see one -> https://material-ui.com/api/table-pagination/

**Comment by dtassone** [comment]
> > > Ok I did some tests and it seems that the easies and most secure option is what @oliviertassinari suggested - hide the selected row and total row count. The reason is that the for the footer we are using the `TablePagination` from `core` and changing that will be tricky. The other option is to implement our own DataGrid footer component. I'm open for suggestions :D
> > 
> > 
> > How about we keep what is circled in orange only?
> > image
> > The row counter is actually displayed already in the pagination
> 
> This change will still require to update/change the `TablePagination` component from `core` because the rows per page section is in it and there is no API to hide it or at least I cant' see one -> https://material-ui.com/api/table-pagination/

You can do it with CSS

**Comment by dtassone** [comment]
You can also display the grid row counter only when there is no pagination

**Comment by DanailH** [comment]
Yes, that's what I'm doing now. If the pagination is available the `Total rows` and `Rows selected` are hidden.

**Comment by DanailH** [comment]
> > > > Ok I did some tests and it seems that the easies and most secure option is what @oliviertassinari suggested - hide the selected row and total row count. The reason is that the for the footer we are using the `TablePagination` from `core` and changing that will be tricky. The other option is to implement our own DataGrid footer component. I'm open for suggestions :D
> > > 
> > > 
> > > How about we keep what is circled in orange only?
> > > image
> > > The row counter is actually displayed already in the pagination
> > 
> > 
> > This change will still require to update/change the `TablePagination` component from `core` because the rows per page section is in it and there is no API to hide it or at least I cant' see one -> https://material-ui.com/api/table-pagination/
> 
> You can do it with CSS

True, but should we do it like this, hack our own components. It's better to introduce a prop in the `TablePagination` to hide then. I can do it, it's not a problem @oliviertassinari ?

**Comment by oliviertassinari** [comment]
@DanailH The data grid relies on core v4 so far, we can't expect any changes to land in it. However, the table pagination exposes enough public API, so no need to hack around.

File: packages/grid/_modules_/grid/components/pagination.tsx [hunk 1]
```diff
@@ -11,6 +12,16 @@ export interface PaginationComponentProps {
   rowsPerPageOptions?: number[];
 }
 
+// Used to hide the drop down select from the TablePaginagion
+const useStyles = makeStyles({
```
Comment (DanailH) [inline packages/grid/_modules_/grid/components/pagination.tsx:16]: Ok, I've updated the logic with what we discussed during the planning today, here is the summary:
 - Remove `Total Rows` when the pagination is available
 - Remove the select and the label inside the `TablePagination`
 - Update the login so the `selected rows` is only shown on desktop when the pagination is available 
 - Adjust the footer items alignment when there is only pagination (it should be aways on the right side)

Last but not least a question - these styles are needed to hide the select from the `TablePagination` component but I'm not sure it this is the best place to keep them, ideas ?

**Comment by DanailH** [comment]
Hmm I guess the flaky test is this one `Chrome 84.0.4147.89 (Mac OS 10.15.6) <XGrid /> keyboard cell navigation with arrows  FAILED` 😅

**Comment by oliviertassinari** [comment]
@DanailH CircleCI allows to rerun test from fails. I have launch it.

File: packages/grid/_modules_/grid/components/pagination.tsx [hunk 2]
```diff
@@ -45,6 +57,8 @@ export const Pagination: React.FC<PaginationComponentProps> = ({
       }
       rowsPerPage={pageSize}
       onChangeRowsPerPage={onPageSizeChange}
+      labelRowsPerPage={''}
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/pagination.tsx:60]:
```suggestion
      labelRowsPerPage=""
```

File: packages/grid/_modules_/grid/components/default-footer.tsx [hunk 3]
```diff
@@ -24,12 +25,26 @@ export const DefaultFooter = React.forwardRef<HTMLDivElement, DefaultFooterProps
...
-      <GridFooter ref={ref}>
-        {!options.hideFooterRowCount && <RowCount rowCount={totalRowCount} />}
-        {!options.hideFooterSelectedRowCount && (
-          <SelectedRowCount selectedRowCount={selectedRowCount} />
-        )}
+      <GridFooter
+        ref={ref}
+        className={classnames({
+          'MuiDataGrid-footer-pagination-visible': isPaginationAvailable,
+          'MuiDataGrid-footer-justifyContent-right': justifyItemsRight,
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/default-footer.tsx:43]: Adding a hypen for separating internal components was one thing, doing it for naming is another. 

```suggestion
          'MuiDataGrid-footer-justifyContentRight': justifyItemsRight,
```

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/default-footer.tsx:43]: Instead of "right" using "end" would be better for RTL.

File: packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts [hunk 4]
```diff
@@ -206,18 +206,26 @@ export const useStyles = makeStyles(
...
-          alignItems: 'center',
-          display: 'none',
-          margin: theme.spacing(0, 2),
-          [theme.breakpoints.up('md')]: {
-            display: 'flex',
+          '&.MuiDataGrid-footer-pagination-visible': {
+            '& .MuiDataGrid-rowCount, & .MuiDataGrid-selectedRowCount': {
+              visibility: 'hidden',
+              [theme.breakpoints.up('md')]: {
+                visibility: 'visible',
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts:223]: Why not using display none?

File: packages/grid/_modules_/grid/components/default-footer.tsx [hunk 5]
```diff
@@ -24,12 +25,26 @@ export const DefaultFooter = React.forwardRef<HTMLDivElement, DefaultFooterProps
...
     return (
-      <GridFooter ref={ref}>
-        {!options.hideFooterRowCount && <RowCount rowCount={totalRowCount} />}
-        {!options.hideFooterSelectedRowCount && (
-          <SelectedRowCount selectedRowCount={selectedRowCount} />
-        )}
+      <GridFooter
+        ref={ref}
+        className={classnames({
+          'MuiDataGrid-footer-pagination-visible': isPaginationAvailable,
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/default-footer.tsx:42]: I think that it shouldatch the content, not the CSS logic we want to apply, it helps for customizations.

```suggestion
          'MuiDataGrid-footer-paginationAvailable': isPaginationAvailable,
```

File: packages/grid/_modules_/grid/components/default-footer.tsx (hunk 3 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/default-footer.tsx:43]: What if we render an empty div instead so we don't have to apply a custom class name?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/default-footer.tsx:43]: Or we could also inverse the direction of the flex container. That could be even better if that's what most people would want, not sure.

**Review by oliviertassinari — COMMENTED** [review]
I wonder how to best test this. Maybe DOM and class name assertions would be ideal.

File: packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts (hunk 4 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts:223]: I need it to take space. The reason is that we want the pagination to always be right-aligned. If I make it `display: none` then the logic to aways align the pagination on the right will be unnecessarily complex.

File: packages/grid/_modules_/grid/components/default-footer.tsx (hunk 3 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/default-footer.tsx:43]: I was thinking of rendering an empty div as well but I didn't like how it looked. Maybe we can reintroduce it. The benefit is that if we add a single empty div around the `row selected` we don't need to add any additional CSS login / styles

**Comment by oliviertassinari** [comment]
I wonder if we shouldn't use the breakpoint before `md` (960) but `sm` (600). People can customize it but that still seems to be common enough per https://github.com/mui-org/material-ui/issues/21902. It's also what we use in the main repo.

**Comment by DanailH** [comment]
> I wonder if we shouldn't use the breakpoint before `md` (960px) but `sm` (600px). People can customize it but that still seems to be common enough per [mui-org/material-ui#21902](https://github.com/mui-org/material-ui/issues/21902). It's also what we use in the main repo (sm).

I just went ahead and changed it to `sm`. This is the only place where we use a breakpoint and with the new changes (we hide part of the `TablePagination`) there is enough space to have both parts on a single line before hitting `sm` resolution

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
- We can no longer change the number of rows per page on desktop
- Something is strange with this demo:

https://deploy-preview-508--material-ui-x.netlify.app/components/data-grid/pagination/#auto-size

Capture d’écran 2020-11-03 à 17 38 26

**Comment by DanailH** [comment]
> * We can no longer change the number of rows per page on desktop, maybe use CSS to target the first `.caption` style on mobile?
> * Something is strange with this demo:
> 
> https://deploy-preview-508--material-ui-x.netlify.app/components/data-grid/pagination/#auto-size
> 
> Capture d’écran 2020-11-03 à 17 38 26

I'll check the demo. Regarding the other point - as far as I understood that was the desired behaviour from our discussion, to hide both the label and the select? I can only hide the label and keep the select.

**Comment by oliviertassinari** [comment]
> I'll check the demo. Regarding the other point - as far as I understood that was the desired behaviour from our discussion, to hide both the label and the select? I can only hide the label and keep the select.

I was under the assumption that it was only on mobile to save space. From my perspective, if we were to change this on desktop too, it would be the type of change that should be done at the `TablePagination` level, not in the data grid.

**Comment by DanailH** [comment]
> > I'll check the demo. Regarding the other point - as far as I understood that was the desired behaviour from our discussion, to hide both the label and the select? I can only hide the label and keep the select.
> 
> I was under the assumption that it was only on mobile to save space. From my perspective, if we were to change this on desktop too, it would be the type of change that should be done at the `TablePagination` level, not in the data grid.

Ok, hopefully, the last update - I've only hidden the Rows per page + the select from mobile resolutions, they are now visible on desktop.

The drawback - I had to return the media query to `md` because if you have a row selected and the pagination on small but not telephone screen resolution the `rows selected` falls on 2 lines and a scroll may appear.

**Review by oliviertassinari — APPROVED** [review]

**Review by dtassone — APPROVED** [review]
