### PR TITLE
[DataGrid] Fix issue with visible rows state

### LINKED ISSUE #1106: [DataGrid] Provide an API to access the client-side filtered rows
No easy method to get the current state of visible rows as the filter component updates. the onFilterModelChange function is one step behind the current state of the table - which may be the intended behavior - because it may be a private method.

- [x] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

onFilterModelChange one step behind actual state of the table - think this is because its a private method and is actually updating the state of the table. 

## Expected Behavior 🤔
a method to get the actual visible rows as the filter updates.

## Steps to Reproduce 🕹

below is a link to a codesanbox
https://codesandbox.io/s/material-demo-forked-nzong?file=/demo.js:867-907

Steps:

1. simply filter on quantity
2. watch the console as you type: >= 500000 and see how the visibleRowsLookup is one step behind actual state
3.
4.

## Context 🔦
notice how it is always one behind actual state...when you look at 
the console of the params object it is actual correct. this must be an 
asynchronous action. I would like to be able to access visible rows
in real time to update state in another part
of the application....imagine if you were updating state in a map (such as google maps and mapbox - my actual scenario - and you may want to style or zoom or visualize other data related to the displayed table in another part of the screen) 
visualization platform -  update state based on 
any applied filters. you may not want to handle or you may not be able to handle all these updates with getSelectedRows - you may not care about whats selected....just filtered....
I don't believe this is an edge case...this is something that I imagine is going to be needed.  if I am missing something...please let me know....I can def be a bonehead....

thanks for the help. 

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

### PR DESCRIPTION
**Pull request by dtassone**
Fix a leaking state bug surfaced with `onFilterModelChange` in #1106 

- [x] add test
- [x] add docs?

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Is this specific to the filters? How would a developer get the displayed rows after sorting is applied?

File: packages/grid/_modules_/grid/models/api/filterApi.ts [hunk 1]
```diff
@@ -12,4 +13,5 @@ export interface FilterApi {
   applyFilterLinkOperator: (operator: GridLinkOperator) => void;
   onFilterModelChange: (handler: (params: GridFilterModelParams) => void) => void;
   setFilterModel: (model: FilterModel) => void;
+  getVisibleRowModels: () => GridRowModel[];
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/api/filterApi.ts:16]: I think that we should fix one problem at a time. The bug is one thing. The missing API is another.

```suggestion
```

**Review by oliviertassinari — CHANGES_REQUESTED** [review]

**Comment by dtassone** [comment]
> How will developers using DataGrid only solve this problem? With the `onStateChange` prop? Should we document it then?
> 
> On a related note. Is the `visibleRowModels` state-specific to the filter feature? It seems to be a broader problem. I wonder if in the future we should refactor it.

The issue is just that the event was triggered before the filter was applied hence the issue with the state.

**Comment by dtassone** [comment]
> > How will developers using DataGrid only solve this problem? With the `onStateChange` prop? Should we document it then?
> > On a related note. Is the `visibleRowModels` state-specific to the filter feature? It seems to be a broader problem. I wonder if in the future we should refactor it.
> 
> The issue is just that the event was triggered before the filter was applied hence the issue with the state.

I can add the visible rows in the on change params...

**Comment by oliviertassinari** [comment]
> The issue is just that the event was triggered before the filter was applied hence the issue with the state.

I have read the issue differently: we expose a global mutable state that developers can't reliably read: it's mutable. I agree that calling the callback after the operation is better. Still, if this state is indeed mutable, I think that it should be private, it's a footgun otherwise.

**Comment by dtassone** [comment]
> > The issue is just that the event was triggered before the filter was applied hence the issue with the state.
> 
> I have read the issue a bit differently: we expose a global mutable state (`visibleRowsLookup`) that developers can't reliably read: it's mutable. I agree that calling the callback after the operation is better. Still, if this state is indeed mutable, I think that it should be private, it's a foot gun otherwise. It also seems to be only a cache and suffers from #874. The only logical conclusion I can get to is: how about we treat this field as private?

why is it mutable? What do you mean only a cache? How is a cache compared to a react state?

**Comment by oliviertassinari** [comment]
> why is it mutable?

You are right, it's only leaking between two states: https://codesandbox.io/s/material-demo-forked-71kve?file=/demo.js. It seems that we are good. I couldn't reproduce what the developer has reported.

> What do you mean only a cache?

What I mean is that `state.visibleRows.visibleRowsLookup` seems to be a derived state of `state.visibleRows.visibleRows`.

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts [hunk 2]
```diff
@@ -271,6 +271,8 @@ export const useGridFilter = (apiRef: GridApiRef, rowsProp: GridRowsProp): void
     [apiRef],
   );
 
+  const getVisibleRowModels = React.useCallback(() => visibleRowModels, [visibleRowModels]);
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:274]: Did you consider only have a dependency on the `apiRef` and read from the state? It would lead to fewer changes of the `getVisibleRowModels` API method. On the other hand, it might also lead to making `getVisibleRowModels ` return a state that isn't yet rendered. I wonder.

**Review by DanailH — APPROVED** [review]
