### PR TITLE
[DataGrid] Fix `Controlled selection` console error

### LINKED ISSUE #2193: [DataGrid] Controlled selection example throws multiple selection error
The DataGrid example from the docs for [controlled selection](https://material-ui.com/components/data-grid/selection/#controlled-selection) works fine on the page and [in sand box](https://codesandbox.io/s/z5hbj), but throws an error to the console about requiring a paid version. The Checkbox Selection example above it does not throw an error, while also allowing multiple selections ([code sandbox](https://codesandbox.io/s/tl2rz)).
Everything functions as expected, but it still logs an error after to this change: https://github.com/mui-org/material-ui-x/pull/1823/files#diff-36939e58755c91e3693a4f18aa7796b137ba1e32f65357a940fb358286048088R247

It just appears that a free feature is suddenly not free, without any warning, despite it not being made clear in the docs and the code still running as expected.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Selections work fine, but still logs an error.

## Expected Behavior 🤔
No error is thrown, like for the [Checkbox Selection example](https://material-ui.com/components/data-grid/selection/#checkbox-selection)

## Steps to Reproduce 🕹

Steps:

1. Run the code for the Controlled Selection example ([forked code sandbox](https://codesandbox.io/s/material-demo-forked-jjcbh))
2. Select more than one item
3. Check log to show it still list multiple items, despite throwing an error

## Context 🔦
I have an app that allows users to select items to batch delete from a database. After `4.0.0-alpha.34`, that started throwing this error.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
System:
    OS: macOS 11.3
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.164
    Edge: 91.0.864.71
    Firefox: 89.0.2
    Safari: 14.1
  npmPackages:
    @material-ui/core: ^4.12.1 => 4.12.2 
    @material-ui/data-grid: ^4.0.0-alpha.34 => 4.0.0-alpha.34 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.12.1 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  17.0.9 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
```
</details>

### PR DESCRIPTION
**Pull request by ZeeshanTamboli**
Fixes #2193 

Preview: https://codesandbox.io/s/material-demo-n3l5c

### CODE REVIEW

File: packages/grid/data-grid/src/DataGrid.tsx [hunk 1]
```diff
@@ -251,15 +251,19 @@ DataGrid.propTypes = {
...
+        Array.isArray(props.selectionModel) &&
+        props.selectionModel.length > 1
+      ) {
         return new Error(
           [
             `Material-UI: \`<DataGrid selectionModel={${JSON.stringify(
               props.selectionModel,
             )}} />\` is not a valid prop.`,
-            'selectionModel can only be of 1 item in DataGrid.',
+            'selectionModel can only be of 1 item in DataGrid having no checkbox selection.',
```
Comment (m4theushw) [inline packages/grid/data-grid/src/DataGrid.tsx:264]:
```suggestion
            'selectionModel can only contain 1 item in DataGrid without checkbox selection.',
```

File: packages/grid/data-grid/src/DataGrid.tsx [hunk 2]
```diff
@@ -251,15 +251,19 @@ DataGrid.propTypes = {
...
             '',
-            'You need to upgrade to the XGrid component to unlock multiple selection.',
+            'You need to upgrade to the XGrid component to unlock multiple non-checkbox selection.',
```
Comment (m4theushw) [inline packages/grid/data-grid/src/DataGrid.tsx:266]:
```suggestion
            'You need to upgrade to the XGrid component to unlock multiple selection.',
```

File: packages/grid/data-grid/src/DataGrid.tsx [hunk 3]
```diff
@@ -251,15 +251,19 @@ DataGrid.propTypes = {
   selectionModel: chainPropTypes(
     PropTypes.oneOfType([PropTypes.number, PropTypes.string, PropTypes.array]),
     (props: any) => {
-      if (Array.isArray(props.selectionModel) && props.selectionModel.length > 1) {
+      if (
+        props.checkboxSelection === false &&
```
Comment (m4theushw) [inline packages/grid/data-grid/src/DataGrid.tsx:255]: Initially this prop is `undefined`.

```suggestion
        !props.checkboxSelection &&
```

**Review by m4theushw — COMMENTED** [review]
Thanks for the quick fix. Could we add a test case? It must check that: 1. an error is emitted when `selectionModel` contains more than 1 item and 2. no error is emitted when `selectionModel` contains more than 1 item but `checkboxSelection` is present?

File: packages/grid/data-grid/src/DataGrid.tsx (hunk 3 above)
Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/DataGrid.tsx:255]: We mention default as `false`:
https://github.com/mui-org/material-ui-x/blob/f1538f0cc386c147a5919e540773b1deecff3d35/packages/grid/_modules_/grid/models/gridOptions.tsx#L50-L53

and also in docs.

I think it would be better if we keep this strict check and instead add `checkboxSelection: false` in `DEFAULT_GRID_OPTIONS`. What do you think?

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/DataGrid.tsx:255]: Interestingly, even if I add `checkboxSelection: false` in `DEFAULT_GRID_OPTIONS`, I get checkboxSelection prop as `undefined` initially in tests.

**Review by m4theushw — APPROVED** [review]
