### PR TITLE
[DataGrid] Add support for custom row ids without cloning

### LINKED ISSUE #1119: [DataGrid] If data has field id, getRowId doesn't work
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.
- [x] The issue is present in the latest release.

## Current Behavior 😯

If origin data has the field `id`, `getRowId` doesn't work. So if field `id` isn't unique will get the warning.

MarineGEO circle logo

## Expected Behavior 🤔

Use new id which I need.

## Steps to Reproduce 🕹

 - Use this sample code to reproduce
```javascript
import React from 'react'
import { DataGrid } from '@material-ui/data-grid'

const BasicGrid = props => {
    const handleGetRowId = (e) => {
        return e.uniId
    }
    return (
        <DataGrid
            columns={[
                { field: 'uniId', width: 200 },
                { field: 'id', width: 200 },
                { field: 'name', width: 200 },
            ]}
            rows={[
                { id: 'company-ta-tb-id', name: 'TA-TB-XXXX', uniId: 'euald4541ajwndd1', },
                { id: 'company-ta-tb-id', name: 'TA-TB-YYYY', uniId: 'eakf4455anfw44dc', },
            ]}
            getRowId={handleGetRowId} />
    )
}

export default BasicGrid
``` 

## Context 🔦

In my project, the data set I got has used field `id` as part of the data, and the field `id` is not a unique identification code, the unique identification code is the field `uniId`.

I don't know why the company designed it this way, but this is a situation I face. 

I used the new API `getRowId` to work on this case, but I got the warning `index.js:1 Warning: Encountered two children with the same key`,  because If origin data have id already, `getRowId` dosen't work. 

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Browser: Chrome, Version 88.0.4324.150 (Official Build) (64-bit)
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 85.0.1
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/data-grid: ^4.0.0-alpha.20 => 4.0.0-alpha.20 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: ^4.0.0-alpha.20 => 4.0.0-alpha.20 
    @material-ui/x-grid-data-generator: ^4.0.0-alpha.20 => 4.0.0-alpha.20 
    @material-ui/x-license:  4.0.0-alpha.20 
    @types/react:  17.0.2 
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 
```
</details>

### LINKED ISSUE #1200: [DataGrid] getRowId causes an object clone
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

If getRowId is used, object clones are returned in the events.

## Expected Behavior 🤔

Original objects should be returned.

## Steps to Reproduce 🕹

Behavior with getRowId:
https://codesandbox.io/s/fragrant-cloud-qb5j8?file=/src/App.tsx

Behavior without getRowId
https://codesandbox.io/s/busy-heyrovsky-wtn1z?file=/src/App.tsx

When a row is clicked, the array is searched for the rowData object.
In the case of getRowId nothing is found.

### LINKED ISSUE #1315: [DataGrid] Remove the requirement of storing `id` in rowData
Avoid cloning row data
Avoid id field on rowData

### PR DESCRIPTION
**Pull request by m4theushw**
### Breaking changes

- [DataGrid] `GridFilterModelParams.rows` changed to `Map<GridRowId, GridRowModel>`
- [DataGrid] `GridFilterModelParams.visibleRows` changed to `Map<GridRowId, GridRowModel>`
- [DataGrid] Return of `apiRef.current.getSelectedRows` changed to `Map<GridRowId, GridRowModel>`
- [DataGrid] Return of `apiRef.current.getRowModels` changed to `Map<GridRowId, GridRowModel>`
- [DataGrid] Return of `apiRef.current.getVisibleRowModels` changed to `Map<GridRowId, GridRowModel>`

---

This is a follow up of #1371. Basically I changed all methods that were returning `GridRowModel[]` to `Map<GridRowId, GridRowModel>`. This structure allows to keep the computed id and data of each row isolated while maintaining the order that they were inserted, even for numeric ids. The sorting with 100k rows is freezing, I have to test again once #1368 gets merged.

Closes #1119
Closes #1200
Closes #1315

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts [hunk 1]
```diff
@@ -15,37 +14,38 @@ const serialiseCellValue = (value) => {
...
+      mappedRow.push(serialiseCellValue(getCellValue(id, column.field))),
   );
   return mappedRow;
 }
 
 export function buildCSV(
   columns: GridColumns,
-  rows: GridRowModel[],
+  rowIds: GridRowId[],
   selectedRows: Record<GridRowId, boolean>,
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts:33]: not sure I understand why this one doesn't just get a set of rows. It should be dumb and selection agnostic.

File: packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts [hunk 2]
```diff
@@ -15,37 +14,38 @@ const serialiseCellValue = (value) => {
...
   getCellValue: (id: GridRowId, field: string) => GridCellValue,
 ): string {
-  const selectedRowsIds = Object.keys(selectedRows);
+  let rowIdsToSerialize = [...rowIds];
+  const selectedRowIds = Object.keys(selectedRows);
 
-  if (selectedRowsIds.length) {
-    rows = rows.filter((row) => selectedRowsIds.includes(`${row.id}`));
+  if (selectedRowIds.length) {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts:39]: this logic should not be here. Is it a big refactoring? Maybe for another PR...

File: packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx [hunk 3]
```diff
@@ -13,14 +13,14 @@ import { buildCSV } from './seralizers/csvSeraliser';
...
-  const visibleSortedRows = useGridSelector(apiRef, visibleSortedGridRowsSelector);
+  const visibleSortedRowIds = useGridSelector(apiRef, visibleSortedGridRowIdsSelector);
   const selection = useGridSelector(apiRef, gridSelectionStateSelector);
 
   const getDataAsCsv = React.useCallback((): string => {
     logger.debug(`Get data as CSV`);
 
-    return buildCSV(visibleColumns, visibleSortedRows, selection, apiRef.current.getCellValue);
-  }, [logger, visibleColumns, visibleSortedRows, selection, apiRef]);
+    return buildCSV(visibleColumns, visibleSortedRowIds, selection, apiRef.current.getCellValue);
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx:22]: `return buildCSV(columns, rows, apiRef.current.getCellValue); `

File: packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts [hunk 4]
```diff
@@ -12,15 +12,41 @@ export const visibleGridRowsStateSelector = (state: GridState) => state.visibleR
...
-  sortedGridRowsSelector,
-  (visibleRowsState, sortedRows: GridRowModel[]) => {
-    return [...sortedRows].filter((row) => visibleRowsState.visibleRowsLookup[row.id] !== false);
-  },
-);
+  Map<GridRowId, GridRowModel>,
+  Map<GridRowId, GridRowModel>
+>(visibleGridRowsStateSelector, sortedGridRowsSelector, (visibleRowsState, sortedRows) => {
+  const map = new Map();
+  sortedRows.forEach((row, id) => {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts:19]: As visible rows might be smaller than sorted rows, it's better to loop through visible rows I think
How about?
```tsx
const union = new Map(
  [...visibleMap.entries()]
    .filter(entry=> entry[1])
    .map(entry=>[entry[0], sortMap.get(entry[0])])
)
```

File: packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts [hunk 5]
```diff
@@ -12,15 +12,41 @@ export const visibleGridRowsStateSelector = (state: GridState) => state.visibleR
...
+  return map;
+});
+
+export const visibleSortedGridRowsAsArraySelector = createSelector<
+  GridState,
+  Map<GridRowId, GridRowModel>,
+  [GridRowId, GridRowModel][]
+>(visibleSortedGridRowsSelector, (visibleSortedRows) => {
+  const result: [GridRowId, GridRowModel][] = [];
+  visibleSortedRows.forEach((row, id) => {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts:33]: why not use `[...visibleSortedRows.entries()]`?

File: packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts [hunk 6]
```diff
@@ -12,15 +12,41 @@ export const visibleGridRowsStateSelector = (state: GridState) => state.visibleR
...
+  return result;
+});
+
+export const visibleSortedGridRowIdsSelector = createSelector<
+  GridState,
+  Map<GridRowId, GridRowModel>,
+  GridRowId[]
+>(visibleSortedGridRowsSelector, (visibleSortedRows) => {
+  const result: GridRowId[] = [];
+  visibleSortedRows.forEach((row, id) => {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts:45]: why not use [...visibleSortedRows.keys()]?

File: packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts [hunk 7]
```diff
@@ -91,17 +91,17 @@ export const useGridFilter = (apiRef: GridApiRef, rowsProp: GridRowsProp): void
         // This way we have latest rows on the first rendering
         const rows = sortedGridRowsSelector(state);
 
-        rows.forEach((row) => {
-          const params = apiRef.current.getCellParams(row.id, filterItem.columnField!);
+        rows.forEach((row: GridRowModel, id: GridRowId) => {
+          const params = apiRef.current.getCellParams(id, filterItem.columnField!);
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts:95]: On another note, this might be a bit slow 🤔 
Might have to reduce the loaded params for filtering as I have done for sorting.
Need some perf test here

File: packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts [hunk 8]
```diff
@@ -20,8 +20,8 @@ import { useLogger } from '../../utils/useLogger';
 import { useGridState } from '../core/useGridState';
 import { getInitialGridRowState, InternalGridRowsState } from './gridRowsState';
 
-export function addGridRowId(rowData: GridRowData, getRowId?: GridRowIdGetter): GridRowModel {
-  return getRowId == null ? (rowData as GridRowModel) : { id: getRowId(rowData), ...rowData };
+function getGridRowId(rowData: GridRowData, getRowId?: GridRowIdGetter): GridRowId {
+  return getRowId ? getRowId(rowData) : rowData.id;
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts:24]: Should we call `checkGridRowIdIsValid` here?
only if `getGridRowId` is always followed by `checkGridRowIdIsValid`

File: packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts [hunk 9]
```diff
@@ -194,10 +197,13 @@ export const useGridRows = (
...
-  const getRowModels = React.useCallback(
-    () => apiRef.current.state.rows.allRows.map((id) => apiRef.current.state.rows.idRowsLookup[id]),
-    [apiRef],
-  );
+  const getRowModels = React.useCallback(() => {
+    const map = new Map<GridRowId, GridRowModel>();
+    apiRef.current.state.rows.allRows.forEach((id) => {
+      map.set(id, apiRef.current.state.rows.idRowsLookup[id]);
+    });
+    return map;
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts:205]: how about 

```tsx
return new Map<...>(apiRef.current.state.rows.allRows.map(id=> [id, apiRef...idRowsLookup[id]]))
```

File: packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts [hunk 10]
```diff
@@ -36,23 +38,20 @@ export const useGridSelection = (apiRef: GridApiRef): void => {
       !options.disableMultipleSelection && isMultipleKeyPressed;
   }, [isMultipleKeyPressed, options.disableMultipleSelection]);
 
-  const getSelectedRows = React.useCallback((): GridRowModel[] => {
-    // TODO replace with selector
-    return Object.keys(gridState.selection).map((id) => apiRef.current.getRowFromId(id));
-  }, [apiRef, gridState.selection]);
+  const getSelectedRows = React.useCallback(() => selectedRows, [selectedRows]);
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts:41]: This might create a tricky bug!
Ie.
User select a row, event is selection change is published.
User subscribe to the event and call `getSelectedRows`.
As the grid did not rerender at that point, `selectedRows` is still set to the previous state. 🤔 
The user should use the params, with latest state but in case they don't...
Maybe you could add a test to check the above.

Alternatively you can make sure its' the latest state by 
```tsx
const getSelectedRows = React.useCallback(() => selectedGridRowsSelector(apiRef.current.getState()), []);
```

File: packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts (hunk 4 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts:19]: To loop first the visible rows we have to convert it to a map or it won't work with numeric ids. It's better to deal with this in https://github.com/mui-org/material-ui-x/issues/874 which will be another PR.

File: packages/grid/_modules_/grid/components/GridCheckboxRenderer.tsx [hunk 11]
```diff
@@ -31,10 +31,7 @@ export const GridHeaderCheckbox: React.FC<GridColumnHeaderParams> = () => {
 
   const handleChange = (event: React.ChangeEvent<HTMLInputElement>, checked: boolean) => {
     setChecked(checked);
-    apiRef!.current.selectRows(
-      visibleRows.map((row) => row.id),
-      checked,
-    );
+    apiRef!.current.selectRows([...visibleRows.keys()], checked);
```
[the remark this answers is not in the document]
Comment (m4theushw) [reply packages/grid/_modules_/grid/components/GridCheckboxRenderer.tsx]: The input is not mutated. `visibleRows.keys()` returns an iterator and `selectRows` requires an array. Changed to get ids from a selector.

File: packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts (hunk 8 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts]: Changed to also call `checkGridRowIdIsValid` after computing the id.

File: packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts (hunk 2 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts:40]: Which logic? The one to compute the records for export or the cast of the id to string?

File: packages/grid/_modules_/grid/hooks/features/selection/gridSelectionSelector.ts [hunk 12]
```diff
@@ -11,3 +13,15 @@ export const selectedGridRowsCountSelector: OutputSelector<
   gridSelectionStateSelector,
   (selection) => Object.keys(selection).length,
 );
+
+export const selectedGridRowsSelector = createSelector<
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/selection/gridSelectionSelector.ts:17]: I wonder. Are we all OK with turning state selectors into state transformation functions? This doesn't seem to be a light change. There is now an indirection.

File: packages/grid/_modules_/grid/models/api/gridRowApi.ts [hunk 13]
```diff
@@ -5,10 +5,10 @@ import { GridRowModel, GridRowId, GridRowModelUpdate } from '../gridRows';
  */
 export interface GridRowApi {
   /**
-   * Get the full set of rows as [[Rows]].
-   * @returns [[Rows]]
+   * Get the full set of rows as [[Map<GridRowId, GridRowModel>]].
+   * @returns [[Map<GridRowId, GridRowModel>]]
    */
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/api/gridRowApi.ts:10]: I might be missing something. Wasn't this public method meant to return all the rows as they exist in the grid (e.g. if updated with the streaming API)? Shouldn't developers expect a flat array? I mean, why do developers need to know about the id? Not a major concern, more a question.

**Review by oliviertassinari — COMMENTED** [review]
It looks almost good to go

File: packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts [hunk 14]
```diff
@@ -15,37 +15,38 @@ const serialiseCellValue = (value) => {
...
   }
 
   const CSVHead = `${columns
     .filter((column) => column.field !== gridCheckboxSelectionColDef.field)
     .map((column) => serialiseCellValue(column.headerName || column.field))
     .toString()}\r\n`;
-  const CSVBody = rows
-    .reduce((soFar, row) => `${soFar}${serialiseRow(row, columns, getCellValue)}\r\n`, '')
+  const CSVBody = rowIds
+    .reduce<string>((soFar, id) => `${soFar}${serialiseRow(id, columns, getCellValue)}\r\n`, '')
```
[the remark this answers is not in the document]
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts:49]: I'm totally with `acc`. I didn't use it here because it's the less used in the codebase, behind `res` and `lookup`.

[the remark this answers is not in the document]
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts:49]: I can count `((acc,` x29, `((res,` x5, `((lookup,` x2 in the codebase.

[the remark this answers is not in the document]
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts:49]: How did you find 29 occurrences of `((acc,`?

image

[the remark this answers is not in the document]
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts:49]: https://github.com/mui-org/material-ui and https://github.com/mui-org/material-ui-x are part of the same codebase.

File: packages/grid/_modules_/grid/models/api/gridRowApi.ts (hunk 13 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/models/api/gridRowApi.ts:10]: Actually, this method could return a flat array. Although, changing it also changes the `rows` prop of the return of `getFilterModelParams` [here](https://github.com/mui-org/material-ui-x/blob/ba5640495504090541b6fc9bb22eff7da036f02d/packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts#L44). Then, we would have `rows` as a flat array and `visibleRows` as a map, not very consistently.

Comment (dtassone) [reply packages/grid/_modules_/grid/models/api/gridRowApi.ts:10]: There are 2 use cases here. 
- The grid uses the api internally and for perf reason, we want to get the id with rows so we don't have to run getRowId for every rows and state update. 
- We can consider adding a method, that would get the values of the map so we get a flat array of rows for the users or we can wait for an issue?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/models/api/gridRowApi.ts:10]: No preferences. I personally think that the current state of the PR is good enough. I was wondering about either there is a potential for improvement or not.

File: packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts (hunk 2 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts:40]: BuildCsv should not care about which rows are selected. It should just receive rows and convert them to CSV. This logic should go to the parent scope. As it's not the serializer responsibility to know what to serialize

**Review by dtassone — APPROVED** [review]
