### PR TITLE
[DataGrid] Fix loader flag from useDemoData hook

### LINKED ISSUE #1276: [docs] Loader in demo page
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Screenshot 2021-03-22 at 14 45 01

## Expected Behavior 🤔

No loading

## Steps to Reproduce 🕹

- load https://material-ui.com/components/data-grid/demo/
- load https://material-ui.com/components/data-grid/getting-started/
- load https://material-ui.com/components/data-grid/demo/

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #1276

### CODE REVIEW

**Review by oliviertassinari — COMMENTED** [review]
What's the rational behind solving the problem with this approach? I mean, in the initial render, it means that the rows are empty and the loading state is false. Is it expected? It seems wrong. F

**Review by dtassone — APPROVED** [review]

**Comment by DanailH** [comment]
OK if you look it that way then yes you are correct - when opening it initially technically the data is loading. The problem was that when you change pages the self invoked function is not being called. 

I'm ok if we say that the loading state is `true`. It's just a different way of looking at the problem.

File: packages/grid/x-grid-data-generator/src/useDemoData.ts [hunk 1]
```diff
@@ -82,7 +82,7 @@ export const useDemoData = (options: DemoDataOptions): DemoDataReturnType => {
   const [data, setData] = React.useState<GridData>({ columns: [], rows: [] });
   const [rowLength, setRowLength] = React.useState(options.rowLength);
   const [index, setIndex] = React.useState(0);
-  const [loading, setLoading] = React.useState(false);
+  const [loading, setLoading] = React.useState(true);
```
Comment (dtassone) [inline packages/grid/x-grid-data-generator/src/useDemoData.ts]: I think that initially the rows are not loading. And the grid should be empty
And only when you get in the useEffect it starts loading.
Have you tried to remove the useEffect?

Comment (DanailH) [reply packages/grid/x-grid-data-generator/src/useDemoData.ts]: As far as I understand the `use.Effect` and what is inside is to prevent the freeze when fetching a lot of data. For me both having it by default as `true` and `false` are logical it depends on how we want to look at it.

**Comment by oliviertassinari** [comment]
> if you look it that way

Yeah, I guess it depends on how we see it. No preferences. 

What do you think about following whatever react-query do to set the loading state based on the missing data? This way we would get closer to what most developers do in their own applications, and hopefully have better constraints for handling the loading state in the data grid?

**Comment by DanailH** [comment]
I would need to check it. I can do it after I open the PR for navigating the header cells with the keyboard. I would still like to merge this fix to have the current version working.

**Comment by oliviertassinari** [comment]
@DanailH In this case, I'm looking at it now, as it takes 5 minutes. https://codesandbox.io/s/relaxed-framework-p5qz7

Screenshot 2021-03-25 at 12 13 49

The current version looks great 👍

**Comment by DanailH** [comment]
Ah ok, I get it, I'll update the PR and add the additional flag today.

**Review by oliviertassinari — APPROVED** [review]
> Ah ok, I get it, I'll update the PR and add the additional flag today.

What do you mean by an addition flag?

**Comment by DanailH** [comment]
> > Ah ok, I get it, I'll update the PR and add the additional flag today.
> 
> What do you mean by an addition flag?

Sorry, the check to see if there is already data although isn't what `if (dataCache.has(cacheKey))` does? It checks if there is cahched data.

**Comment by oliviertassinari** [comment]
@DanailH I don't follow. My point on using react-query as a baseline, was to answer this discussion https://github.com/mui-org/material-ui-x/pull/1279#discussion_r600324714.

**Comment by DanailH** [comment]
Ok, I was left with the impression that I need to do something in addition. If that's ok then I'll just merge 😅

**Review by dtassone — APPROVED** [review]
