### PR TITLE
[DataGrid] Fix changing rows per page size

### LINKED ISSUE #1713: [DataGrid] Changing `Rows per page` is not working
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Changing rows per page is not working.

## Expected Behavior 🤔
Changing rows per page should work.

## Steps to Reproduce 🕹

Can be found in this [demo](https://material-ui.com/components/data-grid/pagination/#page-size)

Steps:

1. Go to the linked `Page Size` demo.
2. Click on `rows per page` dropdown.
3. Change per page size. It does not work.

### PR DESCRIPTION
**Pull request by ZeeshanTamboli**
Fixes #1713 

When changing the page size the other effect was running as `containerSizes` was different for the effect and caused it to run again. It should just depend on `containerSizes?.viewportPageSize`. And thus pageSize prop passed was getting applied to the pageSize state each time the page size is changed.
`pageSize:
            (options.autoPageSize ? containerSizes?.viewportPageSize : options.pageSize) ||
            state.pagination.pageSize,`

Would it better to have a separate selector to select nested `viewportPageSize`?

~~I also took the opportunity to remove `pagination` prop from DataGrid as I think pagination is enabled by default in DataGrid. Correct me if I am wrong.~~

Also changed the demo to be controlled with `pageSize/onPageSizeChange` combination.

Preview: https://deploy-preview-1729--material-ui-x.netlify.app/components/data-grid/pagination/

### CODE REVIEW

File: docs/src/pages/components/data-grid/components/CustomPaginationGrid.js [hunk 1]
```diff
@@ -35,7 +35,6 @@ export default function CustomPaginationGrid() {
   return (
     <div style={{ height: 400, width: '100%' }}>
       <DataGrid
-        pagination
```
Comment (oliviertassinari) [inline docs/src/pages/components/data-grid/components/CustomPaginationGrid.js:38]: > I also took the opportunity to remove pagination prop from DataGrid as I think pagination is enabled by default in DataGrid. Correct me if I am wrong.

I think that it should be reverted. XGrid doesn't have the pagination enabled by default, which would prevent to swap the component and get the same behavior.

File: docs/src/pages/components/data-grid/pagination/SizePaginationGrid.js [hunk 2]
```diff
@@ -3,15 +3,26 @@ import { DataGrid } from '@material-ui/data-grid';
...
 export default function SizePaginationGrid() {
+  const [pageSize, setPageSize] = React.useState(5);
+
   const { data } = useDemoData({
     dataSet: 'Commodity',
     rowLength: 100,
     maxColumns: 6,
   });
 
+  const handleOnPageSizeChange = (params) => {
```
Comment (oliviertassinari) [inline docs/src/pages/components/data-grid/pagination/SizePaginationGrid.js:14]: The naming convention:

```suggestion
  const handlePageSizeChange = (params) => {
```

**Review by oliviertassinari — DISMISSED** [review]

File: docs/src/pages/components/data-grid/components/CustomPaginationGrid.js (hunk 1 above)
Comment (ZeeshanTamboli) [reply docs/src/pages/components/data-grid/components/CustomPaginationGrid.js:38]: I thought it would misleading to show non-existent `pagination` prop on `DataGrid`. But happy to revert.

Comment (ZeeshanTamboli) [reply docs/src/pages/components/data-grid/components/CustomPaginationGrid.js]: Reverted.

**Review by dtassone — APPROVED** [review]
