### PR TITLE
[DataGrid] Fix autoHeight computation for custom headers and footers

### LINKED ISSUE #502: Property autoHeight doesn't take in account custom header
If property `autoHeight` is set and custom header is provided, last row hides because total grid height is calculated not correctly.

- [+] The issue is present in the latest release.
- [+] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Last row is not fully shown

## Expected Behavior 🤔

All rows should be visible

## Steps to Reproduce 🕹

https://codesandbox.io/s/fast-rgb-po00q

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.8  |

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #502

This PR aims to fix an issue that occurs when the autoHeight prop is set and a custom header and/or footer is provided. The bug is that the height of the grid, in that case, is not calculated correctly. That results in the last rows being hidden.

### CODE REVIEW

**Review by oliviertassinari — COMMENTED** [review]
I think that we could have pushed the solution deeper. This is a partial solution. Consider the following case: https://codesandbox.io/s/cool-thunder-olrqk?file=/demo.js.

From my perspective, the best solution would be to move the `AutoSize` to the grid zone.

**Review by oliviertassinari — APPROVED** [review]
`autoHeight={false}` doesn't seem impacted (I don't know why), so happy to call it good enough.

https://codesandbox.io/s/romantic-mestorf-zw1vg?file=/demo.js

File: packages/grid/_modules_/grid/utils/getTotalHeight.ts [hunk 1]
```diff
@@ -5,17 +5,19 @@ import { ContainerProps, GridOptions } from '../models';
...
   }
   const footerHeight = (footerRef.current && footerRef.current.getBoundingClientRect().height) || 0;
+  const headerHeight = (headerRef.current && headerRef.current.getBoundingClientRect().height) || 0;
   let dataHeight = dataContainerHeight;
   if (dataHeight < internalOptions.rowHeight) {
     dataHeight = internalOptions.rowHeight * 2; // If we have no rows, we give the size of 2 rows to display the no rows overlay
   }
 
-  return footerHeight + dataHeight + internalOptions.headerHeight;
+  return headerHeight + footerHeight + dataHeight + internalOptions.headerHeight;
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/utils/getTotalHeight.ts:22]:
```suggestion
  return headerHeight + footerHeight + dataHeight;
```

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/utils/getTotalHeight.ts:22]: What about we remove the `headerHeight` prop?

Comment (DanailH) [reply packages/grid/_modules_/grid/utils/getTotalHeight.ts:22]: > I think that we could have pushed the solution deeper. This is a partial solution. Consider the following case: https://codesandbox.io/s/cool-thunder-olrqk?file=/demo.js.
> 
> From my perspective, the best solution would be to move the `AutoSizer` to the grid zone.

I explored that solution as well. It can be done but it involves removing `outerStyle.height = 0;` and `outerStyle.width = 0;` from the `AutoSizer` to give the grid the correct dimensions. If I don't do it and I move the header and footer outside of the `AutoSizer` they collapse because the grid outer container has a height of 0. This btw maybe another bug that I am happy to solve but I don't know if anything will be impacting my removing those. When I tested it I didn't find any visible regressions. Maybe I can open another PR with the other solution and see if something will fail?

**Comment by DanailH** [comment]
> I think that we could have pushed the solution deeper. This is a partial solution. Consider the following case: https://codesandbox.io/s/cool-thunder-olrqk?file=/demo.js.
> 
> From my perspective, the best solution would be to move the `AutoSizer` to the grid zone.

I explored that solution as well. It can be done but it involves removing `outerStyle.height = 0;` and `outerStyle.width = 0;` from the `AutoSizer` to give the grid the correct dimensions. If I don't do it and I move the header and footer outside of the `AutoSizer` they collapse because the grid outer container has a height of 0. This btw maybe another bug that I am happy to solve but I don't know if anything will be impacting my removing those. When I tested it I didn't find any visible regressions. Maybe I can open another PR with the other solution and see if something will fail?

**Comment by oliviertassinari** [comment]
1. I'm getting confused with the `headerHeight` prop, it seems to be a `columnHeaderHeight` prop after all. Maybe we need to rename it? I start to think that my latest suggestion was wrong.
2. The `AutoSizer` should be left untouched, the logic is correct, it needs to be height = 0 and width = 0 to remove the feedback loop. Here is what I was thinking:

```dif
diff --git a/packages/grid/_modules_/grid/GridComponent.tsx b/packages/grid/_modules_/grid/GridComponent.tsx
index 5e88c334..cc4a6bd2 100644
--- a/packages/grid/_modules_/grid/GridComponent.tsx
+++ b/packages/grid/_modules_/grid/GridComponent.tsx
@@ -103,8 +103,6 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
     );

     return (
-      <AutoSizer onResize={onResize}>
-        {(size: any) => (
           <GridRoot
             ref={handleRef}
             className={props.className}
@@ -152,6 +150,8 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
                       gridState.rows.totalRowCount === 0 &&
                       customComponents.noRowsComponent}
                     {props.loading && customComponents.loadingComponent}
+                    <AutoSizer onResize={onResize}>
+                      {(size: any) => (
                     <GridWindow ref={windowRef}>
                       <GridDataContainer
                         ref={gridRef}
@@ -168,6 +168,8 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
                         )}
                       </GridDataContainer>
                     </GridWindow>
+                      )}
+                    </AutoSizer>
                   </div>
                   {customComponents.footerComponent || (
                     <DefaultFooter
@@ -194,8 +196,6 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
               </ApiContext.Provider>
             </ErrorBoundary>
           </GridRoot>
-        )}
-      </AutoSizer>
     );
   },
 );
``

**Comment by DanailH** [comment]
unfortunately, I can't move it that far down. If I do other components also need tweaking (tried doing it and the `ScrollArea` starts to complain). I was thinking of having something like this:

Screenshot 2020-11-16 at 17 08 40

But that brings other problems. The current solution works. Let's keep it for now and see if people find more problems with this we can spend a bit more time to rework the layout.

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
For point 1. https://github.com/mui-org/material-ui-x/pull/597#issuecomment-728143158, so we don't forget about it.

**Comment by oliviertassinari** [comment]
@DanailH Agree for 2. it would require a strong refactorization. We can wait for developers complaining about [the limitation](https://codesandbox.io/s/romantic-mestorf-zw1vg?file=/demo.js) before spending more time. This is the most pragmatic approach, I think.

**Comment by DanailH** [comment]
> For point 1. [#597 (comment)](https://github.com/mui-org/material-ui-x/pull/597#issuecomment-728143158), so we don't forget about it.

Updated the PR - we still need that prop as it is the default header height (not the columns header).

**Review by oliviertassinari — APPROVED** [review]
@dtassone What do you think about we rename `headerHeight` to `columnHeaderHeight`? Should we open a new issue about it? Right now, it could be confused with the height of the header component. Only the description clears the confusion:

> Set the height in pixel of the column headers in the grid.

File: packages/grid/_modules_/grid/GridComponent.tsx [hunk 2]
```diff
@@ -129,8 +136,10 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
             >
               <ApiContext.Provider value={apiRef}>
                 <OptionsContext.Provider value={gridState.options}>
-                  {customComponents.headerComponent || (
-                    <GridToolbar>
+                  {customComponents.headerComponent ? (
```
Comment (dtassone) [inline packages/grid/_modules_/grid/GridComponent.tsx:139]: So we can't have a headerComponent and a toolbar at the same time 🤔 
Also we are moving the HeaderRef, not ideal, how about we keep it as a container so around either the toolbar or the header?

File: packages/grid/_modules_/grid/GridComponent.tsx [hunk 3]
```diff
@@ -169,7 +178,9 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
                       </GridDataContainer>
                     </GridWindow>
                   </div>
-                  {customComponents.footerComponent || (
+                  {customComponents.footerComponent ? (
+                    <div ref={footerRef}>{customComponents.footerComponent}</div>
```
Comment (dtassone) [inline packages/grid/_modules_/grid/GridComponent.tsx:182]: same here I would prefer to keep the ref as a container that is not dynamic

File: packages/grid/_modules_/grid/GridComponent.tsx (hunk 2 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/GridComponent.tsx:139]: For the first point - yes you can either have a header or a toolbar, that was decided on the previous PR, the one for the toolbar.

On the second point - sure I can wrap them in a div and add the ref to it. Btw there wasn't a `headerRef` until now. This PR adds it.

**Comment by DanailH** [comment]
@dtassone can I merge this ?

**Comment by dtassone** [comment]
For the HeaderHeight, it's like a row height so, it is the ColumnCellHeight or ColumnHeaderCellHeight
HeaderHeight might be confusing now

**Comment by oliviertassinari** [comment]
@dtassone I wonder if we can't even drop this `headerHeight` prop. It seems to be only relevant for the AutoSizer component. If we move the AutoSize inside the rendering-zone only, (excluding the header, header column, footer), we should be able to remove the prop. As far as I understand it.
