### PR TITLE
[DataGrid] Fix scrollbar size on windows

### LINKED ISSUE #660: [DataGrid] When the vertical scrollbar appears, the horizontal scrollbar is shown as well
When the Datagrid has more elements that can be displayed in its current height, the vertical scrollbar appears. This causes the horizontal scrollbar to appear automatically.

- [X ] The issue is present in the latest release.
- [X ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When the vertical scrollbar appears, the horizontal scrollbar appears.

## Expected Behavior 🤔

The horizontal scrollbar should not appear.

## Steps to Reproduce 🕹

(not sure about using this link, sorry, first timer and noob here - it's easy using the steps though)
https://codesandbox.io/s/datagrid-quick-start-forked-1w5mk?file=/src/App.tsx

Steps:

1. start with the demo sandbox : https://codesandbox.io/s/datagrid-quick-start-d3ex9?from-embed
2. copy & paste rows to get more than 3 rows
3. See the vertical scrollbar appear, and the horizontal one as well

## Context 🔦

I was trying to get a Datagrid with a fixed height displaying a random number of rows :)

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.10  |
| React         |    17.0.1     |
| Browser       |    Chrome 86     |
| TypeScript    |         |
| etc.          |         |

### PR DESCRIPTION
**Pull request by dtassone**
fix #660

### CODE REVIEW

File: packages/grid/_modules_/grid/utils/domUtils.ts [hunk 1]
```diff
@@ -74,3 +74,21 @@ export function getCellElementFromIndexes(
     `:scope .${CELL_CSS_CLASS}[aria-colIndex='${colIndex}'][data-rowIndex='${rowIndex}']`,
   ) as HTMLDivElement;
 }
+
+// Todo: Use the @material-ui/utils version once fixed
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/utils/domUtils.ts:78]:
```suggestion
// TODO replace with { unstable_ getScrollbarSize } from '@material-ui/utils'
// once the v4 vs. v5 duplication conflict in the mono-repository is solved.
```

File: packages/grid/_modules_/grid/utils/domUtils.ts [hunk 2]
```diff
@@ -74,3 +74,21 @@ export function getCellElementFromIndexes(
...
+// A change of the browser zoom change the scrollbar size.
+// Credit https://github.com/twbs/bootstrap/blob/3ffe3a5d82f6f561b82ff78d82b32a7d14aed558/js/src/modal.js#L512-L519
+export function getScrollbarSize(doc: Document): number {
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/utils/domUtils.ts:81]: How about we move it with the other temporary patches?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/utils/domUtils.ts:81]: e.g. 

https://github.com/mui-org/material-ui-x/blob/e713ad39f3928f6c11acfe1b2406c6befc6e7d77/packages/grid/_modules_/grid/utils/material-ui-utils.ts#L11

File: packages/grid/_modules_/grid/hooks/utils/useOptionsProp.ts [hunk 3]
```diff
@@ -24,6 +25,7 @@ export function useOptionsProp(apiRef: ApiRef, props: GridComponentProps): GridO
     () => ({
       ...props,
       localeText: { ...DEFAULT_LOCALE_TEXT, ...props.localeText },
+      scrollbarSize: props.scrollbarSize == null ? getScrollbarSize(document) : props.scrollbarSize,
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/utils/useOptionsProp.ts:28]: I don't think that we can run the logic at each render. It would expect it to seriously degrade the performance (looking at what getScrollbarSize does). I don't have a benchmark to prove it. What about a memo per component mount lifecycle?

File: packages/grid/x-grid/src/tests/rows.XGrid.test.tsx [hunk 4]
```diff
@@ -46,6 +46,41 @@ describe('<XGrid /> - Rows ', () => {
...
+        </div>
+      );
+    };
+    render(<Test />);
+
+    const viewport = document.querySelector('.MuiDataGrid-viewport')!;
+    const scrollbarState = apiRef.current.state.scrollBar.scrollBarSize;
+    const scrollbar = apiRef.current.state.options.scrollbarSize;
+
+    expect(viewport.clientWidth).to.deep.equal(583);
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/rows.XGrid.test.tsx:79]: It's not an object

```suggestion
    expect(viewport.clientWidth).to.equal(583);
```

x2

**Review by oliviertassinari — CHANGES_REQUESTED** [review]

File: packages/grid/_modules_/grid/hooks/utils/useOptionsProp.ts (hunk 3 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/utils/useOptionsProp.ts:28]: It also can't work with server-side rendering

File: packages/grid/x-grid/src/tests/rows.XGrid.test.tsx [hunk 5]
```diff
@@ -46,6 +46,41 @@ describe('<XGrid /> - Rows ', () => {
...
+    };
+    render(<Test />);
+
+    const viewport = document.querySelector('.MuiDataGrid-viewport')!;
+    const scrollbarState = apiRef!.current.state.scrollBar.scrollBarSize;
+    const scrollbar = apiRef!.current.state.options.scrollbarSize;
+
+    expect(viewport.clientWidth).to.equal(583);
+    expect(scrollbarState).to.deep.equal({ y: 15, x: 0 });
+    expect(scrollbar).to.equal(15);
```
Comment (dtassone) [inline packages/grid/x-grid/src/tests/rows.XGrid.test.tsx:81]: that should not work with the browser test...

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
It's not working, for instance, on macOS Chrome with the scrollbar width enabled.

Before:

Capture d’écran 2021-02-16 à 13 02 47

https://codesandbox.io/s/gttt1

After:

Capture d’écran 2021-02-16 à 13 01 54

https://codesandbox.io/s/sydhx?file=/demo.js

---

I think that we have two issues. The state is a side effect, hence the above issue. I think that it should be moved to a React state to force a rerender once we resolve its value.

File: packages/grid/_modules_/grid/models/gridOptions.tsx [hunk 6]
```diff
@@ -38,10 +38,9 @@ export interface GridOptions {
    */
   headerHeight: number;
   /**
-   * Set the height/width of the grid inner scrollbar.
-   * @default 15
+   * Override the height/width of the grid inner scrollbar.
    */
-  scrollbarSize: number;
+  scrollbarSize?: number;
```
[the remark this answers is not in the document]
Comment (dtassone) [reply packages/grid/_modules_/grid/models/gridOptions.tsx:43]: Well should we allow to override the scrollbar size? How about when you want to customize the scrollbar in the grid?

[the remark this answers is not in the document]
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/models/gridOptions.tsx:43]: I'm asking because it doesn't seems that the prop is enough to customize the scrollbar of the grid. I mean, for instance, how would a developer use https://www.npmjs.com/package/react-perfect-scrollbar?

[the remark this answers is not in the document]
Comment (dtassone) [reply packages/grid/_modules_/grid/models/gridOptions.tsx:43]: Not entirely sure, but you can put it around the grid. And if you change the size of the scrollbar, you would need to pass it to the grid

**Review by oliviertassinari — APPROVED** [review]
In the future, if we want to avoid the double rendering, we should be able to move the logic after the `NoSsr` and compute the value synchronously.
