### PR TITLE
[DataGrid] Remove `apiRef` from `options` params

### LINKED ISSUE #1301: [DataGrid] Standardize/Reconcile all event handlers and params
1. Events should always be fired with the `params` of the entity it comes from, or with the params relative to its action
ie `onCellClick` has `GridCellParams` 
And `onFilterModelChange` has `GridFilterModelParams` 

Getting params, can be done using apiRef
- `apiRef.current.getCellParams(id: GridRowId, field: string): GridCellParams`;
- We should add `apiRef.current.getColumnHeaderParams(field: string): GridColumnHeaderParams`;

Then it should have the event as a second parameter. 
- This is because event is optional in some cases
ie `options.onColumnReorder(params: GridColumnParams, event?: React.SyntheticEvent); `
```tsx
// in hook
setColumnIndex = (field, newIndex, event?) => {
   apiRef.publishEvent(GRID_COLUMN_REORDER, apiRef.current.getColumnHeaderParams(field), event)
}

// in Api
setColumnIndex: (field, newIndex)=> void
```

2. Events should be granular so it's easily catchable by our users.

Imagine I want to log the cell that users are trying to edit. I could subscribe to the double click event but there are many different ways of getting into edit mode, keyboard, calling the api directly, and one could do it on click...
With granular events, I can easily hook into the event and achieve the above.

```tsx
export function EditCellWithMessageGrid() {
  const apiRef = useGridApiRef();
  const [message, setMessage] = React.useState('');

  React.useEffect(()=> {
    return apiRef.current.subscribeEvent('cellEnterEdit', (param: GridCellParams, event?: React.SyntheticEvent)=> {
      LogUser(`user ${username} is editing `, params) 
      setMessage(`Editing cell with value: ${param.value} at row: ${param.rowIndex}, column: ${param.field},
                        triggered by ${event!.type}
      `);
    });
  }, [apiRef])

  React.useEffect(()=> {
    return apiRef.current.subscribeEvent('cellExitEdit', ()=> {
      LogUser(`user ${username} stopped editing `, params) 
      setMessage('');
    });
  }, [apiRef])

  return (
    <div style={{ height: 400, width: '100%' }}>
      <XGrid
        {...baselineEditProps}
        apiRef={apiRef}
        autoHeight
      />
      { message && <Alert severity="info">{message}</Alert> }
    </div>
  );
}
```

### LINKED ISSUE #1821: [DataGrid] Should not expose apiRef
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Developers can access apiRef in the community plan, while we document it a Pro plan feature.

## Expected Behavior 🤔

Developers shouldn't be able to access apiRef in `DataGrid`, **only** in `XGrid`.

## Steps to Reproduce 🕹

Steps:

1. https://codesandbox.io/s/material-demo-forked-59fsr?file=/demo.tsx

```jsx
export default function DataGridDemo() {
  return (
    <div style={{ height: 400, width: "100%" }}>
      <DataGrid
        onRowSelected={(parmas) => {
          console.log(Array.from(parmas.api.current.getSelectedRows().entries()));
        }}
        rows={rows}
        columns={columns}
        pageSize={5}
        checkboxSelection
      />
    </div>
  );
}
```

## Context 🔦

Saw it in https://github.com/mui-org/material-ui-x/issues/1820

As a side note, the current types and naming looks strange:

1. Why aren't we reducing the types to `GridApiRef` instead of any?

https://github.com/mui-org/material-ui-x/blob/fa346f0fbe3d9b9eea9bb403fe4675f544d6abf9/packages/grid/_modules_/grid/models/params/gridRowSelectedParams.ts#L15-L18

2. Why are naming the prop `api` if we don't provide `GridApi`? Shouldn't it be called `apiRef`?

3. Why expose apiRef when we could provide the api directly?

## Your Environment 🌎

4.0.0-alpha.30

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #1821
Fixes #1301

This is part 2 of 2 for #1821. As we discussed during the call the `api` is removed from all `options` callbacks. It is only present in what callbacks are in the `GridColDef`.

---

### Breaking changes

All `DataGrid` `props` callbacks don't provide access to `api`  anymore. To access `api` you need to use `XGrid` and access it from the `details` parameter.

```
<XGrid 
  onColumnResize={(params, event, details) => console.log(details.api)}
/>
```

- `GridStateChangeParams` is removed, instead `onStateChange` first param is `GridState`

```diff
- onStateChange?: (params: GridStateChangeParams, event: MuiEvent<{}>, details: any) => void; 
+ onStateChange?: (state: GridState, event: MuiEvent<{}>, details: any) => void; 
```

```diff
export interface GridColumnHeaderParams {
   * The column of the current header component.
   */
  colDef: GridStateColDef;
-  /**
-  * API ref that let you manipulate the grid.
-  */
- api: any;
}
```

```diff
export interface GridColumnOrderChangeParams {
   * The old column index.
   */
  oldIndex: number;
-  /**
-   * API ref that let you manipulate the grid.
-   */
-  api: any;
}
```

```diff
export interface GridColumnResizeParams {
   * The column of the current header component.
   */
  colDef: GridStateColDef;
-  /**
-   * API ref that let you manipulate the grid.
-   */
-  api: any;
```

```diff
export interface GridColumnVisibilityChangeParams {
   * The column of the current header component.
   */
  colDef: GridStateColDef;
-  /**
-   * API ref that let you manipulate the grid.
-   */
-  api: any;
```

```diff
export interface GridRowParams {
   * All grid columns.
   */
  columns: GridColumns;
-  /**
-   * GridApiRef that let you manipulate the grid.
-   */
-  api: any;
```

```diff
export interface GridRowScrollEndParams {
   * The grid visible columns.
   */
  visibleColumns: GridColumns;
-  /**
-   * API ref that let you manipulate the grid.
-   */
-  api: any;
```

### CODE REVIEW

File: docs/src/pages/components/data-grid/style/StylingAllCells.tsx [hunk 1]
```diff
@@ -37,7 +41,7 @@ export default function StylingAllCells() {
       <DataGrid
         rows={rows}
         columns={columns}
-        getCellClassName={(params: GridCellParams) => {
+        getCellClassName={(params: GridCellOptionsParams) => {
```
Comment (flaviendelangle) [inline docs/src/pages/components/data-grid/style/StylingAllCells.tsx:44]: Do we want to explicitly set the `params` type here ?
TypeScript can infer it from the `getCellClassName` signature.

File: packages/grid/_modules_/grid/components/cell/GridRowCells.tsx [hunk 2]
```diff
@@ -90,7 +90,9 @@ export const GridRowCells = React.memo(function GridRowCells(props: RowCellsProp
     }
 
     if (getCellClassName) {
-      classNames.push(getCellClassName(cellParams));
+      const classNameParams = { ...cellParams };
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/components/cell/GridRowCells.tsx:93]:
```suggestion
      const classNameParams = { api, ...cellParams };
```

This makes the `delete classNameParams.api` unnecessary.

File: packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts [hunk 3]
```diff
@@ -240,15 +240,17 @@ export function useGridEditRows(
       }
 
       const isEditMode = cellMode === 'edit';
-
       const isModifierKeyPressed = event.ctrlKey || event.metaKey || event.altKey;
+      const stripedParams = { ...params };
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts:244]: Same as above

File: packages/grid/x-grid/src/tests/state.XGrid.test.tsx [hunk 4]
```diff
@@ -50,9 +50,9 @@ describe('<XGrid /> - State', () => {
     render(<Test />);
     const header = screen.getByRole('columnheader', { name: 'brand' });
     fireEvent.click(header);
-    expect(onStateParams.api).to.equal(apiRef.current);
-    expect(onStateParams.state).to.equal(apiRef.current.state);
-    expect(onStateParams.state).to.not.equal(undefined);
+    // expect(onStateParams.api).to.equal(apiRef.current);
```
Comment (flaviendelangle) [inline packages/grid/x-grid/src/tests/state.XGrid.test.tsx:53]: Shouldn't we remove this line altogether ?

File: docs/src/pages/components/data-grid/style/StylingAllCells.tsx (hunk 1 above)
Comment (DanailH) [reply docs/src/pages/components/data-grid/style/StylingAllCells.tsx:44]: It's docs, since this interface is exposed people can also see what is inside it.

File: packages/grid/_modules_/grid/components/cell/GridRowCells.tsx (hunk 2 above)
Comment (flaviendelangle) [reply packages/grid/_modules_/grid/components/cell/GridRowCells.tsx:93]: https://github.com/mui-org/material-ui-x/pull/2312/files#diff-b58ef2608987589ff71f621df6cc9458c607e9b080c9a2c9be7dcaf920539f67R111

In that case we may want to use delete here

File: packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts [hunk 5]
```diff
@@ -108,10 +108,10 @@ export function useGridEditRows(
 
   // TODO it's returning undefined when colDef.editable is undefined
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts:109]: This was already fixed by another PR.

```suggestion
```

File: packages/grid/_modules_/grid/hooks/utils/useResizeContainer.ts [hunk 6]
```diff
@@ -19,9 +19,10 @@ export function useResizeContainer(
   const resizeFn = React.useCallback(() => {
     gridLogger.debug(`resizing...`);
 
-    apiRef.current.publishEvent(GridEvents.debouncedResize, {
-      containerSize: apiRef.current.getState().containerSizes?.windowSizes,
-    });
+    apiRef.current.publishEvent(
+      GridEvents.debouncedResize,
+      apiRef.current.getState().containerSizes?.windowSizes,
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/utils/useResizeContainer.ts:24]: #2300

```suggestion
      apiRef.current.state.containerSizes?.windowSizes,
```

**Review by m4theushw — COMMENTED** [review]
It seems weird to me to remove `api` from `GridRowParams` but keep it in `GridCellParams`. I would remove from both and for those places where it needs to be passed we add a child interface including it: e.g. `ValueParserParams`.

I found `GridCellOptionsParams` a bit confusing, because options and params are the same thing. Maybe by doing the first proposal we don't need it.

**Comment by DanailH** [comment]
> It seems weird to me to remove `api` from `GridRowParams` but keep it in `GridCellParams`. I would remove from both and for those places where it needs to be passed we add a child interface including it: e.g. `ValueParserParams`.
> 
> I found `GridCellOptionsParams` a bit confusing, because options and params are the same thing. Maybe by doing the first proposal we don't need it.

Ok, the problem with that aproach is that by keeping the `GridCellParams` without `api` in it and changing the types to all `ColDef` callback to `ValueParserParams` which includes the `api` the typing won't be descriptive. Basically, the `renderCell`  will get params of type `ValueParserParams`?

I would keep it as it is but maybe change the name of the interface `GridCellOptionsParams`. I agree there are better names for it so I'm open to suggestions.

**Comment by m4theushw** [comment]
> Basically, the renderCell will get params of type ValueParserParams?

No, we would create dedicated interfaces for these callbacks. In the case of `renderCell` it could be `RenderCellParams`. We're already doing that for some callbacks:

https://github.com/mui-org/material-ui-x/blob/8deeab3b2400f0a91b90f9cea4b2a82fe2d8f6d8/packages/grid/_modules_/grid/models/colDef/gridColDef.ts#L91
https://github.com/mui-org/material-ui-x/blob/8deeab3b2400f0a91b90f9cea4b2a82fe2d8f6d8/packages/grid/_modules_/grid/models/colDef/gridColDef.ts#L97
https://github.com/mui-org/material-ui-x/blob/8deeab3b2400f0a91b90f9cea4b2a82fe2d8f6d8/packages/grid/_modules_/grid/models/colDef/gridColDef.ts#L127

The reason I'm against keeping the `api` is that it's not consistent and we need to remember to always delete it when passing the params as argument.

**Comment by DanailH** [comment]
But you would still need to pass in the `api` for those callbacks.

**Comment by m4theushw** [comment]
The `api` would still be passed but it would be in a dedicated interface only for the params related to cell rendering.  

This component could use `RenderCellParams` instead of `GridCellParams`.

https://github.com/mui-org/material-ui-x/blob/8deeab3b2400f0a91b90f9cea4b2a82fe2d8f6d8/packages/grid/_modules_/grid/components/cell/GridBooleanCell.tsx#L5

One of our technical debits is that we used `GridCellParams` a lot only to pass the id and the field and to remove it now it will be a pain.

File: packages/grid/_modules_/grid/components/cell/GridCell.tsx [hunk 7]
```diff
@@ -67,6 +67,7 @@ export const GridCell = React.memo(function GridCell(props: GridCellProps) {
       }
 
       const params = apiRef!.current.getCellParams(rowId, field || '');
+      delete params.api;
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/cell/GridCell.tsx:70]: Could we do the opposite? Only provide the api where it's absolutely needed?

Comment (DanailH) [reply packages/grid/_modules_/grid/components/cell/GridCell.tsx:70]: Will work to create different interfaces for where the `api` is needed.

**Comment by DanailH** [comment]
@m4theushw @oliviertassinari I've updated the `GridCellParams` so now it doesn't contain `api` anymore and `api` is explicitly added to the `GridColDef` methods that need it

**Comment by oliviertassinari** [comment]
I have resolved the conflict that I introduced with #2340 (I work on this after seeing the same in this PR).

File: packages/grid/_modules_/grid/models/gridOptions.tsx [hunk 8]
```diff
@@ -546,12 +546,12 @@ export interface GridOptions {
   onSortModelChange?: (model: GridSortModel, details?: any) => void;
   /**
    * Callback fired when the state of the grid is updated.
-   * @param params
+   * @param state
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/models/gridOptions.tsx:549]:
```suggestion
   * @param state The new state.
```

File: packages/grid/_modules_/grid/models/colDef/gridColDef.ts [hunk 9]
```diff
@@ -110,12 +111,12 @@ export interface GridColDef {
...
    * @param params
    */
-  renderCell?: (params: GridCellParams) => React.ReactNode;
+  renderCell?: (params: GridRenderCellParams) => React.ReactNode;
   /**
    * Allows to override the component rendered in edit cell mode for this column.
    * @param params
    */
-  renderEditCell?: (params: GridCellParams) => React.ReactNode;
+  renderEditCell?: (params: GridRenderCellParams) => React.ReactNode;
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/models/colDef/gridColDef.ts:119]: We can reuse `GridRenderCellParams` but it also need to include `GridEditCellProps` or the user won't be able to access the additional props.

https://github.com/mui-org/material-ui-x/blob/019c7ccb19a8ee31214da7936cdd4c899921aa3c/packages/grid/_modules_/grid/models/gridEditRowModel.ts#L3-L6

```suggestion
  renderEditCell?: (params: GridRenderEditCellParams) => React.ReactNode;
```

**Review by m4theushw — APPROVED** [review]
Nice work!
