### PR TITLE
[DataGrid] Fix keyboard event collisions

### LINKED ISSUE #700: [DataGrid] Row Checkboxes: spacebar does not select row
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

- Select a data row checkbox, and press the spacebar
- Observe the row is not selected

## Expected Behavior 🤔

- Select data row checkbox, press spacebar, row is selected

## Steps to Reproduce 🕹

Steps:

1. Go to https://material-ui.com/components/data-grid/#mit-version
2. Tab focus a row checkbox (not the "select all/none" checkbox)
3. Press spacebar

## Notes

On the commercial XGrid version, the same problem exists, but there's an added effect of paging the table (it scrolls down a bit).

### LINKED ISSUE #701: [DataGrid] Keyboard events trigger interactions twice
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When focusing an input, the grid handle <kbd>Space</kbd>, <kbd>ArrowLeft</kbd>, etc.

## Expected Behavior 🤔

When focusing an input, the grid should ignore most of the keyboard events.

## Steps to Reproduce 🕹

Steps:

1. https://codesandbox.io/s/material-demo-forked-4k9vo?file=/package.json
2. Try typing text containing one space, or using the arrow to make an edit.

Dec-06-2020 20-39-42

## Context 🔦

Noticeable since #673. The issue come to my attention looking at #700.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | not released yet  |

### LINKED ISSUE #797: [DataGrid] Key event regression
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

arrow regression

## Expected Behavior 🤔

The <kbd>ArrowRight</kbd> should prevent the scroll as in https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-o2w9g?file=/package.json

## Context 🔦

A regression from #673 released in v4.0.0-alpha.12. It was [working fine](https://codesandbox.io/s/material-demo-forked-0r10h?file=/package.json) in v4.0.0-alpha.11.

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #701 
Fixes #700  
Fixes #797

### CODE REVIEW

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
A couple of notes:

- GitHub doesn't recognize the "Fixes #a #b" pattern. Each linked issue has be to prefixed in order to get them automatically closed.
- We can't look for any specific dom element. We have no guarantee that it's enough, e.g a node with contentEditable to true. I think that we should do the opposite. Ignore the event not coming from the root of the cell, and whitelist cases we want to be smart about.
- Did you look into the other shortcuts?

**Comment by oliviertassinari** [comment]
It looks like we have overlooked #673. While the two issues we are trying to solve were surfaced by the fix. I have also found regression #797. We might want to start fixing the regression.

**Comment by DanailH** [comment]
> A couple of notes:
> 
> * GitHub doesn't recognize the "Fixes #a #b" pattern. Each linked issue has be to prefixed in order to get them automatically closed.
> * We can't look for any specific dom element. We have no guarantee that it's enough, e.g a node with contentEditable to true. I think that we should do the opposite. Ignore the event not coming from the root of the cell, and whitelist cases we want to be smart about.
> * Did you look into the conflict with the other shortcuts?

Thanks for the heads up for the "Fixes" section.

Regarding the form elements, I was also thinking the same thing. It would be better to just check if the active element is a Cell element, I'll update the fix.

Regarding potential regression - there is one (well kind of, not sure if it counts). It goes like this - the grid navigation by arrows or space bar work as expected until an `input`, for example, becomes active. Then because I am preventing those navigations while the input is active you are no longer able to use the arrows and the space bar to navigate the grid. Also if you press the tab key then the `tabindex` is respected and the focus jumps on the next `input` element, which I think is what actually is expected from a accessibility point of view.

**Comment by oliviertassinari** [comment]
> because I am preventing those navigations while the input is active you are no longer able to use the arrows and the space bar to navigate the grid.

I think that it's fine, for a first iteration. It's what I had in my by "whitelist cases", we could imagine having <kbd>Arrow up</kbd> blur the input and move to the above cell. But that's for alter, I think that it's quite bold and need to be evaluated independently.

**Review by oliviertassinari — COMMENTED** [review]
What about the other shortcuts? Shouldn't disable them all?

**Comment by DanailH** [comment]
> What about the other shortcuts? Shouldn't disable them all?

Maybe I missed something but as far as I can see the other shortcuts require the `shift` key to be pressed which shouldn't conflict with the interactions on an input

**Comment by oliviertassinari** [comment]
@DanailH Please check again, this is simply not true.

**Comment by DanailH** [comment]
> @DanailH Please check again, this is simply not true. Shift conflicts with the `<input>` **and** it's not the only shortcut. I shouldn't have had to test it.

I'm sorry @oliviertassinari, my bad. I didn't take into account more complex interactions. I prevented all but the shortcut for selecting the active row.

**Comment by oliviertassinari** [comment]
Sorry, it was simpler for me to push a few commits than to comment more. I have tried to make them single purposed so you can review them and understand what's going on:

- ebf4dd4: this branch can never be reached (tautologie), remove it
- 9bf656c: we can skip everything, simpler
- 624d2c1: the return shouldn't be here, this branch is focusing on a different problem
- ccd495e: as we have seen before, use the opportunity to clean this technical debt event.code -> event.key.
- 8307dfd: the failing error was obscure. I have simplified the test case to yield a better error message when failing (in case we break it in the future).

File: packages/grid/_modules_/grid/utils/domUtils.ts [hunk 1]
```diff
@@ -17,6 +17,10 @@ export function isCell(elem: Element | null): boolean {
   return elem != null && findParentElementFromClassName(elem, CELL_CSS_CLASS) !== null;
 }
 
+export function isCellActive(elem: Element | null): boolean {
```
[the remark this answers is not in the document]
Comment (DanailH) [reply packages/grid/_modules_/grid/utils/domUtils.ts:20]: I agree the name is more appropriate.

**Review by oliviertassinari — APPROVED** [review]

**Comment by DanailH** [comment]
I checked the changes, thanks, it does look simpler. I've changed the new helper method name to `isCellRoot`.

File: packages/grid/_modules_/grid/utils/domUtils.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (DanailH) [reply packages/grid/_modules_/grid/utils/domUtils.ts]: Updated

**Comment by oliviertassinari** [comment]
@DanailH Great, if you want to challenge some of the changes, please do such 🙏.

I hope this will help as inspiration for future cases like this, I hope there are things to learn from it :). I expect a similar level of solution quality and speed of iteration from you. I understand that there is a learning curve and that it will take time to get there. But we need to get there somehow, it's important, I will try to speed up the learning as we can't scale if I keep doing this or feel I need to keep doing it.

File: packages/grid/_modules_/grid/hooks/features/keyboard/useKeyboard.ts [hunk 2]
```diff
@@ -225,30 +228,24 @@ export const useKeyboard = (gridRootRef: React.RefObject<HTMLDivElement>, apiRef
       if (isMultipleKey(event.key)) {
         logger.debug('Multiple Select key pressed');
         onMultipleKeyChange(true);
-        return;
       }
 
-      if (!isCell(document.activeElement)) {
+      if (!isCellRoot(document.activeElement)) {
         return;
       }
```
Comment (DanailH) [inline packages/grid/_modules_/grid/hooks/features/keyboard/useKeyboard.ts:236]:
```suggestion
     if (!isTabKey(event.code)) {
        // WE prevent default behavior for all key shortcut except tab when the current active element is a cell
        event.preventDefault();
        event.stopPropagation();
      }
```

@oliviertassinari  btw if we return this `if` statement it will fix #797  🤔

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/keyboard/useKeyboard.ts:236]: Agree, I think that we will need to introduce the prevent default back. I think that we should not include the stop propagation event as it's generally considered a footgun unless there a strong case for preventing another listener to handle the event.

Regarding where we should introduce it back, I haven't looked, but maybe inside each if statement that might have a global impact, like the select all, arrow, etc. In the very first version of Damien, we were too aggressive, we were preventing default everything.

Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/keyboard/useKeyboard.ts:236]: Ok, I've added the `event.preventDefault();` only on the navigation parts and the select all shortcut, not on the copy shortcut. I've tested it, this does solve #797 and no other regressions are present.

PS: I know that that this is again looking like a multipurpose PR but I can mark it as a bulk fix since all the issues are related to the same piece of code.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/keyboard/useKeyboard.ts:236]: It seems to work correctly with the latest commit: https://codesandbox.io/s/material-demo-forked-vfcto?file=/demo.js.
We can add one simple test case as a smoke a move forward, great 👍

File: packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx [hunk 3]
```diff
@@ -94,6 +94,36 @@ describe('<DataGrid /> - Keyboard', () => {
...
+
+    render(
+      <div style={{ width: 300, height: 300 }}>
+        <DataGrid rows={rows} columns={columns} />
+      </div>,
+    );
+    // @ts-ignore
+    document.querySelector('[role="cell"][data-rowindex="0"][aria-colindex="0"]').focus();
+    fireEvent.keyDown(document.activeElement!, event);
+    expect(event.preventDefault.called).to.equal(true);
```
Comment (DanailH) [inline packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx:124]: Guys, I would really appreciate the help with this one. I've been trying to test the scroll prevention when an active element is not the root of a cell but I'm struggling with it. I tried a couple of different approaches but couldn't make it fail. In the end, I thought of testing whether the `event.preventDefault` function is being called but that always returns `false` (and the call count is 0). I'm kind of out of ideas at this point.

**Comment by AleKrabbe** [comment]
Sorry for asking, this seems to be directly related to the problem I'm having. I have a renderCell that renders a Input, however when editing the text in that Input I'm not able to use arrow keys to navigate inside the text as it just jumps to the next cell. I thought that maybe adding a stopPropagation on my inputs keyDown event would do the trick; however it didn't. So how should I handle this case? I need to be able to navigate de input text using arrow keys. Thank you.

**Comment by oliviertassinari** [comment]
@AleKrabbe It's fixed in HEAD. You can wait for the next release, 4.0.0-alpha.15.
