### PR TITLE
[DataGrid] Rework columnReorder to work with the new state management

### LINKED ISSUE #452: [XGrid] Reordering class name lost after virtualization
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The `MuiDataGrid-colCellMoving` class name is lost when re-mounting

## Expected Behavior 🤔

The `MuiDataGrid-colCellMoving` class name is restored.

Capture d’écran 2020-10-17 à 18 47 17

## Steps to Reproduce 🕹

reordering css

## Context 🔦

I have tried to implement a fix but I couldn't, we need to wait for the refactorization of the state. We need to store the column that is currently reordering in the state. cc @dtassone.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | latest |

### PR DESCRIPTION
**Pull request by DanailH**
This PR aims to rework the `useColumnReorder` hook to use the new state management in the grid. In addition instead of returning the methods when the hook is called I've moved them in their own section inside the grid API as discussed.

The PR adds `columnReorder` section in the `GridState` with one field -> `dragCol`. This is enough for now as that is what's important while dragging.

In additional I've mapped `useColumnReorder` methods to a more appropriate public API that is added to the grid API

This also fixes  #452

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/column-reorder/useColumnReorder.tsx [hunk 1]
```diff
@@ -1,24 +1,21 @@
 import * as React from 'react';
-import { ColDef } from '../../models/colDef';
-import { useLogger } from '../utils';
-import { ApiRef } from '../../models';
+import { ColDef } from '../../../models/colDef';
+import { useLogger } from '../../utils';
+import { ApiRef } from '../../../models';
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/column-reorder/useColumnReorder.tsx:4]: For the import at the hooks level, better to put the full path, this is to avoid cyclic dependencies

File: packages/grid/_modules_/grid/hooks/features/column-reorder/useColumnReorder.tsx [hunk 2]
```diff
@@ -147,6 +145,15 @@ export const useColumnReorder = (columnsRef: React.RefObject<HTMLDivElement>, ap
     [apiRef, logger],
   );
 
+  const colReorderApi: ColumnReorderApi = {
+    onColCellDragStart: handleDragStart,
+    onColHeaderDragOver: handleColumnHeaderDragOver,
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/column-reorder/useColumnReorder.tsx:150]: What's the diff between colCell and colHeader?

Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/column-reorder/useColumnReorder.tsx:150]: The cell is what is inside `column-header-item` and the header is what's in the `column-header`.

File: packages/grid/_modules_/grid/GridComponent.tsx [hunk 3]
```diff
@@ -23,7 +23,7 @@ import { usePagination } from './hooks/features/pagination/usePagination';
 import { useRows } from './hooks/features/rows/useRows';
 import { useSorting } from './hooks/features/sorting/useSorting';
 import { useApiRef } from './hooks/features/useApiRef';
-import { useColumnReorder } from './hooks/features/useColumnReorder';
+import { useColumnReorder } from './hooks/features/column-reorder';
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/GridComponent.tsx:26]: file name convention

```suggestion
import { useColumnReorder } from './hooks/features/columnReorder';
```

File: packages/grid/_modules_/grid/hooks/features/column-reorder/useColumnReorder.tsx [hunk 4]
```diff
@@ -50,45 +50,59 @@ const hasCursorPositionChanged = (
...
   const handleDragStart = React.useCallback(
     (col: ColDef, currentTarget: HTMLElement): void => {
       logger.debug(`Start dragging col ${col.field}`);
       apiRef.current.publishEvent(COL_REORDER_START);
 
-      dragCol.current = col;
       dragColNode.current = currentTarget;
-      dragColNode.current.addEventListener(DRAGEND, handleDragEnd, { once: true });
       dragColNode.current.classList.add(HEADER_CELL_DRAGGING_CSS_CLASS);
       dragColNode.current.parentElement!.classList.add('MuiDataGrid-colCellMoving');
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/column-reorder/useColumnReorder.tsx:92]: Does it mean we can solve #452 after the refactorization? 

```suggestion
```

If we can this sound like this refactorization is bringing value. If we can't, then we need to rethink the state.

File: packages/grid/_modules_/grid/GridComponent.tsx (hunk 3 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/GridComponent.tsx:26]: Ok, I was wondering what should we use as some of them are with dashes and some camel case.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/GridComponent.tsx:26]: When you have a doubt, check the most popular pattern used in https://github.com/mui-org/material-ui.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/GridComponent.tsx:26]: Actually, I have been wondering about doing "field trips", having community members work on x for a week and the other way around, as a way to share knowledge, better understand each team constraints, etc.

File: packages/grid/_modules_/grid/hooks/features/column-reorder/useColumnReorder.tsx (hunk 4 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/column-reorder/useColumnReorder.tsx]: Done, I've fixed it ;)

File: packages/grid/_modules_/grid/GridComponent.tsx (hunk 3 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/GridComponent.tsx]: I would like that, yes it would be nice also to share the knowadge of the deliverables.

File: packages/grid/_modules_/grid/hooks/features/columnReorder/columnReorderSelector.ts [hunk 5]
```diff
@@ -0,0 +1,11 @@
+import { createSelector } from 'reselect';
+// import { ColDef } from '../../../models/colDef';
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/columnReorder/columnReorderSelector.ts:2]:
```suggestion
```

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx [hunk 6]
```diff
@@ -50,45 +50,60 @@ const hasCursorPositionChanged = (
...
+  const columnsHeaderRef = React.useRef<HTMLElement | null>(null);
   const cursorPosition = React.useRef<CursorCoordinates>({
     x: 0,
     y: 0,
   });
   const removeDnDStylesTimeout = React.useRef<number>();
 
   const handleDragEnd = React.useCallback((): void => {
-    logger.debug(`End dragging col ${dragCol.current!.field}`);
+    logger.debug(`End dragging col`);
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:67]:
```suggestion
    logger.debug('End dragging col');
```

**Review by oliviertassinari — APPROVED** [review]

File: packages/grid/_modules_/grid/components/column-header-item.tsx [hunk 7]
```diff
@@ -8,131 +8,132 @@ import { classnames } from '../utils';
...
-          });
-        }),
-    };
-    const width = column.width!;
+  const dragConfig = {
+    draggable:
+      !disableColumnReorder &&
+      !!apiRef!.current.onColItemDragStart &&
+      !!apiRef!.current.onColItemDragEnter &&
+      !!apiRef!.current.onColItemDragOver,
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/column-header-item.tsx:60]: you don't need those functions checks as they will always be !!apiRef!.current.onColItemDragStart &&

File: packages/grid/_modules_/grid/components/column-header-item.tsx [hunk 8]
```diff
@@ -8,131 +8,132 @@ import { classnames } from '../utils';
...
+    onDragStart:
+      apiRef!.current.onColItemDragStart &&
+      ((event) => apiRef!.current.onColItemDragStart(column, event.currentTarget)),
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/column-header-item.tsx:63]: I would refactor this block like that, 
- remove the dragConfig object
then define each function with useCallback ie
```
const onDragStart = React.useCallback(event =>  {
apiRef!.current.onColItemDragStart(column, event.currentTarget));
} , [column]);
...
```

then
```
const dragConfig = { onDragStart, onDragEnd, ...}
render: (
 <div className="MuiDataGrid-colCell-draggable" {...dragConfig}>
```

File: packages/grid/_modules_/grid/components/column-headers.tsx [hunk 9]
```diff
@@ -126,8 +96,8 @@ export const ColumnsHeader = React.forwardRef<HTMLDivElement, ColumnsHeaderProps
   }, [renderCtx, columns]);
 
   const handleDragOver =
-    onColumnHeaderDragOver && !disableColumnReorder
-      ? (event) => onColumnHeaderDragOver(event)
+    api.current.onColHeaderDragOver && !disableColumnReorder
+      ? (event) => api.current.onColHeaderDragOver(event, ref as React.RefObject<HTMLElement>)
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/column-headers.tsx:100]: Same here. UseCallback

so 
```
const handleDragOver = useCallback((event) => {
if(!disableColumnReorder) {
 api.current.onColHeaderDragOver(event, ref as React.RefObject<HTMLElement>)
}}, [diasbleCol...]);
```

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx [hunk 10]
```diff
@@ -1,24 +1,24 @@
 import * as React from 'react';
-import { ColDef } from '../../models/colDef';
-import { useLogger } from '../utils';
-import { ApiRef } from '../../models';
+import { ColDef } from '../../../models/colDef';
+import { useLogger } from '../../utils';
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:3]: Full path here please. Cyclic dependency avoidance

File: packages/grid/_modules_/grid/components/column-header-item.tsx (hunk 8 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/column-header-item.tsx:63]: I think that we are getting too far with useCallback. What if we forbid it for handlers that are applied on primitives and aren't called repeatively. For instance, it's important to have useCallback for a mouse move but for a mouse start, this creat friction in development without improving performance (it could very well harm it).

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx [hunk 11]
```diff
@@ -50,45 +50,60 @@ const hasCursorPositionChanged = (
...
   const handleDragEnd = React.useCallback((): void => {
-    logger.debug(`End dragging col ${dragCol.current!.field}`);
+    logger.debug('End dragging col');
     apiRef.current.publishEvent(COL_REORDER_STOP);
 
     clearTimeout(removeDnDStylesTimeout.current);
 
-    columnsRef.current!.classList.remove(HEADER_CELL_DROP_ZONE_CSS_CLASS);
-    dragColNode.current!.parentElement!.classList.remove('MuiDataGrid-colCellMoving');
+    columnsHeaderRef.current!.classList.remove(HEADER_CELL_DROP_ZONE_CSS_CLASS);
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:72]: why don't we do the same on this one? Pass using state and props?

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx [hunk 12]
```diff
@@ -50,45 +50,60 @@ const hasCursorPositionChanged = (
...
     dragColNode.current!.removeEventListener(DRAGEND, handleDragEnd);
-    dragCol.current = null;
     dragColNode.current = null;
-  }, [columnsRef, apiRef, logger]);
 
-  const handleDragStart = React.useCallback(
+    setGridState((oldState) => {
+      return {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:77]: if you return straightaway no need for the return... 1 row code

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx [hunk 13]
```diff
@@ -97,35 +112,32 @@ export const useColumnReorder = (columnsRef: React.RefObject<HTMLDivElement>, ap
...
-  const handleColumnHeaderDragOver = React.useCallback(
-    (event) => {
+  const onColHeaderDragOver = React.useCallback(
+    (event: Event, ref: React.RefObject<HTMLElement>) => {
       event.preventDefault();
       apiRef.current.publishEvent(COL_REORDER_DRAG_OVER_HEADER);
-
-      columnsRef.current!.classList.add(HEADER_CELL_DROP_ZONE_CSS_CLASS);
+      columnsHeaderRef.current = ref.current;
+      columnsHeaderRef.current!.classList.add(HEADER_CELL_DROP_ZONE_CSS_CLASS);
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:120]: Can we refactor that to state props...?

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx (hunk 10 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:3]: Could we drop the index.js files in this case?

File: packages/grid/_modules_/grid/components/column-header-item.tsx (hunk 8 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/column-header-item.tsx:63]: if you memo everything and leave a drag handler out then, your underlying component will rerender and hit perf for all the other optimised prop, this is due to a new function that will be defined at every render. So in case of streaming when you render super fast, it can be a perf hit...

The goal is to write good optimised code. 

And by definition, useCallback is here to define a function, and store it for the next render so it doesn't need to redefined it unless the dependencies changed. Hence we use it everywhere. 
It's a bit like instance method stored on the prototype vs method created in the constructor of a function, redefined for each instance.

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx (hunk 10 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:3]: This is important at the hook level especially

They help the typings, and facilitate consumer imports of nested function I think

File: packages/grid/_modules_/grid/components/column-header-item.tsx (hunk 8 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/column-header-item.tsx:63]: ⚠️ We are talking about a primitive here: `<div>` which doesn't implement any memorization.

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx (hunk 10 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:3]: I'm confused. Are you saying we need `../../utils/index.ts` but we can use it to important files?

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx (hunk 13 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:120]: From what I understand, the class needs to be applied before the next RAF, so it's not possible. @DanailH thoughts?

File: packages/grid/_modules_/grid/components/column-header-item.tsx (hunk 8 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/column-header-item.tsx:63]: > don't optimize your code unless you can measure it. 

Not in favor of that, as to me, it means, writes bad unoptimized code everywhere or don't follow any react practices, then when it gets bloated or you start to notice some perf issues, waste time profiling everything, refactor everything, and finally when you wasted a lot of time and headache, adopt some react practices.

Comment (dtassone) [reply packages/grid/_modules_/grid/components/column-header-item.tsx:63]: if nothing changed, divs won't rerender

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/column-header-item.tsx:63]: Haha, that's definitely a valid way to see things! My experience has been the opposite: write code you think is optimized. Later on, notice a performance issue. Dive into understanding what's going on, realize that your optimizations are harming or doing nothing, remove them 😆.

Comment (dtassone) [reply packages/grid/_modules_/grid/components/column-header-item.tsx:63]: Well we are talking about less than 1ms so it will be difficult to measure. But if we multiply it by 10000000, with very fast updates... then you will see limitations...

I'd rather write super optimised code and if issues investigate and remove, instead of the opposite. 
As there are less chances of making mistakes that way

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx (hunk 10 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:3]: in the build we ref indexes, that cascade and build typings accordingly, then concat.
We can use it to import modules with it but we have to be cautious how we do it.
Components can import using indexes. But models for example, that are used everywhere, can create cyclic dependencies

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:3]: > in the build we ref indexes, that cascade and build typings accordingly, then concat.

Interesting, I was hoping the build could contact only using the imports used in the code.

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx (hunk 13 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:120]: That's correct, also I don't think it's necessary to preserve this in the state as it is only used inside this hook. It doesn't bring any value outside of the `useColumnReorder`.

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx (hunk 11 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx:72]: I answered that in the other comment ;)

File: packages/grid/_modules_/grid/components/column-header-item.tsx (hunk 7 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/column-header-item.tsx:60]: Well not necessarily, if you remove the `useColumnReorder` hook from the `GridContainer` component then this will fail, but if we assume that this feature will be there then yes they will be true. I'll remove them tho.

File: packages/grid/_modules_/grid/components/column-header-item.tsx (hunk 8 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/column-header-item.tsx:63]: This is an interesting discussion. I don't think we need it that badly here firstly because the check is not really a heavy computation, and secondly because the underlying method (for instance the `onColItemDragStart `) is already a memorized function. I don't want to go against the grain as I am the least experienced here on that codebase but I'm also against optimizing for the sake of optimizing. I'm not saying that we should write shitty code but if there are performance problems down the road we can analyze and solve them later.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/column-header-item.tsx:63]: No objection to Damien's direction if he has a strong perspective on this. I would simply add that to my experience that memorization of handlers is only important in two cases:

- repeatedly fired events, if you don't memorize you will lose important events (React attach and detach at each render). In our case, it can be the mouse move, our a drag over events, or dependency of useEffect.
- high in the tree React component that computation is heavy and that you can prune with memorization. In our case, it can be the `Viewport` component (because it's large) or a Cell (because there are many)

in other cases, it doesn't matter.

File: packages/grid/_modules_/grid/components/column-header-item.tsx (hunk 7 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/column-header-item.tsx]: Done

File: packages/grid/_modules_/grid/components/column-header-item.tsx (hunk 8 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/column-header-item.tsx]: Updated

File: packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx (hunk 12 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/columnReorder/useColumnReorder.tsx]: done

File: packages/grid/_modules_/grid/components/column-headers.tsx (hunk 9 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/column-headers.tsx]: done

**Review by dtassone — APPROVED** [review]
