### PR TITLE
[DataGrid] Fix manual entry in date fields

### LINKED ISSUE #1920: [DataGrid] Entering value manually in a date field is not working
- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Hi, 

When I try to enter a date (eg 15/06/2021) I get an error typing the year field, it's like 1901. However, if I choose the date from the native date picker, the problem doesn't reproduce itself.

## Expected Behavior 🤔

When i type 2021 the year must be correct.

## Steps to Reproduce 🕹

You can see these materials-ui url that the error persists.

https://material-ui.com/components/data-grid/editing/

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #1920
Preview: https://deploy-preview-2051--material-ui-x.netlify.app/components/data-grid/editing/

The TODO comments can be addressed once #1955 is merged.

### CODE REVIEW

File: packages/grid/_modules_/grid/components/cell/GridEditDateCell.tsx [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+      setValueState(newValue);
+
+      if (newValue === '') {
+        const editProps = { value: null };
+        // TODO use api.setEditCellProps
+        api.publishEvent(GRID_CELL_EDIT_PROPS_CHANGE, { id, field, props: editProps }, event);
+        return;
+      }
+
+      // TODO move to value parser
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/cell/GridEditDateCell.tsx:36]: I'm not sure it would make a difference anymore since we have custom logic in the filtering for dates.

**Review by dtassone — APPROVED** [review]
