### PR TITLE
[DataGrid] Escape regular expression characters in filters

### LINKED ISSUE #1857: [DataGrid] Wildcard char in filters crashes
Filtering a column using contains `*` FireFox throws a `SyntaxError: nothing to repeat` error. 

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When doing a column filter for Contains * on a string type column the browser throws an error.

image

Firefox Error:
image

Chrome Error:
image

## Expected Behavior 🤔

String Column contains `*` should either be treated as a wild card or return no results.

## Steps to Reproduce 🕹

Using the data grid demo on sandbox: https://codesandbox.io/s/7vhnz

Steps:

1. Select First Name column's "Filter" option
2. In the Filter Pane select Contains option with a Value of *
- image

## Context 🔦

I was attempting to filter for non-empty strings in a column and attempted `*` as a sort of wild card character. 

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Unable to provide
```
</details>

Repeatable on the Material-UI provided demo:  https://codesandbox.io/s/7vhnz?file=/index.tsx

Browsers: Firefox and Chrome

### PR DESCRIPTION
**Pull request by ZeeshanTamboli**
Fixes #1857 

Solution from https://github.com/mui-org/material-ui-x/issues/1857#issuecomment-857054361

https://deploy-preview-1899--material-ui-x.netlify.app/components/data-grid/

### CODE REVIEW

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
Please add a test case

File: packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts [hunk 1]
```diff
@@ -2,6 +2,10 @@ import { GridFilterInputValue } from '../../components/panel/filterPanel/GridFil
 import { GridFilterItem } from '../gridFilterItem';
 import { GridFilterOperator } from '../gridFilterOperator';
 
+function escapeRegExp(string: string): string {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts:5]: can we avoid `string: string` please? You can call it `value` or `regex` or...?

File: packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx [hunk 2]
```diff
@@ -184,6 +184,14 @@ describe('<DataGrid /> - Filter', () => {
         expect(getColumnValues()).to.deep.equal(expected);
       });
     });
+
+    ['contains', 'startsWith', 'endsWith'].forEach((operatorValue) => {
+      it('should escape RegExp characters if applied as filter values', () => {
+        const regExpToEscape = '[-[]{}()*+?.,\\^$|#s]';
+        render(<TestCase value={regExpToEscape} operatorValue={operatorValue} />);
+        expect(getColumnValues()).to.deep.equal([]);
```
Comment (oliviertassinari) [inline packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx:192]: I don't think that it's enough, we should still be able to find the result.

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx:192]: If the assertion is checking `[]`, it is ignoring the input value and returning zero rows if it is a regex. So what do we want to support? Should we escape regex and show empty or able to filter without any crash even if it is a RegExp? Like support * as all rows?
Also I checked with Commodity `contains` filter one case wherein `soy*` worked before as `starts with soy` and now it simply returns zero rows for `soy*` in Xgrid demo.  I will have to check that.

Comment (dtassone) [reply packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx:192]: IMO soy* should just search for soy*? So we don't support regex search
Otherwise if a value is *, it is not filterable

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx:192]: > IMO soy* should just search for soy*

This works with the current fix. 
Example: If a row contains `soy*bean` value string, filter operation `contains` `soy*` will return this row. What happens is the filter regex is now `soy\*bean` making * as literal instead of regex special. 
 I could add a test case for this.

Comment (dtassone) [reply packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx:192]: Yes it's the correct behaviour. And yes please add a test so it's a bit more robust.

Comment (ZeeshanTamboli) [reply packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx]: I added one.

**Review by dtassone — APPROVED** [review]
