### PR TITLE
[DataGrid] Make GridMenu accessible

### LINKED ISSUE #881: [DataGrid] The density selector isn't accessible
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

Capture d’écran 2021-01-20 à 00 37 05

## Current Behavior 😯

1. The button has `aria-haspopup="true"`
1. The button doesn't have `aria-labelledby`
1. The button doesn't have `aria-expanded="true"`
1. Opening the popup doesn't move the focus to it
1. <kbd>Arrow Down</kbd> doesn't allow to navigate the options
1. <kbd>Escape</kbd> doesn't closes the popup
1. The ul has a role "menu"
1. The ul has no aria-labelledby

## Expected Behavior 🤔

1. The button has `aria-haspopup="listbox"`
1. The button has a `aria-labelledby` that points to the listbox
1. The button has `aria-expanded="true"`
1. Opening the popup moves the focus to it
1. <kbd>Arrow Down</kbd> allows to navigate the options
1. <kbd>Escape</kbd> closes the popup
1. The ul has a role "listbox"
1. The ul has aria-labelledby

The pattern: https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html

## Steps to Reproduce 🕹

Steps:

1. https://master--material-ui-x.netlify.app/components/data-grid/columns/#column-selector

## Context 🔦

⚠️ The behavior required for the density selector is different from the one needed for the column menu (#882).

## Your Environment 🌎

`@material-ui/data-grid@v4.0.0-alpha.17`

### LINKED ISSUE #882: [DataGrid] The column menu isn't accessible
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

Capture d’écran 2021-01-20 à 00 38 43

## Current Behavior 😯

1. The button doesn't have `aria-haspopup="true"`
1. The button doesn't have `aria-controls`
1. The button doesn't have `aria-expanded="true"`
1. Opening the popup doesn't move the focus to it
1. <kbd>Arrow Down</kbd> doesn't allow to navigate the options
1. <kbd>Escape</kbd> doesn't closes the popup
1. The ul has no aria-labelledby

## Expected Behavior 🤔

1. The button has `aria-haspopup="true"`
1. The button has `aria-controls`
1. The button has `aria-expanded="true"`
1. Opening the popup moves the focus to it
1. <kbd>Arrow Down</kbd> allows to navigate the options
1. <kbd>Escape</kbd> closes the popup
1. The ul has aria-labelledby

The pattern: https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

## Steps to Reproduce 🕹

Steps:

1. https://master--material-ui-x.netlify.app/components/data-grid/columns/#column-selector

## Context 🔦

⚠️ The behavior required for the column menu is different from the one needed for the density selector (#881).

## Your Environment 🌎

`@material-ui/data-grid@v4.0.0-alpha.17`

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #881 
Fixes #882

### CODE REVIEW

File: packages/grid/_modules_/grid/utils/material-ui-utils.ts [hunk 1]
```diff
@@ -44,3 +44,17 @@ export function getScrollbarSize(doc: Document): number {
 
   return scrollbarSize;
 }
+
+export function useId(idOverride) {
```
Comment (DanailH) [inline packages/grid/_modules_/grid/utils/material-ui-utils.ts:48]: I had to copy this from `code` as the import doesn't work, it returns `undefined` :/

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/utils/material-ui-utils.ts:48]: The module seems to be exposed as `unstable_useId` in both v4
https://github.com/mui-org/material-ui/blob/91fa0d7bb0c70d5ed98cb1b42aadba4babecf06d/packages/material-ui/src/utils/index.js#L16
and v5

https://github.com/mui-org/material-ui/blob/4793d2d5d6fc8542aa422c0e98261e11649fb994/packages/material-ui/src/utils/index.js#L12

Comment (DanailH) [reply packages/grid/_modules_/grid/utils/material-ui-utils.ts:48]: Yes I saw it but when you do `import { unstable_useId } from '@material-ui/utils';` the `unstable_useId` is `undefined`.

File: packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx [hunk 2]
```diff
@@ -39,6 +42,10 @@ export function ColumnHeaderMenuIcon(props: ColumnHeaderFilterIconProps) {
         title={apiRef!.current.getLocaleText('columnMenuLabel')}
         size="small"
         onClick={handleMenuIconClick}
+        aria-expanded={open ? 'true' : undefined}
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:45]: `open && 'true' `

File: packages/grid/_modules_/grid/utils/material-ui-utils.ts (hunk 1 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/utils/material-ui-utils.ts:48]: Did you try `@material-ui/core/utils`? I didn't link the utils package.

File: packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx (hunk 2 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:45]:
```suggestion
        aria-expanded={open ? true : undefined}
```

File: packages/grid/_modules_/grid/components/menu/GridMenu.tsx [hunk 3]
```diff
@@ -52,11 +65,20 @@ export const GridMenu: React.FC<MenuProps> = ({
...
+      transition
+      placement={position}
+      {...other}
+    >
       {({ TransitionProps, placement }) => (
         <Grow {...TransitionProps} style={{ transformOrigin: transformOrigin[placement] }}>
           <Paper>
-            <ClickAwayListener onClickAway={onClickAway}>{children}</ClickAwayListener>
+            <ClickAwayListener onClickAway={onClickAway}>
+              <div>{children}</div>
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/menu/GridMenu.tsx:80]: I think that it should aways be a MenuList as a first child (can be coming from children). Why is it not working in HEAD?

Comment (DanailH) [reply packages/grid/_modules_/grid/components/menu/GridMenu.tsx:80]: It's weird, it works for the export and the density but it doesn't for the column menu, by not working I mean it throws a warning in the console.

File: packages/grid/_modules_/grid/utils/material-ui-utils.ts (hunk 1 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/utils/material-ui-utils.ts:48]: I'll try it

File: packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx (hunk 2 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:45]: I took that approach from the core and from the one we did before that.

File: packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenu.tsx [hunk 4]
```diff
@@ -1,29 +1,40 @@
...
 export function GridColumnMenu(props: GridColumnMenuProps) {
-  const { hideMenu, currentColumn } = props;
+  const { hideMenu, currentColumn, open } = props;
+  const columnMenuButtonId = useId('column-menu-button');
+  const columnMenuId = useId('column-menu');
   const handleListKeyDown = React.useCallback(
     (event: React.KeyboardEvent) => {
-      if (event.key === 'Tab') {
+      if (event.key === 'Tab' || event.key === 'Escape') {
         event.preventDefault();
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenu.tsx:23]: I don't think prevent default should be called for <kbd>Escape</kbd>. There are no native action to prevent. We don't prevent in the main repo

File: packages/grid/_modules_/grid/utils/material-ui-utils.ts (hunk 1 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/utils/material-ui-utils.ts]: Done but I needed to `@ts-ignore` because of a warning that reads that the module doesn't have an exported method `unstable_useId`.

File: packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx [hunk 5]
```diff
@@ -1,4 +1,6 @@
 import * as React from 'react';
+// @ts-ignore TODO: remove once the module is fixed
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:2]: So we can't forget to remove it.

```suggestion
// @ts-expect-error fixed in Material-UI v5, types definitions were added.
```

File: packages/grid/_modules_/grid/components/menu/GridMenu.tsx [hunk 6]
```diff
@@ -19,6 +20,17 @@ type MenuPosition =
   | 'top'
   | undefined;
 
+const useStyles = makeStyles(
+  () => ({
+    root: {
+      '& .MuiDataGrid-gridMenuList:focus': {
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/menu/GridMenu.tsx:26]: We don't need to mention `:focus` it's shorter without

```suggestion
      '& .MuiDataGrid-gridMenuList': {
```

File: packages/grid/_modules_/grid/components/menu/GridMenu.tsx (hunk 3 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/menu/GridMenu.tsx]: Ok, I had a look. Any weird behavior is an invitation for exploration. The `GridColumnMenu` component isn't forwarding its ref, not the extra props to the `MenuList` component. It could be solved easily but, there a bunch of extra props (the `GridBaseComponentProps`) and it's not versatile.

Instead, I have pushed a commit to reorganize the composition order. Grow doesn't host any div, it needs to apply props to its children, same for ClickAwayListener. We save one DOM node.

In the process, I have found an improvement opportunity, ClickAwayListener could forward its props to the children.

File: packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenu.tsx [hunk 7]
```diff
@@ -9,21 +11,30 @@ import { SortGridMenuItems } from './SortGridMenuItems';
...
       }
     },
     [hideMenu],
   );
   return (
-    <MenuList id="menu-list-grow" onKeyDown={handleListKeyDown}>
+    <MenuList
+      id={columnMenuId}
+      className="MuiDataGrid-gridMenuList"
+      role="menu"
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenu.tsx:33]: This is the default value
```suggestion
```

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
Things I have seen, we aren't too far:

- There are two approved suggestions that were only partially applied in the changes.
- As far as I know, <kbd>Tab</kbd> should prevent default, there is a native behavior (it scrolls the page before the focus moves back to where it should be) we want to disable. On the other hand, <kbd>Escape</kbd> has no native behavior hence we don't need to prevent default. It seems to be how the Menu in the core behaves. It makes me think of https://github.com/mui-org/material-ui/issues/13470#issuecomment-435029581
- The focus isn't moving to the first item in the list. Related to https://github.com/mui-org/material-ui/pull/17571.
- I don't understand what we do with `useId`. Did you look at what the hook is doing and the requirement for the id to work correctly?

**Comment by DanailH** [comment]
> Things I have seen, we aren't too far:
> 
> * There are two approved suggestions that were only partially applied in the changes.
> * As far as I know, Tab should prevent default, there is a native behavior (it scrolls the page before the focus moves back to where it should be) we want to disable. On the other hand, Escape has no native behavior hence we don't need to prevent default. It seems to be how the Menu in the core behaves. It makes me think of [mui-org/material-ui#13470 (comment)](https://github.com/mui-org/material-ui/issues/13470#issuecomment-435029581)
> * The focus isn't moving to the first item in the list. Related to [mui-org/material-ui#17571](https://github.com/mui-org/material-ui/pull/17571).
> * I don't understand what we do with `useId`. Did you look at what the hook is doing and the requirement for the id to work correctly? In the current usage, using the hook or not changes nothing.

Alright, I pushed the changes requested.

A couple of things, I'll keep `autoFocus` for the `GridColumnMenu` because the `autoFocusItem` is not working due to the current structure (needs refactoring if we want to make it work). It's still accessible via the keyboard. The drawback is that the focus is not on the first element but on the wrapper and you need one arrow to click to select the first or last element in the menu. 
Another thing was the `id`s for the columne menu and the 3dot button - went for the option of keeping them in the state for the time being (there was already a `columnMenu` section in the state that holds the field so I added the `id` and the `labelledby` as well).

File: packages/grid/_modules_/grid/components/toolbar/GridDensitySelector.tsx [hunk 8]
```diff
@@ -99,7 +107,14 @@ export function GridDensitySelector() {
         onClickAway={handleDensitySelectorClose}
         position="bottom-start"
       >
-        <MenuList role="listbox" onKeyDown={handleListKeyDown} autoFocusItem={Boolean(anchorEl)}>
+        <MenuList
+          id={densityMenuId}
+          className="MuiDataGrid-gridMenuList"
+          role="menu"
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/toolbar/GridDensitySelector.tsx:113]: ⚠️

**Review by oliviertassinari — APPROVED** [review]

File: packages/grid/_modules_/grid/components/toolbar/GridDensitySelector.tsx (hunk 8 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/toolbar/GridDensitySelector.tsx]: Removed that one and the one in the export selector

File: packages/grid/_modules_/grid/models/api/columnMenuApi.ts [hunk 9]
```diff
@@ -5,8 +5,10 @@ export interface ColumnMenuApi {
   /**
    * Display the column menu under the field column.
    * @param field
+   * @param id
+   * @param labelledby
    */
-  showColumnMenu: (field: string) => void;
+  showColumnMenu: (field: string, id: string, labelledby: string) => void;
```
Comment (dtassone) [inline packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: why do we need id and labelledBy to show the column menu? And how can consumers get them?

Comment (DanailH) [reply packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: we need them so that the `labelledby` and the `controlledby` are hooked up correctly. I had to do it like this because they that the menu and the button are set up that is the only option. In terms of how users can get them -> there are in the state while the menu is opened.

Comment (dtassone) [reply packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: ShowColumnMenu should only show the menu when one click on the 3 dots icon next to the column title.
Is that still the case?

> there are in the state while the menu is opened.

Well `showColumnMenu` opens the menu so how can we know the `labelledBy` before we call the `showColumnMenu`. Chicken and egg situation? :)

Comment (DanailH) [reply packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: I mean the existing functionality still works the same.

Comment (DanailH) [reply packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: @dtassone can I merge this, it would be nice to include the fix in the upcoming release 🙃

Comment (dtassone) [reply packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: I can approve if you want, but for me the api is not great. I have to pass a mandatory Id that I can't know, and a labelled by that I can't know either. I don't see how this change is going to improve the DX and api.

**Review by dtassone — APPROVED** [review]

File: packages/grid/_modules_/grid/models/api/columnMenuApi.ts (hunk 9 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: > why do we need id and labelledBy to show the column menu?

@dtassone The answer is in https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

> And how can consumers get them?

I think that the question should be the opposite, why is this method public in the first place?

Comment (dtassone) [reply packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: how do you render the grid with the menu open. Imagine if the user want to put a custom component...

Comment (dtassone) [reply packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: How is it harmful?

Comment (DanailH) [reply packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: I don't think that would be an issue, they can still open it right, it's just that the `id` and the `labelledBy` won't be set

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: > How is it harmful?

It could prevent us to improve the internal: e.g. this very discussion. I don't understand the use cases for a developer to open a column menu from outside the normal end-user flows.

Comment (dtassone) [reply packages/grid/_modules_/grid/models/api/columnMenuApi.ts:11]: > I don't think that would be an issue, they can still open it right, it's just that the `id` and the `labelledBy` won't be set

why not make them optional?
Also why calling it id? Something like menuElementId or whatever a bit more specific so it's more understandable
