### PR TITLE
[DataGrid] Simplify footer logic

### LINKED ISSUE #638: Footer total rows and selected rows disappear on adding pagination.
Footer  text for total rows and selected rows disappear on adding pagination. And onPageSizeChange, onPageChange are still showing weird behaviour for server side pagination.

- [ √] The issue is present in the latest release.
- [ √] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.Go to  https://codesandbox.io/s/cgbej?file=/demo.js
2. Add pagination prop
3.
4.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | 4.0.0-alpha.10 |
| React         | 16.9.0       |
| Browser       |     Chrome    |
| TypeScript    |         |
| etc.          |         |

### PR DESCRIPTION
**Pull request by oliviertassinari**
Fixes #638 with the part around by reducing the breakpoint threshold from `md` to `sm`.

> Footer […] selected rows disappear on adding pagination

**Before**

Capture d’écran 2020-12-03 à 12 56 21

**After**

Capture d’écran 2020-12-03 à 12 56 48

### CODE REVIEW

File: packages/grid/_modules_/grid/components/default-footer.tsx [hunk 1]
```diff
@@ -25,23 +25,20 @@ export const DefaultFooter = React.forwardRef<HTMLDivElement, DefaultFooterProps
...
-    );
-    const showSelectedRowCount = !options.hideFooterSelectedRowCount && (
-      <SelectedRowCount selectedRowCount={selectedRowCount} />
-    );
-    const justifyItemsEnd = !selectedRowCount && !options.hideFooterSelectedRowCount;
+    const showSelectedRowCount =
+      !options.hideFooterSelectedRowCount && selectedRowCount > 0 ? (
+        <SelectedRowCount selectedRowCount={selectedRowCount} />
+      ) : (
+        <div />
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/default-footer.tsx:32]: why not null?

File: packages/grid/_modules_/grid/components/selected-row-count.tsx [hunk 2]
```diff
@@ -7,10 +7,6 @@ interface SelectedRowCountProps {
 export function SelectedRowCount(props: SelectedRowCountProps) {
   const { selectedRowCount } = props;
 
-  if (selectedRowCount === 0) {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/selected-row-count.tsx:10]: so we'll show 0 row selected?

File: packages/grid/_modules_/grid/components/default-footer.tsx [hunk 3]
```diff
@@ -25,23 +25,20 @@ export const DefaultFooter = React.forwardRef<HTMLDivElement, DefaultFooterProps
...
-    const isPaginationAvailable = !!paginationComponent;
-    const showRowCount = !options.hideFooterRowCount && !isPaginationAvailable && (
-      <RowCount rowCount={totalRowCount} />
-    );
-    const showSelectedRowCount = !options.hideFooterSelectedRowCount && (
-      <SelectedRowCount selectedRowCount={selectedRowCount} />
-    );
-    const justifyItemsEnd = !selectedRowCount && !options.hideFooterSelectedRowCount;
+    const showSelectedRowCount =
+      !options.hideFooterSelectedRowCount && selectedRowCount > 0 ? (
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/default-footer.tsx:29]: `selectedRowCount > 0 ` I don't think that should be in the footer as it's a `SelectedRowCount` concern.

The footer should be dumb. 
ie if not hidden show...

File: packages/grid/_modules_/grid/components/default-footer.tsx (hunk 1 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/default-footer.tsx:32]: Needed to keep the CSS simple (flexbox space-between)

File: packages/grid/_modules_/grid/components/default-footer.tsx (hunk 3 above)
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/default-footer.tsx:29]: I doubt that the footer can be dumb, it needs to manage the space available

Comment (dtassone) [reply packages/grid/_modules_/grid/components/default-footer.tsx:28]: well it should just show hide the underlying component but it doesn't need to know about the business logic within it. ie 
Show selected rows if screen less than Xpx => footer responsibility
Show selected rows for counter above 0 is the selected rows business logic

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/default-footer.tsx:28]: > well it should just show hide the underlying component but it doesn't need to know about the business logic within it. ie

How would you solve the positioning problem in this case? Mind that I'm using `selectedRowCount` here, and @DanailH did too in the current version:

https://github.com/mui-org/material-ui-x/blob/325d91116efe567df4e563e6eef7b696e3629190/packages/grid/_modules_/grid/components/default-footer.tsx#L35

Comment (DanailH) [reply packages/grid/_modules_/grid/components/default-footer.tsx:28]: I agree, I see the footer more like a manager and the components that are in it should be fairly dumb. Unfortunately the footer is the one responsible for the layout.

**Review by DanailH — APPROVED** [review]
