### PR TITLE
[DataGrid] Fix browser keyboard shortcuts not working when header cell is focused

### LINKED ISSUE #3477: [DataGrid] CMD + R keyboard event get ignored when the column header cell is focused.
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

CMD + R does not refresh the page when head cell has focus

P.S. Looks like most cmd shortcuts get ignored, e.g. CMD+L should focus on browser search bar on chrome

### Expected behavior 🤔

CMD + R should refresh the page when head cell has focus

### Steps to reproduce 🕹

Steps:

This only test on a macOS chrome.

0. https://mui.com/components/data-grid/demo/
1. sort any column. ( so the cell gain focus)
2. press cmd+r

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by valenfv**
Fixes #3477 by only preventing default for non registered shortcuts. This behavior applies both for cells and column headers.

Preview: https://deploy-preview-3692--material-ui-x.netlify.app/components/data-grid/demo/

## The issue
When a cell / header cell had focus, no keyboard shortcuts would work. The problem was on the `useGridKeyboardNavigation` hook which was `event.preventDefault()` to any key press.

## The solution
Only prevent default behavior to shortcuts / keys we are expecting. 

Solution provided by @m4theushw

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts [hunk 1]
```diff
@@ -231,6 +237,14 @@ export const useGridKeyboardNavigation = (
           event.preventDefault(); // prevent Space event from scrolling
```
Comment (cherniavskii) [inline packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts:237]:
```suggestion
          // prevent Space event from scrolling
```

Since `event.preventDefault()` is called below

**Review by cherniavskii — APPROVED** [review]
Thanks!
