### PR TITLE
[DataGrid] Fix `id` and `aria-labelledby` attributes on the column menu

### LINKED ISSUE #1365: [DataGrid] Set the correct `id` and `labelledby` on the column menu
When opening the column menu make sure that the `id` and `labelledby` are correctly set.

This was first mentioned here https://github.com/mui-org/material-ui-x/pull/1289#discussion_r602158285

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Currently, the `id` and the `labelledby` are stored in the state. The problem is that this does not scale very well and if you try and open the column menu using another interaction, for example when pressing `Enter` then those values would not be set correctly.

## Motivation 🔦

We need a solution for this for accessibility reasons.

### LINKED ISSUE #1372: [DataGrid] Failed prop type: Material-UI: The `anchorEl` prop provided to the component is invalid.
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Using https://codesandbox.io/s/6czle a warning is thrown when:

1.) Hover over any column to reveal the column options (three dots) button. Click the options button to display a popover menu and select the `Hide` option.
2.) Hover over another column to reveal the options button. Click the options button to display a popover menu.
3.) When the popover is rendered, the following warning is thrown:

```
Warning: Failed prop type: Material-UI: The `anchorEl` prop provided to the component is invalid.
The anchor element should be part of the document layout.
Make sure the element is present in the document or that it's not display none.
    at Popper (https://9t6f4.csb.app/node_modules/@material-ui/core/esm/Popper/Popper.js:49:24)
    at oi (https://9t6f4.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:4548:14)
    at ii (https://9t6f4.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:4566:32)
    at div
    at Ys (https://9t6f4.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7216:8)
    at Xs (https://9t6f4.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7192:1)
    at div
    at eval (https://9t6f4.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:4106:21)
    at NoSsr (https://9t6f4.csb.app/node_modules/@material-ui/core/esm/NoSsr/NoSsr.js:12:24)
    at eval (https://9t6f4.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7297:15)
    at eval (https://9t6f4.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7501:13)
    at div
    at AntDesignGrid (https://9t6f4.csb.app/demo.tsx:142:58)
```

## Expected Behavior 🤔

Not to throw a warning in development.

## Steps to Reproduce 🕹

https://codesandbox.io/s/6czle

For reproduction steps, see above.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
System:
    OS: Linux 5.8 Linux Mint 20.1 (Ulyssa)
  Binaries:
    Node: 14.16.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.11 - /usr/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
  npmPackages:
    @emotion/react: ^11.1.5 => 11.1.5 
    @emotion/styled: ^11.1.5 => 11.1.5 
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/data-grid: ^4.0.0-alpha.24 => 4.0.0-alpha.24 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/pickers: ^3.3.10 => 3.3.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  16.9.49 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.2.3 => 4.2.3 
```
</details>

### PR DESCRIPTION
**Pull request by m4theushw**
Closes #1365
Closes #1372

My solution was to use the field of the column to create the `id` and `aria-labelledby`, instead of a random value. We could also calculate them during hydration and store as attributes of `GridColDef`, but I think it's a bit overkill.

https://deploy-preview-1460--material-ui-x.netlify.app/components/data-grid/

### CODE REVIEW

File: packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx [hunk 1]
```diff
@@ -16,17 +14,17 @@ export function ColumnHeaderMenuIcon(props: ColumnHeaderFilterIconProps) {
   const { column } = props;
   const apiRef = React.useContext(GridApiContext);
   const columnMenuState = useGridSelector(apiRef, gridColumnMenuStateSelector);
-  const columnMenuButtonId: string = useId();
-  const columnMenuId: string = useId();
+  const columnMenuButtonId = `${column.field}-column-menu-button`;
```
Comment (DanailH) [inline packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:17]: This looks nice but the problem I think comes if the field starts with a number, then the id would not be valid.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:17]: It seems that it would also fail with two data grids with the same column name.

Comment (m4theushw) [reply packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:17]: > This looks nice but the problem I think comes if the field starts with a number, then the id would not be valid.

HTML5 removed this restriction. The [only](https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute) requirement left is to have more than one character. I'm open for the format of the calculated id, we could also use the field at the end.

> It seems that it would also fail with two data grids with the same column name.

This requires the alternative path I added in the description. We can create a random id for the column and store it in the state or we create a stable unique prefix for the entire grid and all ids.

Comment (dtassone) [reply packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:17]: We can also disable portal in popper and/or render the menu in a container.

What issue is the `Id` solving exactly? In the first implementation, there was no Id.

Comment (m4theushw) [reply packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:17]: > We can also disable portal in popper and/or render the menu in a container.

I didn't understand. Even without the portal we need to set `aria-labelledby`.

> What issue is the Id solving exactly? In the first implementation, there was no Id.

Currently, the user has to pass an id and aria-labelledby to `apiRef.current.showColumn` or the screen reader won't read the menu label. This PR removes the need to pass these arguments.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:17]: > What issue is the Id solving exactly? In the first implementation, there was no Id.

@dtassone The first implementation was, more or less saying: "a11y, I don't care". The id allows linking the popup with its action and vice-versa. https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:17]: > HTML5 removed this restriction.

@m4theushw To some extend, try this command: `document.querySelector('.121')` or `document.querySelector('#121')`, it fails.

Comment (m4theushw) [reply packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:17]: > To some extent, try this command: document.querySelector('.121') or document.querySelector('#121'), it fails (tested on Chrome and Safari).

@oliviertassinari Good to know. `document.querySelector` requires a valid CSS selector and `#123` is valid in HTML5 but not in CSS. `document.getElementById('123')` doesn't throw any error. Anyway, I'll put the field at the end.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx:17]: For the solution, IMHO, the cleanest solution is to change the structure. I think that each header column icon should have its own column menu. It shouldn't be shared. Compare the UX between https://elastic.github.io/eui/#/tabular-content/data-grid and ours when opening multiple column menu. If we change the structure, then it becomes trivial to share the same id with `useId()`.

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
The column menu doesn't close on click away

**Comment by m4theushw** [comment]
> The column menu doesn't close on click away

Same cause of #1618. #1628 has to be merged first.

**Comment by dtassone** [comment]
> > The column menu doesn't close on click away
> 
> Same cause of #1618. #1628 has to be merged first.

I will merge #1513  first as it is touching all this area as well

File: packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx [hunk 2]
```diff
@@ -214,6 +229,17 @@ export const GridColumnHeaderItem = React.memo(
...
         />
+        <GridColumnHeaderMenu
+          columnMenuId={columnMenuId}
+          columnMenuButtonId={columnMenuButtonId}
+          field={column.field}
+          open={columnMenuOpen}
+          target={iconButtonRef.current}
+          ContentComponent={apiRef!.current.components.ColumnMenu}
+          contentComponentProps={{
+            ...apiRef!.current.componentsProps?.columnMenu,
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx:240]: this will create a new ref at every render? Why do we need to clone it?

Comment (m4theushw) [reply packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx:240]: I'm not creating a ref at every render, their values are kept across renders. Could you be more specific about the clone problem? I can't see it.

Comment (dtassone) [reply packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx:240]: if GridColumnHeaderMenu is memoized then it will be broken because you pass a new contentComponentProps every time the GridColumnHeaderItem renders
Why do you clone?

Comment (m4theushw) [reply packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx]: It was already there when I moved from GridComponent. It was added in [this](https://github.com/mui-org/material-ui-x/pull/890/files?file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx#diff-7b46969348f36dfdd1132e097c59264a6f22eb1fb68eb881aa02e999e45d1122R127) PR to merge with other props, then these other props were removed in [this commit](https://github.com/mui-org/material-ui-x/commit/169ba3e94b42f5c15764c0925064544e90a9f7d8#diff-7b46969348f36dfdd1132e097c59264a6f22eb1fb68eb881aa02e999e45d1122L132) but the clone didn't. I removed the clone now since it's not needed anymore.

**Review by dtassone — APPROVED** [review]
