### PR TITLE
[DataGrid] Add component slots for toolbar and preference panel

### LINKED ISSUE #946: [XGrid] Column Selector breaks within a Custom Toolbar
When Rendering <GridToolbar /> Within a custom toolbar, the column selector modal no longer opens. The column density modal still opens and works fine.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

- The column chooser button is clicked, and it's associated modal does not open. However the column density modal still function as expected.

## Expected Behavior 🤔

- The column chooser functions the same when rendered in a custom toolbar.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-ui-issue-latest-forked-lnexl?file=/src/Demo.js

Steps:

1. Create a custom toolbar component, render <GridComponent /> within Custom Toolbar
2. Render CustomToolbar in XGrid Header
3. Click Column Chooser button.

## Context 🔦

We need several custom components rendered inside the toolbar component, including a custom filter component, and some action buttons associated to the table. We also want to utilize the built in column chooser and density functionality, and be able to render all these components in a single toolbar.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 84.0.2
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/icons: ^4.9.1 => 4.9.1 
    @material-ui/lab: ^4.0.0-alpha.56 => 4.0.0-alpha.56 
    @material-ui/pickers: ^3.2.10 => 3.2.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.10.2 
    @material-ui/x-grid: ^4.0.0-alpha.18 => 4.0.0-alpha.18 
    @material-ui/x-license:  4.0.0-alpha.18 
    @types/react:  16.9.43 
    react: ^16.14.0 => 16.14.0 
    react-dom: ^16.14.0 => 16.14.0 
    styled-components: ^5.2.1 => 5.2.1 
```
</details>

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #946 

As we discussed I added 2 new component slots, one for the `Toolbar` and one for the `PreferencePanel`. I didn't move them out of the header, we can keep them as they are for now and if we find that the `Header` is not needed we can remove it and restructure it. The end result is that now you can overwrite the toolbar but still keep the OTB preference panel so the columns selector and filters functionality still works when opened from the column menu.

I've removed the `Header` slot component as mentuned below.

Also, the `Toolbar` doesn't have a default value of `GridToolbar`, meaning that if developers want to enable it they will have to provide it to the grid. This is needed for the https://github.com/mui-org/material-ui-x/issues/726 ticket.

I've only updated some of the stories and examples in the doc. If we agree with the approach I'll fix the rest of them in this PR.

PS: Tests might be failing due to the change for the toolbar!

To Do:
- [x] Fix the failing tests.
- [x] Fix the rest of the doc examples and Storybook stories.

### CODE REVIEW

File: docs/src/pages/components/data-grid/rendering/VisibleToolbarGrid.tsx [hunk 1]
```diff
@@ -11,7 +11,13 @@ export default function VisibleToolbarGrid() {
 
   return (
     <div style={{ height: 300, width: '100%' }}>
-      <DataGrid {...data} showToolbar />
+      <DataGrid
+        {...data}
+        components={{
+          Toolbar: GridToolbar,
+        }}
+        showToolbar
```
Comment (oliviertassinari) [inline docs/src/pages/components/data-grid/rendering/VisibleToolbarGrid.tsx:19]: I assume it's no longer needed, proving a component to the slot take this purpose. 

```suggestion
```

File: packages/storybook/src/stories/grid-toolbar.stories.tsx [hunk 2]
```diff
@@ -18,7 +18,15 @@ export const DensitySelectorCompact = () => {
 
   return (
     <div style={{ height: 600 }}>
-      <XGrid rows={data.rows} showToolbar columns={data.columns} density="compact" />
+      <XGrid
+        rows={data.rows}
+        components={{
+          Toolbar: GridToolbar,
+        }}
+        showToolbar
```
Comment (oliviertassinari) [inline packages/storybook/src/stories/grid-toolbar.stories.tsx:26]:
```suggestion
```

File: packages/grid/_modules_/grid/models/gridSlotsComponent.ts [hunk 3]
```diff
@@ -96,6 +105,7 @@ export const DEFAULT_SLOTS_COMPONENTS: ApiRefComponentsProperty = {
   ErrorOverlay,
   Footer: GridFooter,
   Header: GridHeader,
+  PreferencesPanel,
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/gridSlotsComponent.ts:108]:
```suggestion
  PreferencesPanel: GridPreferencesPanel
```

**Review by oliviertassinari — COMMENTED** [review]
It seems to go in the right direction. I would also encourage we don't mention the header, at all, making it a private thing (removing it from the docs, components prop, etc.)

File: docs/src/pages/components/data-grid/rendering/VisibleToolbarGrid.tsx (hunk 1 above)
Comment (DanailH) [reply docs/src/pages/components/data-grid/rendering/VisibleToolbarGrid.tsx:19]: We still do, the change where this is no longer needed is in the other PR https://github.com/mui-org/material-ui-x/pull/948. We decided to do it incrementally as far as I remember.

Comment (oliviertassinari) [reply docs/src/pages/components/data-grid/rendering/VisibleToolbarGrid.tsx:19]: OK, my bad

File: packages/grid/_modules_/grid/models/gridSlotsComponent.ts (hunk 3 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:108]: I can rename it, not a problem. I saw that there are other components that don't have the `Grid` suffix. If agree that this will be what we will do from now one I'm ok with it.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:108]: We treat all the exported modules of Material-UI as a unique namespace, as AWS does with its code. Developers should be able to search for it without landing on potential different components. If there a chance that the component might collide, with another, it needs to be prefixed for uniqueness. This applies to even the types.

Comment (DanailH) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:108]: Ok, but that means that some of the others (maybe even all) that are here https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/models/gridSlotsComponent.ts#L99-L104 would need to be renamed.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:102]: Ok, let's do it in a different effort. We have https://github.com/mui-org/material-ui-x/issues/131 to track it.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:102]: I have made the same comment in https://github.com/mui-org/material-ui-x/pull/969#pullrequestreview-580841832.

File: packages/grid/_modules_/grid/GridComponent.tsx [hunk 4]
```diff
@@ -119,7 +120,7 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
                 )}
               >
                 <div ref={headerRef}>
-                  <components.Header {...componentBaseProps} {...props.componentsProps?.header} />
+                  <GridHeader />
```
Comment (dtassone) [inline packages/grid/_modules_/grid/GridComponent.tsx:123]: I don't think we agreed on removing the header slot?

File: packages/grid/data-grid/src/tests/toolbar.DataGrid.test.tsx [hunk 5]
```diff
@@ -55,7 +55,14 @@ describe('<DataGrid /> - Toolbar', () => {
       const rowHeight = 30;
       const { getByText } = render(
         <div style={{ width: 300, height: 300 }}>
-          <DataGrid {...baselineProps} showToolbar rowHeight={rowHeight} />
+          <DataGrid
+            {...baselineProps}
+            showToolbar
```
Comment (dtassone) [inline packages/grid/data-grid/src/tests/toolbar.DataGrid.test.tsx:60]: I thought we wanted to remove showToolbar

Comment (oliviertassinari) [reply packages/grid/data-grid/src/tests/toolbar.DataGrid.test.tsx:60]: See https://github.com/mui-org/material-ui-x/pull/971#discussion_r568587680

File: packages/grid/_modules_/grid/GridComponent.tsx (hunk 4 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/GridComponent.tsx:123]: If you remove the header we are back to the same point and conversations where you remove the flexibility of moving components around and rendering them in other container...

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/GridComponent.tsx:123]: > If you remove the header we are back to the same point and conversation where you remove the flexibility of moving components around and rendering them in other container...

To which point I don't think is true. Hence the undocumentation path to prove it with having the option to quickly introduce it back (documenting)

Comment (DanailH) [reply packages/grid/_modules_/grid/GridComponent.tsx:123]: Ok my bad, I removed it because of 

> It seems to go in the right direction. I would also encourage we don't mention the header, at all, making it a private thing (removing it from the **docs**, components prop, etc.)

Ok my bad, I'll revert it and only remove it from the docs. I guess I got confused because of "component prop" 
got mentioned. I got left with the impression that the end goal here is to completely remove that component so in the end, we will have the following structure:

```
<DataGrid>
  <GridToolbar />
  <PreferencePanel />
  
  -- EVERYTHING ELSE --
</DataGrid>

**Comment by DanailH** [comment]
Ok if we agree with the slots I'll go and update the docs and the examples so we can move to the other PR.

File: docs/src/pages/components/data-grid/rendering/CustomToolbarGrid.tsx [hunk 6]
```diff
@@ -17,7 +17,7 @@ export default function CustomToolbarGrid() {
     <div style={{ height: 400, width: '100%' }}>
       <DataGrid
         components={{
-          Header: CustomToolbar,
+          Toolbar: CustomToolbar,
```
Comment (oliviertassinari) [inline docs/src/pages/components/data-grid/rendering/CustomToolbarGrid.tsx:20]: Great, thanks for fixing this demo 🙏

File: docs/src/pages/components/data-grid/columns/ColumnSelectorGrid.tsx [hunk 7]
```diff
@@ -11,7 +11,13 @@ export default function ColumnSelectorGrid() {
...
   return (
     <div style={{ height: 400, width: '100%' }}>
-      <DataGrid {...data} showToolbar />
+      <DataGrid
+        {...data}
+        showToolbar
+        components={{
+          Toolbar: GridToolbar,
+        }}
+      />
```
Comment (oliviertassinari) [inline docs/src/pages/components/data-grid/columns/ColumnSelectorGrid.tsx:20]: A side note, now I understand why I got confused by the presence of the `showToolbar` prop. I wasn't expecting any changes in this demo. It looks like we anticipate the next change. But it's actually unrelated to the value proposition of fixing #946. It's fine for this time, I only wanted to clarify it.

File: packages/grid/_modules_/grid/models/api/componentsApi.ts [hunk 8]
```diff
@@ -19,6 +19,14 @@ export interface ApiRefComponentsProperty extends GridIconSlotsComponent {
    * Header component rendered above the grid column header bar.
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/api/componentsApi.ts:19]: How about this change too?

```suggestion
   * Prefer using the `Toolbar` slot. You should never need to use this slot. TODO remove.
```

It effectively creates a constraint to test if we can get away without it. While we don't have yet enough usage to know, I can guarantee you that with the type of scale we can expect from the component, if it's useful (solving a problem better than any alternative), developers will surface it. I think that we can reevaluate in 6 months.

**Review by oliviertassinari — APPROVED** [review]

File: docs/src/pages/components/data-grid/columns/ColumnSelectorGrid.tsx (hunk 7 above)
Comment (DanailH) [reply docs/src/pages/components/data-grid/columns/ColumnSelectorGrid.tsx:20]: Ok, yes I could have left the default toolbar still there but instead, I removed it, I figured it is ok since that was what we discussed when we were refining the ticket. I can reintroduce it if we want to be as granular as possible and remove it in the other PR.

File: packages/grid/_modules_/grid/models/api/componentsApi.ts (hunk 8 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/models/api/componentsApi.ts:19]: Agree, it will be easier to track.

File: packages/grid/_modules_/grid/models/gridSlotsComponent.ts [hunk 9]
```diff
@@ -51,6 +52,14 @@ export interface GridSlotsComponent extends GridIconSlotsComponent {
    * Header component rendered above the grid column header bar.
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/models/gridSlotsComponent.ts:52]: Why do we duplicate the component keys? Shouldn't we have a single source of truth?

```suggestion
   * Prefer using the `Toolbar` slot. You should never need to use this slot. TODO remove.
```

Comment (DanailH) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:52]: As far as I can see the only difference is that here there are optional. Maybe we can just use `Partial` to achieve that @dtassone?

Comment (dtassone) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:52]: It used to map the components with the base props

File: docs/src/pages/components/data-grid/rendering/rendering.md [hunk 10]
```diff
@@ -258,15 +258,15 @@ You can disable column virtualization by setting the column buffer to a higher n
 
 As part of the customization API, the grid allows you to replace and override nested components with the `components` prop. The prop accepts an object with the following keys:
 
-- `header`: The component rendered above the column header bar.
+- `toolbar`: The component rendered above the column header bar.
```
Comment (dtassone) [inline docs/src/pages/components/data-grid/rendering/rendering.md:261]: That's gone. You should rebase and update the api slots page

Comment (DanailH) [reply docs/src/pages/components/data-grid/rendering/rendering.md]: Done, I've updated the API pages as well.

**Review by oliviertassinari — APPROVED** [review]

File: docs/src/pages/components/data-grid/rendering/rendering.md [hunk 11]
```diff
@@ -256,13 +256,8 @@ You can disable column virtualization by setting the column buffer to a higher n
...
 
-As part of the customization API, the grid allows you to replace and override nested components with the `components` prop. The prop accepts an object with the following keys:
-
-- `toolbar`: The component rendered above the column header bar.
-- `loadingOverlay`: The component rendered when the loading react prop is set to true.
-- `noRowsOverlay`: The component rendered when the rows react prop is empty or [].
-- `footer`: The component rendered below the viewport.
-- `pagination`: The component rendered for the pagination feature.
+As part of the customization API, the grid allows you to replace and override nested components with the `components` prop.
+The prop accepts an object of type [GridSlotsComponent](/api/data-grid/#slots) .
```
Comment (dtassone) [inline docs/src/pages/components/data-grid/rendering/rendering.md:260]: Why do you have this changes? You should just revert this file

File: packages/grid/_modules_/grid/models/gridSlotsComponent.ts [hunk 12]
```diff
@@ -46,7 +46,7 @@ export interface GridSlotsComponent extends GridIconSlotsComponent {
    */
   Footer?: React.ElementType<BaseComponentProps>;
   /**
-   * Header component rendered above the grid column header bar.
+   * Prefer using the `Toolbar` slot. You should never need to use this slot. TODO remove.
```
Comment (dtassone) [inline packages/grid/_modules_/grid/models/gridSlotsComponent.ts:49]: I think you can leave the previous description and add that sentence after 🤔

File: docs/src/pages/components/data-grid/rendering/rendering.md (hunk 11 above)
Comment (DanailH) [reply docs/src/pages/components/data-grid/rendering/rendering.md:260]: I pulled from master, that's what I got from it.

Comment (DanailH) [reply docs/src/pages/components/data-grid/rendering/rendering.md:260]: These are not marked as changes in the diff

File: docs/pages/api-docs/x-grid.md [hunk 13]
```diff
@@ -84,7 +84,8 @@ Api of the `components` props of type `GridSlotsComponent`
...
 | <span class="prop-name">FilterPanel</span> | <span class="prop-type">React.ElementType&lt;BaseComponentProps></span> | <span class="prop-type">FilterPanel</span> | Filter panel component rendered when clicking the filter button.|
 | <span class="prop-name">Footer</span> | <span class="prop-type">React.ElementType&lt;BaseComponentProps></span> | <span class="prop-type">GridFooter</span> | Footer component rendered at the bottom of the grid viewport.|
-| <span class="prop-name">Header</span> | <span class="prop-type">React.ElementType&lt;BaseComponentProps></span> | <span class="prop-type">GridHeader</span> | Header component rendered above the grid column header bar.|
+| <span class="prop-name">Toolbar</span> | <span class="prop-type">React.ElementType&lt;BaseComponentProps></span> | <span class="prop-type">GridToolbar</span> | Toolbar component rendered above the grid column header bar.|
+| <span class="prop-name">PreferencesPanel</span> | <span class="prop-type">React.ElementType&lt;BaseComponentProps></span> | <span class="prop-type">PreferencesPanel</span> | PreferencesPanel component rendered above the grid toolbar component slot.|
```
Comment (dtassone) [inline docs/pages/api-docs/x-grid.md:88]: `PreferencesPanel component rendered above the grid toolbar component slot.`
It's not rendered above. 
Component that render the ColumnSelector or FilterPanel within a Panel component.

Comment (DanailH) [reply docs/pages/api-docs/x-grid.md]: Done

File: packages/grid/_modules_/grid/models/gridSlotsComponent.ts (hunk 12 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/models/gridSlotsComponent.ts:50]: done

**Review by dtassone — APPROVED** [review]

**Comment by max4211** [comment]
I am trying to customize the Grid Header/Toolbar using my own component. However, when I add my own button the **Filters** and **Columns** buttons no longer work. 

Wondering if you have any pointers on how to fix this? Thank you!

```js
        components={{
          Header: () => (
            <>
              {handleExport && <Button onClick={handleExport} className="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-textSizeSmall MuiButton-sizeSmall">Export</Button>}
              <FilterToolbarButton />
              <ColumnsToolbarButton />
              <DensitySelector />
            </>
          ),
        }}
```

**Comment by oliviertassinari** [comment]
@max4211 Thanks for raising this pain point. We plan to better document the composability of the toolbar in #1037. Now, the approach is changing a bit with v4.0.0-alpha.20. 

> However, when I add my own button the Filters and Columns buttons no longer work.

Yeah, this sounds very much like #946
