### PR TITLE
[DataGrid] GridPreferencesPanel accessibility fixes

### LINKED ISSUE #880: [DataGrid] Escape should close popup
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Pressing <kbd>Escape</kbd> when the popup is open doesn't close it.

## Expected Behavior 🤔

Pressing <kbd>Escape</kbd> when the popup is open closes it.

## Steps to Reproduce 🕹

Steps:

1. Open https://master--material-ui-x.netlify.app/components/data-grid/columns/#column-selector
2. Click on "Filters" in the toolbar
3. Press <kbd>Escape</kbd>.

## Context 🔦

It seems to be a common UX pattern. There will likely be a challenge around how to filter the events that don't need to be handled from the ones that do. Maybe we can be overzealous and handle any escape event that bubbles up to the document.

## Your Environment 🌎

`@material-ui/data-grid@v4.0.0-alpha.17`

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #880 

- PreferencePanel escape not working
- PreferencePanel focus, <TrapFocus disableEnforceFocus />

### CODE REVIEW

**Review by dtassone — APPROVED** [review]

File: packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx [hunk 1]
```diff
@@ -18,5 +22,9 @@ export function GridPanelWrapper(
 ) {
   const classes = useStyles();
   const { className, ...other } = props;
-  return <div className={classnames(classes.root, className)} {...other} />;
+  return (
+    <TrapFocus open disableEnforceFocus isEnabled={() => true} getDoc={() => document}>
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx:26]: getDoc is used to get the active element is the window the data grid is rendered. The current logic fails if rendered in a popup, iframe, else. @dtassone do you want the grid to support windows different from the main one?

**Review by oliviertassinari — COMMENTED** [review]
Funny how we are working on the same problem, I was just commenting on the missing focus visible in https://github.com/mui-org/material-ui/issues/19149#issuecomment-784206077.

File: packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx (hunk 1 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx:26]: yes we should support iframe popup...
Storybook uses iframe

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx:26]: > Storybook uses iframe

In storybook, the iframe is the main window. It's not the same case.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx:26]: Ok, then we can create a new issue for it. We don't support it, e.g. enable the iframe in the first demo and see how it renders:

```diff
diff --git a/docs/src/pages/components/data-grid/overview/overview.md b/docs/src/pages/components/data-grid/overview/overview.md
index 41ee8b90..3aaf44ca 100644
--- a/docs/src/pages/components/data-grid/overview/overview.md
+++ b/docs/src/pages/components/data-grid/overview/overview.md
@@ -29,7 +29,7 @@ This abstraction also set constraints that allow the component to implement new
 import { DataGrid } from '@material-ui/data-grid';
 ```

-{{"demo": "pages/components/data-grid/overview/DataGridDemo.js", "defaultCodeOpen": false, "bg": "inline"}}
+{{"demo": "pages/components/data-grid/overview/DataGridDemo.js", "defaultCodeOpen": false, "bg": "inline", "iframe": true}}

 ### Commercial version [<span class="pro"></span>](https://material-ui.com/store/items/material-ui-pro/)
```

<img width="830" alt="Screenshot 2021-02-23 at 14 58 33" src="https://user-images.githubusercontent.com/3165635/108854079-bd5fcf00-75e7-11eb-916b-e5fda9e0477d.png">

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx:26]: keyboard navigation is not working, menu container is not the current window, arrow alignment is wrong. I can imagine there are more issues.

**Review by oliviertassinari — APPROVED** [review]
Approving as iframe support seems to be a wider problem. While we support it with the core components. I'm not sure it makes a lot of sense for the advanced ones. At least, I would be eager to see people complain first

File: packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx (hunk 1 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx:26]: Ok this is because of the `getDoc={() => document}` part and if we load it in an iframe right? Should we expand the use case to make it work. I didn't catch it in the docs nor in the storybook demos.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx:26]: I think that we should ignore the problem, until it's surfaced by actual users. 

I'm confident that if we need to solve the problem, we will technically be able to. Even in the core, I have recently fixed one of the component support for it. It's rare developers ask for it.

If we take the arcade game analogie, this is a level 100 boss, we are still at level 25.

Comment (DanailH) [reply packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx:26]: I like the analogy 😅

**Comment by oliviertassinari** [comment]
We could have added a test case, but it's not a major feature. Time will tell if we have a regression.
