### PR TITLE
[DataGrid] Forward props for all Toolbar and Footer components

### LINKED ISSUE #1369: [DataGrid] Forward props in public API
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The props provided to the public components are swallowed. See the following components:

- https://github.com/mui-org/material-ui-x/blob/25edafedf67bea45f6c6ed15281f3ba8f9b6b65e/packages/grid/_modules_/grid/components/toolbar/GridToolbarExport.tsx#L12
- https://github.com/mui-org/material-ui-x/blob/25edafedf67bea45f6c6ed15281f3ba8f9b6b65e/packages/grid/_modules_/grid/components/toolbar/GridColumnsToolbarButton.tsx#L9
- https://github.com/mui-org/material-ui-x/blob/25edafedf67bea45f6c6ed15281f3ba8f9b6b65e/packages/grid/_modules_/grid/components/toolbar/GridDensitySelector.tsx#L17
- https://github.com/mui-org/material-ui-x/blob/25edafedf67bea45f6c6ed15281f3ba8f9b6b65e/packages/grid/_modules_/grid/components/toolbar/GridFilterToolbarButton.tsx#L16
- I didn't find more.

## Expected Behavior 🤔

The props provided to the public components should be forwarded and applied as attributes on the root element. Same for the ref. Can also remove `React.FC` as it's not correct.

## Steps to Reproduce 🕹

- Open https://codesandbox.io/s/material-demo-forked-vyg0z?file=/demo.tsx
- `<GridToolbarExport className="foo" data-testid="export" />` is not working

## Context

This is a follow-up on #1252, #1116

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #1369 

This PR aims to finalize the forwarding for props in the public API components. We seemed to have missed the components in the Toolbar and Footer. This change aims to fix that.

Changed components:
- GridRowCount
- GridSelectedRowCount
- GridColumnsToolbarButton
- GridDensitySelector
- GridToolbarExport

### CODE REVIEW

**Review by oliviertassinari — APPROVED** [review]
Looks good, disabling the whitespace helps during the review: https://github.com/mui-org/material-ui-x/pull/1456/files?diff=unified&w=1.

**Comment by DanailH** [comment]
https://github.com/mui-org/material-ui-x/pull/1436 should be merged before that one.

File: packages/grid/_modules_/grid/components/GridRowCount.tsx [hunk 1]
```diff
@@ -1,20 +1,26 @@
...
 
-export interface GridRowCountProps {
+interface RowCountProps {
   rowCount: number;
 }
 
-export const GridRowCount = (props: GridRowCountProps) => {
-  const { rowCount } = props;
-  const apiRef = React.useContext(GridApiContext);
+type GridRowCountProps = React.HTMLAttributes<HTMLDivElement> & RowCountProps;
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/GridRowCount.tsx:9]: A side note: https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections
