### PR TITLE
[DataGrid] Fix iOS issue when scrolling left

### LINKED ISSUE #269: [DataGrid] iOS scroll stretching issue
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

On iOS, a end-user can stretch the scrollbar. When he does, the cells become invisible.

## Expected Behavior 🤔

Grid rendering on iOS is OK.

## Steps to Reproduce 🕹

1. Open https://master--material-ui.netlify.app/components/data-grid/#commercial-version on iSO
2.

stretch

## Context 🔦

I was writing documentation on virtualization.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v0.1.67  |

### PR DESCRIPTION
**Pull request by DanailH**
This PR fixes an iOS scroll stretching issue that is visible when the user tries to scroll left while the grid is at the left position of 0. The issue occurs because when you scroll on an IOS device a scroll event is fired even if there is no space to scroll in that direction (scroll bouncing).

The fix is achieved by checking the `event.target.scrollLeft` and if it is < 0 prevent the update of the viewport.

Fixes #269

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts [hunk 1]
```diff
@@ -206,6 +206,8 @@ export const useVirtualRows = (
   const scrollingTimeout = React.useRef<any>(0);
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:206]:
```suggestion
  const scrollingTimeout = React.useRef<number>(0);
```

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts [hunk 2]
```diff
@@ -206,6 +206,8 @@ export const useVirtualRows = (
...
   const onScroll: any = React.useCallback(
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:207]:
```suggestion
  const handleScroll = React.useCallback(
```

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts [hunk 3]
```diff
@@ -206,6 +206,8 @@ export const useVirtualRows = (
...
     (event: any) => {
+      if (event.target.scrollLeft < 0) return;
+
       realScrollRef.current = { left: event.target.scrollLeft, top: event.target.scrollTop };
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:211]: The scroll event doesn't bubble, it might be clearer like this.

```suggestion
      realScrollRef.current = { left: windowRef.current!.scrollLeft, top: windowRef.current!.scrollTop };
```

**Review by oliviertassinari — COMMENTED** [review]
What about the vertical scrolling?

I have left a couple of [boy scout](https://deviq.com/boy-scout-rule/) comments

**Review by dtassone — APPROVED** [review]

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts [hunk 4]
```diff
@@ -206,6 +206,8 @@ export const useVirtualRows = (
   const scrollingTimeout = React.useRef<any>(0);
   const onScroll: any = React.useCallback(
     (event: any) => {
+      if (event.target.scrollLeft < 0) return;
```
[the remark this answers is not in the document]
Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:209]: P.S. now I get why ag-Grid RTL was broken last month. Chrome 85 released an update the made them adapt to the latest spec for handling scrollLeft on rtl. On Material-UI side, we didn't see any impact because we feature detect the mode. ag-Grid was using a user-agent logic. I guess it's a reminder that testing user-agent isn't as great as doing feature support detection.

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
need to handle vertical scrolling too

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts (hunk 1 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:206]: Ok, so I had the same issue with the `useColumnsReorder` hook. I guess because this is not inside a `.jsx` file the typings get confused and it says that this is not a number, the solution to this is to predefine it with `widow.`, then it works like this. And of course, the other solution is to type it as `NodeJS.SetTimeout` but that also looks a bit weird.

PS: I managed to fix it in the `useColumnsReorder` hook by removing the second param of the `setTimeout` but I was able to do it because for me it was `0`, here it has a value of `300` so we cant remove it. I suggest to leave it like this.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:206]: > `.jsx`

We have forbidden this extension. The allowed ones are `.js`/`.ts`/`.tsx`.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:206]: > And of course, the other solution is to type it as NodeJS.SetTimeout but that also looks a bit weird.

I don't think that we should ever use this approach. It's false. The type is always a number.

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts (hunk 3 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts]: Done, even better, we don't need the `event` at all as I also used `windowRef.current!.scrollLeft` to fix the IOS bug.

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts (hunk 2 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts]: done

**Comment by DanailH** [comment]
> need to handle vertical scrolling too

I added additional check for vertical scrolling. It suffered from the same problem.

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts [hunk 5]
```diff
@@ -204,21 +204,23 @@ export const useVirtualRows = (
...
-    [apiRef, updateViewport, scrollingTimeout, realScrollRef],
-  );
+  const handleScroll = React.useCallback(() => {
+    if (windowRef.current!.scrollLeft < 0 || windowRef.current!.scrollTop < 0) return;
+
+    realScrollRef.current = {
+      left: windowRef.current!.scrollLeft,
+      top: windowRef.current!.scrollTop,
+    };
+    if (scrollingTimeout.current === 0) {
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:214]:
```suggestion
    if (!scrollingTimeout.current) {
```

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts [hunk 6]
```diff
@@ -204,21 +204,23 @@ export const useVirtualRows = (
...
+      apiRef.current.publishEvent(SCROLLING_START);
+    }
+    clearTimeout(scrollingTimeout.current);
+    scrollingTimeout.current = setTimeout(() => {
+      scrollingTimeout.current = 0;
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:219]:
```suggestion
      scrollingTimeout.current = null;
```

**Review by oliviertassinari — APPROVED** [review]
I have observed 4 other different rendering issues on iOS, but that for another day.

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts [hunk 7]
```diff
@@ -204,21 +204,23 @@ export const useVirtualRows = (
...
-      scrollingTimeout.current = setTimeout(() => {
-        scrollingTimeout.current = 0;
-        apiRef.current.publishEvent(SCROLLING_STOP);
-      }, 300);
-      updateViewport();
-    },
-    [apiRef, updateViewport, scrollingTimeout, realScrollRef],
-  );
+  const handleScroll = React.useCallback(() => {
+    if (windowRef.current!.scrollLeft < 0 || windowRef.current!.scrollTop < 0) return;
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:208]:
```suggestion
    // On iOS the inertia scrolling allow to return negative values. 
    if (windowRef.current!.scrollLeft < 0 || windowRef.current!.scrollTop < 0) return;
```

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts (hunk 5 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts]: Done

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts (hunk 6 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts]: Done

**Review by oliviertassinari — APPROVED** [review]
