### PR TITLE
[DataGrid] Reset sortedRows state on prop change

### LINKED ISSUE #575: [DataGrid] "Cannot read property 'id' of undefined" when rows update
I submitted a ticket to zendesk first and was asked to create an issue here. I was also told this is similar to issue #571  

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I'm working with XGrid and since the Filter feature is not yet available, I'm trying to implement it manually, but I keep getting this error (see screenshot and screen recording bellow) and can't figure out what I'm doing wrong. Essentially what I do is re render all the rows (like in the docs https://material-ui.com/components/data-grid/rows/#the-rows-prop).

Screen Shot 2020-11-12 at 3 25 07 PM

Hnet com-image

## Expected Behavior 🤔

Updating rows and/or columns should work as expected without error.

## Steps to Reproduce 🕹

Tried to reproduce but it's kind of hard to reproduce all the condition since all of the data is brought from a backend, but this [CodeSandbox](https://codesandbox.io/s/youthful-elgamal-gzzl4?file=/src/App.js) link is more or less how I manage the data.

Steps:

1. The rows array get 're calculated' causing the re render. The rows are fewer than before (trying to actually implement Filtering feature manually)
2. Error occurs

## Context 🔦

Basically implement Filtering feature manually.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.8|
| React         |    ^16.13.1     |
| Browser       |    Chrome     |
| TypeScript    |     yes   |

### PR DESCRIPTION
**Pull request by dtassone**
Fix #575

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/sorting/useSorting.ts [hunk 1]
```diff
@@ -236,6 +236,14 @@ export const useSorting = (apiRef: ApiRef) => {
   const sortApi: SortApi = { getSortModel, setSortModel, onSortModelChange, applySorting };
   useApiMethod(apiRef, sortApi, 'SortApi');
 
+  React.useEffect(() => {
+    // When the rows prop change, we reset the sortedRows state.
+    setGridState((state) => ({
+      ...state,
+      sorting: { ...state.sorting, sortedRows: rowsProp.map((row) => row.id) },
+    }));
+  }, [apiRef, forceUpdate, rowsProp, setGridState]);
```
Comment (DanailH) [inline packages/grid/_modules_/grid/hooks/features/sorting/useSorting.ts:245]: Why do we need the `apiRef` and the `forceUpdate` here as a dependency? You only want to run this if the `rowsProp` changes right?

Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/sorting/useSorting.ts:245]: Nicely spotted :)
I forgot them when I was trying other possibilities

File: packages/grid/x-grid/src/XGrid.test.tsx [hunk 2]
```diff
@@ -220,6 +220,47 @@ describe('<XGrid />', () => {
       fireEvent.click(header);
       expect(getColumnValues()).to.deep.equal(['Puma', 'Nike', 'Adidas']);
     });
+
+    it('should reset the sortedRows state when rows prop change', async () => {
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/XGrid.test.tsx:224]: The bug can be reproduced on the DataGrid: https://codesandbox.io/s/fancy-brook-hf3fw?file=/src/App.js.
So I think that the test should be in `DataGrid.test.tsx`.

Comment (oliviertassinari) [reply packages/grid/x-grid/src/XGrid.test.tsx:224]: I think that tests should be as end-to-ends as possible.

```suggestion
    it('should keep rows sorted when rows prop change', async () => {
```

File: packages/storybook/src/stories/grid-sorting.stories.tsx [hunk 3]
```diff
@@ -432,3 +435,58 @@ export const ServerSideSorting = () => {
...
+        onColumnHeaderClick={() => {}}
+        sortModel={[
+          {
+            field: 'name',
+            sort: 'asc',
+          },
+        ]}
+        components={{
+          noRowsOverlay: () => <GridOverlay>No Data</GridOverlay>,
+        }}
```
Comment (oliviertassinari) [inline packages/storybook/src/stories/grid-sorting.stories.tsx:488]: What is it for?
```suggestion
```

File: packages/grid/x-grid/src/XGrid.test.tsx [hunk 4]
```diff
@@ -220,6 +220,47 @@ describe('<XGrid />', () => {
...
+      interface TestCaseProps {
+        rows: any[];
+      }
+      let apiRef;
+      const TestCase = (props: TestCaseProps) => {
+        const { rows } = props;
+        apiRef = useApiRef();
+        return (
+          <div style={{ width: 300, height: 300 }}>
+            <XGrid {...defaultProps} rows={rows} apiRef={apiRef} />
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/XGrid.test.tsx:234]: I think that we should include the sort model to make sure it works:

```suggestion
            <XGrid {...defaultProps} rows={rows} apiRef={apiRef} sortModel={[
                {
                  field: 'brand',
                  sort: 'asc',
                },
              ]} />
```

**Review by oliviertassinari — CHANGES_REQUESTED** [review]

File: packages/grid/x-grid/src/XGrid.test.tsx [hunk 5]
```diff
@@ -220,6 +220,47 @@ describe('<XGrid />', () => {
...
+            id: 4,
+            brand: 'RedBull',
+          },
+          {
+            id: 5,
+            brand: 'Hugo',
+          },
+        ],
+      });
+      await raf(); // wait for the AutoSize's dimension detection logic
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/XGrid.test.tsx]: This is wrong. The await shouldn't be required, the comment is plain wrong

**Review by oliviertassinari — COMMENTED** [review]
`sortedRows` looks like an internal state that should be private. It's fully derived from the input rows and the sort configuration provided by users. Developers' changes to the state are overridden by the grid. So I don't think that any tests should assert it.

On a side note, I was surprised to see this state exist. I was assuming that we would have a "input row" state, as well as a "transformed row" state, the transformed one being computed from grouping, filtering, sorting, etc. It seems that the challenge is to make sure that each transformations is applied in the right order. I guess it can be resolved with a priority value.

File: packages/storybook/src/stories/grid-sorting.stories.tsx (hunk 3 above)
Comment (dtassone) [reply packages/storybook/src/stories/grid-sorting.stories.tsx:488]: yeah useless, I just dropped the codesandbox

**Comment by oliviertassinari** [comment]
Something is off, it jumps:

Nov-18-2020 11-53-39

It renders twice, shouldn't it render once?

```jsx
import * as React from 'react';
import { DataGrid } from '@material-ui/data-grid';

const TestCase = () => {
  const [rows, setRows] = React.useState([
    {
      id: 0,
      brand: 'Nike',
    },
    {
      id: 1,
      brand: 'Adidas',
    },
    {
      id: 2,
      brand: 'Puma',
    },
  ]);

  return (
    <div style={{ width: 300, height: 300 }}>
      <button onClick={() => {
        setRows([
          {
            id: 3,
            brand: 'Asics',
          },
          {
            id: 4,
            brand: 'RedBull',
          },
          {
            id: 5,
            brand: 'Hugo',
          },
        ]);
      }}>Swap</button>
      <DataGrid
        columns={[{ field: 'brand', width: 100 }]}
        rows={rows}
        sortModel={[
        {
          field: 'brand',
          sort: 'asc',
        },
      ]}
      />
    </div>
  );
};

export default TestCase;
```

**Review by oliviertassinari — APPROVED** [review]
At least we fixed the reported bug and we have a solid test in place, so why not defer a better solution to later. I suspect it will require a refactoring of the state. There is an issue with the control flow somewhere, it could be imperative calls that shouldn't be here, it could be missing dependencies, a desynchronization, no idea :).

File: packages/grid/_modules_/grid/hooks/features/sorting/useSorting.ts [hunk 6]
```diff
@@ -236,6 +236,14 @@ export const useSorting = (apiRef: ApiRef) => {
   const sortApi: SortApi = { getSortModel, setSortModel, onSortModelChange, applySorting };
   useApiMethod(apiRef, sortApi, 'SortApi');
 
+  React.useEffect(() => {
+    // When the rows prop change, we reset the sortedRows state.
+    setGridState((state) => ({
+      ...state,
+      sorting: { ...state.sorting, sortedRows: rowsProp.map((row) => row.id) },
```
[the remark this answers is not in the document]
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/sorting/useSorting.ts:243]: > At least we fixed the reported bug and we have a solid test in place, so why not defer a better solution to later. I suspect it will require a refactoring of the state. There is an issue with the control flow somewhere, it could be imperative calls that shouldn't be here, it could be missing dependencies, a desynchronization, no idea :).

I will fix it ;)

[the remark this answers is not in the document]
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/sorting/useSorting.ts]: Fixed

**Comment by oliviertassinari** [comment]
Nice :)
