### PR TITLE
[XGrid] Prevent headers from scrolling during reordering

### LINKED ISSUE #2132: [XGrid] The header looses alignment during reordering
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

the header is not aligned to the data cell when during the reordering of a column from the right end of the scrollable area to leave the scrollable area and release the dragged column there.

## Expected Behavior 🤔

The header remains aligned with the data cells.

## Steps to Reproduce 🕹

Steps:

1. Scroll the table to the right
2. Drag column
3. Scroll a couple of column to the left
4. Leave the scrollable area with that column being dragged
5. Released the column
6. Scroll to the right -- there should be misalignment with the data cells.

The steps are shown at the GIF from https://material-ui.com/components/data-grid/columns/#column-reorder (use the example on the page itself instead of codesandbox):
example_of_issue

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 11.4
  Binaries:
    Node: 14.15.3 - ~/.asdf/installs/nodejs/14.15.3/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.asdf/installs/nodejs/14.15.3/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: Not Found
    Firefox: 87.0
    Safari: 14.1.1
  npmPackages:
    @material-ui/core: 4.11.1 => 4.11.1 
    @material-ui/icons: 4.5.1 => 4.5.1 
    @material-ui/lab: 4.0.0-alpha.56 => 4.0.0-alpha.56 
    @material-ui/pickers: 3.1.2 => 3.1.2 
    @material-ui/styles: 4.11.1 => 4.11.1 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  17.0.0 
    react: 16.12.0 => 16.12.0 
    react-dom: 16.12.0 => 16.12.0 
    typescript: 4.2.3 => 4.2.3 

  Browser:
    Google Chrome Version 91.0.4472.114

```
</details>

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #2132 
Preview: https://deploy-preview-2154--material-ui-x.netlify.app/components/data-grid/demo/

This bug is a bit hard to reproduce. It happens almost randomly. It's caused because the `.MuiDataGrid-columnsContainer` div is, sometimes, also scrolling when dragging a column. However, its `scrollLeft` position should always be zero.

image

To be able to fix it, I had to find a reliable way to reproduce it. What I did was to change the `overflow: hidden` of `.MuiDataGrid-columnsContainer` to `overflow: auto` to see the scrollbar. Then, I did the following movement:

https://user-images.githubusercontent.com/42154031/125847679-7b8abd05-3f0b-4172-85a9-50fba44de21c.mp4

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts [hunk 1]
```diff
@@ -379,30 +379,31 @@ export const useGridVirtualRows = (apiRef: GridApiRef): void => {
...
+  useNativeEventListener(
+    apiRef,
+    () => apiRef.current?.columnHeadersContainerElementRef?.current,
+    GRID_SCROLL,
+    preventScroll,
   );
   useNativeEventListener(
     apiRef,
     () => apiRef.current?.columnHeadersContainerElementRef?.current?.parentElement,
     GRID_SCROLL,
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts:406]: This element is not scrollable, also looking at the origin of the regression, I don't see why we would need this.

```suggestion
```

**Review by oliviertassinari — COMMENTED** [review]
**Off-topic**. The logic is weird, I would rewrite it.

1. We have two hooks, one for the horizontal axis, one for the vertical axis, but here, we handle the rest of the scrollbar for both axes in the vertical axis.
2. We reset the scroll top on the column header, which is not meant to be scrollable in this direction.
2. Why do: preventDefault, return false, and stopPropagation? It doesn't do anything on the scroll event, AFAIK.
3. We call `useNativeEventListener`, shouldn't we use the event name plain, to avoid any possible confusion and mistakes?

```diff
diff --git a/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts b/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
index 18edc0db..b8094eda 100644
--- a/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
+++ b/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
@@ -396,7 +396,7 @@ export const useGridVirtualRows = (apiRef: GridApiRef): void => {
   useNativeEventListener(
     apiRef,
     () => apiRef.current?.renderingZoneRef?.current?.parentElement,
-    GRID_SCROLL,
+    'scroll',
     preventViewportScroll,
   );
   useNativeEventListener(
```

I'm unsubscribing

File: packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts (hunk 1 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts:406]: I didn't find any place where we change the `scrollLeft` of this element. I suspect it's caused because of the browser's behavior.

Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts:406]: > This element is not scrollable

https://www.stefanjudis.com/today-i-learned/elements-with-overflow-hidden-are-scrollable/

We could use `overflow: clip`:

image

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts:406]: To be clear, this line refers to this element: 

Capture d’écran 2021-07-17 à 01 07 35

Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts:406]: Ohh yes. I completely overlooked this.

**Review by oliviertassinari — APPROVED** [review]
👌
