### PR TITLE
[DataGrid] Improve sizing logic

### LINKED ISSUE #344: [DataGrid] Height increase in an endless loop
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When initializing a DataGrid, the height increases rapidly

## Expected Behavior 🤔

The size should be enough for the presented rows and not increase

## Steps to Reproduce 🕹

https://codesandbox.io/s/infallible-wave-3v0d2?file=/src/Demo.js

## Context 🔦

I'm trying to display the table :)

## Your Environment 🌎

See the codesandbox. Chrome 85.0.4183.102 on OSX.

I tried going back to 0.1.67, but that complains of a missing dependency 'styled-components'. Do I need to go back to a previous version of material-ui/core as well? If so, which?

### PR DESCRIPTION
**Pull request by oliviertassinari**
Closes #344. I have refactored AutoSizer from classes to hooks for free. It was interesting to dive into the logic and fix the integration with the grid (of course I have made mistakes during the migration that took me almost an hour to identify).

### CODE REVIEW

File: packages/grid/_modules_/grid/GridComponent.tsx [hunk 1]
```diff
@@ -161,7 +172,7 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
   );
 
   return (
-    <AutoSizerWrapper onResize={debouncedOnResize} style={{ height: 'unset', width: 'unset' }}>
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/GridComponent.tsx:164]: The fix is to remove `style={{ height: 'unset', width: 'unset' }}`

File: packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts [hunk 2]
```diff
@@ -28,10 +28,7 @@ import { useApiEventHandler } from '../root/useApiEventHandler';
 type UseVirtualRowsReturnType = Partial<RenderContextProps> | null;
 
 // TODO v5: replace with @material-ui/core/utils/useEnhancedEffect.
-const useEnhancedEffect =
-  typeof window !== 'undefined' && process.env.NODE_ENV !== 'test'
-    ? React.useLayoutEffect
-    : React.useEffect;
+const useEnhancedEffect = typeof window !== 'undefined' ? React.useLayoutEffect : React.useEffect;
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:31]: why do we need to use blocking useLayoutEffect when window is not available?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:31]: > If you use server rendering, keep in mind that neither useLayoutEffect nor useEffect can run until the JavaScript is downloaded. This is why React warns when a server-rendered component contains useLayoutEffect. To fix this, either move that logic to useEffect (if it isn’t necessary for the first render), or delay showing that component until after the client renders (if the HTML looks broken until useLayoutEffect runs).

https://reactjs.org/docs/hooks-reference.html#uselayouteffect

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:31]: The objective of using useLayoutEffect is to avoid displaying an intermediary state with an empty grid (useLayoutEffect needs to be opt-out on the server-side).

Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:31]: why not use it directly? Have you tried with just useEffect?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts:31]: useEffect would raise a warning: 

> If you use server rendering, keep in mind that neither useLayoutEffect nor useEffect can run until the JavaScript is downloaded. This is why React warns when a server-rendered component contains useLayoutEffect. To fix this, either move that logic to useEffect (if it isn’t necessary for the first render), or delay showing that component until after the client renders (if the HTML looks broken until useLayoutEffect runs).

https://reactjs.org/docs/hooks-reference.html#uselayouteffect

File: packages/grid/_modules_/grid/GridComponent.tsx [hunk 3]
```diff
@@ -119,6 +119,17 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
 
   const onResize = React.useCallback(
     (size: ElementSize) => {
+      if (process.env.NODE_ENV !== 'production') {
+        if (size.height === 0) {
+          console.error(
```
Comment (dtassone) [inline packages/grid/_modules_/grid/GridComponent.tsx:124]: why do we use console? How about the logger?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/GridComponent.tsx:124]: From what I understand, logger is for debugging in dev and prod. This warning is dev only and should never be tempered with.

Comment (dtassone) [reply packages/grid/_modules_/grid/GridComponent.tsx:124]: logger can be used with consumer implementation of logging. For example Buyan, seq logging..., using console will prevent the error going to those tools.
This error is dev only as there is the if condition on the env above, not because it uses the console.
BTW why is there a different behaviour bw dev and prod?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/GridComponent.tsx:124]: It's not obvious. They could be different interpretations of how to handle this case. A couple of thoughts:

1. React never console messages that aren't exceptions in production. I don't think that we should either for consistency with React and `@material-ui/core`. Removing `process.env.NODE_ENV !== 'production'` would break this constraint.
2. We could throw an error directly, however, this case isn't fatal. It could simply be coming from an intermediary state where the grid's container has no height.
3. We could use a console.warn instead of a console.error. No objections. I wasn't sure how important this should be considered. Considering the argument against throwing, console.warn could be better.
4. We never use `logger.warn` yet.
5. We only use `logger.error` once, in the ErrorBoundary. IMHO, we shouldn't have an ErrorBoundary. It's too opinionated for any shared UI components to handle. It breaks the default error forwarding flow. It's also very simple to implement a demo in the docs should be enough. So far, we decided to try it out and see the feedback we get from developers.
6. The only case I see it would make sense to use the logger here is if we want to output this warning in production too without logging it in the console (per 1. only in dev). I don't have a specific point of view on that. Why not. IMHO, 80% of the value of this warning is for configuring the grid, to reduce the onboarding friction as much as possible.

Comment (dtassone) [reply packages/grid/_modules_/grid/GridComponent.tsx:124]: How about we go for a logger.warn without the env check?
So if users decide to not care about it then, it will not appear in prod as the logger is noop by default in prod. They can always change this behavior.
Single point of failure.

Comment (dtassone) [reply packages/grid/_modules_/grid/GridComponent.tsx:124]: logger.error will not show the error message...
Only throw exception will do, to avoid having the users' app crashing

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/GridComponent.tsx:124]: > How about we go for a logger.warn without the env check?

So option 6? The only downside I can think of is that it retains the logic in production, accounting for bundle size. I think that if we change the logic of the default console appender to be silent in production for non error (unless forced), sure. I think it can work great.

Comment (dtassone) [reply packages/grid/_modules_/grid/GridComponent.tsx:124]: in prod it won't be displayed as the logger is null

File: packages/grid/_modules_/grid/components/default-footer.tsx [hunk 4]
```diff
@@ -12,17 +12,18 @@ export interface DefaultFooterProps {
...
-    const api = React.useContext(ApiContext);
+  function DefaultFooter(props, ref) {
+    const { options, rowCount, paginationComponent } = props;
+    const apiRef = React.useContext(ApiContext);
     const [selectedRowCount, setSelectedCount] = React.useState(0);
 
     React.useEffect(() => {
-      if (api && api.current) {
-        return api.current!.onSelectionChange(({ rows }) => setSelectedCount(rows.length));
+      if (apiRef && apiRef.current) {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/default-footer.tsx:21]: We should be able to remove the check

File: packages/grid/_modules_/grid/hooks/utils/useLogger.ts [hunk 5]
```diff
@@ -46,7 +46,13 @@ function getAppender(name: string, logLevel: string, appender: Logger = console)
     if (idx >= minLogLevelIdx) {
       loggerObj[method] = (...args: any[]) => {
         const [message, ...rest] = args;
-        (appender as any)[method](`[${name}] - ${message}`, ...rest);
+
+        // Don't console log non errors in production
+        if (appender === console && method !== 'error' && process.env.NODE_ENV === 'production') {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/utils/useLogger.ts:51]: that's not necessary, we use the factory to initialize the logger and we want to log errors in prod as well

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/utils/useLogger.ts:51]: I think that it's important for 1. of https://github.com/mui-org/material-ui-x/pull/350#discussion_r496013426.
If the message should be logged in production, then it should be an error, not a warning. I forgot to add `forceDebug`

```suggestion
        if (
          appender === console &&
          !forceDebug &&
          method !== 'error' &&
          process.env.NODE_ENV === 'production'
        ) {
```

File: packages/grid/_modules_/grid/components/default-footer.tsx [hunk 6]
```diff
@@ -12,17 +12,18 @@ export interface DefaultFooterProps {
...
+        return apiRef.current!.onSelectionChange(({ rows }) => setSelectedCount(rows.length));
       }
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/default-footer.tsx:23]:
```suggestion
      return apiRef!.current.onSelectionChange(({ rows }) => {
        setSelectedCount(rows.length);
      });
```

File: packages/grid/_modules_/grid/hooks/utils/useLogger.ts (hunk 5 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/utils/useLogger.ts]: IMHO the logging level should not change between prod and dev. Otherwise ppl will have an error in prod and not in dev and they will be like WTF

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/hooks/utils/useLogger.ts]: > Otherwise ppl will have an error in prod and not in dev and they will be like WTF

This can't happen in the current configuration. All the errors reported in production as also reported in development.
The opposite (warn in dev, no warn in pro) is how React and Material-UI behaves (and have been since the beginning), developers are used to it. I think that the surprise will be if we report warning in prod.

> IMHO the logging level should not change between prod and dev.

Oh, I didn't think about that. It could be cleaner. We could have the log level as warning in dev and error in production, instead of the custom forking logic. This sounds better and more consistent! I can do that.

**Review by dtassone — APPROVED** [review]
