### PR TITLE
[DataGrid] Fix incorrect date selection

### LINKED ISSUE #1573: [DataGrid] Edit date picker returns incorrect value
When selecting a date from the native date picker, the rendered cell value is one day off whenever the input type is 'date'. 

[This is due](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#date_time_string_format) to `new Date()` interpreting the 'yyyy-mm-dd' form as UTC time (date-time forms are interpreted as local time). You can see a summary of date parsing behavior in JS [here](https://dygraphs.com/date-formats.html).

This can be fixed by setting `editProps.value` to always be `newValue`, and removing the conditional check to set `editProps.value` to be `new Date(newValue)` in 

https://github.com/mui-org/material-ui-x/blob/3e4be4de6cd41030eee75e8485c64a9a5ba48502/packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx#L30

I am not sure if this would be the preferred way to fix, or if it would be preferred to update the input value formatter on line

https://github.com/mui-org/material-ui-x/blob/3e4be4de6cd41030eee75e8485c64a9a5ba48502/packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx#L39

 so I have created an issue rather than a PR.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate. 

## Current Behavior 😯

When selecting any date with the date picker, the previous date is rendered as the cell value.

## Expected Behavior 🤔

When selecting any date with the date picker, the selected date is rendered as the cell value.

## Steps to Reproduce 🕹

1. Open DataGrid editing [docs](https://material-ui.com/components/data-grid/editing/)
2. Select a date in `Date Created` column (type='date')
3. Compare behavior with `Last Login` column (type='dateTime')

## Your Environment 🌎

 System:
    OS: macOS 11.2.3
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93

### PR DESCRIPTION
**Pull request by aTmb405**
Fixes #1573

### CODE REVIEW

File: packages/grid/_modules_/grid/utils/utils.ts [hunk 1]
```diff
@@ -11,6 +11,11 @@ export function isDateValid(value: Date): boolean {
   return !Number.isNaN(value.getTime());
 }
 
+export function formatDateString(value: string): Date {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/utils/utils.ts:14]: it's not a format function, it's a convert/parse. How about `parseDate` ?

File: packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx [hunk 2]
```diff
@@ -33,13 +38,15 @@ export function GridEditInputCell(props: GridCellParams & InputBaseProps) {
       };
 
       if (isDateColumn) {
-        editProps.value = newValue === '' ? null : new Date(newValue); // TODO fix parsing, this is plain wrong.
+        editProps.value = newValue === '' ? null : formatDateString(newValue);
+      } else if (isDateTimeColumn) {
+        editProps.value = newValue === '' ? null : new Date(newValue);
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx:43]: Should we do the same approach for dateTime? 🤔

Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx:43]: We can't do it, we support Safari 12.1: https://github.com/mui-org/material-ui/pull/23475#issuecomment-839640332

Comment (aTmb405) [reply packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx:39]: When editing a date or dateTime cell in Safari, any changes to the cell cause "Invalid Date" to render. The same occurs in Firefox for dateTime cells. Should this be a separate issue/PR?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx:39]: Is the PR rebased on HEAD? We have worked on a similar issue recently, on Chrome.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx:39]: Otherwise we could leave a to-do, we already improve one aspect.

Comment (aTmb405) [reply packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx:39]: > Is the PR rebased on HEAD? We have worked on a similar issue recently, on Chrome.

Yes, this is happening in the current version of the docs

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx:39]: Ok, so I had a look:

- Firefox. Doesn't support `<input type="datetime-local">`
- Safari. I can't reproduce the issue, however, the onChange event doesn't seem to fire reliably once emptied, and the text vertical alignment is wrong.

It seems that we will need to drop the native implementation.

Comment (aTmb405) [reply packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx:39]: Here's a GIF of this happening in Safari 14.0.3

Screen Capture

Comment (aTmb405) [reply packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx]: I'm having trouble coming up with a solution for this. I'm guessing the preferred behavior would be to :

1. Allow an invalid date while a cell is being edited
2. Render "Invalid Date" upon a submit event/enter/etc. if the value is not a date.

I'm unable to get both 1. and 2. because there is no `onSubmit` prop with `InputBase`. And the function passed to `onChange` does not run on <kbd>Enter</kbd>.

Is there a different way I should go about this?

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx]: @aTmb405 I would give up on it. Native date inputs have limitations and unlikely to be something developers can rely on.

Comment (aTmb405) [reply packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx]: This is added in the most recent commit

**Comment by DanailH** [comment]
Can we add a test case or reuse / update an existing one?

**Comment by oliviertassinari** [comment]
(Adding a test could be challenging as it likely requires to change the timezone. But we might have an existing test case in the main repository we can copy.)

**Comment by dtassone** [comment]
> (Adding a test could be challenging as it likely requires to change the timezone. But we might have an existing test case in the main repository we can copy.)

yes also I'm having issues having test for date operators working for all browsers. Edge is a pain

**Review by dtassone — APPROVED** [review]

**Comment by dtassone** [comment]
Approved as the fix improve the date management but it is likely that we should revisit soon, due to timezone...

**Comment by ichsanulamal** [comment]
Hi which version of datagrid do i need to install to get this fix all all my dates are still a day before the one selected
