### PR TITLE
[DataGrid] Fix filtering of nullish numeric cells

### LINKED ISSUE #3019: [DataGrid] Filtering for value 0 show rows that are null
Once using DataGrid filter for fields with numeric value '0', the filter just shows all values and ignores 0's.

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #3019

### CODE REVIEW

File: packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts [hunk 1]
```diff
@@ -2,6 +2,14 @@ import { GridFilterInputValue } from '../../components/panel/filterPanel/GridFil
 import { GridFilterItem } from '../gridFilterItem';
 import { GridFilterOperator } from '../gridFilterOperator';
 
+const parseNumericValue = (value: string | number | null) => {
+  if (value == null) {
```
Comment (alexfauquette) [inline packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts:6]: For my own learning: Are you using `==` to catch `null` and `undefined`?

**Review by alexfauquette — APPROVED** [review]

File: packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts (hunk 1 above)
Comment (flaviendelangle) [reply packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts:6]: Yes, and I tested both on the test file.
It's to avoid the `Number(null) === 0`
