### PR TITLE
[DataGrid] Remove use of row.id when id prop is available

### LINKED ISSUE #1119: [DataGrid] If data has field id, getRowId doesn't work
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.
- [x] The issue is present in the latest release.

## Current Behavior 😯

If origin data has the field `id`, `getRowId` doesn't work. So if field `id` isn't unique will get the warning.

MarineGEO circle logo

## Expected Behavior 🤔

Use new id which I need.

## Steps to Reproduce 🕹

 - Use this sample code to reproduce
```javascript
import React from 'react'
import { DataGrid } from '@material-ui/data-grid'

const BasicGrid = props => {
    const handleGetRowId = (e) => {
        return e.uniId
    }
    return (
        <DataGrid
            columns={[
                { field: 'uniId', width: 200 },
                { field: 'id', width: 200 },
                { field: 'name', width: 200 },
            ]}
            rows={[
                { id: 'company-ta-tb-id', name: 'TA-TB-XXXX', uniId: 'euald4541ajwndd1', },
                { id: 'company-ta-tb-id', name: 'TA-TB-YYYY', uniId: 'eakf4455anfw44dc', },
            ]}
            getRowId={handleGetRowId} />
    )
}

export default BasicGrid
``` 

## Context 🔦

In my project, the data set I got has used field `id` as part of the data, and the field `id` is not a unique identification code, the unique identification code is the field `uniId`.

I don't know why the company designed it this way, but this is a situation I face. 

I used the new API `getRowId` to work on this case, but I got the warning `index.js:1 Warning: Encountered two children with the same key`,  because If origin data have id already, `getRowId` dosen't work. 

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Browser: Chrome, Version 88.0.4324.150 (Official Build) (64-bit)
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 85.0.1
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/data-grid: ^4.0.0-alpha.20 => 4.0.0-alpha.20 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: ^4.0.0-alpha.20 => 4.0.0-alpha.20 
    @material-ui/x-grid-data-generator: ^4.0.0-alpha.20 => 4.0.0-alpha.20 
    @material-ui/x-license:  4.0.0-alpha.20 
    @types/react:  17.0.2 
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 
```
</details>

### LINKED ISSUE #1200: [DataGrid] getRowId causes an object clone
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

If getRowId is used, object clones are returned in the events.

## Expected Behavior 🤔

Original objects should be returned.

## Steps to Reproduce 🕹

Behavior with getRowId:
https://codesandbox.io/s/fragrant-cloud-qb5j8?file=/src/App.tsx

Behavior without getRowId
https://codesandbox.io/s/busy-heyrovsky-wtn1z?file=/src/App.tsx

When a row is clicked, the array is searched for the rowData object.
In the case of getRowId nothing is found.

### LINKED ISSUE #1315: [DataGrid] Remove the requirement of storing `id` in rowData
Avoid cloning row data
Avoid id field on rowData

### PR DESCRIPTION
**Pull request by m4theushw**
Related to #1119, #1200, #1315

This is the first batch of changes to satisfy the need of removing `id` from the rowData. In this PR I'm replacing `row.id` with the `id` prop in all places where it's already available. It has no breaking changes. In the next PR I'll do the rest of the work that requires changes in the API too.

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts [hunk 1]
```diff
@@ -12,15 +12,16 @@ export const visibleGridRowsStateSelector = (state: GridState) => state.visibleR
...
-);
+  Record<GridRowId, GridRowModel>,
+  Record<GridRowId, GridRowModel>
+>(visibleGridRowsStateSelector, sortedGridRowsSelector, (visibleRowsState, sortedRows) => {
+  return Object.keys(sortedRows).reduce((res, id) => {
+    if (visibleRowsState.visibleRowsLookup[id] !== false) {
+      res[id] = sortedRows[id];
+    }
+    return res;
+  }, {} as Record<GridRowId, GridRowModel>);
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts:23]: Here we want to return the sorted rows array? Not sure why you refactored?

File: packages/grid/_modules_/grid/hooks/features/sorting/gridSortingSelector.ts [hunk 2]
```diff
@@ -27,16 +26,13 @@ export const sortedGridRowsSelector = createSelector<
...
-  (sortedIds: GridRowId[], idRowsLookup, unordered) => {
-    return sortedIds.length > 0 ? sortedIds.map((id) => idRowsLookup[id]) : unordered;
-  },
-);
+  Record<GridRowId, GridRowModel>
+>(sortedGridRowIdsSelector, gridRowsLookupSelector, (sortedIds: GridRowId[], idRowsLookup) => {
+  return sortedIds.reduce((res, id) => {
+    res[id] = idRowsLookup[id];
+    return res;
+  }, {} as Record<GridRowId, GridRowModel>);
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/sorting/gridSortingSelector.ts:34]: same here. not sure why you refactored the return type

**Comment by dtassone** [comment]
Not entirely sure how `useGridRowId` would fit in.
But happy to see it through if it improves the architecture.

File: packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts (hunk 1 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts:23]: Since we don't add an `id` to the row object, it's not reliable to use `row.id` anymore. I converted this selector to return an object because in this way we keep the reference to the original row as value and the keys are the correct ids.

**Review by oliviertassinari — APPROVED** [review]

File: packages/grid/_modules_/grid/components/GridViewport.tsx [hunk 3]
```diff
@@ -60,6 +60,7 @@ export const GridViewport: ViewportType = React.forwardRef<HTMLDivElement, {}>(
           <GridRowCells
             columns={visibleColumns}
             row={r}
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/GridViewport.tsx:62]: could we cleanup here please? row?

File: packages/grid/_modules_/grid/components/GridViewport.tsx [hunk 4]
```diff
@@ -60,6 +60,7 @@ export const GridViewport: ViewportType = React.forwardRef<HTMLDivElement, {}>(
...
+            id={r.id}
```
Comment (dtassone) [inline packages/grid/_modules_/grid/components/GridViewport.tsx:63]: Would that one change with the next PR?

File: packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts [hunk 5]
```diff
@@ -20,10 +20,15 @@ import { useLogger } from '../../utils/useLogger';
 import { useGridState } from '../core/useGridState';
 import { getInitialGridRowState, InternalGridRowsState } from './gridRowsState';
 
+// TODO remove after all row.id are removed
 export function addGridRowId(rowData: GridRowData, getRowId?: GridRowIdGetter): GridRowModel {
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts:24]: can that one go now?

File: packages/grid/_modules_/grid/components/GridViewport.tsx (hunk 3 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/components/GridViewport.tsx:62]: Fixed in https://github.com/mui-org/material-ui-x/pull/1377/files#diff-4d439fd92e7951c822fbe83c5b5357d461de18a795235b490c8c28230369f1f4R62.

File: packages/grid/_modules_/grid/components/GridViewport.tsx (hunk 4 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/components/GridViewport.tsx:63]: Yes, the next PR changes to get the id from the Map.

**Review by dtassone — APPROVED** [review]
