### PR TITLE
[DataGrid] Fix support for numeric ids in selection

### LINKED ISSUE #874: [DataGrid] When the row id is a number type, the rowIds returned by the onSelectionChange event are of type string[]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When the row id is a number type, the rowIds returned by the onSelectionChange event are of type string[]

## Expected Behavior 🤔
Should return number type instead of being converted to string type

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-yi86n?file=/demo.js

Steps:

1.Open the codesandbox link above
2.Open the console
3.Click on any row in the table
4.Console will print string type id

## Your Environment 🌎

v4.0.0-alpha.24

  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.20.0/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Browsers:
    Chrome:  87.0.4280.141
    Firefox: Not Found

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #874

I changed to use a `Set`, as it supports numbers and strings and it's faster than a flat array or a object. This PR should be merged after #1377.

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts [hunk 1]
```diff
@@ -36,23 +37,26 @@ export const useGridSelection = (apiRef: GridApiRef): void => {
...
+  const getSelectedRows = React.useCallback(
+    () => selectedGridRowsSelector(apiRef.current.getState()),
+    [apiRef],
+  );
 
   const selectRowModel = React.useCallback(
-    (row: GridRowModel, allowMultipleOverride?: boolean, isSelected?: boolean) => {
+    (id: GridRowId, row: GridRowModel, allowMultipleOverride?: boolean, isSelected?: boolean) => {
+      const idAsNumber = Number(id);
+      const finalId = Number.isNaN(idAsNumber) ? id : idAsNumber;
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts:48]: Selecting a row with the keyboard will always call this method with a string, because `getIdFromRowElem` relays in the `data-id` attribute. I might move this cast to `getIdFromRowElem`.

https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts#L60-L68

Comment (dtassone) [reply packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts:48]: You need to refactor this function to use the params id of `handleCellKeyDown`. So you already have the id and don't need to retrieve it from the element

**Review by oliviertassinari — DISMISSED** [review]

File: docs/src/pages/components/data-grid/selection/ControlledSelectionGrid.tsx [hunk 2]
```diff
@@ -16,7 +16,7 @@ export default function ControlledSelectionGrid() {
       <DataGrid
         checkboxSelection
         onSelectionModelChange={(newSelection) => {
-          setSelectionModel(newSelection.selectionModel);
+          setSelectionModel([...newSelection.selectionModel.keys()]);
```
[the remark this answers is not in the document]
Comment (m4theushw) [reply docs/src/pages/components/data-grid/selection/ControlledSelectionGrid.tsx:19]: We could:
1. Pass a flat array to `GridSelectionModelChangeParams.selectionModel`
2. Add `GridSelectionModelChangeParams.selectionModelAsArray`

Both options require to iterate over all values.

[the remark this answers is not in the document]
Comment (oliviertassinari) [reply docs/src/pages/components/data-grid/selection/ControlledSelectionGrid.tsx:19]: 1. Sounds a lot better

**Comment by dtassone** [comment]
The issue with the `Set` is that it's not serializable, and the state aims to be serializable.

**Comment by m4theushw** [comment]
> Is there a perf hit?

Might exist one if there's 100k rows and all are selected. A flat array could solve the problem as well. Why an object was used in the first place?

**Review by dtassone — APPROVED** [review]

File: packages/grid/_modules_/grid/models/api/gridSelectionApi.ts [hunk 3]
```diff
@@ -9,10 +9,10 @@ export interface GridSelectionApi {
   /**
    * Toggle the row selected state.
    * @param id
-   * @param allowMultiple Default: false = deselect other rows if isSelected is true
    * @param isSelected Default true
+   * @param allowMultiple Default: false = deselect other rows if isSelected is true
    */
-  selectRow: (id: GridRowId, allowMultiple?: boolean, isSelected?: boolean) => void;
+  selectRow: (id: GridRowId, isSelected?: boolean, allowMultiple?: boolean) => void;
```
Comment (DanailH) [inline packages/grid/_modules_/grid/models/api/gridSelectionApi.ts:15]: Why do we need this change?

Comment (m4theushw) [reply packages/grid/_modules_/grid/models/api/gridSelectionApi.ts:15]: Because the TypeScript definition don't match the actual implementation.

https://github.com/mui-org/material-ui-x/blob/348a6731494faebeedebf48266c576d8e353da3e/packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts#L102-L107

**Review by DanailH — APPROVED** [review]
