### PR TITLE
[DataGrid] refactoring on focus cell and cols

### LINKED ISSUE #1416: [DataGrid] Broken cell focus on edit with external button
focus

_Originally posted by @oliviertassinari in https://github.com/mui-org/material-ui-x/pull/1287#r613117865_

Reproduce on documentation 
https://master--material-ui-x.netlify.app/components/data-grid/editing/#edit-using-external-button

### LINKED ISSUE #1420: [DataGrid] Focus lags behind on double click
Focus lags behind on double click

bug 4

Mentioned in https://github.com/mui-org/material-ui-x/pull/1287#pullrequestreview-635996299

### LINKED ISSUE #1493: [DataGrid] Filter UI loses focus while searching / typing
While using the filter in the table header the filter text field loses the focus after the user stops typing and the search starts. It looks like the header cell somehow steels the focus? This issue is present in the latest Firefox 88.0. 

mui-bug

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The text field in the filter loses the focus after typing. 

## Expected Behavior 🤔

I expect that the text field is still focused so that I can modify my filter parameter without selecting the text field again. 

## Steps to Reproduce 🕹

Steps:

1. Open https://cb7st.csb.app/
2. Click in any header cell to sort it
3. Click the menu icon to open the filter dialog
4. Type some random characters and wait while the search starts
5. The focused UI element changed

## Context 🔦

Doesn't matter I guess. 

## Your Environment 🌎

Sandbox-App: https://cb7st.csb.app/
Sandbox: https://codesandbox.io/s/cb7st

### PR DESCRIPTION
**Pull request by dtassone**
- fix #1416
- Help with #1430
- fix #1493
- fix wrong initial tab index. it should be on the first header cell, not the first body cell.
- fix #1420

Preview: https://deploy-preview-1421--material-ui-x.netlify.app/components/data-grid/editing/#edit-using-external-button

### CODE REVIEW

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
This breaks the roving index

**Comment by dtassone** [comment]
> This breaks the roving index, cc @DanailH.
> 
> I think that we absolutely need tests for the tab and focus behavior, it's brittle and easy to break.

I can do tests but why is the roving index broken?

**Comment by oliviertassinari** [comment]
> I can do tests but why is the roving index broken?

@dtassone One example of regression:

roving index

File: packages/grid/_modules_/grid/components/cell/GridCell.tsx [hunk 1]
```diff
@@ -59,9 +59,6 @@ export const GridCell: React.FC<GridCellProps> = React.memo((props) => {
   const valueToRender = formattedValue || value;
   const cellRef = React.useRef<HTMLDivElement>(null);
   const apiRef = React.useContext(GridApiContext);
-  const currentFocusedCell = apiRef!.current.getState().keyboard.cell;
-  const isCellFocused =
```
Comment (DanailH) [inline packages/grid/_modules_/grid/components/cell/GridCell.tsx:63]: Why did you remove that check? It is there to make sure that only the cell with coordinates `0-0` has `tabIndex={0}`.

File: packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx [hunk 2]
```diff
@@ -149,6 +153,10 @@ export const GridColumnHeaderItem = ({
     }
   });
 
+  const isFirstTabbable =
```
Comment (DanailH) [inline packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx:156]: I'm not sure that the first column header should be tabbale. I was left with the impression that the first cell should be tabble.

Comment (dtassone) [reply packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx:156]: That's the thing, IMO, the first tabbable control of a sortable grid should be the first sortable column header
https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html

So in our case, I put the first column so we could argue that if none of the columns have an action then it should be the first cell of the first row

File: packages/grid/_modules_/grid/components/cell/GridCell.tsx (hunk 1 above)
Comment (dtassone) [reply packages/grid/_modules_/grid/components/cell/GridCell.tsx:63]: yes I understand but I'm not it is correct as mentioned in my other comment

**Comment by dtassone** [comment]
split cell focus state and tabindex state
so when tab leave grid we can focus back on the previously focused element

**Comment by oliviertassinari** [comment]
> fix #1420 (not sure about 2.)

I meant that the rating is a radio group, that should handle arrow keys.

File: packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx (hunk 2 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx:156]: Actually, if we use that logic then the first tabbable cell should be either the column header that is sortable or the one that has a column menu as it is also a interaction.

File: packages/grid/_modules_/grid/components/cell/GridCell.tsx (hunk 1 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/cell/GridCell.tsx:63]: Ok, I'll resolve that one in favour of the other one to keep the discussion in a single place.

**Comment by DanailH** [comment]
> This breaks the roving index, cc @DanailH.
> 
> I think that we absolutely need tests for the tab and focus behavior, it's brittle and easy to break.

It's on my radar. I'll work on it today.

**Comment by DanailH** [comment]
> > This breaks the roving index, cc @DanailH.
> > I think that we absolutely need tests for the tab and focus behavior, it's brittle and easy to break.
> 
> It's on my radar. I'll work on it today.

Here is the PR with the e2e setup https://github.com/mui-org/material-ui-x/pull/1443

File: packages/grid/_modules_/grid/hooks/features/core/gridState.ts [hunk 3]
```diff
@@ -66,7 +69,9 @@ export const getInitialGridState: () => GridState = () => ({
   scrollBar: { hasScrollX: false, hasScrollY: false, scrollBarSize: { x: 0, y: 0 } },
   viewportSizes: { width: 0, height: 1 },
   sorting: getInitialGridSortingState(),
-  keyboard: { cell: null, columnHeader: null, isMultipleKeyPressed: false },
+  keyboard: { isMultipleKeyPressed: false },
+  focus: { cell: null, columnHeader: null },
+  tabIndex: { cell: null, columnHeader: null },
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/hooks/features/core/gridState.ts:74]: This looks better. We should soon be able to kill `keyboard` with #1437 from @m4theushw.
I would also advocate to kill `focus` but it will be for another discussion.

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
- This is not enough to close #1420. Only point 3 is fixed. I would recommend we focus on #1416 and only
- There is still a regression in the tab index behavior. tab index
- We need a test case for #1416

File: packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx [hunk 4]
```diff
@@ -230,4 +234,105 @@ describe('<XGrid /> - Edit Rows', () => {
...
+    render(<TestComponent />);
+    fireEvent.click(getCell(0, 0));
+
+    fireEvent.click(screen.getByRole('button', { name: /Edit/i }));
+    fireEvent.click(getCell(1, 0));
+    fireEvent.click(screen.getByRole('button', { name: /Edit/i }));
+    const inputs = document.querySelectorAll('input');
+    expect(inputs.length).to.equal(2);
+    const nikeInput = getCell(0, 0).querySelector('input');
+    fireEvent.click(nikeInput);
```
Comment (dtassone) [inline packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx:331]: @oliviertassinari any idea why this test does not work?

**Comment by DanailH** [comment]
Ok I think I found a bug but I'm struggling to make i video of it I'll try and list the steps:

- `Tab` until you focus the first grid cell
- Press the right arrow key until you reach the last cell in the row
- Press the right arrow key one more time
- `Tab` again to move out of the grid
- `Shift + Tab` to move back into the grid. It doesn't select the grid bug skips it and selects the tabbable element before the grid.

@dtassone if you want to ping me and I will show you the problem if you cant reproduce it.

File: packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx (hunk 4 above)
Comment (oliviertassinari) [reply packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx:331]: As for why the test case doesn't work. I recall that your first commit was to add a blur listener to fix the issue, so if you don't handle the activeElement, I don't see how the test could work, e.g. calling .focus(). We are inside a browser, fire event click doesn't trigger all the intermediary event (mouse down/mouse up/focus) that a real browse have. You have to simulate them.

**Review by oliviertassinari — COMMENTED** [review]
The fix seems to work and I can't spot a regression. I'm adding test cases for the one we found #1459.

**Comment by dtassone** [comment]
I thought it would fire focus on click with fireevent 
https://testing-library.com/docs/guide-events/

If I simulate the event then the test doesn't fail without the fix

**Comment by oliviertassinari** [comment]
- @dtassone you need to rebase, as you are changing the behavior of existing tests that are not on your base commit
- I have updated the PR's description to be more accurate on the issues that are fixed
- Could we add test cases for each individual bug we bundled together in this PR?

File: packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx [hunk 5]
```diff
@@ -230,4 +230,25 @@ describe('<XGrid /> - Edit Rows', () => {
     expect(cell.textContent).to.equal('1970');
     expect(getActiveCell()).to.equal('1-0');
   });
+  it('should the focus to the new field', () => {
```
Comment (oliviertassinari) [inline packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx:233]:
```suggestion

  it('should the focus to the new field', () => {
```

**Review by oliviertassinari — APPROVED** [review]
I didn't look closely in the logic, @m4theushw interested in having a closer look?

I didn't see a test case for the change of focused element for the checkboxes @dtassone what do you think about adding a regulae jsdom/Karma test to cover the new behavior?

**Comment by oliviertassinari** [comment]
I have updated the title so developers can understand the problem solved by this PR once it's displayed in the changelog. Also notice the capitalization so it behaves like a full sentence.
