### PR TITLE
[DataGrid] Remove 'hide: true' from a column should correctly resize the others column

### LINKED ISSUE #2004: [DataGrid] Hidden columns widths still used in calculation
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

https://user-images.githubusercontent.com/5405326/123953124-2c3ea180-d9a7-11eb-917e-154e26012cd8.mp4

## Expected Behavior 🤔

Should update the column as soon as the column changes.

## Steps to Reproduce 🕹

Steps:

1. Open https://material-ui.com/components/data-grid/columns/#fluid-width
2. Hide a column
3. 💥

## Context 🔦

Reported by @si7o in https://github.com/mui-org/material-ui-x/issues/708#issuecomment-871336411.

## Your Environment 🌎

v4.0.0-alpha.32

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #2004 

Based on 2nd diff in this comment https://github.com/mui-org/material-ui-x/issues/2004#issuecomment-871781521
The issue with the code in the comment was that when we changed the `columns` prop to remove a column, `upsertColumnsState` was neither removing them from the columns list nor publishing the event.

### CODE REVIEW

**Comment by flaviendelangle** [comment]
I'll add a test :+1:

File: packages/grid/_modules_/grid/models/api/gridColumnApi.ts [hunk 1]
```diff
@@ -47,8 +47,9 @@ export interface GridColumnApi {
   /**
    * Updates the definition of multiple columns at the same time.
    * @param {GridColDef[]} cols The new column [[GridColDef]] objects.
+   * @param {boolean} allColumnsProvided Determines if the `cols` argument contains all the columns or just the updated ones
    */
-  updateColumns: (cols: GridColDef[]) => void;
+  updateColumns: (cols: GridColDef[], allColumnsProvided?: boolean) => void;
```
Comment (dtassone) [inline packages/grid/_modules_/grid/models/api/gridColumnApi.ts:52]: `allColumnsProvided` is this one to flag if it is a reset or an update? 🤔

Comment (flaviendelangle) [reply packages/grid/_modules_/grid/models/api/gridColumnApi.ts:52]: The issue was that @oliviertassinari was trying to use `updateColumns` when the column prop change.
But when we removed column from the prop, they were not removed from the state because `upsertColumnsState` keeps the previous columns in the internal state.
So I added a flag on `updateColumns` to ask the code not to keep the previous ones.

It's indeed a flag to differentiate update and reset

If you don't want to pollute `updateColumn`, we could add a method `setColumns` and the effect that runs when the `columns` prop changes would call `setColumns`. 
`updateColumns` could also call `setColumns` to keep as much logic in common as possible.

Comment (dtassone) [reply packages/grid/_modules_/grid/models/api/gridColumnApi.ts:52]: > If you don't want to pollute updateColumn, we could add a method setColumns and the effect that runs when the columns prop changes would call setColumns.
updateColumns could also call setColumns to keep as much logic in common as possible.

Yes that sounds much cleaner.

Comment (flaviendelangle) [reply packages/grid/_modules_/grid/models/api/gridColumnApi.ts]: Updated

File: packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts [hunk 2]
```diff
@@ -160,13 +165,32 @@ export function useGridColumns(apiRef: GridApiRef, { columns }: { columns: GridC
     [columnsMeta.positions, getColumnIndex],
   );
 
+  const setColumnsWithNewState = React.useCallback(
```
Comment (dtassone) [inline packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts:168]: rename to `setColumnsState`.

**Review by dtassone — APPROVED** [review]

File: packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx [hunk 3]
```diff
@@ -375,6 +380,61 @@ describe('<DataGrid /> - Layout & Warnings', () => {
         });
       });
 
+      it('should resize flex: 1 column when setting hide: false on a column to avoid exceeding grid width', async () => {
```
Comment (oliviertassinari) [inline packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx:383]:
```suggestion
      it('should resize flex: 1 column when setting hide: false on a column to avoid exceeding grid width', () => {
```

File: packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx [hunk 4]
```diff
@@ -375,6 +380,61 @@ describe('<DataGrid /> - Layout & Warnings', () => {
...
+        const TestCase: React.FC<DataGridProps> = (props) => (
```
Comment (oliviertassinari) [inline packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx:384]: We don't allow FC in the codebase (x an core). See https://github.com/mui-org/material-ui-x/pull/1436 why 

```suggestion
        const TestCase = (props: DataGridProps) => (
```

**Review by oliviertassinari — COMMENTED** [review]
The added test case is not failing on HEAD. I don't know what's testing, but not the bug. The logic looks great otherwise, one abstraction where it's meant to be one.

**Comment by flaviendelangle** [comment]
@oliviertassinari Indeed I was a bit quick on this one
If we update the columns through the props, it worked, it only failed with updates through `apiRef`

I'll make a new PR to move the text
